### PR TITLE
DEVELOPER-2989 - JBDS Learn page doesn't display any quickstarts

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 at http://developers-pr.stage.redhat.com/pr/1072/build/1084/products/devstudio/learn/ I'm not seeing any results for searches, should I be look at a different page?

**Comment by Dantheman720** [comment]
@LightGuard - Not sure why, but the dcp instance doesn't seem to be working. 
jboss_developer_studio_-_developer_materials

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Let's see if rebuilding it forces the dcp the restart

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
This is looking good now!

**Comment by LightGuard** [comment]
@Dantheman720 Please proceed to have this signed off and we'll merge.

**Pull request merged**
