### PR TITLE
Footer Updates

### PR DESCRIPTION
**Pull request by adelasofia**
Updated the RHD footer so it can support 3 or 4 columns dynamically. These changes will also be bundled in the Footer Reference implementation, but wanted to push them here first due to Joe's deadline.

### JIRA Issue Link
-- No Jira ticket

Marvel mockup: https://marvelapp.com/c6c454h/screen/60231484/

### Verification Process
1. Check that the footer looks and works properly.
2. To add or remove columns, go to Structure > Menus > RHD Footer
3. Add or remove a column and it's links (Existing columns are Featured Topics, Communicate, Quicklinks)
4. Save the changes 
5. Check that the footer looks and works properly.

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by adelasofia** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by adelasofia** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by sjcox-rh** [comment]
@adelasofia  @joeschram and I have reviewed the footer changes and it's all good to go - UX approved.  Thanks!

**Pull request merged**
