### PR TITLE
DEVELOPER-3525 prepare for devstudio 10.1...

### PR DESCRIPTION
**Pull request by nickboldt**
DEVELOPER-3525 prepare for devstudio 10.1 release (note that the docs listed on product.yml may need to be updated again when new docs are available)

### CODE REVIEW

**Comment by nickboldt** [comment]
test this please

**Comment by nickboldt** [comment]
(can I get whitelisted so you don't need to manually approve my PRs before building them?)

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
I've also whitelisted you @nickboldt

**Comment by LightGuard** [comment]
@nickboldt Good to merge?

**Comment by nickboldt** [comment]
@LightGuard yes, feel free to merge to production. Doc changes will follow in a separate PR as per https://issues.jboss.org/browse/DEVELOPER-3488

**Pull request merged**
