### PR TITLE
Revert "[OCTOPUS] Merge branch developers.redhat.com/master into DEVELOPER-2742-final"

### PR DESCRIPTION
**Pull request by adelasofia**
Reverts redhat-developer/developers.redhat.com#933

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
We still have failing tests, but I'm confident this is fine. Going to merge anyway.

**Pull request merged**
