### PR TITLE
DEVELOPER-2847 RHEL Get Started Added tab selection to the URL

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
failed due to flaky download test :(

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Failed on download hack. I have suggested to Paul that disable them until David has implemented a solution for the redirect.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
Approved by Tiffany Nolan

**Pull request merged**
