### PR TITLE
[DEVELOPER-5468] Remove google +

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5468

### CODE REVIEW

**Comment by alistairmc** [comment]
please retest

**Comment by LightGuard** [comment]
retest this please

**Comment by alistairmc** [comment]
This looks good now, merged in the test fixes from master

**Comment by alistairmc** [comment]
Ready to review and merge from my perspective

**Pull request merged**
