### PR TITLE
Fixes DEVELOPER-3385 (tabs rendered incorrectly)

### PR DESCRIPTION
**Pull request by LightGuard**
Styling issue due to competing styles with Drupal.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia Mind taking a look at this and making sure tabs are still rendered as you'd expect?

**Comment by adelasofia** [comment]
@LightGuard they look good to me

**Comment by rct** [comment]
I can confirm this fixed the horizontal tabs at the top of /products/rhel/get-started and /products/softwarecollections/get-started-rhel7-nodejs.html

Note: it doesn't fix the tab alignment problem in the Step 4 tabs. (It was in the same ticket).
See http://developers-pr.stage.redhat.com/pr/drupal/production/products/rhel/get-started.html#Step4

**Pull request merged**
