### PR TITLE
[RHDX 129] Resolve poor URL Alias validation

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-129

#### Node (URL)
1. Edit a node alias field
2. Enter a full external URL into the alias field
3. See validation that notifies you that a full URL is not allowed and that the node does not save

#### Node (Duplicates)
Already in core

#### View (URL)
1. Create a new view
2. Check the "Create a page" box
3. Enter a full URL into the "Path" field
4. See validation that notifies you that a full URL is not allowed and that the view does not save

#### View (Duplicates)
1. Create a new view
2. Check the "Create a page" box
3. Enter an alias into the "Path" field that already exists on a node (ie: "events")
4. See validation that notifies you that a duplicate alias is not allowed and that the view does not save

#### Known Issues
1. Views path does not check for duplicates against other view paths
2. Editing an existing View path does not validate

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
Other than my one comment above, about the naming of the validation function, I approve of this PR. I have created this issue: https://projects.engineering.redhat.com/browse/RHDX-235 after reviewing this issue and thinking about how disorganized our form validation(s) are on this project. RHDX-235 will follow up on this work and properly organize all of our form validations into a single custom module.

**Review by staceymosier — COMMENTED** [review]
I was not able to use :// in the alias on a node.

However, I was able to go to Configuration -> Search and Metadata -> Url Aliases,  edit the alias of the assembly page that I created, and enter /https://something.com/, which gives the fatal error

- Alias ID: 17054178

- https://developer-preview-3480.ext.us-west.dc.preprod.paas.redhat.com/admin/config/search/path/filter?search=/test-alias

- https://developer-preview-3480.ext.us-west.dc.preprod.paas.redhat.com/test-alias

I am not sure if this form was part of the acceptance criteria, OR which of the users are able to navigate to this path to edit the alias instance.

Other than that, there are 17 new phpcs items. If you happen to have that configured and will be making changes,  please review them.  We want to add it to the build process in the future.

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Review by jordanpagewhite — APPROVED** [review]
This looks good. Thank you.

**Pull request merged**
