### PR TITLE
[DEVELOPER 5491] v2 second attempt

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5491

### CODE REVIEW

**Comment by robpblake** [comment]
@alistairmc Suggest that we get #2737 in first so that we're addressing the problem we had previously first.

cheers,

Rob

**Comment by alistairmc** [comment]
@robpblake Fine by me, I need you to review this to merge anyway.

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@alistairmc How do we check that this is working?

cheers,

Rob

**Comment by alistairmc** [comment]
This look good for me, I think its ready to merge

**Pull request merged**
