### PR TITLE
cdk/resources and megamenu fixes

### PR DESCRIPTION
**Pull request by adelasofia**
Removed broken link from cdk/resources and fixed highlighting of
‘Resources’ from megamenu when cdk/resources is active

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
@paulrobinson @adelasofia This PR is refering to the same sha as PR 836. Can we please close this PR .

**Comment by ollyjshaw** [comment]
@adelasofia @paulrobinson actually, it appears that this is a lot more simple than 836, so I suggest that 836 be removed.

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Replaced by: https://github.com/redhat-developer/developers.redhat.com/pull/844

**Pull request closed without merging**
