### PR TITLE
[DEVELOEPER-3310] Product Pages Drupalized

### PR DESCRIPTION
**Pull request by LightGuard**
See https://issues.jboss.org/browse/DEVELOPER-3310 for full information.

This allows product pages to be built within Drupal. There are two know issues currently:

* Product sub pages will not show up in the sitemap, and therefore will not be exported, yes, that's a bit a blocker
* Product sub pages will not have the meta tags that other pages will have, still working on this

This PR is to put this out there and get people to play around with it.

### CODE REVIEW

**Comment by LightGuard** [comment]
I believe @MikGue has said this is good to merge.

**Comment by MikGue** [comment]
+1

**Comment by MikGue** [comment]
Please advise when it's in production.  Thanks, Jason.

**Comment by LightGuard** [comment]
@paulrobinson @adelasofia @KamiQuasi I think we're good to merge

**Pull request merged**
