### PR TITLE
DEVELOPER-4058 Added hero for Advanced Linux Cheat Sheet

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4058](https://issues.jboss.org/browse/DEVELOPER-4058) - Added RHD hero for Advanced Linux Cheat Sheet

### CODE REVIEW

**Comment by adelasofia** [comment]
DON'T MERGE - PR still awaiting approval from Emily

**Comment by adelasofia** [comment]
Pending final approval

**Comment by adelasofia** [comment]
This has been approved by Emily and James

**Comment by LightGuard** [comment]
Good to merge?

**Pull request merged**
