### PR TITLE
Developer 3141 and 3140 - create/update new login/registration flows.

### PR DESCRIPTION
**Pull request by RubyGemTSL**
changes to logn/registration page.

removed ignore tag

completed updates to registration tests.

wip

added remaining scenario

Update cdn.store

fixed merge conflicts

added nightly tags to password reset tests

added new test account for keycloak API

attempting to fix selenium Net::ReadTimeout (Net::ReadTimeout) error.

minor adjustment to browser timeout

Made changes to test on mobile browsers.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@LightGuard @paulrobinson @robpblake - @velias has given his approval on the JIRA ticket so this is good to be merged now. Thanks!

**Pull request merged**
