### PR TITLE
DEVELOPER-3207 set current_version =...

### PR DESCRIPTION
**Pull request by nickboldt**
DEVELOPER-3207 set current_version = 10.0.0.GA ... does this still need to happen\? Is this how the Resources page decides which doc to show\?

### CODE REVIEW

**Comment by Dantheman720** [comment]
@nickboldt - The docs seemed to be in articles. I added those articles to https://github.com/redhat-developer/developers.redhat.com/pull/1205

Can you review to make sure it makes sense? 

http://developers-pr.stage.redhat.com/pr/1205/build/1534/products/devstudio/docs-and-apis/

**Comment by nickboldt** [comment]
Docs look good, except where I've opened JIRAs to fix typos. 
* https://issues.jboss.org/browse/TOOLSDOC-750
* https://issues.jboss.org/browse/TOOLSDOC-751

**Comment by nickboldt** [comment]
I've added some doc links. Is that what you were expecting?

**Comment by paulrobinson** [comment]
Yep, looks right @nickboldt. If you have time, can you fix the merge conflict? If not I'll try get to it, but I have a *lot* of Summit/DevNation prep to do so can't guarantee when it will get done.

**Comment by mishaone** [comment]
Looks good to me.

**Comment by nickboldt** [comment]
Merge conflict fixed. See also https://github.com/jboss-developer/www.jboss.org/pull/1039 in which I also added the same doc links.

**Comment by robpblake** [comment]
this is ok to test

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
