### PR TITLE
[DEVELOPER-3339] Incorrect base URL being sent to searchisko

### PR DESCRIPTION
**Pull request by LightGuard**
See https://issues.jboss.org/browse/DEVELOPER-3339 for full information.

There were instances of us creating the Searchisko helper manually
instead of using the default method which included the fix for the final
base url. The changes in aweplug are available at https://github.com/awestruct/aweplug/commit/598e62eef1b187820e74f86b611df5b1c0d7a603.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by Dantheman720** [comment]
+1 Ready to merge?

**Pull request merged**
