### PR TITLE
Update Alerts to new styles

### PR DESCRIPTION
**Pull request by mindreeper2420**
### GitHub Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3314

### Verification Process
Navigate to a page that has an alert/notification block.

They should look like this:
Screen Shot 2019-11-26 at 4 37 41 PM
Screen Shot 2019-11-26 at 4 37 44 PM
Screen Shot 2019-11-26 at 4 37 49 PM
Screen Shot 2019-11-26 at 4 37 52 PM
Screen Shot 2019-11-26 at 4 37 56 PM
Screen Shot 2019-11-26 at 4 37 59 PM

### CODE REVIEW

**Comment by mindreeper2420** [comment]
NOTE: The icons look a bit off, as they are still using the old icons, served from the jboss.org reference URL. I was unable to get the Alerts to utilize the Font Awesome icons.

**Comment by KamiQuasi** [comment]
this is okay to test

**Comment by robpblake** [comment]
this is ok to test

**Comment by mindreeper2420** [comment]
@gdoyle1 Here is the latest version of the Alerts:
InlineAlerts

The icons (alert icons and the close icon) are still using the SVGs from the JBoss URL, so that will have to be updated in a future version.

Regarding the Download alert, I will have to check that once the build has completed. The download is failing for me on the current production site.

**Comment by mindreeper2420** [comment]
rebuild this please

**Comment by mindreeper2420** [comment]
@gdoyle1 I'm unable to get the Thank You alert to actually appear (the download fails for me), so I cannot verify that alert. As there is a separate issue for the Thank You alert (https://github.com/redhat-developer/developers.redhat.com/issues/3313), I'd recommend that be left as a separate PR/work item so that these alerts can be merged in and used. Thoughts?

**Pull request merged**
