### PR TITLE
DO NOT MERGE [DEVELOPER-5432]  code snippets assembly

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5432

### Verification Process

Go here:

Relative URL: `/node/add/article`

Do this:

* Enter any content for required fields
* Once you reach the Content field, you should notice that you now have an option of using a Code Snippet assembly type.
* Add a new code snippet assembly type
* Enter some name for the code snippet that makes sense to you
* In the Code, long text unformatted field, enter some code like:

```
var msg = 'hello world';
console.log(msg);
```

* Finish filling out any required fields and save the edit form to create the Article

You should see this:

* You should be redirected to your newly created Article containing a code snippet assembly

githubhighlightjstheme

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
For posterity, this PR (closed) originally contained work for DEVELOPER-5432: https://github.com/redhat-developer/developers.redhat.com/pull/2662 It was closed because I was experiencing some git issues and cherry-picking the commits to a new branch and opening a new PR (this PR) seemed quicker. I have resolved the suggestions from Matt and Roger in that old PR.

**Comment by fearlsgroove** [comment]
@jordanpagewhite I don't think visual styles is the right way to provide the type for the snippet here. It automagically creates documentation/help text which is pretty cumbersome looking. Visual styles also allows multiple selections which doesn't make sense here.

I also don't see where you're actually passing that meta (language style) into highlight js. Is it able to pull that detail off the parent element? Assuming so that explains why you implemented with the visual styles, but the help text makes that unwieldy.

I'd recommend adding a new list/text field to the assembly with the visual styles and add the class directly to the code element. in preprocess or the template.

**Comment by jordanpagewhite** [comment]
I have completed these changes locally, but unfortunately I have run into the same git 'failed to push refs' issue as I previously encountered in this ticket. I think that I am misunderstanding the desired git workflow for forked repositories, in the way that we are handling pull requests. I will take some time to remind myself how this git workflow works over the weekend so that I can push up my work Monday morning.

Thanks again for the feedback. I appreciate it.

**Comment by jordanpagewhite** [comment]
I am going to close this PR due to the same git issue I experience previously in this ticket, and I will cherry pick the commits over. I have consulted with Rob, Luke and Jason, and I am fairly confident that the git rebase I was using from the contributing docs was causing this issue. I will use merge going forward.

**Pull request closed without merging**
