### PR TITLE
Allowing product editors access to edit products

### PR DESCRIPTION
**Pull request by LightGuard**
I'm helping some product people and noticed some changes to the permissions that need to be made.

### CODE REVIEW

**Comment by LightGuard** [comment]
Timeout on keycloak. I'll try retesting one more time.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Same errors that happening on all PRs.

**Comment by Dantheman720** [comment]
Can this be merged without keycloak tests passing? The permissions don't depend on Keycloak.

**Comment by LightGuard** [comment]
Yes, the DM/KC stuff doesn't affect this at all.

**Pull request merged**
