### PR TITLE
DEVELOPER-4010 Added text to product download pages

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4010](https://issues.jboss.org/browse/DEVELOPER-4010) Added text to the Product Download pages

### CODE REVIEW

**Comment by LightGuard** [comment]
Going to see what Heinz thinks about this.

**Comment by adelasofia** [comment]
This has been approved and is ready to be merged once tests are passing.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia is there work that needs to be done on this still? the JIRA isn't clear about that.

**Comment by adelasofia** [comment]
@LightGuard This is approved and can be merged 👍

**Pull request merged**
