### PR TITLE
DEVELOPER-3135 Updated Multi-path Get Started pages layout

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by rct** [comment]
Thanks for your help.  This looks good to me.  

I've pinged Mike Guerette to take a look through the JIRA ticket. 

No idea why the acceptance test failed.

**Comment by RubyGemTSL** [comment]
there seems to be an issue with keycloak

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/844/artifact/_cucumber/reports/rhd_test_report.html

Looking at the screenshots the login, register, and logout links are there which suggests to me it is keycloak. I'll take a look at other PR's to see if they also have this issue.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
This is green now, @adelasofia who needs to sign off before we can merge?

**Comment by MikGue** [comment]
Looks good.  Good to go.

Sorry for the delay.

**Pull request merged**
