### PR TITLE
[HOLD] - DEVELOPER-3587 - Improve the performance of downloads

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-3587

Testing to make sure export picks up the products.json.

### CODE REVIEW

**Comment by LightGuard** [comment]
Still on hold?

**Comment by Dantheman720** [comment]
Yeah, still on hold.

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
Needs additional refactoring

**Pull request closed without merging**
