### PR TITLE
Fixing a method missing error with my last impl

### PR DESCRIPTION
**Pull request by LightGuard**
The Drupal8Service was missing a method if the first attempt failed.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
1 fail - Received a 500 on login page:
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/508/artifact/_cucumber/reports/rhd_test_report.html

This is happening at least a couple of times a day now, i'll report it to Libor.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL I've tested this locally and it fixes the missing method declaration. Once the tests have passed, please feel free to merge.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
@robpblake - OK will do

**Comment by LightGuard** [comment]
Yay, tests passed! @RubyGemTSL all yours to merge.

**Pull request merged**
