### PR TITLE
DEVELOPER-3247 - Don't display superfluous tags on /resources page

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
Closing until Jenkins comes back

**Comment by robpblake** [comment]
@Dantheman720 Who needs to sign off on this?

**Comment by Dantheman720** [comment]
@lkrzyzanek - Can you please review this? http://developers-pr.stage.redhat.com/pr/1269/build/1728/resources/

**Comment by Dantheman720** [comment]
@paulrobinson Thanks!

**Pull request merged**
