### PR TITLE
New download Page - DEVELOPER-2769

### PR DESCRIPTION
**Pull request by wesbos**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
Looks like there's a problem with the downloads.html.slim file:

An error during rendering /downloads.html.slim occurred.
05:59:02 While processing file /home/awestruct/developer.redhat.com/downloads.html.slim
05:59:02 An error occurred: wrong number of arguments (0 for 1)
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:46:in `index'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:46:in `block (3 levels) in singleton class'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:34:in `each'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:34:in `block (2 levels) in singleton class'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:29:in `each'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:29:in `block in singleton class'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:3:in `instance_eval'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:3:in `singleton class'
05:59:02 /home/awestruct/developer.redhat.com/downloads.html.slim:1:in `__tilt_69876778488780'
05:59:02 /home/awestruct/gems/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `call'
05:59:02 /home/awestruct/gems/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `evaluate'
05:59:02 /home/awestruct/gems/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/handlers/base_tilt_handler.rb:134:in `rendered_content'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/page.rb:143:in `rendered_content'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/engine.rb:433:in `generate_page'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/engine.rb:406:in `block in generate_output'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:408:in `call'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:379:in `process_incoming_jobs'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:361:in `block in worker'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:354:in `fork'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:354:in `worker'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:345:in `block in create_workers'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:344:in `each'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:344:in `create_workers'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:301:in `work_in_processes'
05:59:02 /home/awestruct/gems/gems/parallel-1.6.2/lib/parallel.rb:232:in `map'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/engine.rb:404:in `generate_output'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/engine.rb:121:in `run'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/cli/generate.rb:22:in `run'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/cli/invoker.rb:152:in `invoke_generate'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/lib/awestruct/cli/invoker.rb:74:in `invoke!'
05:59:02 /home/awestruct/gems/bundler/gems/awestruct-1e8d7b90006b/bin/awestruct:9:in `<top (required)>'
05:59:02 /home/awestruct/gems/bin/awestruct:23:in `load'
05:59:02 /home/awestruct/gems/bin/awestruct:23:in `<main>'
05:59:02 Please see .awestruct/error.log for more information

**Comment by wesbos** [comment]
retest this please

**Comment by LightGuard** [comment]
@wesbos: An error during rendering /downloads.html.slim occurred.
While processing file /home/awestruct/developer.redhat.com/downloads.html.slim
error occurred: wrong number of arguments (0 for 1)

**Comment by wesbos** [comment]
looks like docker is breaking. 

retest this please

**Comment by wesbos** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@wesbos @LightGuard looking at the failures now. Will fix and raise a PR on Wes's branch if needed.

**Comment by LightGuard** [comment]
@RubyGemTSL Great, thank you!

**Comment by RubyGemTSL** [comment]
I've updated the tests for this, however won't raise a PR yet as I'm adding a couple of extra scenarios for the most popular section. Will finish off in the morning (UK).

**Comment by LightGuard** [comment]
@wesbos This has diverged from master now and I'm not able to retest it.

**Comment by wesbos** [comment]
@RubyGemTSL have you put in all your PRs? If so I'll rebase it

**Comment by RubyGemTSL** [comment]
@wesbos yes the tests are ready. Just needs a rebase.

**Comment by wesbos** [comment]
@LightGuard ok 👌

**Comment by RubyGemTSL** [comment]
@wesbos @LightGuard there's 1 failure in the acceptance tests:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-frontend-acceptance-tests/2091/console

expected "Red Hat Products" to include "Technologies"

Will fix and raise a PR. If this is not right, ignore my PR and fix the title.

**Comment by RubyGemTSL** [comment]
@wes - done

**Comment by wesbos** [comment]
@RubyGemTSL I don't see a PR on my fork

**Comment by RubyGemTSL** [comment]
@wesbos PR is https://github.com/wesbos/developers.redhat.com/pull/22

**Comment by LightGuard** [comment]
Is this just waiting a sign off then?

**Comment by LightGuard** [comment]
Received the :+1: from Tiffany

**Pull request merged**
