### PR TITLE
[NO ISSUE] Disable Katacoda Tracking

### PR DESCRIPTION
**Pull request by KamiQuasi**
This is to disable Katacoda tracking linked to my Firebase account.
In the event this is still wanted the code just needs to be uncommented and the associated values filled in.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
@KamiQuasi I will be bringing this up in about 30 minutes with Joe during our sprint planning call so that we can understand his requirements and next steps. I completely forgot that this was still associated to your Firebase account. Thank you for the reminder and PR

**Comment by jordanpagewhite** [comment]
@KamiQuasi Joe was unable to attend our sprint planning call this morning. I have reached out to him in Slack, and he has requested a week to consider these changes and discuss them with our data analysts. I will respond in this thread when Joe has determined how he would like to proceed with this issue. Thank you.

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
We cannot merge this PR as-is because it would result in data loss until we can replace the current implementation with some CXnO-owned implementation. This scope of work has not been prioritized thus far, and I do not, unfortunately, have an ETA on a resolution. I have brought this up many times as a high priority item, and I will continue to do so going forward.

It also seems that there could be some bigger Red Hat efforts to get Katacoda data into Adobe Analytics, whereas it was previously not allowed in Adobe Analytics. If that happens, then we could resolve this issue and entirely take the Katacoda tracking off of Luke's "hands" by getting a data export file that we can then import into Adobe Analytics.

At this time, I need to close this pull request to prepare for a repo migration that we will be performing in the near future.

**Pull request closed without merging**
