### PR TITLE
[SURGE-3056] Curated links

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* #3056 
* #3070 

#### Curated Links assembly type

Go to: https://developer-preview-3081.ext.us-west.dc.preprod.paas.redhat.com/openshift

You should see this:

Screen Shot 2019-09-12 at 5 54 20 PM

#### FontAwesome RHD Kit

Also, our new RHD FontAwesome kit should load https://kit.fontawesome.com/3f83b4c6d2.js , and our prior iteration of the FontAwesome script should not js/all.min.js

This addresses #3070

### CODE REVIEW

**Comment by gdoyle1** [comment]
@jordanpagewhite Fontawesome is working but the margins on this assembly are larger than 64px on the sides and top and bottom padding is larger than 24px (not sure if that matters here - if it doesn't then I'll approve)

**Comment by jordanpagewhite** [comment]
@gdoyle1 You are right. I will take a look at that now.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
Spacing and <style> issue to be addressed in https://github.com/redhat-developer/developers.redhat.com/issues/3085

**Pull request merged**
