### PR TITLE
[WIP] - DEVELOPER-2870 - Added url change for new filter added to searchisko …

### PR DESCRIPTION
**Pull request by Dantheman720**
…configuration

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
I'm having difficulty testing this. My plan is to use a custom query to return the results instead of manipulating the data with JS during the rendering process.

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 ready for merging or still WIP?

**Comment by Dantheman720** [comment]
@LightGuard I think this can be closed for now. This issue is currently undefined.

**Pull request closed without merging**
