### PR TITLE
[RHDX-120] Fix nested component spacing and article page

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-120

### Verification Process
go to /che-custom-stacks/ and check spacings match the prototype https://rhd-frontend-demo.netlify.com/pages/articles/#

### CODE REVIEW

**Comment by alistairmc** [comment]
@gdoyle1 the issue you reported is current live behaviour, I will make the change in this PR but should be a new feature request.

**Comment by alistairmc** [comment]
@gdoyle1 @staceymosier I have made the changes you requested please re-review

**Comment by alistairmc** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
