### PR TITLE
DEVELOPER-4256: Refactor current Search acceptance tests using webdriverIO

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[DEVELOPER-4256](https://issues.jboss.org/browse/DEVELOPER-4256): Refactor current Search acceptance tests using webdriverIO

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
Going to retest again just to verify that my fix wasn't a fluke!

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Unit-tests failed for some reason. Not related to this PR. Retesting again.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Still not fixed. Sigh.

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
