### PR TITLE
RHD-619 Updated content for Software Collections getting started page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@catrobson can you review the content change looks as you wanted?

**Comment by paulrobinson** [comment]
Needs rebasing.

**Comment by adelasofia** [comment]
@paulrobinson Approved by Catherine :+1:

**Comment by paulrobinson** [comment]
@wesbos can you review please?

**Comment by wesbos** [comment]
Builds are failing, but code it :+1: good to merge

**Comment by paulrobinson** [comment]
Needs rebasing.

**Comment by adelasofia** [comment]
@paulrobinson rebased :+1:

**Comment by paulrobinson** [comment]
Sorry, needs rebasing again :-(

**Comment by adelasofia** [comment]
@paulrobinson rebased :+1:

**Pull request merged**
