### PR TITLE
[RHDX-148] Fix background position on CTA component

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-148

### Verification Process
go to /products/openjdk/overview the cta background should run to the edge of the component

### CODE REVIEW

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
That is a great point @staceymosier Thanks. It would be great to combine these files if possible since they both seem to target the same assembly type/component

**Comment by alistairmc** [comment]
@staceymosier @jordanpagewhite 
 I don't think the 2018 one is loaded anymore

**Comment by jordanpagewhite** [comment]
@alistairmc Yep, sorry about that. You are right. I had to read through the various `@import` statements, but it looks like that file isn't processed into a dist asset at all. I can create a separate issue to perhaps clean up some of the legacy SCSS that is only causing clutter in the `rhdp2` theme then, but that will not be in the scope of this issue/PR. Thanks Alistair.

**Comment by jordanpagewhite** [comment]
@staceymosier Can you give this another review, considering Alistair's comment above, when you have a chance? Thanks.

**Pull request merged**
