### PR TITLE
[RHDX-101] Fix code snippet assembly

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-101](https://projects.engineering.redhat.com/browse/RHDX-101)

Affects 4 instances of content using the Code snippet assembly

1. https://developer-preview-3449.ext.us-west.dc.preprod.paas.redhat.com/che-custom-stacks/ - View steps 3, 4 and 5
2. https://developer-preview-3449.ext.us-west.dc.preprod.paas.redhat.com/coderland/serverless/building-a-serverless-service/ - Find mvn clean package
3. https://developer-preview-3449.ext.us-west.dc.preprod.paas.redhat.com/coderland/serverless/deploying-serverless-knative/ - Find minishift config set openshift-version v3.11.0
4. https://developer-preview-3449.ext.us-west.dc.preprod.paas.redhat.com/products/fuse/hello-world-fuse-tooling/ - The first content on the page is a snippet, see oc new-project knativetutorial

### Verification Process
1. View the current content that has code snippet assemblies and verify they appear in the PR environment, compared to production where the snippet does not render on the page.
2. Create test content and create various code snippets, assigning language values or leaving the values empty.  Verify the Code* field of the assembly is required, and that you cannot save it with no content.
3. Verify (if possible) that the highlight.js js and styles are inherited from the rhd-frontend site. 
The rhd-frontend theme will show the language syntax highlighting with the github style.
4. Example #2 above has a code snippet using visual style no-padding-top and no-padding-bottom. 

Notes:
- I did not test it with **audience selection** and I assume these fields still function as expected. 
- The name and author of the snippet do not appear on the site.

### CODE REVIEW

**Comment by staceymosier** [comment]
@jordanpagewhite    I have a DNM in the title here because I was looking into adding the .component class on the assembly as part of this PR. 

However, it looks as thought the class will be added in each assembly--type.html.twig file.
So I think it would be better to add the class via preprocess_assembly and add it to the attributes for all assemblies,  therefore it would not need to be done as part of this work.    Otherwise if you want it to be added to the assembly--code-snippet.html.twig,  I can do that as part of this push.

**Comment by staceymosier** [comment]
https://developer-preview-3449.ext.us-west.dc.preprod.paas.redhat.com/che-custom-stacks/?v=1

I had to add a cache bust parameter to it to see the latest work.

Screen Shot 2019-12-19 at 3 32 14 PM

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
