### PR TITLE
DEVELOPER-3647 - Vimeo videos do not load on product overview pages when browsing the site over HTTPS

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by paulrobinson** [comment]
@RubyGemTSL the IoT topic is the first result, but the tests are failing, claiming it isn't: http://developers-pr.stage.redhat.com/pr/1601/export/search/?q=iot

Any ideas?

**Comment by RubyGemTSL** [comment]
@paulrobinson - that is not what happened during the test run, the screenshot shows "Watch Dev Nation 2014" as the top result.

I can also reproduce this manually:
The test searches for "Internet of things"

This always returns "Watch Dev Nation 2014" as the top result?

Should I be searching for iot instead?

**Comment by robpblake** [comment]
retest this please

**Comment by paulrobinson** [comment]
@Dantheman720 this seems to be working. Can you work with @LightGuard to get the Aweplug change into aweplug master and this updated?

**Comment by Dantheman720** [comment]
@paulrobinson - will do.

**Comment by Dantheman720** [comment]
This is ready now.

**Pull request merged**
