### PR TITLE
[URGENT] DEVELOPER-3733 Updated mega menu OpenJDK label

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by KamiQuasi** [comment]
@adelasofia and @LightGuard it looks like the errors are just mis-ordered data. Other than that looks good

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia Could you fix the technology page/tests so the tests pass as well, please?

**Comment by adelasofia** [comment]
@LightGuard I updated the /products page on Drupal so the tests would pass, so hopefully I'll get all tests passing this time

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
