### PR TITLE
Join now A/B Test DEVELOPER-2763

### PR DESCRIPTION
**Pull request by wesbos**
Can be run in target or the console with:

```js
$(function() {
  app.abTest.swap('variants/join-now-2', '.register-banner');
});
```

### CODE REVIEW

**Comment by LightGuard** [comment]
That's a subtle change, was difficult to catch the change.

**Comment by wesbos** [comment]
Is that a problem? It lines up with what was requested. Most notably the social icons show up

**Comment by LightGuard** [comment]
No, I was simply expecting a larger change and in reviewing it was difficult to tell anything had changed at first.

**Comment by LightGuard** [comment]
Who needs to sign off on this?

**Comment by insectengine** [comment]
Ray or Axel should sign off A/B testing stuff.

**Comment by LightGuard** [comment]
I think there's a question about the image and text being used, it doesn't match https://issues.jboss.org/browse/DEVELOPER-2763. Is there something I'm missing here?

**Comment by wesbos** [comment]
@LightGuard Okay they gave me new SVGs and I've added them in.

**Comment by LightGuard** [comment]
@wesbos looks like the LinkedIn icon on the new banner section goes to redhat.com instead of LinkedIn, is this intentional?

**Comment by wesbos** [comment]
@LightGuard @insectengine  Ah yes -where should the linked in icon go to? I wasn't provided with any url

**Comment by LightGuard** [comment]
https://www.linkedin.com/company/red-hat ?

On Mon, Apr 11, 2016 at 9:16 AM, Wes Bos <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> @insectengine
> <https://github.com/insectengine> Ah yes -where should the linked in icon
> go to? I wasn't provided with any url
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/987#issuecomment-208397548>
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by insectengine** [comment]
@rayploski  @wesbos @LightGuard : All social streams should point to RHD streams not Red Hat proper as this is about joining RHD.  We *may* not have a linkedin stream at this point so we'll need to remove it. Ray, can you confirm?

**Comment by wesbos** [comment]
Okay I've taken it out. can we merge this?

**Comment by mistermoule** [comment]
Works for me. @rayploski is that ok with you?

**Comment by akandel** [comment]
Look good to me. @rayploski is that ok with you?

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
I'm going to do a re-test to get all green then we'll merge! Thanks @wesbos

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@wesbos I think we just need the conflict resolved and we're good to go here.

**Comment by wesbos** [comment]
Merged in master - the homepage hero has been changed so let's double check that before we merge

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by wesbos** [comment]
I've added in the commits for the hero AB testing (DEVELOPER-2779) here as well - they both rely on the same setup. 

To test: ` app.abTest.swap('variants/hero2', '.homepage-main');`

**Comment by LightGuard** [comment]
@wesbos Who is the one to sign off on this then?

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
I can review this.

**Pull request merged**
