### PR TITLE
[DEVELOPER-3871] Fixed technologies tests URL checks

### PR DESCRIPTION
**Pull request by robpblake**
URL changes in Drupal have resulted in the tests failing. This is an attempted fix.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL This should resolve the FE tests failing. I think the registration failures are unrelated. Can you please merge if you're happy with this.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
The scenario: `Scenario User links new social account to existing RHD account` was failing as the Github account got a bit tangled up. The remove authorized applications API call must not have been executed on a previous test run (on this PR or any PR for that matter). Hence why the test was failing on 'Authorise App' button.

Will keep an eye out for this one.

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
