### PR TITLE
[DEVELOPER 3277] Update Event title max length to 60 characters

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3277

### Verification Process
1. Edit node: /node/212225/
2. Change title to 60 characters long and save
3. Change title to 61 characters and see validation error

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Review by jordanpagewhite — APPROVED** [review]
Looks good to me! Thanks Roger

**Pull request merged**
