### PR TITLE
[WiP] DEVELOPER-3417 Fixed angular binding to prevent code flickering

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
There is 1 false failure on this PR (as well as others), the 6th result returned from DCP (when searching for containers) does not contain 'container'.

**Comment by paulrobinson** [comment]
I'm still seeing this happening on http://developer-drupal.web.prod.ext.phx2.redhat.com/products/datagrid/learn

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Pull request closed without merging**
