### PR TITLE
RHD-1070 Updated vJBUG page for Dec session

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
@paulrobinson The RSVP button is hidden because there's no meetup page for this session

**Comment by paulrobinson** [comment]
Thanks Adela, We'll have the missing content once the date is confirmed.

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Meetup URL: http://www.meetup.com/JBoss-User-Group-Worldwide/events/226969315/
See that for new date and time.
The video is moving to this YouTube ID, expect that page to be in production within 10mins: YoC0vDIWpC8 

Need anything else?

**Comment by adelasofia** [comment]
retest this please

**Comment by paulrobinson** [comment]
This is failing due to us running out of disk space. working on it...

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Pull request merged**
