### PR TITLE
[SURGE 3295] Two Column Eloqua Form

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3295

### Verification Process
1. Go to https://developer-preview-3310.ext.us-west.dc.preprod.paas.redhat.com/contact-sales
2. Edit "Sign-up Form" assembly and add the "Two column" visual style
3. View the page and confirm the form displays in two columns

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
There is a very annoying CSS 'bug' that I am trying to track down right now that we'll need to resolve before approving/merging this PR

**Comment by jordanpagewhite** [comment]
This 3 line rule: https://github.com/redhat-developer/rhd-frontend/blob/master/src/styles/2018/_legacy.scss#L2032 is causing a _regression_ of sorts, where the style is being applied since the classes `two-column` and `assembly-type-rich_text_columns` are siblings.

**Comment by jordanpagewhite** [comment]
Blocked by https://github.com/redhat-developer/rhd-frontend/issues/408

**Comment by jordanpagewhite** [comment]
PR on blocking issue in `rhd-frontend` made here: https://github.com/redhat-developer/rhd-frontend/pull/409

**Comment by jordanpagewhite** [comment]
@rogeralloymagnetic Can you pull in the latest changes to `rhd-frontend` when you get a chance?

**Review by gdoyle1 — CHANGES_REQUESTED** [review]
(Marking this as request changes for now...) So I found that when I added an assembly (since the sign-up form assembly is a nested one), it pulled in the style of two-column or one-column from the child. I think the visual style you apply to that should be overwriting it. For example, I pulled in a two-column sign-up from assembly and did not apply any visual style to it - shouldn't that mean that it is one column?

**Comment by robpblake** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 I'm having trouble following the issue you're describing. Can you give me the following information to reproduce?

1. A node/url you notice the issue on
2. The assembly/nesting you're using
3. Where you're adding the visual style

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 actually, this is an older PR and has been replaced by: https://github.com/redhat-developer/developers.redhat.com/pull/3395

I'm going to close this one, please add any other review comments to the PR linked above.

**Pull request closed without merging**
