### PR TITLE
[HOLD] RHD-1027 Created Product pages for CDK

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
Failing due to acceptance tests and merge issues. Please rebase.

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
Please resolve conflicts before retesting. @adelasofia @paulrobinson

**Pull request closed without merging**
