### PR TITLE
[DEVELOPER-3761] Separate testing infrastructure from other environments

### PR DESCRIPTION
**Pull request by robpblake**
This pull request implements the first steps of separating out the testing infrastructure from the other environments defined as part of the RHD project. Broadly in this PR we have:

1. Created a new Docker image for running the acceptance tests that allows testing to have control over their own dependencies in `_cucumber/Gemfile` and `_cucumber/Gemfile.lock`
2. Created a new testing docker-compose.yml in `_cucumber/environments` that gives testing the flexibility to alter the testing environment definition without any concern about impacting other environments
3. Introduced new wrapper scripts for running the tests that greatly reduces the complexity inherited from `control.rb` and again allows testing to make changes to these with no concern about impacting other parts of the project
4. The new  wrapper scripts provide consistency when running the tests on the command line on the local machine or within Docker. Only difference now is to supply the `--use-docker` flag to instruct the tests to run within Docker.
5. Updates the GitHub Status wrapper to allow us to run acceptance tests from Jenkins without having to send updates into GitHub. Useful for when we want to run the acceptance tests when there is no pull-request associated with them e.g. nightlies or deployments to production.

**NOTE:** As-per the acceptance criteria on DEVELOPER-3761, this PR does not attempt to clear-up the deprecated testing infrastructure. That is happening under another user-story otherwise there would be too many changes going on at one time.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL I think this is now ready for review by you and if you're happy to be merged.

Can you please:

1. Go through all of the changes here and make sure you're happy with them
2. Review the console output from the successful run of the acceptance tests: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-drupal/899/console to make sure output looks logical
3. Check that the artifacts associated with the build job are what you expect and that the status links on this issue work as expected for the tests

If everything all looks good to you, then I think this can be merged!

cheers,

Rob

**Comment by RubyGemTSL** [comment]
Excellent work @robpblake really happy with the changes. I'm happy for this to be merged @paulrobinson if Rob is OK with it.

In the next sprint i'll need to do some documentation so the team can understand the changes.

**Comment by paulrobinson** [comment]
@RubyGemTSL any reason why you have approved but not merged? Do you feel another person's review is needed?

**Comment by RubyGemTSL** [comment]
sorry @paulrobinson I didn't think I could merge as I also contributed to this PR. Merging now.

**Pull request merged**
