### PR TITLE
[MWES-2846] Update production Drupal to use RHEL 7 and SCL dependencies

### PR DESCRIPTION
**Pull request by robpblake**
This PR brings in the changes applied in `stage` as part of #2832 to our production environment now that we've had a chance to test it in staging.

### JIRA Issue Link
* https://issues.jboss.org/browse/MWES-2846

### Verification Process

* Build should go green
* Please log into Drupal and make sure that there are no suspicious looking errors.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
Ready whenever.

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
