### PR TITLE
DEVELOPER-5676: update e2e tests to webdriverio v5+

### PR DESCRIPTION
**Pull request by RubyGemTSL**
### JIRA Issue Link
* DEVELOPER-5676: update e2e tests to webdriverio v5+

### Verification Process
* Tests are passing
* Code review.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Can you give this a once over @robpblake. Just a refactor of existing tests using updated version webdriverio which had breaking changes.

**Comment by robpblake** [comment]
@RubyGemTSL What's your availability to fix this if it breaks things? I know you said you're away on holiday very shortly. Is it better to leave this one to go in until you're back?

cheers,

Rob

**Comment by RubyGemTSL** [comment]
@robpblake - yes no harm until waiting until I am back.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
