### PR TITLE
DEVELOPER-4360 - Fix for failing nightly broken link checks

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[DEVELOPER-4360](https://issues.jboss.org/browse/DEVELOPER-4360) - Broken link check nightly prod job is broken

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
Please don't merge this until the e2e and blc Jenkins jobs have been updated to reflect this this.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@robpblake the failures are related to /dotnet not this PR so if you're happy please merge ;-)

**Comment by robpblake** [comment]
Failures unrelated to this PR (if it was this PR, the tests wouldn't even run). Looks good to merge.

**Pull request merged**
