### PR TITLE
[DEVELOPER-3039] / [DEVELOPER-3223] Drupal Acceptance Tests

### PR DESCRIPTION
**Pull request by robpblake**
This PR adds the ability to run the acceptance tests locally against an export of the Drupal site. It additionally fixes DEVELOPER-3223 as the work was very closely related.

This PR:

1. Updates Drupal to run on port 80 and searchisko to run on port 8080 in the drupal-dev environment
2. Starts an Apache instance on port 9000 in the drupal-dev environment that can host an instance of the exported site
3. Provides a transformer to the content import process into Drupal that removes all trailing slashes from links within the content. This is to provide consistency with the httrack export
4. Updates the httrack export definition to prevent it copying the Drupal 404 page for any pages that cannot be found

Additionally I have had to re-introduce the docker_chrome service definition into each docker-compose.yml for the environments that need it. This is because I need to link the docker_chrome service definition to different containers with the link `docker` depending on the environment.

### CODE REVIEW

**Comment by robpblake** [comment]
@LightGuard / @RubyGemTSL Could I ask you both to have a quick test of this PR. Can you please both try the following:

```
cd _docker
bundle exec ./control.rb -e drupal-dev --run-the-stack
bundle exec ./control.rb -e drupal-dev --export
```

When both of those have finished, you should be able to visit `docker:9000` on your machine and see a static export of the site from Drupal. Drupal is now available at `docker`.

cheers,

Rob

**Comment by LightGuard** [comment]
```
- Executing 'docker-compose' -f '/home/jporter/projects/developers.redhat.com/_docker/environments/drupal-dev/docker-compose.yml' with command 'run' and args '["--rm", "export"]'
WARNING: The DOCKER_HOST_IP variable is not set. Defaulting to a blank string.
[2016-07-05 20:51:58] INFO - Beginning export of content from Drupal at 'docker:32769'...
[2016-07-05 20:51:58] INFO - Invoking cron on host 'http://docker:32769/cron/rhd'. Please be patient this may take a while...
[2016-07-05 20:51:58] ERROR - Failed to export content from Drupal at 'docker:32769'
/usr/local/lib/ruby/2.1.0/net/http.rb:879:in `initialize': getaddrinfo: Name or service not known (SocketError)
        from /usr/local/lib/ruby/2.1.0/net/http.rb:879:in `open'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /usr/local/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:583:in `start'
        from /home/awestruct/developer.redhat.com/_docker/lib/export/cron_invoker.rb:27:in `invoke_cron!'
        from _docker/lib/export/export.rb:32:in `export!'
        from _docker/lib/export/export.rb:67:in `<main>'
Error running docker-compose
```

**Comment by RubyGemTSL** [comment]
I've also had issues.

Gist of output here:

https://gist.github.com/RubyGemTSL/3b573be3adb2c96c8c0bdf419789869c

**Comment by RubyGemTSL** [comment]
Sorry after speaking to Rob, it did actually work for me. The output in my gist is a seperate issue that Rob has raised. 

Looks good to me

**Comment by robpblake** [comment]
@LightGuard Are you sure you have this PR correctly checked out? It looks like you're running in a different branch as I have updated Drupal to run on port 80 and removed use of the `DOCKER_HOST_IP` variable.

cheers,

Rob

**Comment by LightGuard** [comment]
I'll try it again, maybe when I checked out the branch it didn't actually checkout.

**Comment by LightGuard** [comment]
A bunch of 404s on images and the ..html problem, but I think you already know about those.

**Pull request merged**
