### PR TITLE
DEVELOPER-2949 - Drupal event page has css issues on the event cards

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@Dantheman720 It looks like the Jenkins slave "had a moment" during the initial build for this PR. I can't get it to build from the revision of this PR for some reason. Could you please close this PR and simply open another one with your change? I think that will sort it.

cheers,

Rob

**Comment by LightGuard** [comment]
This is good

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Please recreate this PR @Dantheman720

**Pull request closed without merging**
