### PR TITLE
DEVELOPER-4345 Created middleware landing page

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4345 - Create /middleware Landing Page](https://issues.jboss.org/browse/DEVELOPER-4345)

### CODE REVIEW

**Comment by adelasofia** [comment]
@KamiQuasi could you please review this PR but not merge it please? I'll merge it once Heinz is ready for it to go live

**Comment by KamiQuasi** [comment]
@adelasofia everything looks good. Is the plan to create this with Awestruct and then disable the Awestruct and do future edits in Drupal?

**Comment by KamiQuasi** [comment]
retest this please

**Comment by adelasofia** [comment]
@KamiQuasi yes exactly

**Pull request merged**
