### PR TITLE
DEVELOPER-3089 Content editors to edit meta tags

### PR DESCRIPTION
**Pull request by LightGuard**
JIRA: https://issues.jboss.org/browse/DEVELOPER-3089

You should be able to see a new section in the right hand side of content creation and editing which says "Meta Tags."
Those with the "content_creator" should be able to see the aforementioned section.

### CODE REVIEW

**Comment by LightGuard** [comment]
Interesting that the mobile tests passed but the others didn't.

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please.

Grr.... no changes at all to the front-end and the tests break.

**Comment by RubyGemTSL** [comment]
@LightGuard there's one flaky search test that's killing me right now. Its flaky as hell. Fix will be here soon.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
@KamiQuasi If you're happy with this, please go ahead and merge.

**Pull request merged**
