### PR TITLE
JBDSUpdated - DEVELOPER-2981 and DEVELOPER-2984 merged result

### PR DESCRIPTION
**Pull request by Dantheman720**
This should make it easier for review

### CODE REVIEW

**Comment by Dantheman720** [comment]
@rayploski @LightGuard - Is this okay to merge?

**Comment by LightGuard** [comment]
Looking good to me

**Comment by paulrobinson** [comment]
There are still several references to devstudio 8.1 that need updating.

**Comment by paulrobinson** [comment]
ignore the above. Fuse and AMQ don't work with DevStudio 9.1 yet

**Pull request merged**
