### PR TITLE
DEVELOPER-3749 Updated product downloads page text

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
Approved by Tiffany N.

**Comment by RubyGemTSL** [comment]
Looks like registration page changes. feel free to merge if approved.

**Pull request merged**
