### PR TITLE
Added option to override title on product pages.

### PR DESCRIPTION
**Pull request by unibrew**
This pull request allows overriding page title on pages inheriting from product-base.html.slim layout.

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
Do you have an example of where I can see this working?

**Comment by unibrew** [comment]
I'm not yet on VPN to double check but difference in title should be visible between those two pages:
http://developers.redhat.com/products/softwarecollections/get-started-rhel7-nodejsbeta/

http://developers-pr.stage.redhat.com/pr/1134/build/1288/products/softwarecollections/get-started-rhel7-nodejsbeta/

**Comment by unibrew** [comment]
doublechecked, the second link contains the correct, longer title

**Comment by rctrh** [comment]
@unibrew Thanks that takes care of the title.  However the :awestruct-description: isn't being picked up from the file.  Should this fix have address that as well?

**Comment by unibrew** [comment]
I didn't spot that description doesn't work. I'm currently fixing descriptions in content and I already noticed some that are problematic. So, I'll provide a separate fix for this and let's leave this PR to be only about titles.

**Comment by rct** [comment]
Ok, in that case, this looks good.  When do you you anticipate merging this?

**Comment by unibrew** [comment]
I cannot merge it because I'm not part of the frontend team, just helping out temporarily.
@paulrobinson was planning to merge it today.

**Pull request merged**
