### PR TITLE
[DEVELOPER-3639] Ensure Drupal boot fails if drush start-up commands error

### PR DESCRIPTION
**Pull request by robpblake**
This PR ensures that the Drupal boot sequence will not continue if any of the commands executed fail. This provides the user with concrete feedback that their changes are not being applied cleanly as the Drupal instance will not start.

### CODE REVIEW

**Comment by robpblake** [comment]
@LightGuard Would you mind taking a quick look at this one. It basically adds the `set -e` option to the Drupal start-up shell script which ensures that any command that fails during the Drupal start-up procedure will prevent the whole thing from booting. Without this it just carries on regardless, whether any of the drush command failed or not.

cheers,

Rob

**Comment by LightGuard** [comment]
Didn't work for me. Maybe because we need the return value of the ruby process?

**Comment by robpblake** [comment]
@LightGuard Just to confirm that we're testing this in the same way, can you please do the following for me:

Using current master, update `_docker/environments/drupal-dev/docker-compose.yml` at line 83 to read:

`image: redhatdeveloper/drupal-data:195`

This is the version of the data image that contains the broken configuration that fails to synchronize.

Then run:
`
bundle exec ruby _docker/control.rb --run-the-stack
`

and then in another terminal once the container is available:

`
docker logs -f drupaldev_drupal_1
`

For me, using the current master branch I see a failure on the output of the Drupal container something like this:

```
DEBUG - executing command /var/www/drupal/vendor/bin/drush ["--root=/var/www/drupal/web", "-y", "cim", "--skip-modules=devel"]
scripts/drupal_install_checker.rb:9:in `exec!':  Collection  Config                         Operation  (RuntimeError)
             shortcut.set.james             delete    
             shortcut.set.jame-s-shortcuts  delete
Import the listed configuration changes? (y/n): y
Drupal\Core\Config\ConfigImporterException: There were errors            [error]
validating the config synchronization. in
Drupal\Core\Config\ConfigImporter->validate() (line 728 of
/var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                         [error]
Entities exist of type <em class="placeholder">Shortcut link</em> and
<em class="placeholder"></em> <em class="placeholder">James</em>.
These entities need to be deleted before importing.
Entities exist of type <em class="placeholder">Shortcut link</em> and
<em class="placeholder"></em> <em class="placeholder">Jame&#039;s
Shortcuts</em>. These entities need to be deleted before importing.
	from scripts/drupal_install_checker.rb:136:in `import_config'
	from scripts/drupal_install_checker.rb:156:in `<main>'
httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3 for ServerName
```

However Drupal continues to boot and is available at `docker:80` even though there have been failures during the boot process.

I then do the following:

```
git stash
git checkout developer-3639-drush-fail-if-boot-errors #dependent on your branch name for this PR
git stash apply
bundle exec ruby _docker/control.rb --run-the-stack
```

and then again in another terminal:

```
docker logs -f drupaldev_drupal_1
```

This time, the boot sequence fails with 

```
Updating configuration...
DEBUG - executing command /var/www/drupal/vendor/bin/drush ["--root=/var/www/drupal/web", "-y", "cim", "--skip-modules=devel"]
scripts/drupal_install_checker.rb:10:in `exec!':  Collection  Config                         Operation  (RuntimeError)
             shortcut.set.james             delete    
             shortcut.set.jame-s-shortcuts  delete
Import the listed configuration changes? (y/n): y
Drupal\Core\Config\ConfigImporterException: There were errors            [error]
validating the config synchronization. in
Drupal\Core\Config\ConfigImporter->validate() (line 728 of
/var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                         [error]
Entities exist of type <em class="placeholder">Shortcut link</em> and
<em class="placeholder"></em> <em class="placeholder">James</em>.
These entities need to be deleted before importing.
Entities exist of type <em class="placeholder">Shortcut link</em> and
<em class="placeholder"></em> <em class="placeholder">Jame&#039;s
Shortcuts</em>. These entities need to be deleted before importing.
	from scripts/drupal_install_checker.rb:137:in `import_config'
	from scripts/drupal_install_checker.rb:157:in `<main>'

DEBUG - execution of command '/var/www/drupal/vendor/bin/drush ["--root=/var/www/drupal/web", "-y", "cim", "--skip-modules=devel"]' has failed with status code='1'
```

A `docker ps` shows that the `drupaldev_drupal_1` container is no longer running and `docker:80` gives a connection refused.

Can you please advise if you see the same behaviour?

cheers,

Rob

**Comment by LightGuard** [comment]
@robpblake Okay, that's working. I do have a small concern, though. The PRs will continue to run until they timeout. We should probably be checking to make sure the containers are still running and bail if they terminated. That should fail the build pretty quickly if we fail the ruby process if containers die.

**Comment by robpblake** [comment]
@LightGuard Good point. I'll make an amendment to the build scripts to check that the container is actually still running after we've  run `docker-compose up`.

cheers,

Rob

**Comment by robpblake** [comment]
@LightGuard Following your feedback, I've updated the build scripts to fail now if the Drupal container disappears during boot.

Would you mind taking a quick look at the new changes. If you're happy, from my perspective this is good to merge.

cheers,

Rob

**Pull request merged**
