### PR TITLE
RHD-1068 - Added fail case for Developer materials

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by ollyjshaw** [comment]
ok to test

**Comment by paulrobinson** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by ollyjshaw** [comment]
@paulrobinson @Dantheman720 Please ignore the  jboss-developer-ci failure

**Comment by paulrobinson** [comment]
Preview: http://it-developers-pr.stage.redhat.com/pr/594/build/68/

**Pull request merged**
