### PR TITLE
[DEVELOPER-4044] Sync production Drupal content into staging environment

### PR DESCRIPTION
**Pull request by robpblake**
This pull-request adds the ability to sync content from production environment Drupal instance into the staging environment (developers.stage.redhat.com) Drupal instance. This is needed so that staging is more representative of production.

The work in this PR builds on what we know already works in dev and PR environments, namely using a Docker data image to obtain most of the content from Production. The staging Drupal instance has been re-configured in the `docker-compose.yml` for the `drupal-staging` environment to mount the active Drupal configuration and any images from production.

The major difference here is how we apply the database synchronisation. As the database in the staging environment is a fully IT managed MariaDB instance, we cannot use the current Docker-based approach to seed it with data from production. Therefore this PR adds a small Ruby class that will:

1. Take a backup of the current database
2. Drop the current database and re-create and empty version of it
3. Import the latest production database dump from the command line into this empty database.

All of the above is controlled via the [Sync_Production_Data](https://redhat-dev-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/developers.stage.redhat.com%20(Staging)/job/Sync_Production_Data/) Jenkins job. This job runs every night and resets the developers.stage.redhat.com Drupal instance to contain the latest production data. This means that essentially each night, the staging environment resets itself to be a mirror of production.

**For Reviewers:**

Unfortunately there isn't really a convenient way to test this PR ( a side-effect of different ways of managing databases in our environments) that doesn't involve playing around with the Docker configuration for the drupal-dev environment on your machine, but not committing the changes. 

I have tested it myself when working on it with a temporary Docker configuration on my local machine and have verified it works as expected, so perhaps just a comprehensive code review.

### CODE REVIEW

**Comment by robpblake** [comment]
@RubyGemTSL Can you cast an eye over the code on this one to make sure I'm not making any obvious mistakes.

I'd like to merge this one early in the day UK time so that I can then work with the staging environment to get things up and running. So lets co-ordinate a merge time if you're happy.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
@robpblake Looks good! I'll merge this first thing in the morning 👍

**Comment by robpblake** [comment]
@RubyGemTSL Can you ping me before you merge this so I can get the staging environment ready for the merge.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
will do @robpblake

**Comment by LightGuard** [comment]
I don't see any issues with the code. Where are we storing the backups for staging?

**Comment by robpblake** [comment]
@LightGuard The backup for staging gets stored onto the NFS mounted disk attached to the staging VM. I'm going to take a manual backup before I do this work so that we have a backup of staging before production data goes in. 

After that, the backups are really fairly inconsequential as the staging database will be an exact replica of the production database and it will get reset every night as well. I've added it as another line of defence, but in reality the backup gets over-written each night anyway.

cheers,

Rob

**Comment by robpblake** [comment]
@RubyGemTSL Given the instability in staging this week,  I'm going to let things settle today and ensure the environment is stable again before we do more things to it.  Lets perhaps look at getting this merged tomorrow.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
👍

**Pull request merged**
