### PR TITLE
[RHDX-228] Apply patternfly styles to tables

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-228](https://projects.engineering.redhat.com/browse/RHDX-228)

### Verification Process
The `<table>` markup rendered in wysiwyg fields does not inherit the .pf-c-table styles.
Rather than expecting editors or otherwise apply the classes to base tables,  we are extending the component styles to `.pf-c-content table`.

To review, view tables in the following places.
Also verify the old paragraph-based product Download tables are not affected by this change.
Also verify there is no need to use Foundation style tables anywhere on the site.

**In assemblies:**
https://developer-preview-3487.ext.us-west.dc.preprod.paas.redhat.com/devnationlive-austin/
https://developer-preview-3487.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/eclipse-vertx-cheat-sheet/

**Table, with headers, in article**
https://developer-preview-3487.ext.us-west.dc.preprod.paas.redhat.com/coderland/reactive/building-a-reactive-system/
https://developer-preview-3487.ext.us-west.dc.preprod.paas.redhat.com/articles/red-hat-developer-program-benefits/
https://developer-preview-3487.ext.us-west.dc.preprod.paas.redhat.com/products/amq/hello-world-amq-interconnect/#fndtn-macos

**Table, no headers, in article**
https://developer-preview-3487.ext.us-west.dc.preprod.paas.redhat.com/articles/hello-world-jboss-eap-runtime-codeready-studio/

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by staceymosier** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
One of the CSS `@import` statements is failing here:

```
Error: File to import not found or unreadable: helpers/tables.\n        on line 71 of node_modules/@rhdstyles/rhd-theme/_rhd-theme.scss\n        from line 40 of node_modules/@rhdstyles/rhd.scss\n>> @import \"helpers/tables\";\n\n   ^\n
```

**Comment by jordanpagewhite** [comment]
That formatting is bad, but check out line 71 of `./rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss` I think that is the `@import` statement

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by staceymosier** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Pull request merged**
