### PR TITLE
Update Drupal core to 8.7.11

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-105

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
This PR environment pulled in the content bug with the EAP product page that was resolved about a week ago. I am going to rebuild the environment. If you authenticate currently, you will experience a fatal error, but if you navigate to the logs, you will see that it is due to the EAP bug (pulled in via the db image), and not related to this Drupal core update.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
@rogeralloymagnetic / @jordanpagewhite The tests are failing because it doesn't look like `drush cim` is synchronising content fully on this PR. See attached screenshot:

Screenshot 2020-01-06 at 09 10 38

**Comment by rogeralloymagnetic** [comment]
@jordanpagewhite @robpblake Looks like tests are passing now. This should be ready for review.

**Comment by jordanpagewhite** [comment]
Thanks @rogeralloymagnetic I'll take a look in a moment when I get to a good stopping point in my current issue.

**Comment by staceymosier** [comment]
@jordanpagewhite   I viewed the site pages, content types and assemblies both anon and authenticated. I ran cron and a recache. I checked the REST views. I checked the recent logs and there are no new php errors/warnings.  I did not test the user roles.

**Pull request merged**
