### PR TITLE
DEVELOPER-3644 - Fix for the display issues on article pages

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@robpblake any idea why http://developers-pr.stage.redhat.com/pr/1582/export/articles/red-hat-developer-program-benefits is not in the export? The page exists in Drupal: http://stumpjumper.lab4.eng.bos.redhat.com:36582/articles/red-hat-developer-program-benefits and production: http://developers.redhat.com/articles/red-hat-developer-program-benefits/

**Comment by robpblake** [comment]
@paulrobinson It looks like to me the page is unpublished or something like that. It doesn't appear in the sitemap.xml here: http://stumpjumper.lab4.eng.bos.redhat.com:36582/sitemap.xml

and when I directly access the page:
http://stumpjumper.lab4.eng.bos.redhat.com:36582/articles/red-hat-developer-program-benefits

I get an "Access Denied" error.

**Comment by paulrobinson** [comment]
@robpblake yes it is unpublished. But for some reason there's this article in production: http://developers.redhat.com/articles/red-hat-developer-program-benefits/.

Any ideas how that could happen?

**Comment by paulrobinson** [comment]
@robpblake nevermind figured it out. will explain shortly.

**Comment by paulrobinson** [comment]
The issue was that in the PR builds, the article is still in draft, but has since been published in the production Drupal instance. Using an up-to-date dump of the production data would have resolved this.

**Comment by paulrobinson** [comment]
I've found a published article we can use to review this. It's being discussed on https://issues.jboss.org/browse/DEVELOPER-3644

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
FYI the old status is not cleared on your current PR's. Please ignore the old status: 'Drupal:Acceptance Tests' above.  New Pull-Requests will only include the new statuses:
- Drupal:FE KC/DM Acceptance Tests
- Drupal:FE Acceptance Tests

**Comment by LightGuard** [comment]
This does not look right at all any more.

**Comment by Dantheman720** [comment]
@LightGuard - it seems to be showing up alright on the articles. Have you noticed problems elsewhere?

**Pull request merged**
