### PR TITLE
Addresses RHD-1154

### PR DESCRIPTION
**Pull request by LightGuard**
This will probably be a long running PR, but RHD-1154 is ready to look at with this pull request

### CODE REVIEW

**Comment by paulrobinson** [comment]
Is this ready for review and merge?

**Comment by ollyjshaw** [comment]
@paulrobinson @LightGuard This all looks good from the stuff I understand. I can't really add much on the drupal specifics unfortunately.

**Comment by paulrobinson** [comment]
Needs rebase.

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
I got this working. Looks like i was being affected by https://issues.jboss.org/browse/RHD-1365 when I first ran it.

**Comment by paulrobinson** [comment]
However, it's not clear to me what to do, once I visit the site at: http://docker:32769/. Some docs would be useful.

**Pull request merged**
