### PR TITLE
DEVELOPER-2874 Microsite for DevNation promo code

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
Approved by Mike Guerette

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
Do not merge yet -  waiting on new image

**Comment by adelasofia** [comment]
Approved by Mike Guerette and Jason Brock

**Comment by LightGuard** [comment]
Still waiting on the image?

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@LightGuard Nope, the image is now in place. Good to go 👍

**Pull request merged**
