### PR TITLE
DEVELOPER-3554 Restyled Product page mobile view

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
[~adelaarreola] Does the download button need adjusting slightly? If you check for android and iOS in the chrome dev tools, it's smaller than the 'Get Started' button, and slightly off centre? Will email you a screenshot as I can't figure out how to add one with this comment.

**Comment by LightGuard** [comment]
@RubyGemTSL wouldn't #1502 address that?

**Comment by RubyGemTSL** [comment]
@LightGuard  - I'm not sure - I wasn't aware of that PR.

**Comment by LightGuard** [comment]
@RubyGemTSL @adelasofia merging this if the buttons still need a fix, please submit a new PR

**Pull request merged**
