### PR TITLE
[HOLD] Search Page - Developer 1795

### PR DESCRIPTION
**Pull request by wesbos**
Search page is done, I just need some help with the final tests that I can't figure out. 

@RubyGemTSL  - can you hep me here? specifically when I say `@page.search.send("pagination_#{pageNum}").click` - it doesn't trigger a click. I can see the CSS change because something is happening, but no action is taken. I've spent far too long trying to get these to work and I just don't understand what is wrong with it.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@wesbos i'll take a look

**Comment by RubyGemTSL** [comment]
@wesbos - have you tried clicking the page pagination manually? I can reproduce it manually. I.e. just try and click on page 2, 3, 4 or 5 and none of the links work. That is why the tests aren't clicking.

**Comment by wesbos** [comment]
@RubyGemTSL Okay - can you look over my tests and let me know what you think? I think they are all running - one of them has a TODO I'd like help with.

It seems to open in Firefox now and I get `      Net::ReadTimeout (Net::ReadTimeout)` about half the time after a 5 min wait

**Comment by RubyGemTSL** [comment]
@wesbos i raised a PR on your branch a couple days ago. The other tests looked good.

Once you have fixed the issue with pagination i'll help you finish them off.

Yes we had to change the default driver to firefox when we enabled the download tests.

What happens when you run a single scenario? using bundle exec rake wip? (on a scenario tagged @wip)

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
@wesbos we are looking at evaluating the results we get back from the DCP. However, I noticed that it's returning results for all content types, where is should just be for 'type=rht_website'. Can you update?

**Comment by wesbos** [comment]
@paulrobinson done

**Comment by LightGuard** [comment]
@wesbos Still on hold?

**Comment by wesbos** [comment]
@LightGuard Waiting on @RubyGemTSL to do the rest of the tests

**Comment by LightGuard** [comment]
@wesbos @RubyGemTSL Looks like this will need to have master merged to it due to the merge conflict.

**Comment by RubyGemTSL** [comment]
I've been trying to work on this today - however I can't build the site locally due to an error:
"Failed to initialize pipeline: No such file or directory @ rb_sysopen - _jdf-stack/stacks.yaml"

I also could not use the generated URL above as no results are found when searching, I just get a permanent loading spinner?

**Comment by wesbos** [comment]
@LightGuard Do you have any ideas on the above? 

@RubyGemTSL Can you merge in master? All the conflicts are in the tests.

Make sure you are on the vpn when searching too

**Comment by RubyGemTSL** [comment]
@wesbos I did merge master and was on the VPN.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Don't know why you wouldn't have that file @RubyGemTSL. Did you delete the _jdf_stacks folder, or the stacks.yaml file?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
@wesbos can you rebase this? We don't currently have a build that can be tried by Tiffany.

**Comment by wesbos** [comment]
@RubyGemTSL can you rebase and send a PR - the conflicts are in the tests

**Comment by wesbos** [comment]
@RubyGemTSL Did you rebase this?

**Comment by RubyGemTSL** [comment]
@wesbos - yes when you were on holiday and rasied another PR: https://github.com/redhat-developer/developers.redhat.com/pull/1038

**Comment by RubyGemTSL** [comment]
@wesbos - any update on this or #1038

**Comment by paulrobinson** [comment]
Replaced.

**Pull request closed without merging**
