### PR TITLE
DEVELOPER-3730 Fixes removing node links in sitemap

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@LightGuard is there a JIRA for this? If not, can you add some context to the PR description and an explanation of how to review it.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
FINALLY!!! @Dantheman720 This is just about done, it should be good to go. This is the update to what we were working on last night.

**Pull request merged**
