### PR TITLE
[RHDX-133] Configure Redirect 404

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-133](https://projects.engineering.redhat.com/browse/RHDX-133)

### Verification Process
View 404s in the environment.
Check the Reports -> Recent Log messages and verify 'Page not found' is no longer reporting here.
Check the Configuration -> Search and Metadata -> URL redirects -> Fix 404 pages and verify the page not found hits are recorded here.

The intention is to reduce writing logs to Recent Logs, but also provide a report for frequently hit invalid paths.

### CODE REVIEW

**Comment by staceymosier** [comment]
rebuild this please

**Comment by staceymosier** [comment]
The redirect_404 module has a conflict with the products route.

https://developer-preview-3466.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/download

Please do not merge until this is resolved.

**Comment by staceymosier** [comment]
> The redirect_404 module has a conflict with the products route.
> 
> https://developer-preview-3466.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/download
> 
> Please do not merge until this is resolved.

The recent push should fix this one.

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
