### PR TITLE
[HOLD] DEVELOPER-3714 Update content related to OpenShift

### PR DESCRIPTION
**Pull request by paulrobinson**
See: https://issues.jboss.org/browse/DEVELOPER-3714

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
The failing tests need to be updated to pass.

**Comment by RubyGemTSL** [comment]
@paulrobinson want me to update the tests for you?

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
It should pass now. The Openshift product name needed updating in Drupal on developers.redhat.com/products/

**Comment by paulrobinson** [comment]
@RubyGemTSL  can you review and merge please?

**Pull request merged**
