### PR TITLE
DEVELOPER-3196 - 'Docker Cheatsheet' Promo page

### PR DESCRIPTION
**Pull request by insectengine**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
this is OK to test

**Comment by LightGuard** [comment]
Who needs to sign off?

**Comment by insectengine** [comment]
This still needs the download to be added to the Download manager by Mark N.

**Comment by adelasofia** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
This needs some engineering work to get the download working. Closing this PR, but please don't delete the branch, as the Engineer will pull the commit from it.

**Pull request closed without merging**
