### PR TITLE
[HOLD] DEVELOPER-4184 Added 'DevNation Live' MVP Page

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4184 - Implement 'DevNation Live' MVP: Page](https://issues.jboss.org/browse/DEVELOPER-4184)
&&
[DEVELOPER-4247 - Implement 'DevNation Live' MVP: YouTube Live Chat](https://issues.jboss.org/browse/DEVELOPER-4247)

### CODE REVIEW

**Comment by paulrobinson** [comment]
This is looking good, thanks!

Can you make the upcoming sessions display the time in the user's current timezone?

**Comment by paulrobinson** [comment]
Should I see something in the chat area? See: https://www.dropbox.com/s/lk8jf7l30qubpqm/Screenshot%202017-06-28%2010.23.33.png?dl=0

**Comment by paulrobinson** [comment]
Also, can you change the displayed date format to: "20th July 2017 17:00 BST" or similar? Essentially Burr wanted a format that spelt out the month, rather than using numbers.

**Comment by paulrobinson** [comment]
The upcoming sessions seem to be missing a title.

**Comment by adelasofia** [comment]
Closing this. Luke will open a PR with my changes and his together.

**Pull request closed without merging**
