### PR TITLE
[DEVELOPER 5505] Install Compose Module

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5505

### CODE REVIEW

**Comment by robpblake** [comment]
@rogeralloymagnetic Merge conflict on `composer.json` and  `composer.lock`.

cheers,

Rob

**Comment by rogeralloymagnetic** [comment]
@robpblake Could you let me know what the test failure is here?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
