### PR TITLE
DEVELOPER-2851 Added branded error pages

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@adelasofia can you ask James to review?

**Comment by RubyGemTSL** [comment]
@paulrobinson - we probably should have a task in JIRA to test error branded pages now we have them? This is something that could be tested once we start using a web proxy to stub results.

**Comment by robpblake** [comment]
@paulrobinson Just noticed this issue. Additionally it is probably worth understanding how this applies to the Drupal version of the site (in particular the export).

**Comment by LightGuard** [comment]
For Drupal we'll want to edit the System -> Basic Site Settings to add these to the 404 and 403 sections.

**Comment by LightGuard** [comment]
Can't test this because there's no rules in apache currently to display these pages.

**Pull request closed without merging**
