### PR TITLE
[DONT MERGE] bump to ruby 2.3

### PR DESCRIPTION
**Pull request by ollyjshaw**

### CODE REVIEW

**Comment by LightGuard** [comment]
We'll want to update the .ruby-version file as well.

**Comment by paulrobinson** [comment]
Yeah, this needs changing: https://github.com/redhat-developer/developers.redhat.com/blob/838995354a379a8e4fb68e7f370d17706bd98de6/.ruby-version#L1

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Pull request closed without merging**
