### PR TITLE
DEVELOPER-3675 - Migrate Books content to Drupal

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by Dantheman720** [comment]
@paulrobinson - All of the books are in place here. I will be testing the searchisko functionality first things next week. You can see the books here:

http://stumpjumper.lab4.eng.bos.redhat.com:36694/admin/content?status=All&type=books&title=&uid=&langcode=All

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@LightGuard - Can you review and merge when you get the chance?

**Pull request merged**
