### PR TITLE
DEVELOPER-4640 - Fix DevSuite file versions to latest 2.2.0

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-4640

Since the version changes are a manual process we will have to do this every time for DevSuite and CDK.

### CODE REVIEW

**Comment by LightGuard** [comment]
Yuck. Any way we could automate this?

**Comment by LightGuard** [comment]
I'm good with this.

**Comment by rct** [comment]
Did this get merged?  I see the right filenames on the main downloads page now, but the download button on the product page still shows the old version.

**Comment by LightGuard** [comment]
@rct No, it still says open, it has not been merged yet. Would you like to review it at https://developers-pr.stage.redhat.com/pr/2180/export/products/devsuite/download/ ?

**Comment by Dantheman720** [comment]
Drupal-namespace.js is required for the product download page. I replaced this PR with https://github.com/redhat-developer/developers.redhat.com/pull/2184. My previous change broke the product downloads page.

**Pull request closed without merging**
