### PR TITLE
DEVELOPER-3316 	Migrated SO code to AngularJS

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Hi @adelasofia - I've been refactoring the acceptance tests with your changes to Search/Resources/SO pages. Would you like me to merge my changes into this branch and raise a PR on this? It will fix the failing tests. There's quite a lot of changes to the tests, but was much needed.

**Comment by adelasofia** [comment]
@RubyGemTSL that sounds good! thanks!

**Comment by RubyGemTSL** [comment]
@adelasofia - expect a PR at some point today. Just finishing off doing some tidying up of my branch.

**Comment by RubyGemTSL** [comment]
@adelasofia PR waiting for you now

**Comment by RubyGemTSL** [comment]
@adelasofia - tests looking good. Is this ready for someone to review?

**Comment by LightGuard** [comment]
This needs to be reviewed within the context of DEVELOPER-3420 as well. I believe @Dantheman720 is going to be looking into it.

**Comment by Dantheman720** [comment]
@LightGuard @adelasofia This can be merged. I have drupal namespace updated and everything should work once that is merged.

**Pull request merged**
