### PR TITLE
Update devnation-pass-giveaway.adoc

### PR DESCRIPTION
**Pull request by brocked**
Adding link to DevNation Pass Giveaway T&Cs

### CODE REVIEW

**Comment by adelasofia** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@brocked There is no page for terms and conditions here, it 404s.

**Comment by LightGuard** [comment]
@RubyGemTSL @robpblake Not sure why the builds are not calling back that tests are done, did something change?

**Comment by LightGuard** [comment]
@brocked Looks like you created another PR for it, got it.

**Pull request merged**
