### PR TITLE
Developer 3437 - add rubocop and fix offences.

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@paulrobinson @LightGuard this is good to go

**Comment by RubyGemTSL** [comment]
actually don't merge yet. I've decided to make some small changes.

**Comment by LightGuard** [comment]
@RubyGemTSL Just let us know when

**Comment by RubyGemTSL** [comment]
@LightGuard @paulrobinson good to go now - finished making some changes.

**Pull request merged**
