### PR TITLE
[DEVELOPER-5501] New Product assemblies and content type updates

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* [Product Download List](https://issues.jboss.org/browse/DEVELOPER-5501)
* [Product Download Hero](https://issues.jboss.org/browse/DEVELOPER-5497)
* [Product Try It Hero](https://issues.jboss.org/browse/DEVELOPER-5499)
* [Update Product Content Type](https://issues.jboss.org/browse/DEVELOPER-5492)

### Verification Process

* You can now create the following assembly types: Product Download List, Product Download Hero and Product Try It Hero
* If a value is present for the Product Download Page field on a Product node, a new page+route should exist at `/products/[field_url_product_name]/downloads` e.g. `/products/rhamt/downloads`. That page should render whatever assemblies are referenced in the Product Download Page field on that Product node.
* Similarly, if a value is present for the Product Try It Page field on a Product node, a new page+route should exist at `/products/[field_url_product_name]/getting-started` e.g. `/products/rhamt/getting-started`. That page should render whatever assemblies are referenced in the Product Try It Page field on that Product node.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
h3. Feedback from call with UX

h5. Requested changes

* Remove page title from Downloads and Getting Started pages
  * The 'page title' will be the title of the top-most assembly. This will rely upon editorial decision making, governance, etc.
* Add a title field to the Download List assembly type
* Change all instances of 'Try It Page' to 'Getting Started Page'
* Add optional link text to the Learn More link field
* Add an Assembly field to the Product node that will contain all of the content for the new version of the actual Product page
* Add a Boolean field to the Product node that, when checked, will use the new assembly-based Product pages (Downloads and Getting Started too)
  * This will also need to include the routing, etc.
  * If the field is uncheck (False), then everything should behave exactly as it is now
* Remove the background image fields on the Download Hero and Try It Hero assembly types. These will be implemented as visual styles.

h5. Additional discovery

* Test the checkboxes and radios widget for the visual styles assembly type field
  * Report findings to UX
* Determine if we can add a description to the visual styles field to inform users that they can select multiple (?) This may be more challenging since the field is provided by the module, and this may become more evident if the checkboxes/radio widget works.

h5. Notes

* We will be using visual styles to implement the background images on the Download Hero and Try It Hero assembly types. Styles to be provided by SJ.

**Comment by sjcox-rh** [comment]
@jordanpagewhite Here are the two backgrounds to be used on the Try it Hero and Download Hero.  There is one for the light visual style and another for a dark visual style.

producthero_darkbackground
producthero_lightbackground

Let me know if those dimensions don't work!

**Comment by jordanpagewhite** [comment]
## Remaining changes to implement after commit(s) pushed (moments ago)

#### Requested changes

* Add an Assembly field to the Product node that will contain all of the content for the new version of the actual Product page
  * I created a Google sheet with all available assembly types that UX will use to determine which assembly types should be available to editors
* Add a Boolean field to the Product node that, when checked, will use the new assembly-based Product pages (Downloads and Getting Started too)
  * This will also need to include the routing, etc.
  * If the field is uncheck (False), then everything should behave exactly as it is now

#### Notes

* SJ has provided the backgrounds for the light and dark visual styles above. These will be the visual styles on the Try it Hero and Download Hero components for our initial release of these updated/new Product pages

**Comment by jordanpagewhite** [comment]
## Updates

This latest commit(s), which I pushed moments ago, include all of the outstanding edits listed under Requested Changes in the comment above. We still have to implement the background using the assembly visual styles.

#### Notes

* SJ has provided the backgrounds for the light and dark visual styles above. These will be the visual styles on the Try it Hero and Download Hero components for our initial release of these updated/new Product pages

## Next steps

* Review this PR once the PR environment builds

**Comment by jordanpagewhite** [comment]
## Updates

This latest commit(s), which I pushed moments ago, includes adding the light, dark, centered and slim visual styles to the Product Download Hero and Product Try It Hero assembly types.

## Next steps

* Review this PR once the PR environment builds

## Remaining work after PR is merged

Actually writing the CSS/styles to make the classes added by the visual styles work. This can be done in the Style tickets for these 2 assembly types unless anyone else feels otherwise.

**Comment by robpblake** [comment]
@jordanpagewhite Who needs to review and sign-off on this one?

cheers,

Rob

**Comment by jordanpagewhite** [comment]
@sjcox-rh Will be reviewing this ticket. I don't believe that she has been online since my latest changes, except for perhaps this morning, due to the holiday. Thanks Rob and SJ.

**Comment by sjcox-rh** [comment]
@jordanpagewhite Tested out all the updates. Looking good! I just have a couple of comments.

1. Referencing this update - "Add an Assembly field to the Product node that will contain all of the content for the new version of the actual Product page"
- I see the section to add assemblies under the content header. I'm assuming this is where you would add a hero and additional assemblies to add to the product page. However, it's currently showing an assembly field widget. Is that what we want to show here? Or should it be the assembly creation experience? I was trying to add a download hero to the product page and couldn't do it successfully.

2. For the Try It Hero, do we want to give users the ability to change the text on the "Try It" button? @tiffanynolan. Also, would it be possible to change the title of this section to "Try It Button" as opposed to "Try It Link". It threw me off for a second.

3. When I went to preview all the hero's I created, the page was blank. Wasn't sure if this was because I created this in a staging environment, but just wanted to make sure this wasn't broken. Would love to be able to preview the hero's to make sure they look good :]

Let me know if I'm just doing something wrong (which is very likely) when creating a test product page.

**Comment by jordanpagewhite** [comment]
In my latest commit, I have re-ordered the new product page fields on the Product node edit form, as requested by Tiffany. I also grouped them in a way that I believe will be more intuitive to editors. Please let me know if you feel otherwise.

127 0 0 1_8888_node_37375_edit_destination _admin_content

**Comment by LightGuard** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
### Updates

There was a conflict on the /products/[product-url-code]/download URL
pattern between the current implementation of the Product pages and this
new implementation. To resolve it, I had to add logic to both
controllers that handled each routing condition based upon whether or
not the 'Use New Product Page' boolean field on a given Product node
was, or was not, checked.

Furthermore, this commit provides more assembly types on the Downloads
Page Content field, as requested by Tiffany. These changes can be seen
in our running Google sheet.

### Remaining work

* @tiffanynolan discussed in Slack the idea of altering the existing redirect present on production that redirects from `/products/[product-url-code]` to `/products/[product-url-code]/overview` CC: @sjcox-rh If we can nail down this requirement ASAP, I would appreciate it. Would this need to be included in an MVP?

**Comment by jordanpagewhite** [comment]
The js-e2e-tests have 1 failure because the `<title>` of `/products/rhel/download/` is:

`<title>Red Hat Developer |</title>` 

instead of:

<title>Red Hat Developer | Red Hat Enterprise Linux Download</title>

It seems that this discrepancy might be somewhere in the custom code that handles the custom routing for the existing Product page routing/templates.

### Next steps

* Resolve issue resulting in incorrect <title> value of Product sub-pages (possibly only the /download sub-page)

**Comment by tiffanynolan** [comment]
@jordanpagewhite Since we have the metatags fields now on the Drupal pages, including the product page, do we still need to have that title check as part of the tests?

cc: @sjcox-rh

**Comment by jordanpagewhite** [comment]
My latest commit fixes an issue that ultimately resulted in missing <title> tag
content for the /download and /getting-started routes. This sets the
dynamic page title, as we would expected in transitioning for our old
approach, so that Metatag can properly identify the content that needs
to go into the <title> tag.

### Next steps

Verify changes on PR environment

**Comment by tiffanynolan** [comment]
@jordanpagewhite @sjcox-rh Changes look good as far as I can tell. This should be ready to merge.

**Pull request merged**
