### PR TITLE
Fixed JBDSIS instructions

### PR DESCRIPTION
**Pull request by cvanball**

### CODE REVIEW

**Comment by LightGuard** [comment]
this is okay to test

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
1 failure that has no impact on this PR. 

This is due an issue with a registration tests test outside of the PR. https://issues.jboss.org/browse/DEVELOPER-3276

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
Who needs to verify this?

**Pull request merged**
