### PR TITLE
DEVELOPER-2885 Articles in Drupal

### PR DESCRIPTION
**Pull request by LightGuard**
Layout files and small module additions within drupal

### CODE REVIEW

**Comment by LightGuard** [comment]
@Dantheman720 since you're the only other one who has it up and running on their box, would you mind taking a look at this and see if it matches the "Definition of Done", and following comments, in the ticket?

**Comment by Dantheman720** [comment]
@LightGuard Will do.

**Comment by Dantheman720** [comment]
The images currently are not being added to the body text. I think it would be easier for the user to add the image tags directly to the html so that users have the flexibility of adding the images wherever they want.  Other than that, I think it's pretty intuitive.

https://www.dropbox.com/s/e883atq5ke6n9c2/DrupalArticle.mp4?dl=0

**Comment by LightGuard** [comment]
@adelasofia according to @Dantheman720 this is good to merge, mind handling the merge?

**Pull request merged**
