### PR TITLE
DEVELOPER-4303: OneBox - OneBox E2E Testing

### PR DESCRIPTION
**Pull request by RubyGemTSL**
Adding tests for [OneBox search component ](https://issues.jboss.org/browse/DEVELOPER-4302)

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL Good to go?

**Comment by RubyGemTSL** [comment]
@robpblake I just assigned it to Luke as he worked on the oneBox implementation. He may want to check out the test scenarios before merging to see if I'm covering all cases.

**Comment by RubyGemTSL** [comment]
@KamiQuasi yes I thought it was strange that searching for "Red Hat Container Development kit" wasn't a keyword for " Red Hat Container Development kit wasn't a keyword for "

**Pull request merged**
