### PR TITLE
[DEVELOPER-5862] [DEVELOPER-5863] [DEVELOPER-5864] Assembly Fields Audit

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5864

### Verification Process
Look at "Audience Selection" fields in all assemblies and verify that they are all checkboxes.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by sjcox-rh** [comment]
UX approved for merge!

**Pull request merged**
