### PR TITLE
DEVELOPER-4199 - Unit tests updated for new search

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks good, lots of skipped tests, @Dantheman720 is that expected?

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
Is this good to go?

**Comment by LightGuard** [comment]
@KamiQuasi could you take a look at this one? You know those tests better than I. It looks like it's good, all the tests are running and passing.

**Comment by Dantheman720** [comment]
@KamiQuasi @LightGuard - My guess is that Luke will have some suggestions here. I converted it to work with the Typescript code and reworked some of the tests.

**Comment by robpblake** [comment]
@KamiQuasi Can you take a look at this one as it looks like Dan thinks you may have some suggestions/comments.

cheers,

Rob

**Pull request merged**
