### PR TITLE
[DEVELOPER-3018] Patch content_moderation_notifications module

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### Github Issue Link
* #3018 

### Verification Process
1. Create test content moderation role
2. Add user to the new role
3. Create content moderation notification rule using the new role
4. Modify a content node in a way that will send a notification email as per your setup in step 3
5. Check that email is sent successfully to role and author
6. Change user status to "Blocked" for user in new role and author
7. Check that no email is sent to the blocked users

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
These code changes, including the patch on drupal.org, look good to me. Thank you @rogeralloymagnetic I will test out the changes on the PR environment when it builds successfully.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
I am having difficulty testing this PR. I created a new user with a test email address like  jowhite+example@redhat.com. I figured that these would still send to my inbox, but I didn't receive anything. @robpblake Are you aware of a way that I can test emails on PR environments? Will the PR environment send to non-RH gmail addresses? I am trying that now.

**Comment by robpblake** [comment]
@jordanpagewhite I just tested with my RH email address and also my RH email address with the `+example` suffix. Both emails have turned up fine.

This still not working for you?

**Comment by rogeralloymagnetic** [comment]
I wasn't able to get email variables to work when I was testing either. I
changed my test user's address to my main r.c email account.

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
@rogeralloymagnetic What's the status of this one please?

cheers,

Rob

**Comment by rogeralloymagnetic** [comment]
@robpblake I've rebased with master and will wait to make sure the tests pass. This was a special request from @jordanpagewhite and should be good to go once he's had a chance to review it.

**Comment by robpblake** [comment]
@jordanpagewhite Can you please review and merge/close this as appropriate.

cheers,

Rob

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
