### PR TITLE
DEVELOPER-1972-use docker selenium for ac tests

### PR DESCRIPTION
**Pull request by RubyGemTSL**
wip

taking away pretty output as it doesn't look good with parallel tests and just confuses people looking at results.

adding fix for random chrome crashes

minor update to changes in site nav login/register links

minor update to rake file

removed debug puts that are cluttering the console output.

removed debug puts that is cluttering the console output.

fixed flaky tests

wip

added wait for ajax to complete when switching back to PR environment from staging (during downloads)

reducing processes to test on jenkins

ignoring download tests for now

fixed broken yml file

took out not necessary wait_for_ajax

logout method should not be attempted of the page title contains Status 500.

added debug puts message

removed a failing scenario due to work that is currently being carried around this scenario. Will be re-enabled once this work is complete.

revert last commit

removed rescue for attempting to navigate to login/register pages. If this causes test failures it is not a test issue, it is a site issue that needs fixing. we shouldn't have to hack the tests around flaky site functionality.

renamed driver to match current jenkins acceptance test job.

increasing processes.

increasing processes.

increasing processes.

increasing processes.

bump selenium version

bump selenium version

removing gemfile.lock

re-added gemfile.lock

re-added gemfile.lock

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
New Acceptance test job for this work can be found here:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/

**Comment by RubyGemTSL** [comment]
Once this is merged the old AC test job will be replaced with http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
This is looking good, @RubyGemTSL are you okay with this being merged now?

**Comment by RubyGemTSL** [comment]
@LightGuard - great! Yes - Once you merge just ping me and i'll switch the PR builder to point to the docker selenium test job.

**Comment by RubyGemTSL** [comment]
@LightGuard - actually could you hold off on this for a couple hours? I'll let you know when it's ready. I need to check that I dont get an error installing report_builder. Its seems to be happening within docker. I'll take it out if so as there is another ticket for this going into the current sprint.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@LightGuard this can be merged now. Thanks.

**Pull request merged**
