### PR TITLE
[SURGE 3099] Events Hero Assembly

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3099
* https://github.com/redhat-developer/developers.redhat.com/issues/3149

### Verification Process

Go here: https://developer-preview-3173.ext.us-west.dc.preprod.paas.redhat.com/

1. Create or use an existing Events Hero assembly
2. Add 1, 2 & 3 events to see each different layout
3. Make sure each event you add has presenters assigned

### Known issues
* https://github.com/redhat-developer/rhd-frontend/issues/364
* ~~https://github.com/redhat-developer/developers.redhat.com/issues/3172 (not a visible issue)~~
* ~~https://github.com/redhat-developer/rhd-frontend/issues/317~~
* ~~https://github.com/redhat-developer/rhd-frontend/issues/311~~

### Updated Screenshots
Screen Shot 2019-10-15 at 9 50 29 AM
Screen Shot 2019-10-15 at 9 49 44 AM
Screen Shot 2019-10-15 at 9 43 49 AM
Screen Shot 2019-10-15 at 9 47 10 AM
Screen Shot 2019-10-15 at 9 44 31 AM
Screen Shot 2019-10-15 at 9 45 13 AM

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Review by gdoyle1 — CHANGES_REQUESTED** [review]
@rogeralloymagnetic @jordanpagewhite Only thing I am seeing here is that the background image was stripped out (the one that is currently implemented). The visual styles are good other than that!

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 There's a "Background Image" field available in line with other assemblies that can be used by the content manager to directly assign a background image.

**Comment by gdoyle1** [comment]
@rogeralloymagnetic  We used to have the default background with that background image -  @sjcox-rh is that something we still want? I'm assuming I'd just create a ticket in the frontend repo for that but unsure

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 & @sjcox-rh I've added the default background in, but this is blocked by the other Events Hero changes that need Drupal markup changes.

**Comment by gdoyle1** [comment]
@rogeralloymagnetic Okay will approve this then!

**Review by gdoyle1 — APPROVED** [review]

**Pull request merged**
