### PR TITLE
DEVELOPER-5058 && DEVELOPER-4763 Removing awestruct take two

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by KamiQuasi** [comment]
Think we'll need to point the tests at the new JS file to make them pass.

**Comment by LightGuard** [comment]
@KamiQuasi what needs to happen? Is it an include or something somewhere?

**Comment by KamiQuasi** [comment]
`/Users/ldary/rh/developers/_tests/unit/config/karma.conf.js` just needs to point from `../../../javascripts/build.js` to the rhd.min.js file in the new theme I believe.
You could also bump the version on the web components stuff up to 1.2.0 while you're in there too.

**Comment by LightGuard** [comment]
@KamiQuasi any other ideas?

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
It was being kept around as a base to look at for removing awestruct, but we can close it.

**Pull request closed without merging**
