### PR TITLE
Removed xPaaS content for DevSuite

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@MikGue can review this I think.

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by MikGue** [comment]
Testing is showing spotty results so this is not ready for GA

From HipChat:

[4:24 PM] Jason Brock: @JasonPorter I see this:
[4:24 PM] Jason Brock: 
    File uploaded: Screen Shot 2016-09-13 at 3.24.16 PM.png
    [https://s3.amazonaws.com/uploads.hipchat.com/405735/2699617/NDCRxfqvSNMPcPN/Screen%20Shot%202016-09-13%20at%203.24.16%20PM.png]
[4:24 PM] Adela Arreola: Same here
[4:25 PM] Mike Guerette: @brock @Adela which browser?
[4:25 PM] Ray Ploski: I see 10.0.0 - Restricted in Vivaldi, Chrome and Safari.  Fails in FF
[4:25 PM] Jason Brock: Chrome. Latest release.
[4:26 PM] Jason Brock: Also works in Safari. But similar to Ray, no luck in FireFox
[4:26 PM] Jason Porter: @MikeGuerette okay, your call then.
[4:26 PM] Mike Guerette: too weird.  For me, works on FF, but not on Chrome or Safari.
[4:27 PM] Mike Guerette: I don't think we can put this out @JasonPorter
[4:27 PM] Mike Guerette: 1/3 of the browsers fail

**Comment by paulrobinson** [comment]
@MikGue are you commenting on the right PR? I'm not sure how the presence of '10.0.0 - Restricted' relates to this change.

This fix is simply to remove the 'JBoss xPaaS Services for OpenShift' section from the page. This seems to have worked.

Before: https://www.dropbox.com/s/oakjx2qi4jjwj93/Screenshot%202016-09-14%2011.57.10.png?dl=0
After: https://www.dropbox.com/s/ilar8cvf0hhx1wc/Screenshot%202016-09-14%2011.57.21.png?dl=0

**Comment by MikGue** [comment]
The removal of the xPaas, for whatever reason, is rendering differently by user and browser.  You can see that from the HipChat recording and these attachments show A) what I'm seeing, and B) the Javascript console from my Chrome browser.

I'm not comfortable releasing this update until we're all able to view correctly.  Please advise on next step and/or if you believe this should be released.

Mike
screen shot 2016-09-13 at 4 19 28 pm
screen shot 2016-09-13 at 4 12 22 pm

**Comment by paulrobinson** [comment]
@MikGue this is odd. Do you know if anyone tested to see if it is also broken in production? Might be a separate issue that we already have.

**Comment by MikGue** [comment]
I have not.

**Comment by paulrobinson** [comment]
@jkbrock sees this in production also. I think we can merge this PR, but we do need to investigate the issue @MikGue reports.

**Comment by LightGuard** [comment]
@paulrobinson @MikGue Are we good to merge then?

**Comment by paulrobinson** [comment]
Looks good to me

**Comment by MikGue** [comment]
yes thanks.

**Pull request merged**
