### PR TITLE
[DEVELOPER-3394] Katacoda course hero spacing

### LINKED ISSUE #3394: (1) /courses/[course-name]
**Estimate:** 1

**Description**
The course page heros should match the spacing as seen on the heros on the /courses page.
Follow up issue to #3190 

**To Reproduce**
1. Start any of the courses on developers.redhat.com/courses
2. Hero up top is the one I'm referring to

**Expected behavior**
The hero spacing should match what is seen on the /courses page which is 24px above and below the content. 

**Screenshots/GIFs**
This is what I'm currently seeing
Screen Shot 2019-11-20 at 12 20 11 PM

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### Github Issue Link
Resolves #3394 

### Verification Process

Open 2 tabs and

Go here: https://developer-preview-3403.ext.us-west.dc.preprod.paas.redhat.com/courses/

You should see this:

Screen Shot 2019-11-23 at 9 43 52 AM

and go here: https://developer-preview-3403.ext.us-west.dc.preprod.paas.redhat.com/courses/service-mesh/

You should see this:

Screen Shot 2019-11-23 at 9 44 30 AM

In general, the 2 hero components should have the same spacing and general styling applied as much as possible given that the content will not be identical.

**NOTE:** There might appear to be slightly more spacing on the bottom of the hero on https://developer-preview-3403.ext.us-west.dc.preprod.paas.redhat.com/courses/service-mesh/ This is because of the padding of the button though, which I don't _think_ we want to alter/remove but let me know what you think.

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by sjcox-rh** [comment]
@jordanpagewhite 24px top and bottom padding looks good on these page heroes. 

Addressing your question on the button padding, I agree we don't want to remove the padding on the button, especially since it's the same button styling used throughout the site. 

I did notice a 4px margin on the bottom of the button though on the istio page. Is that something that can be removed? It's not much, im just not sure why it's there.

**Comment by jordanpagewhite** [comment]
@sjcox-rh Yes, absolutely. I just pushed up a commit that removes those 4px of margin-bottom on the Katacoda hero CTA. The environment should rebuild shortly and be ready to re-test. Thanks.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by gdoyle1** [comment]
@jordanpagewhite it looks like that 4px padding is still appearing because the Learn more CTA is in a < p >. I'm looking at this link here: https://developer-preview-3403.ext.us-west.dc.preprod.paas.redhat.com/courses/openshift-operators/. The /courses page looks good though!

**Comment by jordanpagewhite** [comment]
@gdoyle1 Okay, sounds good. I can take care of that. I think that you are referring to the padding, whereas SJ was referring to the margin. Do we generally want the last children of an assembly container to have 0 margin-bottom and 0 padding-bottom? It would be cleaner to create a rule like "all of the last children of an assembly container have 0 margin-bottom  and 0 padding-bottom" (for example) instead of creating/maintaining rules for each instance.

**Comment by jordanpagewhite** [comment]
Oh, or perhaps you're referring to the margin-bottom: 8px on the last <p> element within  the assembly container? That's probably it. Either way, we should  determine if this is a general case or just specific to this instance. Thanks.

**Comment by gdoyle1** [comment]
@jordanpagewhite Sorry just seeing this now - I did mean the 8px on the last < p > that includes the Learn More link. Would replacing it with a link button (seen here: https://redhat-developer.github.io/rhd-frontend/components/btn-cta/) be possible? I realize that it will still have padding around it as other buttons do. This would definitely be a one time instance type of thing. If replacing with a link button doesn't make a difference to the padding underneath then I can just approve this!

**Comment by robcoffman** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
I am closing this for now in hopes that it will make managed platform work. I can reopen it later.

**Pull request closed without merging**
