### PR TITLE
DEVELOPER-3696 Change "Private Cloud" label to just "Cloud"

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by LightGuard** [comment]
I think you're missing some other places within Drupal

**Comment by paulrobinson** [comment]
@LightGuard agreed. i'll need to make those changes on the Drupal server around the same time as this is merged.

**Comment by paulrobinson** [comment]
This test will pass once the change is made on the drupal server:

timed out after 30 seconds, waiting for {:id=>"cloud", :tag_name=>"div"} to be located (Watir::Exception::UnknownObjectException)
./_cucumber/lib/pages/technologies_page.rb:13:in `product_title'
./_cucumber/features/step_definitions/technologies_steps.rb:7:in `block (2 levels) in '
./_cucumber/features/step_definitions/technologies_steps.rb:7:in `each'
SD: ./_cucumber/features/step_definitions/technologies_steps.rb:7:in `/^I should see product sections with headings$/' 
FF: _cucumber/features/technologies/technologies.feature:11:in `Then I should see product sections with headings'

**Comment by paulrobinson** [comment]
Merging myself as Rob and Ian are away today. Plus it requires careful timing to get both the awestruct and drupal changes in together. Finally it't pretty trivial and Jason has already looked at it.

**Pull request merged**
