### PR TITLE
[DEVELOPER-4094] Remove hard-coded production links from Drupal content

### PR DESCRIPTION
**Pull request by robpblake**
This PR attempts to remove any hard-coded production links from content within Drupal. It does this by replacing the FQDN of the current production Drupal instance from the content stored within the Drupal database. 

For example, links are rewritten as follows:

`http://developer-drupal.web.prod.ext.phx2.redhat.com/foo/bar` becomes `/foo/bar`

To test:

- Ensure all tests are reporting as working correctly
- Inspect the Blinkr report attached to this PR. There should be zero incorrect environment warnings in the report.

### CODE REVIEW

**Comment by robpblake** [comment]
@RubyGemTSL Could you take a look at the Blinkr report on this one when the build is complete to make sure the environment warnings are what you would expect?

cheers,

Rob

**Comment by RubyGemTSL** [comment]
@robpblake looks good. The report doesn't contain any incorrect environments.

It contains 22 errors (broken links) which are not actually broken links. It's has discovered an issue with blinkr. The links just display code snippets of a pom.xml file. I've taken a copy of the report and will look at a fix tomorrow (Wed's).

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL From your perspective this is good to go?

@LightGuard Any concerns from you on this one?

cheers,

Rob

**Comment by RubyGemTSL** [comment]
@robpblake looks good to me 👍

**Pull request merged**
