### PR TITLE
FUSEDOC-1661 Refactored EAP tab in Fuse Get Started

### PR DESCRIPTION
**Pull request by fbolton**
This pull requests implements [FUSEDOC-1661](https://issues.jboss.org/browse/FUSEDOC-1661), which is an enhancement request to document the steps for installing the Fuse on EAP runtime explicitly in the Get Started doc, instead of referencing the JBoss Fuse product docs on the customer portal.

### CODE REVIEW

**Comment by robpblake** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
The test failures are expected, so this is safe to merge.

**Comment by paulrobinson** [comment]
Just waiting on approval from the Fuse team.

**Comment by fbolton** [comment]
The preview looks good to me, @paulrobinson. I approve the merge.

**Pull request merged**
