### PR TITLE
DEVELOPER-2567 - Topics visual updates

### PR DESCRIPTION
**Pull request by Dantheman720**
Having difficulties with the ellipsis colors.  Also, it doesn't seem to be supported with FF.  I am currently working on a solution.

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
Don't spend too long fighting with this. I'm sure @adelasofia or @wesbos would be able to get you on track pretty quickly.

**Comment by paulrobinson** [comment]
@adelasofia can you do a code review please.

**Comment by adelasofia** [comment]
@paulrobinson I don't think the issue with the ellipsis color is fixed here, I'll try to fix it today and send @Dantheman720 a PR :smiley:

**Comment by paulrobinson** [comment]
@adelasofia not sure if you heard the conversation with Wes, but we concluded that the ellipsis colour issue is a browser bug.

**Comment by paulrobinson** [comment]
retest this please

**Comment by adelasofia** [comment]
@paul Approved by @insectengine and I :+1:

**Pull request merged**
