### PR TITLE
[RHDX-139] Remove blog_posts assembly.

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-139

### Verification Process
1. Login
2. Navigate to /node/210205/edit
3. See that the "Blog Posts" assembly is now a "Dynamic Content" module
4. Navigate to /admin/structure/assembly and see that "Blog Posts" module is empty
5. Create a new Product node
6. Add a new assembly and see that "Blog Post" is no longer available

### Note
* Blog Post assembly content will have to be deleted from developers.redhat.com before merging this in or it will cause an error.
* I'm not sure how this will effect the testing environment and will check once the PR env is live.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
Jordan removed the three instances of the Blog Post assembly on Production. This PR can be rebuilt tomorrow morning once the new database image has synced.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
I just remembered why this won't build today 🤦‍♂ I will sign off for now. Ha

**Comment by robpblake** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Review by staceymosier — CHANGES_REQUESTED** [review]
Can you please check the hook in rhd_assemblies.module `rhd_assemblies_theme_registry_alter` and the twig templates there as well.  
And are you keeping `rhd_assemblies/src/Plugin/AssemblyBuild/BlogPostsBuild.php`?

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
This looks good to me after the latest commit. @staceymosier Can you give this another review when you have a chance?

**Review by staceymosier — APPROVED** [review]

**Pull request merged**
