### PR TITLE
[DEVELOPER-5663] Disable Taxonomy Term Views Pages (not tags)

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This disables the View pages generated by the taxonomy_term View except
for the tags taxonomy terms/vocab.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5663

### Verification Process

Go here: /taxonomy/term/8725 (8725 is a taxonomy term id under the product_categories vocabulary)

You should see the RHDP 404 Page Not Found page/template.

### CODE REVIEW

**Comment by robpblake** [comment]
@jordanpagewhite I think you need to merge master into your branch as you seem to be missing updates to tests to support the new login page.

cheers,

Rob

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
This requires approval from Joe and/or SJ prior to being merged

**Pull request merged**
