### PR TITLE
DEVELOPER-1786 - Added requested images and updated events page with …

### PR DESCRIPTION
**Pull request by Dantheman720**
…JUDCon Brno

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please.

**Comment by paulrobinson** [comment]
You don't need to add 'images/events/events_judcon2016brno.png' that image is used for the event cards, and is managed by @insectengine.

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Pull request merged**
