### PR TITLE
DEVELOPER-2927 Fixed anchor links in Technologies Menu

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
@adelasofia @paulrobinson looks like we have some dead videos, not sure if this is just in staging or in prod too.

**Comment by paulrobinson** [comment]
@LightGuard: What 'dead videos' do you mean, and where are they linked from? Can it be caused by this PR?

**Comment by LightGuard** [comment]
http://developers-pr.stage.redhat.com/pr/1103/build/1181/video/youtube/i5V5kRFUyxI/ is an example. There are related videos at the bottom of the page, like Mobile Field Workforce Management Demo, that don't exist on YouTube, but supposedly we have pages for them, which we don't. You can find them through blinkr. I'm not sure if that's a symptom of stale data in the DCP or an actual problem.

**Comment by LightGuard** [comment]
I just checked http://developers.redhat.com/video/youtube/i5V5kRFUyxI/ we have the problem in the live site as well.

**Comment by paulrobinson** [comment]
Ok, so looks like a separate issue. Can you raise a JIRA issue?

On Thu, May 19, 2016 at 5:30 PM, Jason Porter <notifications@github.com>
wrote:

> I just checked http://developers.redhat.com/video/youtube/i5V5kRFUyxI/ we
> have the problem in the live site as well.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1103#issuecomment-220379577>
>



-- 
Paul

-----
Paul Robinson
Red Hat Developer Program Engineering (Web Development lead)
JBoss Developer Program (Web Development lead)

Free/busy info:
https://www.google.com/calendar/embed?src=probinso%40redhat.com&ctz=Europe/London

JBoss, a Division of Red Hat
Registered in England and Wales under Company Registration No. 03798903
Directors:Michael Cunningham (US), Charles Peters (US), Matt Parson (US),
Paul Hickey (Ireland)

**Comment by LightGuard** [comment]
DEVELOPER-3054 has now been created

**Pull request merged**
