### PR TITLE
DEVELOPER-2828 Save selected tab in Get Started pages

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia Who needs to sign off?

**Comment by adelasofia** [comment]
@LightGuard Just approved by Mike G.

**Comment by RubyGemTSL** [comment]
Export Hold issue on account when downloading. Will report.

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
