### PR TITLE
[RHDX-302] Removed what is not used of PFE

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-302

### Verification Process
Build should go green and the site should look and function the same as the current live site.

### CODE REVIEW

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
rebuild this please

**Pull request merged**
