### PR TITLE
[HOLD] Add driver binaries

### PR DESCRIPTION
**Pull request by RubyGemTSL**
Re-added driver binaries as the Gemfile solution just didn't cut it.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@robpblake the issue that we seen here appears to be an issue with the latest version of selenium. I dropped back to the same version as master and tests are passing again.

**Comment by robpblake** [comment]
@RubyGemTSL There is a now a merge conflict on this PR. I merged your fixes to the registration tests first.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Rob, placed this on hold whilst I figure out the issues locally.

**Pull request closed without merging**
