### PR TITLE
[DEVELOPER-5670] - add new breakpoint for medium 992px

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5670

### Verification Process
add a rich text column assembly to a page with three cols, test at portrait tablet size cols should wrap and be underneath each other.

### CODE REVIEW

**Comment by sjcox-rh** [comment]
@alistairmc Just reviewed the PR. It's fixed for portrait tablet mode. However, it's still needs to be adjusted in responsive mode. When I'm on my desktop and I decrease the window size, the columns width just decreases incrementally from 768-1000 so that the line length is 1-3 words. It doesn't adjust to single column stacking until after 768.  Is this something that can be adjusted?

**Comment by alistairmc** [comment]
@sjcox-rh once this has built give it a test and see what you think, has to tweak some title font sizes since it looked odd.

**Comment by sjcox-rh** [comment]
@alistairmc Much better! This is ux approved!

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this

**Comment by robpblake** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
@adelasofia would you be able to review this please

**Pull request merged**
