### PR TITLE
Tidying up unused Article stuff

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
failed due to downloads test.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Failed on download hack.

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
This is ready for code-review. I was the requestor, and it looks good to me.

**Pull request merged**
