### PR TITLE
DEVELOPER-2944 Update build to use the newest Searchisko configuratio…

### PR DESCRIPTION
**Pull request by paulrobinson**
…n branch v2.1.5

### CODE REVIEW

**Comment by paulrobinson** [comment]
We should hold this PR until we have a DCP dump from this version of the DCP. I'm currently working on it.

**Comment by paulrobinson** [comment]
I manually added a new DCP dump. Checking it worked.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
This looks to have worked. Ready to review once the tests complete.

**Comment by paulrobinson** [comment]
Looks like it's failing due to downloads Acc tests. @RubyGemTSL agreed?

**Comment by paulrobinson** [comment]
retest this please

**Comment by LightGuard** [comment]
No surprise there really.

On Mon, Apr 25, 2016 at 10:36 AM, Paul Robinson <notifications@github.com>
wrote:

> Looks like it's failing due to downloads Acc tests. @RubyGemTSL
> <https://github.com/RubyGemTSL> agreed?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1045#issuecomment-214432141>
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by RubyGemTSL** [comment]
@paulrobinson @LightGuard - the failure was not due to flaky downloads tests:
Scenario: A customer has correct login credentials can log in on mobile/tablet devices.

I've seen that failure twice today. I'll make a note of that and retest.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Failed on download hack. I think we should disable them until David has implemented a solution for the redirect?

**Comment by paulrobinson** [comment]
retest this please

**Comment by LightGuard** [comment]
This is working correctly?

**Comment by LightGuard** [comment]
https://issues.jboss.org/browse/DEVELOPER-2944 is not in the sprint, nor does it contain a point estimate.

**Comment by paulrobinson** [comment]
Thanks @LightGuard. I've now updated https://issues.jboss.org/browse/DEVELOPER-2944 with review instructions, and an explanation as to why I needed to work on this as an urgent issue.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@paulrobinson I'm seeing `net::ERR_ADDRESS_UNREACHABLE` in the browser console. Looks like it isn't working correctly, probably searchisko isn't building or deploying properly.

**Comment by paulrobinson** [comment]
I've seen the DCP die for other PRs. This will need investigating, before we merge this PR. Clearly, we need to be sure the new DCP version works.

I'll try and figure it out via this PR. Otherwise, I'll raise a JIRA and schedule it on the sprint.

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
received a 500 on login page:
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/471/artifact/_cucumber/reports/rhd_test_report.html

will retest

**Comment by RubyGemTSL** [comment]
retest this plase

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Looks like this is working now!

**Comment by paulrobinson** [comment]
@LightGuard can you merge if you are happy with it?

**Pull request merged**
