### PR TITLE
Style fixes for Product Learn pages

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by paulrobinson** [comment]
The pagination disabling doesn't seem to be working quite right. Try this:

1. go to: http://it-developers-pr.stage.redhat.com/pr/450/build/935/products/eap/learn/#!project=eap&randomize=false
2. Select page 2
3. Select 'first'
4. Notice that 'last; is disabled, despite not being on the last page: https://www.dropbox.com/s/quouv3jzjidzfty/Screenshot%202015-10-05%2010.49.14.png?dl=0

**Comment by paulrobinson** [comment]
Looks good: "RHD-742 Fixed length of 'Show entries' dropdown in Learn pages"

**Comment by paulrobinson** [comment]
Looks good: "RHD-744	Fixed date widget on Learn pages"

**Comment by paulrobinson** [comment]
Ready to merge, once the pagination bug is fixed.

**Comment by adelasofia** [comment]
@paulrobinson Fixed the pagination issue.

**Pull request merged**
