### PR TITLE
Removing elevated privileges

### PR DESCRIPTION
**Pull request by ollyjshaw**
@paulrobinson @LightGuard I don't believe we need this, but let me know if there's something I'm missing

### CODE REVIEW

**Comment by LightGuard** [comment]
I had faced an issue with selinux and volume mounting early on. We'd need
to try this with an selinux enabled system to verify.

On Tuesday, December 22, 2015, Oliver Shaw <notifications@github.com> wrote:

> @paulrobinson <https://github.com/paulrobinson> @LightGuard
> <https://github.com/LightGuard> I don't believe we need this, but let me
> know if there's something I'm missing
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/redhat-developer/developers.redhat.com/pull/654
> Commit Summary
>
>    - Removing elevated privileges
>
> File Changes
>
>    - *M* _docker/docker-compose.yml.erb
>    <https://github.com/redhat-developer/developers.redhat.com/pull/654/files#diff-0>
>    (3)
>
> Patch Links:
>
>    -
>    https://github.com/redhat-developer/developers.redhat.com/pull/654.patch
>    -
>    https://github.com/redhat-developer/developers.redhat.com/pull/654.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/654>.
>


-- 
Sent from Gmail Mobile

**Comment by paulrobinson** [comment]
@ollyjshaw did you test this on a SELinux box?

**Comment by ollyjshaw** [comment]
@paulrobinson @LightGuard I don't have one handy, do either of you? If no one else does I'd say it's not something to worry about.

**Comment by paulrobinson** [comment]
@LightGuard do you have an SELinux box?

**Comment by LightGuard** [comment]
Fedora is SELinux by default.

On Wed, Jan 6, 2016 at 10:59 AM, Paul Robinson <notifications@github.com>
wrote:

> @LightGuard <https://github.com/LightGuard> do you have an SELinux box?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/654#issuecomment-169404920>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by ollyjshaw** [comment]
@LightGuard @paulrobinson If someone has a fedora box can you test?

**Comment by LightGuard** [comment]
I'll spin up one on OS-1 as I'm not comfortable using my main box for
testing a new docker change in the middle of my Drupal work.

On Thursday, January 7, 2016, Oliver Shaw <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> @paulrobinson
> <https://github.com/paulrobinson> If someone has a fedora box can you
> test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/654#issuecomment-169664402>
> .
>


-- 
Sent from Gmail Mobile

**Comment by LightGuard** [comment]
On a brand new fedora 23 box this worked fine, also the README is still up to date :)

**Pull request merged**
