### PR TITLE
DEVELOPER-3806 Bad link from Technologies Primary-nav menu item

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
I've created a [ticket](https://issues.jboss.org/browse/DEVELOPER-3812https://issues.jboss.org/browse/DEVELOPER-3812) to investigate these random SO failures. I'm working on it now.

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by robpblake** [comment]
@paulrobinson This seems fairly trivial and works as far as I can see. Is this good to merge?

cheers,

Rob

**Comment by paulrobinson** [comment]
Yes, looks good to me.

**Pull request merged**
