### PR TITLE
Developer-2966 - Correct links in page copy to prevent 301 redirecting

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@RubyGemTSL - This seems to be falling on date issues with "accepting terms and conditions". I did add a trailing slash there, but it seems unrelated to the expected date vs actual date error.

**Comment by RubyGemTSL** [comment]
@Dantheman720 - its a timezone issue in the get current date method in the tests I suspect. 

Error: 
expected: "Jun 29, 2016"
got: "Jun 28, 2016"

I'll look into it.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
or maybe we were just unlucky and the time went from 11:59 pm 28th to 12:00 am on 29th June. The current method gets the system time which would be the same as the browser? I'm going to update the test that failed to get the current system time as the moment the test click on register button.

**Comment by RubyGemTSL** [comment]
@Dantheman720 - I've made a slight modification to the tests and it's been merged. Its a difficult one to reproduce, however my fix should hopefully stop this happening again.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by LightGuard** [comment]
Is this good to merge?

**Comment by RubyGemTSL** [comment]
This only failed on the time the customer registered again. No impact from Dan's work. I'm going to have to get the time of registration from the keycloak API to avoid this happening again. I'll fix in another PR.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Pull request merged**
