### PR TITLE
DEVELOPER-2950 - Drupal quickstart and demo pages are not working

### PR DESCRIPTION
**Pull request by Dantheman720**
Updates to incorporate aweplug changes for Drupal

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard - Can you review this when you get the chance?

**Comment by LightGuard** [comment]
It looks okay from a code perspective, but the DCP died here again :(

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 I had one: Welcome to the SwitchYard Quickstart Repository which is going to the wrong spot, but it seems like we don't really want that one anyway. It's being placed at /quickstarts/fues/switchyard/index.html seems like it's a root README which simply doesn't match our requirements (it doesn't have a topic for example) because it isn't actually a quickstart. @paulrobinson Not sure what we want to do with that. I thought We wanted to just not include those that didn't fit the criteria.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
