### PR TITLE
[DEVELOPER-5821] added or / and select on dynamic content list

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5821

### Verification Process
Go to dynamic content list on the homepage in the cms, you should be able to tick an option to enable AND filter logic on the list unselected is an OR filter

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by alistairmc** [comment]
@jordanpagewhite Can you take a look at this, please. Seems to be working, the only problem I can see is when you change to and it works fine however when you change back to or it's not refreshing the query wondering if its a cache issue or something, locally a server restart resolves the issue.

Do you have any ideas?

**Comment by robpblake** [comment]
@alistairmc All queries to Wordpress are cached by a piece of middleware on the Guzzle HTTP client. I'm not 100% on the origins of this, but I believe it was because the Drupal integration ended up getting blocked by Akamai as spam traffic.  Unfortunately the caching mechanism is a bit blunt, so if you need some granular control over it, there might be a bit of work to do here.

See https://issues.jboss.org/browse/DEVELOPER-5615 for a bit more background on this and ping me on Slack if you need to discuss anything.

cheers,

Rob

**Comment by alistairmc** [comment]
@jordanpagewhite Can you review this, please.  @robpblake do you know how long the cache keeps content?

**Comment by robpblake** [comment]
@alistairmc Forever.

**Comment by alistairmc** [comment]
@jordanpagewhite I have updated the rest endpoint it seems to be working properly now.

**Pull request merged**
