### PR TITLE
Added new jboss bpmsuite starter kit to get started page.

### PR DESCRIPTION
**Pull request by eschabell**
Please merge so developers pages match jboss.org product page.

### CODE REVIEW

**Comment by eschabell** [comment]
Patch verified on jboss.org here: https://github.com/jboss-developer/www.jboss.org/pull/969

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
Thanks @eschabell. I'll wait for a build on here to make sure it interacts correctly with this build too.

**Comment by eschabell** [comment]
preview looks perfect, merge to main site please.

**Comment by eschabell** [comment]
Build works great, checked and verified above PREVIEW link, please merge on through to main site.

**Pull request merged**
