### PR TITLE
DEVELOPER-4759 and DEVELOPER-4567 - DTM and Search updates

### PR DESCRIPTION
**Pull request by KamiQuasi**
Search-related issues: https://issues.jboss.org/browse/DEVELOPER-4759
DTM-related issues: https://issues.jboss.org/browse/DEVELOPER-4567

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@KamiQuasi I had the same failure on my PR. The results should include blog posts related to "Red Hat JBoss Data Grid 7.0 is out" however they aren't. Is this the DCP, or us?

**Comment by KamiQuasi** [comment]
@RubyGemTSL Prod does the same thing. If I filter by blog posts it does show up as like the sixth value, but without the filter I'm not seeing it. I know there were some tweaks to speed things up, which may explain the issue.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Pull request merged**
