### PR TITLE
DEVELOPER-4403 replaced text underneath the forum titles

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
Have you made the change to the file in Drupal as well?

**Comment by adelasofia** [comment]
@LightGuard the content change? I did

**Comment by RubyGemTSL** [comment]
ah damn - it looks like other PR's are now seeing the same dependancy issues I was having on my PR. I have fixed as part of my current [PR](https://github.com/redhat-developer/developers.redhat.com/pull/2022). If my latest push passes it will fix. If not i'll raise a separate PR.

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
