### PR TITLE
[DEVELOPER-5665] Set metatag metadata nodes

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5665

### og:image config by content type

|Content Type|og:image (1)|og:image (2)|
| ------------ | ------------ | ----------- |
|content (default)|[node:field_card_image:uri]||
|Article|[node:field_image:share]|http://design.jboss.org/redhatdeveloper/website/redhatdeveloper_1_0/social/images/RHD_twitteravatar.jpg|
|Author|[node:field_headshot:uri]||
|Books|[node:field_card_image:uri]||
|Events|[node:field_event_background_image:share]||
|Page|[node:field_share_image:share:url]|http://design.jboss.org/redhatdeveloper/website/redhatdeveloper_1_0/social/images/RHD_twitteravatar.jpg|
|Topic Page|[node:field_share_image:share]|http://design.jboss.org/redhatdeveloper/website/redhatdeveloper_1_0/social/images/RHD_twitteravatar.jpg|

### Verification Process

For each content type in the table above,

1. find a node of that type
2. Ensure that there is an image uploaded or referenced from the field in the og:image (1) column. If one is not already there, just upload or reference one for testing.
3. Save the node edit form and view the node, right click and view source
4. Search (Cmd+f or ctrl+f) for `<meta ` to find the metatags in the HTML.
5. Verify that the og:image tag value is the URL to the image referenced by the node.
5b. In the instance of content types with the twitteravatar.jpg value in column og:image (2), ensure that there is no image referenced in the field in column og:image (1), then search for the metatags in the HTML and ensure that http://design.jboss.org/redhatdeveloper/website/redhatdeveloper_1_0/social/images/RHD_twitteravatar.jpg is the value of the og:image tag (like a fallback image).

*note:* The Metatag module provides this pseudo-fallback image like functionality by allowing you to define as many og:image tags as you want. The social media platforms will use the image with the higher resolution, so since the twitteravatar.jpg img is 250x250, our other image fields should enforce an image style of higher resolution than that.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
It seems that the error in the PR build in Jenkins relates to the changes I made to the metatag configuration, but I'm not sure (at a glance) that I understand why the parser thinks the URI(s) are invalid. I will take a look at this later.

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by robpblake** [comment]
@jordanpagewhite What's the status on this one? Is this being broken by the export?

cheers,

Rob

**Comment by robpblake** [comment]
@jordanpagewhite Shall we close this one for now? It looks like it's not going to work whilst the export still exists and there is really no point putting more work into the export when we are very close to completely removing it from the PR pipeline.

**Pull request closed without merging**
