### PR TITLE
[Testing do not merge] [RHDX-456] ie11 compatibility mods

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-456

### Verification Process
Check site functions in ie11

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Pull request closed without merging**
