### PR TITLE
Moving title up higher for monitoring checks

### PR DESCRIPTION
**Pull request by LightGuard**
Our monitoring solutions need to verify the correct page is loaded. They
would like something towards the top that is guaranteed to be there. The
title seemed to be a good option, but it needs to be within the first 5k
of the response. I'm moving it up higher so it's guaranteed to be in
that amount.

### CODE REVIEW

**Comment by paulrobinson** [comment]
The title should be in this format:

Red Hat Developer | <Page Title>

**Comment by LightGuard** [comment]
We changed it??

**Comment by paulrobinson** [comment]
I think that's always been the plan. Not sure it got scheduled in JIRA tho.

**Comment by paulrobinson** [comment]
Notice the name of the site in the logo: https://developers.stage.redhat.com/

**Pull request merged**
