### PR TITLE
[BLOCKED] RHD-971 Dependant on DEVELOPER-1792

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[HOLD] Dependant on DEVELOPER-1792

### CODE REVIEW

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
expected fail due to lack of chrome drive

**Comment by paulrobinson** [comment]
Can you close this PR, and Re-open when the blockers have been resolved, and thus it's ready for review and merge?

**Pull request closed without merging**
