### PR TITLE
Reverted the SO page to use the correct DCP for the selected environment

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Really getting tired of this dying... :(

**Comment by LightGuard** [comment]
@paulrobinson Is there a point of merging this? Seems like we've been fine without it.

**Comment by paulrobinson** [comment]
@LightGuard I hadn't realised this one had been hanging around (and failing) for so long. I can't think of a reason why using dcp2.jboss.org would cause a problem in this case as it's purely read-only. It just seems wrong, and may bite us one day.

Having said that, I'm not sure it's worth the effort to get this PR to pass. Maybe there is some stale state somewhere that is not being cleaned. I'll open a new PR and see if that runs cleanly.

**Pull request closed without merging**
