### PR TITLE
[DEVELOPER-5473_5474] style changes headings and author name

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5474
https://issues.jboss.org/browse/DEVELOPER-5473

### CODE REVIEW

**Comment by sjcox-rh** [comment]
Looks good from our end. UX approves of merging this!

**Comment by alistairmc** [comment]
RETEST THIS PLEASE

**Comment by alistairmc** [comment]
Retest this please

**Comment by alistairmc** [comment]
retest this pleaes

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
@KamiQuasi  Can this be merged before the new sprint?

**Pull request merged**
