### PR TITLE
[RHDX-425] Update usage of hide class

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-425](https://projects.engineering.redhat.com/browse/RHDX-425?filter=-1)

### Verification Process
Any usage of `.hide` in  twig templates, hooks or js files intended to hide/show elements on the page should be replaced with `.pf-u-hidden`, now that Foundation is removed. 

- Check video resource;  There should not be calls to slideshare.net if there is no slide deck.
- Check show more text on Videos and Learning Paths
- Simplified table of contents twig classes; Check that it hides when its supposed to (field_hide_toc)

There is some usage of `.hide`  in the rhdp-searchapp, I did not update that usage since the class exists within that web component.

/videos/youtube/FC3jSKgTNK0/
/videos/youtube/ajlY_qiIunA/
/videos/youtube/ywrA0312bOo/
/videos/youtube/B9MdhWCvDCM/
/videos/youtube/Cv8_EHQgUZ4/

### CODE REVIEW

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
@staceymosier on /videos/youtube/FC3jSKgTNK0/ the show more feature is now broken.

**Comment by alistairmc** [comment]
retest this please

**Pull request merged**
