### PR TITLE
[DEVELOPER-3334] Fixed robots.txt to only include paths that exist

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 you've tested all of these paths in prod and verified they don't actually exist on the site?

**Comment by robpblake** [comment]
@LightGuard / @Dantheman720 Does this work need to be ported over to the Drupal version of the site?

**Comment by LightGuard** [comment]
I have no idea. It's probably not a bad idea to add these to the `_docker/drupal/drupal-filesystem/web/robots.txt` file though.

**Comment by LightGuard** [comment]
@Dantheman720 mind making the change to the robots one for drupal too?

**Comment by Dantheman720** [comment]
@LightGuard @robpblake  - I move this over to drupal as well. I tested these paths and they don't exist.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
