### PR TITLE
DEVELOPER-5050 - Cheatsheet download is triggered twice

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-5050

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@Dantheman720 could you please also update the cheatsheet test at [this](https://github.com/redhat-developer/developers.redhat.com/blob/master/_tests/e2e/specs/rhd-cheatsheet-downloads.js#L40) line to the following:

```
expect(dowloadHelper.getDownloads().length,
            'Failed to download cheatsheet').to.eql(1)
```

**Comment by Dantheman720** [comment]
Will do!

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@Dantheman720 did you try this manually on the export? I just tried and the download didn't trigger

**Comment by RubyGemTSL** [comment]
@Dantheman720 scratch that. It worked fine in and incognito window.

**Pull request merged**
