### PR TITLE
DEVELOPER-3642 - Remove server-side base_url

### PR DESCRIPTION
**Pull request by KamiQuasi**
Quick fix to remove the server-side base_url value because it doesn't function with export.

### CODE REVIEW

**Comment by paulrobinson** [comment]
How can I check that this is working?

**Comment by LightGuard** [comment]
As long as the site and DCP calls are working, it's working.

**Comment by KamiQuasi** [comment]
@paulrobinson in developer console, look at the digitalData object. You should see appropriate values for page >> pageInfo >> pagename AND page >> category >> primary/sub category fields

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
I'm seeing 'export' in the data fields: https://www.dropbox.com/s/t6c4djv2vr7rjzh/Screenshot%202016-11-15%2014.41.50.png?dl=0

Are you picking the wrong level in the URL for pull requests?

**Comment by KamiQuasi** [comment]
@paulrobinson think those indexes are sorted out now

**Comment by paulrobinson** [comment]
Is this what you expected to see: https://www.dropbox.com/s/sabjtcxug103nam/Screenshot%202016-11-15%2019.00.31.png?dl=0

Notice that it's only showing 2 levels of sub-catagories, "1600" and "export".

Also, I presume we are happy for it to parse the full URL for Pull Requests? I.e it has the "pr", "1600" and "export" parts of the URL parsed.

**Comment by KamiQuasi** [comment]
@paulrobinson yep until we find a stable way to pass the environment to the front-end it'll look like this on the PR server. Drupal server should look more reasonable.

**Pull request merged**
