### PR TITLE
Fixes DEVELOPER-3731 and DEVELOPER-3736 (Help page tickets)

### PR DESCRIPTION
**Pull request by LightGuard**
Please see 
* https://issues.jboss.org/browse/DEVELOPER-3731
* https://issues.jboss.org/browse/DEVELOPER-3736

for further information and a definition of done.

Decided to do DEVELOPER-3736 while I was in there and this incorporates
a lot of the work needed for it anyway.

SO section now takes up the full allotted width if there are no forums.
Also if it is full width we're displaying two columns and eight
questions instead of one column and four questions.

If there is no forum link and no SO to display we're no longer
displaying "Community Q&A".

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@paulrobinson As issue reporter, can you take a look at this please

**Comment by paulrobinson** [comment]
See: http://developer-drupal.web.prod.ext.phx2.redhat.com/products/devsuite/help. Notice that no help content is displayed, yet the 'Community Q&A' header is visible. I'm not sure if this page should show any content or not.

**Comment by paulrobinson** [comment]
Same here: http://developer-drupal.web.prod.ext.phx2.redhat.com/products/mobileplatform/help as above comment

**Comment by paulrobinson** [comment]
I'm only seeing a single column of content on http://developer-drupal.web.prod.ext.phx2.redhat.com/products/openshift/help

**Comment by paulrobinson** [comment]
Ignore above comments, it seems like the export is linking off to the production server.

**Pull request merged**
