### PR TITLE
DEVELOPER-3767 - Adobe DTM "Social Account Linked" event firing

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3767

When a social account is linked, the event should fire and the linked account exist in the digitalData object.

### CODE REVIEW

**Comment by LightGuard** [comment]
@adelasofia @KamiQuasi We have social KC tests for Github, but they're slow and I don't believe they're currently run. We may need to run them manually to check everything. Would one of you mind running those and reporting back?

**Comment by LightGuard** [comment]
I don't know how to test this. I tried to link a new social account after I was logged in and it didn't trigger. @KamiQuasi there's also a conflict now.

**Comment by KamiQuasi** [comment]
@LightGuard fixed the merge conflict

**Comment by LightGuard** [comment]
Going to merge

**Pull request merged**
