### PR TITLE
[HOLD] DEVELOPER-4418 - Redo Technology section for October launch

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-4418

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@LightGuard the ruby test failed because the content hasn't been updated, btw.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Pull request merged**
