### PR TITLE
[DEVELOPER-5840] Update Drupal core to 8.7.3 & Lighting to 3.3.1

### PR DESCRIPTION
**Pull request by jordanpagewhite**
I have updated Drupal core to the latest security release, 8.7.3, and
I've updated acquia/lightning to the matching release, 3.3.1. After
updating these packges with composer, I ran the database updates (there
were a lot) and exported the config.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5840

### Verification Process

* `drupal/core` should be on version 8.7.3
* `acquia/lighting` should bee on version 3.3.1
* The config should import cleaning and there should be no dangling config or failed database updates
* All composer patches should apply cleanly

### CODE REVIEW

**Comment by robpblake** [comment]
@jordanpagewhite Any reason why we shouldn't go straight to Drupal 8.7.3?

**Comment by jordanpagewhite** [comment]
@robpblake Good point. Let me read the release notes for 8.7.2 and 8.7.3 to see what is included in those releases. I just defaulted to updating to the latest security version, but we could just go to latest as long as the contents of the releases seem fine for our site.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
@robpblake I missed your comment about the Lightning versions. Yeah, I noticed that as well. I am keeping our `acquia/lightning` version at version 3.3.1 right now instead of moving up to the newly released major version 4.0.0 (and 4.0.1 was released 10 days ago). The 4.0.0 release of `acquia/lightning` installs the Claro administration theme, and I will need to ensure that none of their admin theme opinions conflict with our recent Compose work in any way. I figured that, since there are no significant benefits from updating right now, that it would be fine to postpone this major version update until all of the Compose work is merged and I can ensure that Lightning will not interfere with any functionality in the admin theme and/or editorial workflows.

**Pull request merged**
