### PR TITLE
DEVELOPER-5331, DEVELOPER-5372 and DEVELOPER-5351

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
* Link to the JIRA ticket(s) this pull request solves
https://issues.jboss.org/browse/DEVELOPER-5331
https://issues.jboss.org/browse/DEVELOPER-5372
https://issues.jboss.org/browse/DEVELOPER-5351

### CODE REVIEW

**Comment by alistairmc** [comment]
Please review and merge

**Comment by alistairmc** [comment]
have checked 
https://issues.jboss.org/browse/DEVELOPER-5351 into this bug by mistake can we just review.

@KamiQuasi  can this be reviewed as on or do I need to split them?

**Comment by tiffanynolan** [comment]
Fixes verified by UX team.

**Comment by alistairmc** [comment]
@KamiQuasi Please review and merge, sorry for the 3 bugs in 1 PR

**Pull request merged**
