### PR TITLE
DEVELOPER-4321 Hero for "Advanced EAP Cheat Sheet"

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4321 - Implement Hero for "Advanced EAP Cheat Sheet"](https://issues.jboss.org/browse/DEVELOPER-4321) 

DO NOT MERGE -- SHOULD GO LIVE MONDAY 08/07

For review purposes only, will close once approved and reopen closer to the date

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
Approved. Will reopen this PR closer to the date it needs to go live.

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
