### PR TITLE
DEVELOPER-3627 - Tag labels are displayed on new article pages and should't be

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard - This should be good to go once the acceptance tests pass

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
You can see the problem at http://developers.redhat.com/articles/no-cost-rhel-faq-2/ on the right side you'll see the "Tags" listed twice

**Comment by LightGuard** [comment]
Failed tests are ones that are expected to fail currently.

**Pull request merged**
