### PR TITLE
DEVELOPER-3975 part two (Modules installed)

### PR DESCRIPTION
**Pull request by LightGuard**
The Lightning Media Image module should now be installed

JIRA: https://issues.jboss.org/browse/DEVELOPER-3975

To test this, log into Drupal as an admin, go to "Extend" and verify that the Lightning Media Image module has a check next to it.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
The KC/DM acceptance tests timed out: https://redhat-dev-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Acceptance_Tests/937/console I suppose that will probably be the case for some time until all the systems get up and running. You can log into the drupal site, however, and verify that the modules are indeed installed.

**Comment by LightGuard** [comment]
@KamiQuasi @Dantheman720 I leave it up to you as far as what you want to do.

**Comment by Dantheman720** [comment]
Unrelated to KC and DM acceptance tests. Merged.

**Pull request merged**
