### PR TITLE
DEVELOPER-5450: Part 1, Uninstall RHD Theme

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This commit must precede my other commit for DEVELOPER-5450. The RHD
theme must be uninstalled from Drupal before we can delete it from the
filesystem.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5450

### Verification Process

* Go here `/admin/appearance`
* Observe that the RHD theme is no longer an installed theme (it may exist on the page somewhere, but it can't be installed)

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@jordanpagewhite 

Looks like Drupal is failing to boot on this one with the following:

```
DEBUG - executing command /var/www/drupal/vendor/bin/drush ["--root=/var/www/drupal/web", "-y", "cim"]
drupal_install_checker.rb:10:in `exec!': +------------+----------------+-----------+ (RuntimeError)
| Collection | Config         | Operation |
+------------+----------------+-----------+
|            | core.extension | Update    |
+------------+----------------+-----------+

 // Import the listed configuration changes?: yes.                              

 [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Configuration <em class="placeholder">block.block.rhd_account_menu</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_branding</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_breadcrumbs</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_content</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_footer</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_help</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_local_actions</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_local_tasks</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_main_menu</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_messages</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_page_title</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_powered</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_search</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">block.block.rhd_tools</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import.
Configuration <em class="placeholder">rhd.settings</em> depends on the <em class="placeholder">RHD Theme</em> theme that will not be installed after import. in Drupal\Core\Config\ConfigImporter->validate() (line 737 of /var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php). 

In ConfigImportCommands.php line 259:
                                                                               
  The import failed due to the following reasons:                              
  Configuration <em class="placeholder">block.block.rhd_account_menu</em> dep  
  ends on the <em class="placeholder">RHD Theme</em> theme that will not be i  
  nstalled after import.                                                       
  Configuration <em class="placeholder">block.block.rhd_branding</em> depends  
   on the <em class="placeholder">RHD Theme</em> theme that will not be insta  
  lled after import.                                                           
  Configuration <em class="placeholder">block.block.rhd_breadcrumbs</em> depe  
  nds on the <em class="placeholder">RHD Theme</em> theme that will not be in  
  stalled after import.                                                        
  Configuration <em class="placeholder">block.block.rhd_content</em> depends   
  on the <em class="placeholder">RHD Theme</em> theme that will not be instal  
  led after import.                                                            
  Configuration <em class="placeholder">block.block.rhd_footer</em> depends o  
  n the <em class="placeholder">RHD Theme</em> theme that will not be install  
  ed after import.                                                             
  Configuration <em class="placeholder">block.block.rhd_help</em> depends on   
  the <em class="placeholder">RHD Theme</em> theme that will not be installed  
   after import.                                                               
  Configuration <em class="placeholder">block.block.rhd_local_actions</em> de  
  pends on the <em class="placeholder">RHD Theme</em> theme that will not be   
  installed after import.                                                      
  Configuration <em class="placeholder">block.block.rhd_local_tasks</em> depe  
  nds on the <em class="placeholder">RHD Theme</em> theme that will not be in  
  stalled after import.                                                        
  Configuration <em class="placeholder">block.block.rhd_main_menu</em> depend  
  s on the <em class="placeholder">RHD Theme</em> theme that will not be inst  
  alled after import.                                                          
  Configuration <em class="placeholder">block.block.rhd_messages</em> depends  
   on the <em class="placeholder">RHD Theme</em> theme that will not be insta  
  lled after import.                                                           
  Configuration <em class="placeholder">block.block.rhd_page_title</em> depen  
  ds on the <em class="placeholder">RHD Theme</em> theme that will not be ins  
  talled after import.                                                         
  Configuration <em class="placeholder">block.block.rhd_powered</em> depends   
  on the <em class="placeholder">RHD Theme</em> theme that will not be instal  
  led after import.                                                            
  Configuration <em class="placeholder">block.block.rhd_search</em> depends o  
  n the <em class="placeholder">RHD Theme</em> theme that will not be install  
  ed after import.                                                             
  Configuration <em class="placeholder">block.block.rhd_tools</em> depends on  
   the <em class="placeholder">RHD Theme</em> theme that will not be installe  
  d after import.                                                              
  Configuration <em class="placeholder">rhd.settings</em> depends on the <em   
  class="placeholder">RHD Theme</em> theme that will not be installed after i  
  mport.                                                                       
                                                                               

config:import [--preview [PREVIEW]] [--source SOURCE] [--partial] [--diff] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify] [--xh-link XH-LINK] [--] <command> [<label>]

	from drupal_install_checker.rb:123:in `drush_config_import'
	from drupal_install_checker.rb:32:in `prepare_drupal_for_boot'
	from drupal_install_checker.rb:133:in `<main>'
```

**Comment by jordanpagewhite** [comment]
Thank you @robpblake I removed all of the dependent config items in the commit I just pushed up.

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
