### PR TITLE
DEVELOPER-4977

### PR DESCRIPTION
**Pull request by alistairmc**
added images into theme and added responsive styles for header graphic.

to test go to /eclipse and see if page hero image is loaded and works on all device sizes.

### CODE REVIEW

**Comment by KamiQuasi** [comment]
this is ok to test

**Comment by alistairmc** [comment]
Any update on this @KamiQuasi

**Comment by Dantheman720** [comment]
@alistairmc - I'm not seeing the image on the site export.  https://developers-pr.stage.redhat.com/pr/2507/export/eclipse/

**Comment by alistairmc** [comment]
ok so have updated the image location to test in export you need to edit the css in inspector to /pr/2507/export/images from /images

images are now in _docker/lib/export/static/images this is a patch until we find a better solution images will work in developer.redhat.com live site but not drupal to pr environment 

@KamiQuasi is this ok?

**Pull request merged**
