### PR TITLE
remove temp portal reg for RHEL get started - Dev-2806

### PR DESCRIPTION
**Pull request by MikGue**
This section is no longer required because we incorporated Customer Portal T&C agreements into the RHDev registration page.

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
@MikGue can you review that this does what you want? @adelasofia can you review and merge after Mike approves?

**Comment by paulrobinson** [comment]
I'm not sure why @JBossJenkins keeps asking me to verify it. The build seems to have happened regardless.

**Comment by adelasofia** [comment]
Approved by Mike Guerette

**Pull request merged**
