### PR TITLE
[RHDX-469] static_item assembly uri and title field updates.

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-469

### Verification Process
1. Create a "Curated Content" (static_content_band) assembly on a node.
2. Add a "Static Item" (static_item) assembly to it.
3. Confirm that "Title" is a required field.
4. Add an internal reference to the URL field. (ie: "/node/210265/" or "< front >")
5. Save and view the front-end
6. Confirm the internal reference link works correctly by clicking the title in the card.

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Review by staceymosier — CHANGES_REQUESTED** [review]
https://developer-preview-3579.ext.us-west.dc.preprod.paas.redhat.com/node/219195/

I edited the 'About Red Hat' curated content, and for the first static item,  the generated url is 
/node/219195/node/213565

when you view the assembly itself, you see the same
https://developer-preview-3579.ext.us-west.dc.preprod.paas.redhat.com/assembly/205/view

I am expecting the link to be /openshift/command-line-tools/

In Drupal admin,  when editing that static item,  I start typing the title of a node, and select the item from list --  instead of typing a path. 

My assumption is that the output would be  <a href="/node/1234" data-drupal-uuid="xxx"></a>, the latest alias is found for the uuid,  the href is replaced to the correct url.  The card twig component may not support this usage.

**Comment by staceymosier** [comment]
Added to body field, using the Link button and typing in a Title

`<p><a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="157af927-b6a3-4bc3-9386-c6f95ab4b762" href="/node/213585">This is a link</a> using the generate link tool.</p>`

https://developer-preview-3579.ext.us-west.dc.preprod.paas.redhat.com/che-custom-stacks

If you edit the article, you'll see /node/213585
if you view the source of the page, you'll see /openshift/url-logging-command-line/

**Comment by rogeralloymagnetic** [comment]
@staceymosier commit https://github.com/redhat-developer/developers.redhat.com/pull/3579/commits/f42a66ca179dc44f7555336676d1796fc8b0e685 adds a check for the prepended forward slash to ensure root relative urls. When clicked the generated url also redirects to the alias.

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Review by jordanpagewhite — APPROVED** [review]
These changes look good to me. As discussed on call(s) and chat, I will work on an issue to describe the bigger issue. That doesn't need to hold this up right now though.

**Review by staceymosier — APPROVED** [review]

**Pull request merged**
