### PR TITLE
[URGENT] RHD-1648 Updated Get Started page for JDG 7

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
Should this include #1301 ?

**Comment by adelasofia** [comment]
@cvanball This is the pull request with the changes you requested via e-mail. But I see you made other changes to the same file in #1301 , which is the correct version of datagrid/get-started.adoc ?

**Comment by adelasofia** [comment]
Approved 👍

**Comment by LightGuard** [comment]
Error is completely unrelated, merging anyway.

**Pull request merged**
