### PR TITLE
DEVELOPER-2520 - Remove Satellite and Atomic Host products from RHDev

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
You need to fix the download page tests too. See: https://github.com/redhat-developer/developers.redhat.com/blob/master/_cucumber/features/downloads.feature#L11

**Comment by ollyjshaw** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by Dantheman720** [comment]
@paulrobinson This created two broken links to atomic and satellite in devops/adoption.adoc.  I removed them from the second commit in case you would prefer to use a different change.

**Pull request merged**
