### PR TITLE
DEVELOPER-3203 - Added Jess K to about page.

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
Closing until Jenkins comes back

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by Dantheman720** [comment]
Opening a new PR for this. Not sure why the builds are failing.

**Pull request closed without merging**
