### PR TITLE
DEVELOPER-2847 Added tab selection to the RHEL Get Started url

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
This seems to be blocked by Blinkr as OS1 is offline.

**Comment by LightGuard** [comment]
Who needs to sign off on this? If we can get there sign off, we'll just wait for the blinkr report to run.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
Closing this (more changes were requested). I'll open a new one next week with the latest version.

**Pull request closed without merging**
