### PR TITLE
Drupal Core Update: 8.6.10

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This updates Drupal core to version 8.6.10 and updates the following
contrib projects: admin_toolbar, ctools, jsonapi, lightning,
lightning_core, lightning_media, lightning_workflow, paragraphs and
metatag.

See: https://www.drupal.org/sa-core-2019-003 for details on this
security release.

### JIRA Issue Link
* n/a

### Verification Process

* All tests are green
* Drupal core is 8.6.10
* Paragraphs is 8.x-1.6
* Metatag is 8.x-1.8
* JSONAPI is 8.x-2.3

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
I forgot to mention that we can now drop this patch: https://www.drupal.org/files/issues/2018-10-11/3000677-30.patch as the changes have been included in Drupal core. You can see the issue discussion here: https://www.drupal.org/project/drupal/issues/3000677#comment-12924241 and review the file changes in Drupal core diffs if you'd like.

**Comment by jordanpagewhite** [comment]
It seems like the <title> of the /blog page may have changed from:

"RHD Blog - Insights and news on Red Hat developer tools, platforms and more"
to
"Red Hat Developer Blog - Insights and news on Red Hat developer tools, platforms and more"

**Comment by robpblake** [comment]
@jordanpagewhite This is nice work! Thanks for being on top of this so quickly.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@jordanpagewhite Can you please merge in master to pick up the latest test changes.

cheers,

Rob

**Comment by jordanpagewhite** [comment]
@robpblake Yep, of course. I just pushed that up.

**Comment by jordanpagewhite** [comment]
@robpblake I just updated the acquia/lightning package to the release they made yesterday afternoon

**Comment by jordanpagewhite** [comment]
I confirmed that this leaves the config in a clean state, and all of the tests are passing

**Pull request merged**
