### PR TITLE
[DO NOT MERGE] Testing some awestruct perf changes

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
I'm going to use a different PR that's cleaner.

**Pull request closed without merging**
