### PR TITLE
[DEVELOPER-5417] Update onebox file

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link

https://issues.jboss.org/browse/DEVELOPER-5417

### Verification Process
check spreadsheet linked in the story and check updates applied.

### CODE REVIEW

**Comment by adelasofia** [comment]
@alistairmc I noticed that when I search for some of the updated names, the onebox is not displayed. These are the products with this bug:

- Red Hat AMQ
- Red Hat Process Automation Manager
- Red Hat Developer Studio

**Comment by alistairmc** [comment]
I can add those params but they were not part of the changes detailed in the spreadsheet, I agree they should be though.

**Comment by alistairmc** [comment]
@adelasofia this has been updated

**Comment by alistairmc** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
