### PR TITLE
[PREVIEW] Search Page

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
docker build

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Pull request closed without merging**
