### PR TITLE
DEVELOPER-3676, 3677 - Stub tests for Search and SO pages.

### PR DESCRIPTION
**Pull request by RubyGemTSL**
This PR covers both DEVELOPER-3676, 3677 tickets - Completed stubbed tests for Search and SO pages.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
I'll talk to @robpblake about getting this merged tomorrow.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retesting to verify that the noise generated from puffing-billy in the console is grepped out.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@robpblake hopefully ready to merge now. Also fixes issues for other failing PR's.

**Comment by robpblake** [comment]
A lot here, but as far as I can tell it all is working as expected. Merging.

**Pull request merged**
