### PR TITLE
[HOLD] DEVELOPER-4060 Added RHAMT to mega menu, downloads, and products pages

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4060](https://issues.jboss.org/browse/DEVELOPER-4060)

Added RHAMT - "Red Hat Application Migration Toolkit" to:

- Mega menu
- /products/
- /downloads/

**The product pages for /products/rhamt will need to be published in Drupal before this PR can be merged. They are scheduled to be published tomorrow (Friday Apr 28th) at 4pm ET**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Can't find the actual results of the tests :( Trying again so I can see them.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
One more time

**Comment by adelasofia** [comment]
@LightGuard I'm closing this PR and will reopen a new one with the changes to /downloads and /products once I figure out what is going on. https://github.com/redhat-developer/developers.redhat.com/pull/1848 is working fine with the update to the mega menu, which is the highest priority for today.

**Pull request closed without merging**
