### PR TITLE
Fixes DEVELOPER-3368 (SO forums not working)

### PR DESCRIPTION
**Pull request by LightGuard**
We ultimately need to find the right Adobe DTM code, as what we have
isn't working, or if we're even using DTM any longer.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard Is this good to merge or are you chasing up whether or not DTM is still be used?

**Comment by LightGuard** [comment]
Still chasing.

**Comment by LightGuard** [comment]
@robpblake This is good. We currently don't have DTM setup for the site, per Marcia Coman. I've removed it from the rhd.settings.yml file for prod.

**Pull request merged**
