### PR TITLE
DEVELOPER-2870 - 'Latest Content' on homepage should only include blo…

### PR DESCRIPTION
**Pull request by Dantheman720**
…g posts from RHD blog

### CODE REVIEW

**Comment by Dantheman720** [comment]
@lincolnthree - This should fix the problem with latest blog content coming from outside sources. I will need to have the searchisko configuration pushed to production before this query will work there.

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 Is this ready to merge?

**Comment by Dantheman720** [comment]
@LightGuard - This should be ready to merge; however, it looks like the staging dcp is down for previewing. This is the query https://dcp.stage.jboss.org/v2/rest/search/resources?newFirst=true&size10=true&sys_type=quickstart&sys_type=video&sys_type=demo&sys_type=jbossdeveloper_example&sys_type=jbossdeveloper_archetype&sys_type=jbossdeveloper_bom&sys_type=article&sys_type=blogpost&sys_type=book&blogbyurl=developers.redhat.com that we want to test and make sure that only blogs from the developers.redhat.com domain are returned.

**Comment by Dantheman720** [comment]
@lincolnthree @LightGuard - This should be ready for a merge. Rysiek pushed the configuration file into the production dcp instance and the query seems to be working locally.

**Pull request merged**
