### PR TITLE
DEVELOPER-3352 - Updated forum description for dotnet.

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
@RubyGemTSL - I am not totally sure what I'm doing wrong here. Perhaps we can discuss tomorrow morning?

**Comment by RubyGemTSL** [comment]
@Dantheman720 I'd bet that its the apostrophe. If you look at the description:
Original: world's
Updated:  world’s 

I've had this problem before, I'll look into it

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
