### PR TITLE
Fix for Topics acceptance tests

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
Not sure what's happening here, but the tests are failing for redirects to the topic pages.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@KamiQuasi I haven't been able to get these refferer tests to pass. Do you know what else needs updating?

**Comment by KamiQuasi** [comment]
@adelasofia that was a tricky one. Take out the leading "/" on the feature's URL. The referrer check is kind of unforgiving, but what the test is navigating to ends up being //topics/devops and that doesn't work.

**Pull request merged**
