### PR TITLE
Rhd 1617

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
ok to test

**Comment by paulrobinson** [comment]
This is ok to test

**Comment by paulrobinson** [comment]
@pmuir is this what you need the project code normalization to work for?

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
The DCP data dump is now updated. Hopefully the CDK normalization will now work.

**Comment by pmuir** [comment]
retest this please

**Comment by pmuir** [comment]
retest this please

**Comment by paulrobinson** [comment]
Is this ready for review and merge?

**Comment by pmuir** [comment]
@paulrobinson good to merge once #1179 has landed.

**Pull request merged**
