### PR TITLE
DEVELOPER-3273 - Updated products to no longer list GA variables

### PR DESCRIPTION
**Pull request by Dantheman720**
All products should now show up without GA; however, I need to review Blinkr to make sure that this doesn't cause problems with the documentation.

### CODE REVIEW

**Comment by LightGuard** [comment]
Closing until Jenkins comes back

**Comment by LightGuard** [comment]
@Dantheman720 Blinkr built, there's 1700-something errors. I think that's a few more than what we were at before, but not sure how much.

**Comment by LightGuard** [comment]
Didn't they also want to possibly drop the final digit?

**Comment by Dantheman720** [comment]
@LightGuard - That was the original request, but the ticket was updated to only drop the GA. I can work on dropping the final digit as well, but we'll need the DoD updated to reflect that.

**Comment by paulrobinson** [comment]
We are just dropping the GA. Dropping the micro version wasn't worth the effort.

**Comment by LightGuard** [comment]
Okay, that's fine then. Do we have sign off for this now?

**Comment by LightGuard** [comment]
There are significantly less issues in blinkr now, I think we are good to merge this, anyone want to give it a second opinion?

**Comment by Dantheman720** [comment]
I think this is ready too. I asked Robert to review and make sure that everything looks okay.

https://issues.jboss.org/browse/DEVELOPER-3273

**Comment by Dantheman720** [comment]
@LightGuard @paulrobinson Robert approved this.

https://issues.jboss.org/browse/DEVELOPER-3273

**Pull request merged**
