### PR TITLE
Fix for bpm suite product buzz feed

### PR DESCRIPTION
**Pull request by eschabell**
Changed feed to filter on 'bpm suite' instead of 'bpmsuite', brings feed up to date instead of showing last years articles.

### CODE REVIEW

**Comment by eschabell** [comment]
Can someone please initiate a test build?

**Comment by LightGuard** [comment]
I doubt that one will return anything either.
You could use `jbpm` though. Working with the guys in Brno to find you the right combo.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Okay, use `bpm suite` all lowercase. You'd end up with this bit:

```
buzz_tags:
  - bpm suite
```

Which looks like what you have currently.

**Comment by LightGuard** [comment]
retest this please

**Comment by eschabell** [comment]
No way to test... trying it now several different tags on jboss.org....

**Comment by LightGuard** [comment]
Hm, `bpm suite` should work :(

**Comment by LightGuard** [comment]
Do we need to rebuild?

**Comment by LightGuard** [comment]
retest this please

**Comment by eschabell** [comment]
Yeah, bpm suite should work as current bpmsuite is old tag from year ago... now showing on http://developers.redhat.com/products/bpmsuite/buzz/.

Expect problem with feed on jboss.org is same here?

**Comment by LightGuard** [comment]
Yes, it's the same problem.

**Comment by LightGuard** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
Working right?

http://it-developers-pr.stage.redhat.com/pr/489/build/1018/products/bpmsuite/learn/#!project=bpmsuite&randomize=false

**Comment by eschabell** [comment]
Nope, not working: http://it-developers-pr.stage.redhat.com/pr/489/build/1018/products/bpmsuite/buzz/

**Comment by eschabell** [comment]
Not working: 

http://it-developers-pr.stage.redhat.com/pr/489/build/1018/products/bpmsuite/buzz/

screen shot 2015-10-21 at 10 12 17 am

**Comment by LightGuard** [comment]
For kicks and giggles, would you try `bpm+suite` please?

**Comment by eschabell** [comment]
Not the fix... 

http://it-developers-pr.stage.redhat.com/pr/489/build/1025/products/bpmsuite/buzz/

screen shot 2015-10-21 at 11 17 52 am

**Comment by eschabell** [comment]
Any progress on this?

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Dan fixed this in another PR. Should be fixed now: http://developers.redhat.com/products/bpmsuite/buzz/

**Pull request closed without merging**
