### PR TITLE
DEVELOPER-4245 Added loading image in search results

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4245 - Add loading image while waiting for results](https://issues.jboss.org/browse/DEVELOPER-4245)

Requirements:
The amount of time to return search results can be multiple seconds. There should be an image showing that loading is happening so users do not get confused.

To test:

1.  Search for 'eap'
2. Loading gif should show while results load
3. Click on the 'books' filter (this one takes the longest so you see the gif for a bit

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
@KamiQuasi I fixed the load more issue, it should be good to go now 👍

**Pull request merged**
