### PR TITLE
DEVELOPER-3554 Product mobile page style changes

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
@KamiQuasi Please take a look at this one too.

**Comment by robpblake** [comment]
retest this please

**Comment by KamiQuasi** [comment]
Looks good to me.

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
Hm, thought the tests were fixed

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
Approved by James and Tiffany

**Comment by RubyGemTSL** [comment]
Export hold issue when downloading again!

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
