### PR TITLE
Fixes DEVELOPER-3480 (robots.txt missing)

### PR DESCRIPTION
**Pull request by LightGuard**
See https://issues.jboss.org/browse/DEVELOPER-3480 for full information.

Added a few methods to fetch the robots.txt from the Drupal instance and
save that as part of the export. Also fixed tests that changed / were
added.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard Functionality looks fine. 

We still need to port over the previous robots.txt to Drupal as that  included disallows to `/auth` and `/download-manager`. I'm also not sure if content of the robots.txt produced by Drupal makes sense for the site.

**Comment by LightGuard** [comment]
Sure, we can add in those ones, trying to get a different robots.txt just for the exportis not going to be easy, unless we want to store it somewhere else and fetch it that way.

**Comment by robpblake** [comment]
@LightGuard I've just added a comment to https://issues.jboss.org/browse/DEVELOPER-3481 for an alternative approach that would help us solve the problem with the missing `robots.txt` and also the missing `.htaccess`.

**Comment by robpblake** [comment]
Closing this due to alternative approach implemented in #1429

**Pull request closed without merging**
