### PR TITLE
Update to brms overview product page.

### PR DESCRIPTION
**Pull request by eschabell**

### CODE REVIEW

**Comment by eschabell** [comment]
What is wrong with the build? I can't really see what is causing the failure...

**Comment by paulrobinson** [comment]
I'll need to look into this more tomorrow, but it's the acceptance tests that are failing: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/frontend-acceptance-tests/365/console

You shouldn't need to do this, but try updating this branch with upstream master. 

We have just added these tests, and we are working out some issues.

**Comment by eschabell** [comment]
It was a fresh fork just minutes before I PR'ed.... nothing to update that I can see... waiting on your findings.

**Comment by paulrobinson** [comment]
We've found the root cause of the problem. It's a bug in our new testing setup.

@RubyGemTSL Can you manually run the acceptance tests on this PR and report back?

**Comment by ollyjshaw** [comment]
ok to test

**Comment by eschabell** [comment]
Looks good now on the preview: 

http://it-developers-pr.stage.redhat.com/pr/593/build/1301/products/brms

My changes can go to production at your convenience.

**Comment by RubyGemTSL** [comment]
@paulrobinson you can go ahead and merge this. 

We need to run the tests on the branch rather than master to avoid this happening in the future. @ollyjshaw and I will sort it.

**Comment by eschabell** [comment]
This has still not hit production site: http://developers.redhat.com/products/brms/overview/

**Comment by paulrobinson** [comment]
Sorry @eschabell I missed the above comments.

**Comment by eschabell** [comment]
Thanks @paulrobinson but so far it has failed to update: http://developers.redhat.com/products/brms/overview/

**Comment by eschabell** [comment]
All good now... thanks and can be closed.

**Pull request merged**
