### PR TITLE
[RHDX-318] Add new metatag images and update configs.

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-318

### Verification Process
1. Share link from non-article page with Facebook to see global metatag og:image https://developer-preview-3522.ext.us-west.dc.preprod.paas.redhat.com/events/
2. Share link from article page without node share image to Facebook to see article metatag og:image view-source:https://developer-preview-3522.ext.us-west.dc.preprod.paas.redhat.com/articles/ubi-faq/
2. Share link from article page without node share image to Twitter to see article metatag twitter image view-source:https://developer-preview-3522.ext.us-west.dc.preprod.paas.redhat.com/articles/ubi-faq/

### CODE REVIEW

**Comment by alistairmc** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Review by jordanpagewhite — APPROVED** [review]
This looks good to me. I walked through the verification steps successfully. In the future, we could consider whether or not the level-of-effort would be worth investing time towards making the og_image URL values respect environments, but it does not seem like it is worth the investment of time currently. Thanks!

**Review by sjcox-rh — APPROVED** [review]
@rogeralloymagnetic this all seems to be working and looks good!

**Pull request merged**
