### PR TITLE
[HOLD - Merge Tuesday 05/02, 9:30 AM ET] DEVELOPER-4055, RHD-1964 -  RHD hero for OSIO, promo for summit

### PR DESCRIPTION
**Pull request by adelasofia**
Opening this PR for approval. DO NOT MERGE before Tuesday May 2nd, 9:30 AM Boston time.

[DEVELOPER-4055 ](https://issues.jboss.org/browse/DEVELOPER-4055) - Added RHD hero for OSIO and [RHD-1964](https://issues.jboss.org/browse/RHD-1964?_sscc=t) updated promo for summit.

Will close this PR once approved and reopen on Monday.

### CODE REVIEW

**Comment by adelasofia** [comment]
Approved by Mike and James. Will reopen on Monday to be merged Tuesday.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@KamiQuasi  @paulrobinson this is ready to go for tomorrow

**Comment by paulrobinson** [comment]
@adelasofia can you change the text from green to white? See: https://www.dropbox.com/s/mocc9j07nbehf0z/Screenshot%202017-05-01%2018.33.57.png?dl=0. the text is getting lost. This would look clearer: https://www.dropbox.com/s/4jg4szxp6rcn8f0/Screenshot%202017-05-01%2018.34.42.png?dl=0

@insectengine and @jkbrock suggested and approved this change.

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
