### PR TITLE
RHD-618 Updated A-MQ Getting Started Page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by catrobson** [comment]
This should not be published to the production site.  @rayploski has content updates to follow the Get Started Recipe more accurately and these should be added before publishing.

**Comment by adelasofia** [comment]
@catrobson I added @rayploski's changes :smiley: 

Preview A-MQ Get Started: http://it-developers-pr.stage.redhat.com/pr/413/build/832/products/amq/get-started/

**Comment by catrobson** [comment]
Looks good to me!

**Comment by rayploski** [comment]
Looks great!

**Pull request merged**
