### PR TITLE
DEVELOPER-2499 - Docker nighly build is using production keycloak

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by paulrobinson** [comment]
Looks good to me. @ollyjshaw can you review?

**Comment by ollyjshaw** [comment]
Looks good to me. Can we change 
# Pull Request configuration (with Docker)
to 
# Docker staging configuration (PR and Nightly)
on line 103 for clarity?

**Comment by RubyGemTSL** [comment]
@ollyjshaw - done

**Comment by ollyjshaw** [comment]
:+1:

**Pull request merged**
