### PR TITLE
DEVELOPER-5432: Github style for all snippets

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This adds the Github code snippet style and Highlight.js syntax
highlighting for all code snippets, both those included in Body
(WYSIWYG) fields on Article content types and those created using this
new Code Snippet assembly type. This will provide consistent styling, to
the end user, even though the editorial tool 'behind' the scene allows
for either the old way (Body field, WYSIWYG) or the new way using the
assembly type.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5432

### Verification Process

The styling between code snippets added via the new assembly type and existing code snippets included in the Body field should both have syntax highlighting and use the Github code theme/style.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
@LightGuard I am receiving the following failed tests locally when I run the JS unit tests:

```
HeadlessChrome 0.0.0 (Linux 0.0.0) Search Result Count should not have a term with only a count FAILED
        Expected '10 results found ' to equal '10 results found'.
            at <Jasmine>
            at UserContext.<anonymous> (/home/unit/src/tests/unit/rhdp-search/rhdp-search-result-count_spec.js:20:30)
            at <Jasmine>
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 109 of 134 (1 FAILED) (skipped 1) (0 secs / 1.226 secs)
HeadlessChrome 0.0.0 (Linux 0.0.0) Search Sort and Paging should read "Sort results by [[sort]] FAILED
        Expected 'Sort results by
        Relevance
        Most Recent' to equal 'Sort results by'.
            at <Jasmine>
            at UserContext.<anonymous> (/home/unit/src/tests/unit/rhdp-search/rhdp-search-sort-page_spec.js:40:37)
            at <Jasmine>
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 132 of 134 (2 FAILED) (skipped 2) (2.488 secs / 1.538 secs)
TOTAL: 2 FAILED, 130 SUCCESS
```

Do you have any hunch why I am getting these failing tests in areas of the site that seem unrelated to the changes I've made in this PR?

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by LightGuard** [comment]
merge conflict

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@jordanpagewhite Who needs to sign-off on this one?

**Pull request merged**
