### PR TITLE
ignoring all social tests for PR's

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by LightGuard** [comment]
Will this help us with the timeouts?

**Comment by RubyGemTSL** [comment]
@LightGuard @robpblake - once this is complete can you please merge to stop PR's from failing.

**Comment by LightGuard** [comment]
@RubyGemTSL Any reason to wait for blinkr?

**Comment by RubyGemTSL** [comment]
@LightGuard - nope -please merge :)

**Pull request merged**
