### PR TITLE
Implement new nav twig and css for jump nav

### LINKED ISSUE #3387: Jump-to nav has no margins
Estimate: 1

**Description**
The jump-to nav has no margins on larger viewports so it's getting flushed left.

**To Reproduce**
1. Go to any page with jump nav... developers.redhat.com/topics/istio/service-mesh
2. See the no padding

**Expected behavior**
The component should have the same margins as the rest of the content on the page and should match the expanding margins once at the larger breakpoint (as the rest of the site has). Margins on tablet and mobile **are correct**.

**Screenshots/GIFs**
Screen Shot 2019-11-19 at 9 56 39 AM

**Additional context**

### LINKED ISSUE #3425: Jump-to nav has no margins twig update
**Description**
* https://github.com/redhat-developer/developers.redhat.com/issues/3387

**To Reproduce**
jump nav has an incorrect border

**Expected behavior**
border aligns with other content

### PR DESCRIPTION
**Pull request by alistairmc**
### GitHub Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3387
Fixes #3425 
Fixes #3387 

### Verification Process
go to /topics/kubernetes/
validate nav margins are correct and nav works as expected

### CODE REVIEW

**Comment by mindreeper2420** [comment]
LGTM - desktop and mobile views work/look as expected with the latest updates.

**Comment by alistairmc** [comment]
Sure @gdoyle1 I will make that change now

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Pull request merged**
