### PR TITLE
DEVELOPER-5891 - Updated Author tile styles

### PR DESCRIPTION
**Pull request by adelasofia**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5891

### Verification Process
Author tiles should have the following styles: [see screenshot](https://issues.jboss.org/secure/attachment/12452598/Author%20page.png)

Author tiles appear in video heros, featured article cards, article pages and event heros.

Verify that author tiles look as expected on pages such as /events/, /devnation/, /rhel8/install-rhel8-vbox/, etc

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by adelasofia** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
@adelasofia Who's the best person to sign off on this one?

cheers,

Rob

**Pull request merged**
