### PR TITLE
[WiP] Octopus Launch

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@adelasofia Ideally, we should get this into the Octopus branch on Tuesday. Can you take a look at the test failures: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-frontend-acceptance-tests/1690/console. 

@RubyGemTSL can you help Adela if she's not sure what the cause is?

**Comment by paulrobinson** [comment]
Try rebasing with master, maybe @RubyGemTSL already fixed these tests.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@paulrobinson the job has vanished. Now retesting, will have a look once it is completed.

**Comment by paulrobinson** [comment]
I've updated the Octopus branch with master, and raised the following PR, with the branch updated to master too. https://github.com/redhat-developer/developers.redhat.com/pull/925

I suggest waiting on the outcome of that first before spending any time on it.

**Comment by RubyGemTSL** [comment]
@paulrobinson  - roger that, will do.

**Comment by RubyGemTSL** [comment]
@adelasofia the tests are failing due to the registration flow changing that I was not aware of. I will fix this. 

 ```
Scenario: Unauthorised customer should see a list of 'Other developer resources' # _cucumber/features/downloads/downloads.feature:15
    Given I am on the Downloads page                                               # _cucumber/features/step_definitions/common/navigation_steps.rb:1
    Then the following 'Other developer resources' links should be displayed:      # _cucumber/features/step_definitions/downloads.steps.rb:42
      | Container development kit |
      | Building Linux RPMs       |
      | Developing with OpenShift |
      expected ["Building linux rpms", "Developing with openshift"] to include "Container development kit" (RSpec::Expectations::ExpectationNotMetError)
      ./_cucumber/features/step_definitions/downloads.steps.rb:45:in `block (2 levels) in <top (required)>'
      ./_cucumber/features/step_definitions/downloads.steps.rb:43:in `each'
      ./_cucumber/features/step_definitions/downloads.steps.rb:43:in `/^the following 'Other developer resources' links should be displayed:$/'
      _cucumber/features/downloads/downloads.feature:17:in `Then the following 'Other developer resources' links should be displayed:'

```
There was also one failure that may be due to your changes. If this is expected go to _cucumber/features/downloads/downloads.feature:17 and remove "Container development kit".

**Comment by RubyGemTSL** [comment]
retest this now please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@RubyGemTSL you need to use this syntax exactly: 'retest this please'

**Comment by RubyGemTSL** [comment]
@paulrobinson - yep, not sure where I got that from!

**Comment by RubyGemTSL** [comment]
see my comments on #925

**Comment by paulrobinson** [comment]
Replaced by https://github.com/redhat-developer/developers.redhat.com/pull/925. @RubyGemTSL and I will work to get the tests passing and it merged tomorrow morning UK time.

**Pull request closed without merging**
