### PR TITLE
[SURGE 3254] dynamic_content_list CTA Button Fix

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3254

### Verification Process
1. View homepage a2 375px wide
2. Confirm CTA button is centered with the correct margins/padding

Screen Shot 2019-10-22 at 1 38 32 PM

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@rogeralloymagnetic Should this be targeting `master` now that `surge` has been released?

**Comment by robpblake** [comment]
@rogeralloymagnetic Who needs to review/sign-off on this one please?

cheers,

Rob

**Comment by rogeralloymagnetic** [comment]
@robpblake this is for Jordan and Joe, I already have them set as reviewers.

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Review by jordanpagewhite — APPROVED** [review]
I verified these changes here: https://developer-preview-3301.ext.us-west.dc.preprod.paas.redhat.com/ . The button is centered and container margins are respected.

**Review by jordanpagewhite — CHANGES_REQUESTED** [review]
I didn't read the full scope of the issue before submitting my review. Sorry. I do not think that the issue is entirely resolved. If you scroll down to the bottom of the homepage, you will see that the Rich Text assembly at the very bottom of the content of the homepage has 2 buttons. The 2nd button is not centered properly on mobile viewports.

**Review by jordanpagewhite — APPROVED** [review]
Okay, I now understand all 3 of the issues raised in the original issue report, made by Joe. Sorry for the back and forth and confusion. Yes, given that 2 of these button issues are with markup that is content vs. generated in some way by Drupal templates, then those will need to be resolved in content. @rogeralloymagnetic pointed out how we could do that for those scenarios. This PR addresses the other scenario. I will approve this. Thanks.

**Review by gdoyle1 — APPROVED** [review]
@rogeralloymagnetic Going to approve this because it did fix the dynamic content assembly CTA! I found another area where the CTA was not full-width so I'll create a follow up issue for that.

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
