### PR TITLE
added RHEL Get Started note if already registered

### PR DESCRIPTION
**Pull request by MikGue**
This is just to clarify that if an existing user has already registered in the CP, then they can skip this section.

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
General approach for cases where Mike is making quick edits in GitHub:

Mike: please check the preview and confirm this is what you wanted. 

Adela: please check the code and the preview. Merge it if you are happy.

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by MikGue** [comment]
Let's cancel this now. Override via #957

**Comment by adelasofia** [comment]
Closing this PR, see Mike's comment above.

**Pull request closed without merging**
