### PR TITLE
DEVELOPER-3550 SOLP mobile layout and css changes

### PR DESCRIPTION
**Pull request by adelasofia**
https://issues.jboss.org/browse/DEVELOPER-3550

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this pleae

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
FYI the old status is not cleared on your current PR's. Please ignore the old status: 'Drupal:Acceptance Tests' above.  New Pull-Requests will only include the new statuses:
- Drupal:FE KC/DM Acceptance Tests
- Drupal:FE Acceptance Tests

**Comment by adelasofia** [comment]
Approved by James C.

**Pull request merged**
