### PR TITLE
[HOLD] Updated SO query to use the same DCP as the rest of the build.

### PR DESCRIPTION
**Pull request by paulrobinson**
Trying this again with a clean PR. Maybe there was some stale state in the old one.

### CODE REVIEW

**Comment by paulrobinson** [comment]
@RubyGemTSL any ideas why these tests are failing: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/2420/artifact/_cucumber/reports/rhd_test_report.html.

They seem to be timing out. Maybe the SO query is taking too long in the staging environment, vs the production environment? That's the only change in this PR.

**Comment by RubyGemTSL** [comment]
@paulrobinson strange that it is not taking a screenshot on fail. Will investigate.

**Comment by RubyGemTSL** [comment]
@paulrobinson - there is one failing resources test that I can reproduce. It is failing on a test that selects 'show results from "Last Quarter"'. It seems the results that are displayed are from slightly over the past quarter. I've raised a PR to ignore this test until we can intercept results from DCP and stub results as it is always failing. The SO pages are working fine for me so maybe there was some issues when the tests were ran. I'll do a retest.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Once #1493 is merged this will pass.

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Need to see what's going on with this one

**Comment by RubyGemTSL** [comment]
@LightGuard for some reason with this PR I have to log in to stumpjumper and manually kill the pr image in order to retest it. The tests are bombing out for drupal as the previous image is still hanging around.

**Comment by paulrobinson** [comment]
That's odd. Maybe we leave this PR around for @robpblake to investigate on his return? It may be symptomatic of something bigger and might happen again.

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@paulrobinson / @RubyGemTSL I can't see anything Docker specific causing a problem here. From what I can see the StackOverflow tests time out on original acceptance test job, which means that they are still running when the Drupal Acceptance test job kicks off.

It looks like to me that using the staging DCP with the StackOverflow tests just doesn't work. @RubyGemTSL Please correct me if I'm wrong?

**Comment by RubyGemTSL** [comment]
@robpblake - yep you're right. This is the only PR that is affected by this. As we discussed, shall we just run the smoke tests on awestruct builds? In the unlikely event that we have to switch to the awestuct build we can run the full suite of tests before the switch?

**Comment by paulrobinson** [comment]
I think we'll be turning off the Awestruct builds soon anyway. I'm ok with us switching to just smoke-tests on Awestruct.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@robpblake so we finally got this working. Can you review?

You can see it actually working on the site here: http://developers-pr.stage.redhat.com/pr/1487/export/stack-overflow/?q=

Also the tests passed, apart from an unrelated and expected failure.

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request closed without merging**
