### PR TITLE
RHD-1641 Add videos from RH Middleware Youtube Channel to Mobil…

### PR DESCRIPTION
**Pull request by paulrobinson**
…e Platform "Learn" page on RHD

### CODE REVIEW

**Comment by LightGuard** [comment]
Is this ready to be merged? Who needs to sign off?

**Comment by paulrobinson** [comment]
I've requested review on https://issues.jboss.org/browse/RHD-1641

**Comment by paulrobinson** [comment]
I've not heard bak from Fiona. This looks right to me and the change is pretty clear in the PR. I think we can merge after an engineering review.

**Comment by paulrobinson** [comment]
@robpblake if you have time, this is a quick review, and will get the PR count lowered.

**Pull request merged**
