### PR TITLE
DEVELOPER-4769 Scheduled Publishing Date

### PR DESCRIPTION
**Pull request by LightGuard**
JIRA: https://issues.jboss.org/browse/DEVELOPER-4769

To test verify all content types have a scheduled update section at the bottom and the Moderation State field is just before it.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by Dantheman720** [comment]
@LightGuard - Can you rebase on this? Looks like we have some merge conflicts

**Comment by Dantheman720** [comment]
@LightGuard - The moderation state location does not immediately precede the scheduled updates (not sure if that matters); however, it seems to be missing entirely on the "Coding Resource" content-type.

**Comment by LightGuard** [comment]
Which content types @Dantheman720 ? Also, I'm leaving Coding Resource alone as that's used by the maven plugin.

**Comment by Dantheman720** [comment]
@LightGuard - The moderation state needs to be adjusted on the following content types:
Article, Books, Cheatsheets, Events, Basic page, and Video Resources.

**Comment by LightGuard** [comment]
?! Dang. Guess that's what I get for hand merging config changes.

**Comment by Dantheman720** [comment]
:)

**Pull request merged**
