### PR TITLE
[TESTING] [DO NOT MERGE] DEVELOPER-5530 Katacoda embed test content.

### PR DESCRIPTION
**Pull request by visuale**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5530

### CODE REVIEW

**Comment by KamiQuasi** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@visuale this needs a re-sync with master

**Comment by robpblake** [comment]
@visuale What's the status of this PR? Does it need to be merged or is this just a test?

cheers,

Rob

**Comment by visuale** [comment]
@robpblake It's there for testing, but as it turns out I might be overwriting at least part of it.

**Pull request closed without merging**
