### PR TITLE
Tidy test format with guard rerun

### PR DESCRIPTION
**Pull request by ollyjshaw**

### CODE REVIEW

**Comment by LightGuard** [comment]
I know this isn't related to your changes, but blinkr is failing due to an undefined constant at https://github.com/redhat-developer/developers.redhat.com/blob/master/_ext/blinkr/bad_text.rb#L22. Would you mind changing `Blinkr::Error` to `::Blinkr::Error` please?

**Comment by LightGuard** [comment]
ready to test

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by paulrobinson** [comment]
@RubyGemTSL can you review this?

**Comment by RubyGemTSL** [comment]
@paulrobinson @ollyjshaw - looks good to me.

**Pull request merged**
