### PR TITLE
DEVELOPER-4531 new fields for Learning Path

### PR DESCRIPTION
**Pull request by LightGuard**
JIRA: https://issues.jboss.org/browse/DEVELOPER-4531

Added the new fields requested to articles, videos, cheat sheets, and
books.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Looks like something strange is going in PR/staging environment. I'm looking into it.

**Comment by RubyGemTSL** [comment]
I know that Keycloak appears to be down but not sure why that would break the Blinkr tests.

**Comment by LightGuard** [comment]
This is ready to merge now, Tiffany approves.

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
