### PR TITLE
RHD-512 Changed Foundation's Small breakpoint to match the mobile header

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by wesbos** [comment]
What was the issue with the header here?

**Comment by adelasofia** [comment]
@wesbos the 'small' breakpoint for the Mobile header was 768px and foundation's 'small' breakpoint  was 641px, so the collapsing and rearrangement of components was happening at different widths

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by wesbos** [comment]
:+1: Good to merge

**Pull request merged**
