### PR TITLE
[DEVELOPER-3025] Only wait for Drupal and Searchisko if necessary

### PR DESCRIPTION
**Pull request by robpblake**
The PR reaper job is failing: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-pr_reaper/

This is because the job is trying to wait for searchisko to start, but there is no searchisko container for that scenario.

This update to control.rb ensure that we only wait for Drupal and Searchisko if they are part of the supporting_services required by the job that is executing.

### CODE REVIEW

**Comment by robpblake** [comment]
@LightGuard I would appreciate a code review on this please.

cheers,

Rob

**Comment by robpblake** [comment]
This doesn't work because we always start Drupal no matter if we're using it or not, and hence this waits for Drupal and then uses the env variables.

**Comment by robpblake** [comment]
Updated to only start the required services for each environment. That means that right now we do not start Drupal or it's database for a pull request.

**Comment by LightGuard** [comment]
@robpblake Shouldn't we have a test to verify the supported services check method?

**Comment by RubyGemTSL** [comment]
grrrrr, again with the 500 on login page!

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard Tests added for new function in control.rb.

cheers,

Rob

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Maybe we need to do a docker-down first? I thought we were though.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
