### PR TITLE
DEVELOPER-4202 - Add Content for New Search Landing Page

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4202

### CODE REVIEW

**Comment by Dantheman720** [comment]
@KamiQuasi - That sounds good. I think I know what you mean. I'll give that a go

**Comment by RubyGemTSL** [comment]
lots of failures on this. I'll look into them.

**Comment by Dantheman720** [comment]
I definitely broke a test with this change. The results page is pretty tightly coupled to the search app. I think I'll need to modify the tests for this to work.

**Comment by RubyGemTSL** [comment]
The e2e tests are failing as the spinner (.loading class) isn't displayed anymore when searching via the primary nav. Instead of "Loading..." I briefly see the "well this is awkward..." text. 

Steps to repro: 

Do a search from the homepage
When you're on the search page you briefly see the "well this is awkward..." text.

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@RubyGemTSL - I see that there is an issue with the "Load More" functionality, but I don't think my code should affect that. By spot checking, I'm not able to replicate the error.

**Comment by RubyGemTSL** [comment]
@Dantheman720 I see what's happened here. The problem is for the particular scenario that is failing it is navigating to the search page directly. So you get the "well this is awkward" page instead of search results. I'll raise a PR on your branch with a fix for you.

**Comment by RubyGemTSL** [comment]
@Dantheman720 PR waiting for you fixing test and added extra scenario.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@Dantheman720 has @tiffanynolan approved this?

**Comment by KamiQuasi** [comment]
@Dantheman720 and @tiffanynolan it looks good from what I can see. I'll give it until the EOB today and then merge if I don't hear otherwise.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
