### PR TITLE
[RHDX-116] Review and standardize assembly attributes render array

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-116](https://projects.engineering.redhat.com/browse/RHDX-116)

The following JIRA Issues are included in this PR:
[RHDX-138](https://projects.engineering.redhat.com/browse/RHDX-138)
[RHDX-80](https://projects.engineering.redhat.com/browse/RHDX-80)
[RHDX-85](https://projects.engineering.redhat.com/browse/RHDX-85)
[RHDX-95](https://projects.engineering.redhat.com/browse/RHDX-95)

### Verification Process

The intention of this PR is to simplify and standardize how some attributes are rendered, by removing duplicate markup from Twig templates, and injecting the attributes via preprocess hooks. 

To make this review process easier, a [spreadsheet](https://docs.google.com/spreadsheets/d/1cD6W-nwd4wqyhMclD_kqJffnmOvjM_RNA8sT_C-UXoc/edit?folder=19VNClRm4l5-by69H2tAgbuMXTqG0aUmT#gid=0) is available to review examples of each of the following. 

- View the Assembly Classes sheet and view an example of each assembly. Verify the top-level/parent assemblies have the .component css class and the children/nested assemblies do not.
- The **style** attribute for a background-image was moved from twig to a hook;  Verify the assemblies with background images renders as expected.
-- The video_hero assembly should have the class rhd-m-video-background if it does not have a background.
- The **level** attribute on learning-path-cards (for field_difficulty) was relocated from twig to a hook. Verify the level attribute renders as expected.
- The **audience_selection** attribute was relocated from twig to hooks. Verify the audience_selection attribute appears on the assemblies that use the field.
- Various PHP warnings related to twig and hooks were included and are listed above.

### CODE REVIEW

**Comment by staceymosier** [comment]
rebuild this please.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by staceymosier** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by staceymosier** [comment]
rebuild this please

**Comment by staceymosier** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Pull request merged**
