### PR TITLE
DEVELOPER-2978 DTS 4.1 Beta product updates page

### PR DESCRIPTION
**Pull request by rctrh**
* Add an updates page covering Devloper Toolset 4.1 Beta
* (An Updates link in the left nav should automatically be added)

### CODE REVIEW

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
retest this please

**Comment by rctrh** [comment]
I can't tell why the build failed. @LightGuard ?

**Comment by RubyGemTSL** [comment]
An error occurred: the server responded with status 502 on the PR builder - is why it failed.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by rctrh** [comment]
Please merge this.   Approved by @MikGue - https://issues.jboss.org/browse/DEVELOPER-2978

**Comment by rctrh** [comment]
Are there any admins who can merge this or let me know what's blocking it?

**Pull request merged**
