### PR TITLE
DEVELOPER-3295 - Issues with JBoss DV Getting started page

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by Dantheman720** [comment]
Harshul approved this https://issues.jboss.org/browse/DEVELOPER-3295. @LightGuard/ @adelasofia - Can this be merged?

**Pull request merged**
