### PR TITLE
[RHDX-443] Events Collection Assembly

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-443

### Verification Process
1. Add sessions to multiple events with different categories.
2. Add the new "Events Collection" assembly to an events or assembly_page node.
3. Run through the possible options on the assembly. See links to preassembled options below.

Sessions for Single Event (with filter):
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/node/219975/
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/node/219975/edit

Sessions for Single Event (without filter):
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/node/217595/
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/node/217595/edit

All Sessions Ungrouped (with filter):
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/events/
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/events/edit

All Sessions Grouped by Event:
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/devnation/upcoming/
https://developer-preview-3566.ext.us-west.dc.preprod.paas.redhat.com/devnation/upcoming/edit

### Known Issues
- [x]  Table width style issues. (ready for next commit)
- [x]  Expandable styles don't exactly match design site. (ready for next commit)
- [x]  Make event categories required on an event. (ready for next commit)
- [x]  Remove "Register" link on ungrouped table & add link to event title. (ready for next commit)
- [x]  Fix register link conditional logic. (ready for next commit)

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
Rebuild this please.

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
Rebuild this please.

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by Scottbredhat** [comment]
Verification requirements 
1. Add sessions to multiple events with different categories - I did so using all known permutations, including new and curated events. encountered no bugging. no page loss or redirect. no broken links. also registered for a session and received email confirmation. this is a screen shot of the youtube address the mail directed me to to view the session:
Screen Shot 2020-05-26 at 9 09 35 AM

this is one of the emails i received
Screen Shot 2020-05-26 at 9 10 54 AM

here's the other
Screen Shot 2020-05-26 at 9 21 04 AM
all links on all sessions sent me to the correct reg and the correct link. all links sent to me via email took me to proper destination

2. Add the new "Events Collection" assembly to an events or assembly_page node - I did so using notes from presentation plus exploration. had no issues merging existing content, creating single events (ungrouped and grouped). tested filters as well with no cosmetic or connective breaks when content shifted. 
only encountered a single cosmetic issue (shown below in a screen shot). the number sequences that include date, time and zone are not separated or identifiable from one another. the copy should be broken, punctuated or otherwise displayed to be certain dates and times are distinct and identifiable.
Screen Shot 2020-05-22 at 5 01 04 PM

3. Run through the possible options on the assembly. See links to preassembled options below - I used links to preassembled options to test and view all known options. i also explored available permutations and viewed the 'fields' and 'settings' values. did not encounter any broken links, any cosmetic question marks or any connective failure. also tested the parameters of curated versus new content and how those differed in terms of interaction. did not encounter any issues and did not have any serious breaks in logic.

**Comment by rogeralloymagnetic** [comment]
@Scottbredhat I was not able to reproduce #2 form your comment above. Given that all of the tables generated in the Events Collection assembly split date and time into separate columns, I believe that to be something you saw from some other content.

**Review by maryshak1996 — APPROVED** [review]
Looks great -- no issues on my end!

**Review by staceymosier — CHANGES_REQUESTED** [review]
I left some feedback and screenshots on the JIRA task.

There are multiple js errors on the /events page possibly related to tablesort; Would prefer to see those resolved or mitigated (or excluded in Sentry if necessary).

There is also a change to the active state of links after you right-click on them. Please see screenshot in the JIRA.  I'm not sure if it should hold up the merge, but fyi in case no one noticed it.

**Review by staceymosier — APPROVED** [review]

**Pull request merged**
