### PR TITLE
Added Ian's new key to vault

### PR DESCRIPTION
**Pull request by paulrobinson**
Also updated README.md to add Rob Terzi’s details, which were missed in
a previous commit.

### CODE REVIEW

**Comment by paulrobinson** [comment]
@RubyGemTSL please download the secrets file and confirm that it works.

@LightGuard please tech-review the PR. Notice that I also updated the Readme.md. This is needed to document which keys people need when updating this file in the future. This step was missed when you added Rob Terzi.

**Comment by LightGuard** [comment]
Looks fine to me. @RubyGemTSL are you able to decrypt?

**Comment by RubyGemTSL** [comment]
@paulrobinson - all OK! @LightGuard - it's good to merge

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
