### PR TITLE
Cache wasn't rebuilding in prod / staging

### PR DESCRIPTION
**Pull request by LightGuard**
If we're not building from scratch there was an issue where the cache,
and updating the db for module updates, wasn't being done. I've tried
this out on the command line it works fine.

### CODE REVIEW

**Comment by LightGuard** [comment]
@robpblake Please look this over and apply if you're happy with it.

**Comment by robpblake** [comment]
@LightGuard The unit tests are failing. Could you also please raise a JIRA issue for this as a bug, linked to the v1 release just so that we can track what work is going into the release.

cheers,

Rob

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard Looks good to me.

**Pull request merged**
