### PR TITLE
[HOLD] DEVELOPER-4266: Refactor current Login/Registration acceptance tests using webdriverIO

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[DEVELOPER-4266:](https://issues.jboss.org/browse/DEVELOPER-4266) Refactor current Login/Registration acceptance tests.

This PR decouples the keycloak e2e tests from the rhd website tests. Keycloak tests will not be ran as part our PR pipeline. Instead they will be ran via a separate staging job on Jenkins which we will not own. 

As part of this PR, there was 2 scenarios added to the website tests. These two scenarios simply click on the Login and Register links within the site nav and verify that they correctly navigate a user to the login/register pages.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
Hey @lkrzyzanek could you please review the test scenarios for [login](https://github.com/RubyGemTSL/developers.redhat.com/blob/a8e6641c51f8c83424faf30bc5c156334e87a277/_tests/e2e/keycloak/features/kc_basic_login.feature), [register](https://github.com/RubyGemTSL/developers.redhat.com/blob/a8e6641c51f8c83424faf30bc5c156334e87a277/_tests/e2e/keycloak/features/kc_basic_registration.feature), and [social login](https://github.com/RubyGemTSL/developers.redhat.com/blob/a8e6641c51f8c83424faf30bc5c156334e87a277/_tests/e2e/keycloak/features/kc_social_login.feature)?

**Comment by RubyGemTSL** [comment]
ping @lkrzyzanek

**Comment by lkrzyzanek** [comment]
Could you please ping me next week and we could go through those changes via BJ? Thanks.

**Comment by RubyGemTSL** [comment]
@lkrzyzanek 👍

**Pull request closed without merging**
