### PR TITLE
Feature/consolidate title margins and size 3291 3290 3284

### LINKED ISSUE #3284: Dynamic Content Assembly Title should be left aligned
**Estimate:** 

The title field should be left aligned for the dynamic content assembly with disqus.  It is currently centered by default.

Screen Shot 2019-10-17 at 1 12 55 AM

### LINKED ISSUE #3290: Inconsistent H2 font size
**Estimate:**

All H2's should be 28px.

Currently there are inconsistencies in sizes. Some H2's are 32px and some are 28px.

For ex: Rich text assembly Titles are H2 but come up at 32px. When using the H2 class in a rich text wysiwyg, it also comes up at 32px. Both these cases need to be updated to 28px. 

In card style assemblies H2 is correct at 28.

A good example page is [/topics/service-mesh/](https://developers.redhat.com/topics/service-mesh/) page.

### LINKED ISSUE #3291: (3) Title padding for assemblies is inconsistent
Estimate: 3

I noticed in [/topics/service-mesh/](https://developers.redhat.com/topics/service-mesh/) page that  the bottom padding for the assembly title is inconsistent. 

On rick text assemblies, the bottom padding is 16px (this is correct):
Screen Shot 2019-10-17 at 9 46 22 AM

On assemblies with cards, the bottom padding is 24px for titles:
Screen Shot 2019-10-17 at 9 46 08 AM

Let's update it to 16px throughout all assemblies.

### Acceptance Criteria

- All header elements of similar weight render exactly the same way across the site. This could include  h2, h2.pf-c-title, etc.
- Existing header elements in WYSIWYG are styled appropriately h1,h2,h3, ... no classes

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
Fixes #3291 
Fixes #3290 
Fixes #3284 

### Verification Process
Build goes green 

Review titles across the site for consistency and meets requirements for fixed stories

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by alistairmc** [comment]
@gina I have pushed the change you requested, once the build is finished can you check and approve if ok

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
