### PR TITLE
DEVELOPER-3751 - Adobe DTM - Implement Page Type Values in Drupal

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3751

`digitalData.page.category.pageType`, `digitalData.page.category.contentType`, and `digitalData.page.category.contentSubType` should be set as listed here: https://docs.google.com/a/redhat.com/spreadsheets/d/1mRQ2_Rmt3tx7nnJ_RmKwIP_qz9S8pBtt7TmEA6UcJjw/edit?usp=sharing

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@LightGuard the quickest way to test this is plop this in the dev console and make sure there is at least one sensible value in the array on each page: `[digitalData.page.category.pageType, digitalData.page.category.contentType, digitalData.page.category.contentSubType]`

**Comment by KamiQuasi** [comment]
@LightGuard @adelasofia @Dantheman720 the quickest way to test this is plop this in the dev console and make sure there is at least one sensible value in the array on each page: `[digitalData.page.category.pageType, digitalData.page.category.contentType, digitalData.page.category.contentSubType]`

**Pull request merged**
