### PR TITLE
add link to devsuite installer

### PR DESCRIPTION
**Pull request by nickboldt**
add link to devsuite installer

### CODE REVIEW

**Comment by LightGuard** [comment]
@nickboldt Good to go once the tests pass?

**Comment by nickboldt** [comment]
Well, I'd hoped for feedback from one of the various stateholders here, but sure. Punch it.

**Comment by LightGuard** [comment]
@nickboldt who would be the best stake holder to ask, @MikGue  ?

**Comment by nickboldt** [comment]
Yes, and @alexeykazakov @dgolovin

**Pull request merged**
