### PR TITLE
[DEVELOPER-3146] added nightly tags to social registration tests.

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
failed due to keycloak error (500 on login page)

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL Are you OK for this to be merged?

**Comment by RubyGemTSL** [comment]
@robpblake yes, please merge. Thanks!

**Pull request merged**
