### PR TITLE
[DEVELOPER-2679] - added visibility library to foundation

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by paulrobinson** [comment]
Retest this please

**Comment by paulrobinson** [comment]
Retest this please

**Comment by paulrobinson** [comment]
@lkrzyzanek can you review this please?

**Comment by lkrzyzanek** [comment]
Where is PR build output please? I cannot find any link here or in jira.

**Comment by paulrobinson** [comment]
Click on 'Show all Checks' below and select 'Details' next to 'Site Preview'. We consolidated all the chatty messages into there.

**Comment by lkrzyzanek** [comment]
Ah, I see. nice.

**Comment by lkrzyzanek** [comment]
Yep looks good. You can go to production.

**Comment by paulrobinson** [comment]
Thanks @lkrzyzanek. It should be live within 30 mins.

**Pull request merged**
