### PR TITLE
Allowing asciidoctor includes for sections

### PR DESCRIPTION
**Pull request by LightGuard**
Sections were not working with includes before, they are now.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
@rctrh has verified this works for him.

One small caveat is that anything you're including inside sections (which are being rearranged via a layout) must have a lower section heading (if the section being included has a level 2 heading the headings in the included content must be level 3 or lower) level otherwise things break without any apparent cause.

**Comment by robpblake** [comment]
I suspect @adelasofia is better placed than I am to say if this works or not.

cheers,

Rob

**Comment by LightGuard** [comment]
@adelasofia You'll need to try an asciidoctor include in a page that uses sections to verify this works. When you do the include make sure you're make it relative to the base of the project, not the file you're adding the include to.

**Pull request merged**
