### PR TITLE
Cucumber daily build

### PR DESCRIPTION
**Pull request by ollyjshaw**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@LightGuard can you review?

**Comment by paulrobinson** [comment]
@RubyGemTSL Can you review the changes around the tests.

**Comment by LightGuard** [comment]
Looks fine to me. Really wondering if we want to build phantomjs though or if we should ship the binary in the repo for the image.

**Comment by RubyGemTSL** [comment]
+1 on this - looks good.

@LightGuard, that would be possible if running on Mac, or Windows, but on Linux for the latest version of phantom you have to build from source.

**Comment by LightGuard** [comment]
@RubyGemTSL Not if you build it on the target architecture once and the just copy that binary to the repo and add it into the docker image that way :)

**Comment by ollyjshaw** [comment]
@lightguard. That sounds like a good idea. Would be a big boost. Also, we can have a docker image repo too. That would make things easier.

**Comment by LightGuard** [comment]
We have an internal repo for all of Red Hat, but I'm not sure of the
current state of that.

On Thu, Oct 15, 2015 at 11:27 AM, Oliver Shaw <notifications@github.com>
wrote:

> @lightguard <https://github.com/lightguard>. That sounds like a good
> idea. Would be a big boost. Also, we can have a docker image repo too. That
> would make things easier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/476#issuecomment-148465906>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by ollyjshaw** [comment]
Ok cool, might be one for a separate improvement.

**Pull request merged**
