### PR TITLE
DEVELOPER-3424 DEVELOPER-3404 DEVELOPER-3400

### PR DESCRIPTION
**Pull request by LightGuard**
This fixes all the renames for content types

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
