### PR TITLE
DEVELOPER-3242 Updated keycloak.js

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
tests will fail due to failing tests being pushed over the weekend. I will have a PR merged soon to fix this.

**Comment by LightGuard** [comment]
retest this please

**Comment by lkrzyzanek** [comment]
Thanks. I can review once site preview will be live.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by lkrzyzanek** [comment]
Looks good. You can merge it to PROD.

**Pull request merged**
