### PR TITLE
DEVELOPER-3771 Changing the url for the "Get Started" Button

### PR DESCRIPTION
**Pull request by LightGuard**
Fixing the URL of the "Get Started" button to point to the Hello World pages instead of Get Started pages.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Tiffany said this was good to go.

**Comment by tiffanynolan** [comment]
@LightGuard Can this get merged today?

**Comment by RubyGemTSL** [comment]
@LightGuard - i'm not sure what is happening with the acceptance tests. I'm getting 

`
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/redhat-developer/developers.redhat.com/
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:735)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:983)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1016)
	at hudson.scm.SCM.checkout(SCM.java:484)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1274)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/redhat-developer/developers.redhat.com/ +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*" returned status code 1:
stdout: 
stderr: error: there are still refs under 'refs/remotes/origin/pr/1704'
`

Any ideas? I've not made any changes that could have caused this :-/ cc @robpblake

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard @RubyGemTSL The failure was being caused as we had a branch called 'pr/1704' that had been pushed to this repo. That branch was causing naming conflicts when Jenkins was trying to check-out this pull request branch. I've deleted the 'pr/1704' branch and it seems OK now.

@LightGuard Can you double-check your Git config. I notice as well that this PR is raised from a branch pushed directly to the redhat-developers/developers.redhat.com repository.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
thanks @robpblake

**Comment by LightGuard** [comment]
@robpblake Yeah, I pushed it. Thought it would go straight to the PR as it was a small change. No such luck. On the plus side, tests have all passed. Looks like we're good to merge.

**Pull request merged**
