### PR TITLE
[HOLD] DEVELOPER-4266: Refactor current Login/Registration acceptance tests using webdriverIO

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[DEVELOPER-4266 ](https://issues.jboss.org/browse/DEVELOPER-4266): Refactor current Login/Registration acceptance tests using webdriverIO

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request closed without merging**
