### PR TITLE
Fixes 'missing argument: -p'  error when not running docker

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
:+1:  This is needed for anyone not using docker (which is pretty much everyone)

**Comment by paulrobinson** [comment]
@adelasofia can you confirm this works for you?

**Comment by adelasofia** [comment]
@paulrobinson It works :smiley:

**Comment by LightGuard** [comment]
I helped her find the fix

**Comment by paulrobinson** [comment]
just dbl-checking.

**Pull request merged**
