### PR TITLE
DEVELOPER-3195 - 'Microservices for Java Developers' Promo page

### PR DESCRIPTION
**Pull request by insectengine**
Created promotion page for the Microservices for Java Developers book

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by LightGuard** [comment]
Who needs to sign off on this?

**Comment by insectengine** [comment]
We still need to update the download link to the book once it's put in the Download Manager by Mark N.

**Comment by paulrobinson** [comment]
This needs some engineering work to get the download working. Closing this PR, but please don't delete the branch, as the Engineer will pull the commit from it.

**Pull request closed without merging**
