### PR TITLE
[SURGE 3131] Author detail page

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3131

### Verification Process

- https://developer-preview-3150.ext.us-west.dc.preprod.paas.redhat.com/author/doug-tidwell/
- https://developer-preview-3150.ext.us-west.dc.preprod.paas.redhat.com/marcus_biel_bio/

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
This looks great other than the one comment I left @rogeralloymagnetic Thanks.

**Review by jordanpagewhite — APPROVED** [review]
Looks good to me! Thanks for the change @rogeralloymagnetic

**Review by sjcox-rh — COMMENTED** [review]
@rogeralloymagnetic I realize we didn't provide any designs, but this page looks good!!

A couple very minor requested updates. However, these are not show stoppers so if this needs to get merged, we can revisit later as long as tickets are created to track the update, up to you!

1. Left align pagination under cards
2. Remove 24 px top padding from card section
Screen Shot 2019-10-01 at 9 43 24 PM

**Comment by jordanpagewhite** [comment]
@rogeralloymagnetic You can find an example of a left aligned pager element below a card grid here: http://localhost:1313/components/collection/ . Hopefully that is similar enough to your use case

**Comment by rogeralloymagnetic** [comment]
> @rogeralloymagnetic I realize we didn't provide any designs, but this page looks good!!
> 
> A couple very minor requested updates. However, these are not show stoppers so if this needs to get merged, we can revisit later as long as tickets are created to track the update, up to you!
> 
> 1. Left align pagination under cards
> 2. Remove 24 px top padding from card section
> 
> Screen Shot 2019-10-01 at 9 43 24 PM

@sjcox-rh these updates are complete in the latest commit.

**Review by gdoyle1 — CHANGES_REQUESTED** [review]
@rogeralloymagnetic Can we make the author name in the article cards black so that it is only text? (since the link would take them to that page they are already on)

**Comment by jordanpagewhite** [comment]
I have created this issue to address @gdoyle1 's feedback above: https://github.com/redhat-developer/developers.redhat.com/issues/3160

Per Slack conversation, we will merge this PR with the understanding that the remaining issue will be addressed in #3160

**Review by jordanpagewhite — APPROVED** [review]
Looks good to me

**Pull request merged**
