### PR TITLE
added visibility library to foundation

### PR DESCRIPTION
**Pull request by wesbos**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
Replaced with: https://github.com/redhat-developer/developers.redhat.com/pull/884

I think all open PRs need re-opening :-(

**Comment by paulrobinson** [comment]
Retest this please

**Pull request closed without merging**
