### PR TITLE
DEVELOPER-4432 - Create 'Try it now' feature for EAP Kitchensink quickstart

### PR DESCRIPTION
**Pull request by Dantheman720**
This is a PR to work off of for the try it now feature.
https://issues.jboss.org/browse/DEVELOPER-4432

Test see what it looks like, I've been running this in the chrome console:

sel = document.querySelector('#block-rhd-content > article > section.product-graphics.application-development');
sel.removeChild(sel.firstElementChild);
var title = "Try EAP 7 right now in the cloud.
No download, installation or configuration needed.",
subtitle = "Within seconds, you could be using a browser based IDE to evaluate EAP 7.",
buttonID = "test button id",
buttonText = "Launch EAP 7 Now",
buttonLink = "http://www.google.com",
icon = "https://static.jboss.org/rhd/images/icons/rocket.png";

wc = document.createElement('rhdp-tryitnow');
wc.title = title;
wc.subtitle = subtitle;
wc.buttonID = buttonID;
wc.buttonText = buttonText;
wc.buttonLink = buttonLink;
wc.icon = icon;
sel.insertBefore(wc, sel.firstChild);

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard @RubyGemTSL @KamiQuasi - Not sure what's going on here, but npm install seems to be causing the build to fail.

**Comment by LightGuard** [comment]
Yeah, Luke is looking into it

Jason Porter
Sent from Outlook<https://aka.ms/qtex0l> on iOS
________________________________

**Comment by RubyGemTSL** [comment]
@Dantheman720 what happened when you ran them locally?

Just a guess but it may be the use of "use strict"; at the top of your tests? 

FYI: to run the unit tests in docker (as we do on PR's): 
`ruby _tests/run_tests.rb --unit --use-docker`

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
Looks like we're waiting on some changes here @Dantheman720 to merge this.

**Pull request merged**
