### PR TITLE
DEVELOPER-4018 - Research why the code for the Thank you message is not firing for media downloads

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4018

To test: 
* Visit http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37082/promotions/building-reactive-microservices-in-java/ and download the book.
* You will be redirected back to developers.redhat.com. 
* Change the domain to http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37082/, but keep the media-download-confirmation and url query string intact.
* The download should automatically fire now.

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@Dantheman720 I'm not sure why the tests don't seem to finish

**Comment by Dantheman720** [comment]
@adelasofia - I think it's kind of happening across the board now :(

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
I'm going to remove the ruby tests in the next sprint. They are using hardcoded products so they keep failing. I'll refactor these and move them to the e2e's, using the drupal rest endpoint for products in the next sprint. If your PR has no impact on the failing tests please go ahead and merge. Sorry about this.

**Pull request merged**
