### PR TITLE
[DO NOT MERGE] [MWES-3342] Migrate Drupal to use the database for configuration storage

### PR DESCRIPTION
**Pull request by robpblake**
This PR introduces a major change into the way in which Drupal stores its configuration. This PR migrates the active configuration from being on the filesystem into the database. We are doing this as a first step in trying to resolve some of our performance issues with Drupal.

This PR works in the following way:

- It introduces the `fs-to-db-config.yml` migration Ansible Playbook
- This will copy all configuration into the database by executing `drush php:script` against the PHP migration script in this PR
- Once the configuration is migrated, the playbook will archive the existing on-disk configuration into `/config/active/drupal-active-config-pre-migration.tar.gz`
- It will then write `/config/active/config.migrated.DO_NOT_DELETE`. This is a filesystem flag to Drupal that allows it to switch over the configuration source. When this flag is not present, Drupal will use the Filesystem configuration. When the flag is present, Drupal will use the DatabaseStorage for configuration

### JIRA Issue Link
* https://issues.jboss.org/browse/MWES-3342

### Verification Process

* The build should go green
* [Log in to the Drupal container](https://github.com/redhat-developer/developers.redhat.com/tree/master/previews/README.md)
  * `drush config:status` should work and report that there are no changes to import
  * `drush updatedb:status` should work and report that there are no updates to run
  * `drush cr` should work
  * Go into the `/config/active` directory and ensure that `drupal-active-config-pre-migration.tar.gz` exists
  * Finally, check that the service configured in Drupal for storage is the database version:

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
@jordanpagewhite This is going to need some serious tire kicking, but from my initial playing this seems to be working OK.

Any comments on the approach here greatly appreciated. If you look at it and recoil in horror, then lemme know. I don't want to put in ugly hacks that can't be easily backed out.

Could you have a play with it and see if the admin workflows feel any faster? If anything at least we know that we can get to the position where we have configuration in the DB which feels easier for us to scale moving forwards.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by joeschram** [comment]
Thanks for the work on this @rob

**Comment by robpblake** [comment]
retest this please

**Comment by fearlsgroove** [comment]
This code looks reasonable to me but I couldn't get it to run locally. Here's the failure:

```
TASK [Rebuild the Drupal Cache] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "drush cr && touch /drupal-workspace/drupal_1/work/drupal.cr.do.not.delete", "delta": "0:00:00.818957", "end": "2019-08-13 04:36:36.291996", "msg": "non-zero return code", "rc": 1, "start": "2019-08-13 04:36:35.473039", "stderr": "\nIn Container.php line 153:\n                                                                               \n  You have requested a non-existent service \"cache.backend.null\". Did you mea  \n  n one of these: \"cache.backend.memory\", \"cache.backend.apcu\", \"cache.backen  \n  d.php\"?                                                                      \n                                                                               \n\ncache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify] [--druplicon] [--] <command>", "stderr_lines": ["", "In Container.php line 153:", "                                                                               ", "  You have requested a non-existent service \"cache.backend.null\". Did you mea  ", "  n one of these: \"cache.backend.memory\", \"cache.backend.apcu\", \"cache.backen  ", "  d.php\"?                                                                      ", "                                                                               ", "", "cache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify] [--druplicon] [--] <command>"], "stdout": "", "stdout_lines": []}
```

The important bit is:
```
You have requested a non-existent service \"cache.backend.null\"
```
The PR build looks fine tho so...

**Comment by robpblake** [comment]
> This code looks reasonable to me but I couldn't get it to run locally. Here's the failure:
> 
> ```
> TASK [Rebuild the Drupal Cache] ****************************************************************************
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "drush cr && touch /drupal-workspace/drupal_1/work/drupal.cr.do.not.delete", "delta": "0:00:00.818957", "end": "2019-08-13 04:36:36.291996", "msg": "non-zero return code", "rc": 1, "start": "2019-08-13 04:36:35.473039", "stderr": "\nIn Container.php line 153:\n                                                                               \n  You have requested a non-existent service \"cache.backend.null\". Did you mea  \n  n one of these: \"cache.backend.memory\", \"cache.backend.apcu\", \"cache.backen  \n  d.php\"?                                                                      \n                                                                               \n\ncache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify] [--druplicon] [--] <command>", "stderr_lines": ["", "In Container.php line 153:", "                                                                               ", "  You have requested a non-existent service \"cache.backend.null\". Did you mea  ", "  n one of these: \"cache.backend.memory\", \"cache.backend.apcu\", \"cache.backen  ", "  d.php\"?                                                                      ", "                                                                               ", "", "cache:rebuild [--cache-clear [CACHE-CLEAR]] [--no-cache-clear] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--xh-link XH-LINK] [--notify] [--druplicon] [--] <command>"], "stdout": "", "stdout_lines": []}
> ```
> 
> The important bit is:
> 
> ```
> You have requested a non-existent service \"cache.backend.null\"
> ```
> 
> The PR build looks fine tho so...

@fearlsgroove hmm...lemme take a look at that.

**Comment by robpblake** [comment]
@fearlsgroove Fixed up that error you were receiving. I'd managed to break the local development experience.

cheers,

Rob

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
Rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Pull request closed without merging**
