### PR TITLE
DEVELOPER-2878: RHEL Get Started KVM changes

### PR DESCRIPTION
**Pull request by rctrh**
Incorporated feedback from Daniel Berrange

### CODE REVIEW

**Comment by LightGuard** [comment]
ok to test

**Comment by RubyGemTSL** [comment]
This seems to be blocked by Blinkr as OS1 is offline.

**Comment by rctrh** [comment]
Is there a resolution in site for the Blinkr problem?  I'd like to get this out soon if possible.

**Comment by LightGuard** [comment]
Blinkr is running now

**Comment by LightGuard** [comment]
Though you didn't make any changes that create links so I'm going to call it good

**Pull request merged**
