### PR TITLE
DEVELOPER-2869 Add KVM tab

### PR DESCRIPTION
**Pull request by rctrh**
* Added KVM/libvirt sections
* Improved wording: your red hat account
* Added KVM images
* Cleanup: Removed some trailing spaces and double spaces

### CODE REVIEW

**Comment by rctrh** [comment]
@adelasofia - Do any of the templates need to change to add the 5th, KVM tab?

**Comment by LightGuard** [comment]
Looks like there's merge conflicts

**Comment by rct** [comment]
There shouldn't be a merge conflict. Only products/rhel/get-started.adoc gets updated. Several images are added.  I don't see anything on github.

**Comment by LightGuard** [comment]
Maybe github hadn't refreshed.

**Comment by LightGuard** [comment]
@adelasofia Are you okay handling this one when it's ready (if it isn't ready)?

**Comment by adelasofia** [comment]
Closing this. Replaced by [992](https://github.com/redhat-developer/developers.redhat.com/pull/992)

**Comment by rctrh** [comment]
Sorry there are some typos that need to be corrected.   I updated https://issues.jboss.org/browse/DEVELOPER-2869. 

Trying to edit via the github UI kept making other sections as changed and I think loosing some headings/links.

The changes can be seen in this commit on my repo:  [https://github.com/rctrh/rh-tthw/commit/90ad209850c7854b8973ed3c7dd116537d7013cf]

Can you please pick up the file from https://github.com/rctrh/rh-tthw/blob/master/install-rhel7-combined.adoc (Raw link: https://raw.githubusercontent.com/rctrh/rh-tthw/master/install-rhel7-combined.adoc).

Note: I verified that there were no changes against the `get-started.adoc` in your PR

Thanks & sorry for the trouble.

**Pull request closed without merging**
