### PR TITLE
[NEEDS JIRA ISSUE] Product page drafts available to anonymous role

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This resolves an issue where Product page drafts were available to view
by anonymous users (unauthenticated). Since we have a custom
implementation of a Node-like page, controller and routing, we need to
validate each possible scenario where a node is or isn't published and
the role(s) of the current user visiting the page. In this instance, we
we properly validating the roles, but did not check the published status
of the Node object. I thought that this was handled by the routing, if
the 'thing' you are routing is a Node object, but it does not.

In addition to these changes, there are some minor changes made to
resolve some variables that were being accessed without validation in
rhd_common.product_related.inc and rhdp.theme. This should resolve some
related errors in the Drupal watchdog logs.

### JIRA Issue Link
* n/a

### Verification Process

All of these steps will assume that, for a given Product node, the `field_use_new_product_page` checkbox/bool field is checked i.e. we are using the 'New/assembly-based' Product pages.

#### Content Creator, Content Editor, Content Admin and Admin roles

In a browser window, log into an account with at least one of the roles above to perform the verification steps. This will be the 'default' verification steps for each section. I will explicitly state when you should switch to another role (anonymous).

#### Anonymous role (unauthenticated)

In a different incognito window/session, please remain unauthenticated and visit the site to perform the verification steps. I will provide a section within each verification step, when appropriate to state the Anonymous role verification steps.

#### Create a Product node we will use to verify this PR

You will need to be logged into an account that can create Product nodes

Go here: /node/add/product

Do this:

* Add values for all of the required fields
* Add values for the Overview Page Content, Getting Started Page Content and Download Page Content assembly fields. You can just reference any existing assembly if you'd like
* Add a dummy value for URL Product Name. Don't use an existing/known URL Product Name, although the form validation should prevent you from adding a URL Product Name that already exists in Drupal (see https://github.com/redhat-developer/developers.redhat.com/pull/2761)
* Ensure that the moderation state is Draft and save the Node edit form

#### Unpublished (draft) Product page - /overview

Do this:

* Visit the /overview sub-route of the Product node you created above

You should see this:

* You should be able to view the Product node with the content you add to the Overview Page Content field
* If you visit /admin/reports/dblog, there should be no errors in the log related to the Product page /overview sub-route

##### Anonymous role

You should see this:

* You should receive the 404 page since you are not permitted access to drafts

#### Unpublished (draft) Product page - /getting-started

Do this:

* Visit the /getting-started sub-route of the Product node you created above

You should see this:

* You should be able to view the Product node with the content you add to the Getting Started Page Content field
* If you visit /admin/reports/dblog, there should be no errors in the log related to the Product page /getting-started sub-route

##### Anonymous role

You should see this:

* You should receive the 404 page since you are not permitted access to drafts

#### Unpublished (draft) Product page - /download

Do this:

* Visit the /download sub-route of the Product node you created above

You should see this:

* You should be able to view the Product node with the content you add to the Download Page Content field
* If you visit /admin/reports/dblog, there should be no errors in the log related to the Product page /download sub-route

##### Anonymous role

You should see this:

* You should receive the 404 page since you are not permitted access to drafts

#### Published (current revision is published) Product page - /overview

Do this:

* Go into the Node edit form our the Product you created, and move the Moderation state to Published and save the Node edit form
* Visit the /overview sub-route of the Product node you just published

You should see this:

* You should be able to view the Product node with the same content as in the last steps (when it was a Draft)
* If you visit /admin/reports/dblog, there should be no errors in the log related to the Product page /overview sub-route

##### Anonymous role

You should see this:

* You should see the exact same content as the authenticated role

#### Published (current revision is published) Product page - /getting-started

Do this:

* Visit the /getting-started sub-route of the Product node you just published

You should see this:

* You should be able to view the Product node with the same content as in the last steps (when it was a Draft)
* If you visit /admin/reports/dblog, there should be no errors in the log related to the Product page /getting-started sub-route

##### Anonymous role

You should see this:

* You should see the exact same content as the authenticated role

#### Published (current revision is published) Product page - /download

Do this:

* Visit the /download sub-route of the Product node you just published

You should see this:

* You should be able to view the Product node with the same content as in the last steps (when it was a Draft)
* If you visit /admin/reports/dblog, there should be no errors in the log related to the Product page /download sub-route

##### Anonymous role

You should see this:

* You should see the exact same content as the authenticated role

#### Published (draft) Product page - /overview

Do this:

* Go into the Node edit form our the Product you created, and make an arbitrary change like add another existing assembly to the Overview Page Content field
* Then move the Moderation State back to Draft and save the Node edit form
* Visit the /overview sub-route of the Product node

You should see this:

* You should see the latest revision (not the latest published revision) of the Node. This means that you would see the arbitrary existing assembl(ies) you added to the Overview Page Content field in the previous step.

##### Anonymous role

You should see this:

* You should see the last *published* revision of this content. That means that you will *not* see the same content as you did with the other role(s). You will see the same version of this page that you saw prior to the draft being published.

#### Published (draft) Product page - /getting-started

Do this:

* Go into the Node edit form our the Product you created, and make an arbitrary change like add another existing assembly to the Getting Started Page Content field
* Then move the Moderation State back to Draft and save the Node edit form
* Visit the /getting-started sub-route of the Product node

You should see this:

* You should see the latest revision (not the latest published revision) of the Node. This means that you would see the arbitrary existing assembl(ies) you added to the Getting Started Page Content field in the previous step.

##### Anonymous role

You should see this:

* You should see the last *published* revision of this content. That means that you will *not* see the same content as you did with the other role(s). You will see the same version of this page that you saw prior to the draft being published.

#### Published (draft) Product page - /download

Do this:

* Go into the Node edit form our the Product you created, and make an arbitrary change like add another existing assembly to the Download Page Content field
* Then move the Moderation State back to Draft and save the Node edit form
* Visit the /download sub-route of the Product node

You should see this:

* You should see the latest revision (not the latest published revision) of the Node. This means that you would see the arbitrary existing assembl(ies) you added to the Download Page Content field in the previous step.

##### Anonymous role

You should see this:

* You should see the last *published* revision of this content. That means that you will *not* see the same content as you did with the other role(s). You will see the same version of this page that you saw prior to the draft being published.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
To build upon Rob's feedback above. Only the old, paragraphs-based Product download pages load with no content. The new, assembly-based Product download pages load as expected.

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
I just completed the following verification steps to test my latest changes.

h3. Verification steps for existing Products

h5. Unauthenticated

The following pages should load with the old, paragraphs-based Product page design:

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/overview/
https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/download/

This page should load a 404 as the route/page does not exist:

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/getting-started

These pages should load as the new, assembly-based Product page designs:

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/openjdk/overview/
https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/openjdk/download/
https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/openjdk/getting-started/

h5. Authenticated

* Repeating the steps above should result in the same experience

h3. Create a new, assembly-based Product draft

* Create a Product and check the 'Use New Product Page' field in the Compose tab
* Fill out the rest of the required fields with dummy content
* Reference at least 1 assembly from the Overview, Getting Started and Download assembly reference fields
* Save the node as a Draft

If you visit the 3 routes/pages of your new Product page:

h4. Authenticated (w/ View All Revisions permission)

h5. Overview

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/TestProduct0805190934/overview

You should see the Code here. Go anywhere. CTA assembly I referenced.

h5. Getting Started

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/TestProduct0805190934/getting-started

You should see the Featured Evangelists assembly I referenced.

h5. Download

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/TestProduct0805190934/download

You should see the Service Mesh with Istio assembly I referenced.

h4. Unauthenticated

h5. Overview

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/TestProduct0805190934/overview

You should see a 404.

h5. Getting Started

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/TestProduct0805190934/getting-started

You should see a 404.

h5. Download

https://developer-preview-2985.ext.us-west.dc.preprod.paas.redhat.com/products/TestProduct0805190934/download

You should see a 404.

**Comment by jordanpagewhite** [comment]
@robpblake I removed the Changes Request label since I've addressed your feedback. Please let me know if you spot any other issues. I've detailed my latest verification steps in a comment above.

**Comment by robpblake** [comment]
@jordanpagewhite All looks fine to me. Can you create a JIRA issue for this so that we can track the changes that have gone in?

cheers,

Rob

**Comment by joeschram** [comment]
@jordanpagewhite I’m seeing a similar issue which may be related—an inability to *unpublish* previously published nodes, specifically katacodas. I’m tracking down more details, I’ll share them soon.

**Comment by robpblake** [comment]
@jordanpagewhite What's the status of this one please?

cheers,

Rob

**Comment by robpblake** [comment]
@jordanpagewhite As discussed, closing this for now to reclaim some resources, but please re-open when it suits you.

cheers,

Rob

**Pull request closed without merging**
