### PR TITLE
[HOLD] Developer 3534 - Increase browser/device testing coverage

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by LightGuard** [comment]
@robpblake please review and merge

**Comment by RubyGemTSL** [comment]
@LightGuard - I'm still working on this.

**Comment by paulrobinson** [comment]
@robpblake needs to review this as it touches the Docker configuration.

**Comment by RubyGemTSL** [comment]
@robpblake I think given the size of this PR it will be best to wait until I am back from Holiday to merge this. Lets keep it on hold.

**Pull request closed without merging**
