### PR TITLE
New RHEL Overview page - DEV-2799

### PR DESCRIPTION
**Pull request by MikGue**
This has the new text plus pointers to the correct images (commented at bottom of doc). However, an expert will need to correctly insert the images.

### CODE REVIEW

**Comment by LightGuard** [comment]
ok to test

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@MikGue I have my doubts about this looking the way you envisioned it. Is it displaying correctly?

**Comment by adelasofia** [comment]
@MikGue I'm not sure how this is supposed to look, is there a wireframe I can look at so I can fix this layout?

**Comment by adelasofia** [comment]
Closing this PR, it has been replaced by [#969](https://github.com/redhat-developer/developers.redhat.com/pull/969)

**Pull request closed without merging**
