### PR TITLE
RHD-592 Fixed redirect links

### PR DESCRIPTION
**Pull request by Dantheman720**
I combined these into one PR; however there is one issue.  Instead of saying the actual product it displays the current product instead of what is downloaded - https://github.com/redhat-developer/developers.redhat.com/blob/master/_partials/getstarted-thankyou.html.slim#L4

image

### CODE REVIEW

**Comment by paulrobinson** [comment]
Notice that EAP need fixing too:

https://photos-6.dropbox.com/t/2/AACEtKvkeR4dpAxV0QuL3nyEpP7Qt_hYAOaLBQW5Dr9aTA/12/541583/png/32x32/1/_/1/2/Screenshot%202015-09-28%2018.08.32.png/EPKnTBjOotfwAyABIAIoAQ/BeNkqo2U3Nb_4bir7XNDU2S5pobCr4X1W6WSvTlVeuQ?size=1280x960&size_mode=2

**Comment by paulrobinson** [comment]
retest this please

**Comment by Dantheman720** [comment]
Working on the Javascript to display the correct product on redirect

**Comment by paulrobinson** [comment]
You are missing a space character. Notice: 'downloadingJBoss' on the thankyou banner.

**Pull request merged**
