### PR TITLE
DEVELOPER-3908 - Update sites for release of devstudio 10.3.0.GA

### PR DESCRIPTION
**Pull request by mbooth101**
Change also includes updates to get-started.adoc

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
this is ok to test

**Comment by RubyGemTSL** [comment]
ok to test

**Comment by LightGuard** [comment]
@mbooth101 Thanks for the PR, however, all of this information is now in Drupal. You should make your changes there. Let me know if you need further information.

**Comment by nickboldt** [comment]
@LightGuard How do we edit stuff in Drupal? How do we get access? please grant nboldt and mabooth access to such system and provide URLs to see the repo/site/whatever.

**Comment by nickboldt** [comment]
Note also that these changes should not be applied until the download manager links work .. https://projects.engineering.redhat.com/browse/RCM-12959

**Pull request closed without merging**
