### PR TITLE
[DO NOT MERGE] DEVELOPER-5099 - Outage message updates

### PR DESCRIPTION
**Pull request by KamiQuasi**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5099

### Verification Process
TBD

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Pull request closed without merging**
