### PR TITLE
Updated supported hypervisior

### PR DESCRIPTION
**Pull request by praveenkumar**
Added Hyper-V and removed VMware for CDK-2.1 release.

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
@pmuir can you review the content change?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
Is this good to merge?

**Comment by LightGuard** [comment]
@RubyGemTSL @praveenkumar are we waiting for download manager links or anything for this?

**Comment by RubyGemTSL** [comment]
@LightGuard I'm not sure.

**Comment by praveenkumar** [comment]
@LightGuard I don't think we are waiting for anything because this PR is to add Hyper-V support.

**Comment by LightGuard** [comment]
Okay, I'm going to merge then.

**Pull request merged**
