### PR TITLE
[WIP] [RHDX-468] Fix node latest route

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-468

### Verification Process

The current state of this PR is to compare disabling trailing slash for a content type, and evaluate a possible change in editorial workflow.

- View a published Topic node as an editor
- See the local tasks block on the page
- Use the edit button
- Make a change to the node, save as Draft
- Upon save, you are taken to /my-node/latest (with no trailing slash)
- You are able to view your changes here, but /my-node displays the published state

Compare this workflow with other content types.

Before this can be merged, we need to discuss the intention of handling trailing slashes, or if we need a patch that the trailing_slash module does not interfere with workflow routes.

### CODE REVIEW

**Comment by staceymosier** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
Removing trailing slash (my preferred option) will required some changes to our custom Product node/multiple routes implementation. We can take a look at this if everyone is fine with removing Trailing Slash.

**Comment by alistairmc** [comment]
retest this please

**Comment by staceymosier** [comment]
Closing so that the layout work is done in a different PR.

**Pull request closed without merging**
