### PR TITLE
[DO NOT MERGE] [DEVELOPER-5500] Remove Unneeded Content Types

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This removes some permissions from the Content Creator role for the
following content types (by machine name): page, promotion_card,
promotion_page, rhd_microsite, rhd_solution_overview and topic. This
will remove almost all instances of these deprecated content types from
sight of the Content Creator role. There is, however, at least one
instance which does not seem to be controlled by permissions, and that
is filtering of nodes, such as on the /admin/content page. Content
Creators can filter by these deprecated content types, but they still
cannot edit any of these nodes.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5500

### Verification Process

* I need to determine the verification process with SJ and/or Joe TBD

### CODE REVIEW

**Comment by LightGuard** [comment]
Merge conflict

**Comment by robpblake** [comment]
@jordanpagewhite What's the status on this one. Is it a case of close this PR and try again at a later date?

cheers,

Rob

**Comment by jordanpagewhite** [comment]
Hey @robpblake Yeah, I suppose we can just close this one and I will try again later. This has turned into a bigger discussion. Joe wants to entirely remove the content types from the database, but there are > 1000 nodes of these content types, so I sent him a table of those, but I am waiting on him to review that / next steps now.

**Comment by LightGuard** [comment]
Merge conflict

**Pull request closed without merging**
