### PR TITLE
[SURGE 3258] Call to action button text

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3258

### Verification Process
1. Edit the "Link text" field in the "CTA Link" section of a Call To Action assembly and confirm your text shows up.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@rogeralloymagnetic Should this be targeting `master` now that `surge` has been released?

**Comment by rogeralloymagnetic** [comment]
Good catch @robpblake updating my open PR's now.

**Review by sjcox-rh — APPROVED** [review]
Works as it should so good to merge!

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@rogeralloymagnetic Looks like this was approved by @sjcox-rh . Is there anything stopping us merging this?

cheers,

Rob

**Comment by rogeralloymagnetic** [comment]
@robpblake Just needs a quick technical review.

**Review by jordanpagewhite — APPROVED** [review]
Looks good to me! Thanks Roger

**Pull request merged**
