### PR TITLE
Adding Jim Applebee to secrets file

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
@drupalbee does this secrets file work for you?

**Comment by drupalbee** [comment]
Yes.

**Comment by paulrobinson** [comment]
@LightGuard you need to update the README.md to add Jim's name to the list. See the docs, also in README.md

**Comment by LightGuard** [comment]
Yeah, I forgot, sorry. We do this so often

**Pull request merged**
