### PR TITLE
DEVELOPER-2663 Updated Downloads page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
needs a rebase to get latest test updates with changes to login/register pages.

**Comment by paulrobinson** [comment]
@RubyGemTSL any idea why this is still failing the acc tests?

**Comment by paulrobinson** [comment]
This was approved by @tiffanynolan and @MikGue. Code looks fine to me too.

**Comment by paulrobinson** [comment]
Will merge once tests pass.

**Comment by RubyGemTSL** [comment]
@paulrobinson there is one failure in the Acceptance tests. that one scenario needs updating.

Failing Scenarios:
cucumber _cucumber/features/technologies/technologies.feature:8 # Scenario: Product landing page should display a list of available products separated by sections.

@adelasofia to fix:

```
Scenario: Product landing page should display a list of available products separated by sections.
    Given I am on the Technologies page
    Then I should see the Technologies page title
    And I should see the following main products sections:
      | INFRASTRUCTURE                   |
      | CLOUD PRODUCTS                   |
      | MOBILE                           |
      | JBOSS DEVELOPMENT AND MANAGEMENT |
      | INTEGRATION AND AUTOMATION       |
    And I should see a list of available products
    And I should see a description of available products
```

And the technologies page needs updating to reflect these changes. 
Update the page to:

```
require_relative 'base_page'
require_relative '../../../_cucumber/lib/helpers/products_helper'

class Technologies < BasePage

  class << self
    include ProductsHelper
  end

  set_url '/products/'

  elements :products_sections, '.development-tool'
  elements :products_link, 'h4 > a'
  element :infrastructure, '#infrastructure'
  element :cloud_products, '#cloud_products'
  element :mobile, '#mobile'
  element :jboss_dev_and_management, '#jboss_development_and_management'
  element :integration_and_automation, '#integration_and_automation'

  get_products[0].each do |product_id|
    # define elements for each available product
    element :"#{product_id}_section", "#development-tool-#{product_id}"
    element :"get_started_with_#{product_id}_button", "#get-started-with-#{product_id}"
    element :"product_#{product_id}_link", "##{product_id}"
    element :"learn_#{product_id}_link", "#learn-#{product_id}"
    element :"#{product_id}_docs_and_apis", "##{product_id}-docs-and-apis"
    element :"download_#{product_id}", "#download-#{product_id}"
  end

  def initialize(driver)
    super
  end

  def open
    load
    loaded?('Red Hat Products')
  end

  def product_titles
    titles = []
    elements = [infrastructure, cloud_products, mobile, jboss_dev_and_management, integration_and_automation]
    elements.each { |el| titles << el.text }
    titles
  end

  def available_products
    products = []
    products_link.map { |name|
      products << name.text }
    products
  end

end
```

**Comment by paulrobinson** [comment]
@RubyGemTSL can you confirm that this is failing for the same reason as the tests on the Octopus branch? If so, we can merge this as it doesn't make the situation any worse. We also need to get the Octopus branch tests passing ASAP. @RubyGemTSL is about to raise a PR for that.

**Comment by RubyGemTSL** [comment]
@paulrobinson - this is fine to merge

**Pull request merged**
