### PR TITLE
DEVELOPER-2433 - Allow acceptance tests to run concurrently

### PR DESCRIPTION
**Pull request by RubyGemTSL**
additional wip of DEVELOPER-2433

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@paulrobinson @ollyjshaw can we get this merged? I have change the acceptance test job to run in parallel and tests all green. Now we need this merged so we can run concurrent builds

**Comment by ollyjshaw** [comment]
:+1: Nice

**Comment by paulrobinson** [comment]
Great, waiting for tests to pass, then I'll merge.

**Comment by paulrobinson** [comment]
Failing ass tests: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-frontend-acceptance-tests/947/console

**Comment by RubyGemTSL** [comment]
@paulrobinson my bad, the step that Olly requested being put back in needed a slight modification. Should be green again soon.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by ollyjshaw** [comment]
Build failed due to increasingly common issue with github 5xx error. Creating a ticket for this 
@paulrobinson @RubyGemTSL

**Comment by RubyGemTSL** [comment]
cheers @ollyjshaw

**Comment by ollyjshaw** [comment]
Added a ticket for this https://issues.jboss.org/browse/DEVELOPER-2467

**Comment by RubyGemTSL** [comment]
@paulrobinson - good to go

**Pull request merged**
