### PR TITLE
[DO NOT MERGE][RHDX-499] Disable trailing slash to support Content Moderation Transitions

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-499
https://projects.engineering.redhat.com/browse/RHDX-504

### Verification Process
When you need to make changes to a currently published node, you should be able to do that and move that node into a Draft or Needs Review moderation state.  The published revision of the node is still available to end-users.  You should be able to view /my-node/latest to view the latest version.

We are suggesting to disable trailing slash module, so that content moderation state works correctly again, as of right now you will be taken to /latest/ and will see a 404.

As this affects other areas of the site, and how routes behave generally, any points of concern or things to test are in the JIRA issue.

There are other issues for Content Moderation Workflow that are not addressed in this PR; Those can be found liked to the JIRA ticket mentioned or in a relevant epic.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
This test failure is a false negative. I verified the workflow manually. I am going to look into this now.

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by staceymosier** [comment]
retest this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
retest this please

**Pull request closed without merging**
