### PR TITLE
DEVELOPER-4290 - Mike updated the product title

### PR DESCRIPTION
**Pull request by LightGuard**
Mike updated the title on the product and would like the link in the technology menu to match the title of the product.

### CODE REVIEW

**Comment by LightGuard** [comment]
@KamiQuasi feel free to merge whenever you're ready. This only changes the text in the Technologies menu for the .NET product.

**Comment by robpblake** [comment]
@LightGuard The tests will need updating to reflect the new menu item.

cheers,

Rob

**Comment by RubyGemTSL** [comment]
@LightGuard Is there any want we can hit a drupal end point to test product existence rather than hard-code them? I'd like to avoid hard coding products when I begin refactoring the tests.

**Comment by LightGuard** [comment]
Not currently.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@RubyGemTSL I think the test that is failing is due to the page not being updated. Not sure it will pass until that happens. Should we go ahead and merge, and then update Prod Drupal with the change?

**Comment by RubyGemTSL** [comment]
@KamiQuasi  yes let's do that. I want to get rid of hard coding products in tests. When we get the REST endpoint we can avoid these issues.

**Pull request merged**
