### PR TITLE
[SURGE 3064] Learning Paths assembly ('card' view_mode)

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3064

### Verification Process
1. View Learning Paths assembly: https://developer-preview-3161.ext.us-west.dc.preprod.paas.redhat.com/training/
2. Check Visual Styles all work as expected

Screen Shot 2019-10-07 at 9 07 33 AM

### CODE REVIEW

**Comment by robpblake** [comment]
@rogeralloymagnetic Drupal is failing to boot with the following errors:

```
 There were errors validating the config synchronization.\nUnable to install the <em class=\"placeholder\">devel_debug_log</em> module since it does not exist.\nUnable to install the <em class=\"placeholder\">kint</em> module since it does not exist. in Drupal\\Core\\Config\\ConfigImporter->validate() (line 737 of /var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php). \n\nIn ConfigImportCommands.php line 259:\n  
```

**Review by jordanpagewhite — APPROVED** [review]
This looks good to me. I tested out the dark and centered visual style. Looks good!

**Review by gdoyle1 — CHANGES_REQUESTED** [review]
These cards are supposed to look like this: 
Screen Shot 2019-10-07 at 12 17 53 PM. What's the best way I can go about requesting changes for this? Should I open a ticket in the front-end repo?

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 this is updated:
Screen Shot 2019-10-07 at 12 29 11 PM

**Review by sjcox-rh — APPROVED** [review]
@rogeralloymagnetic updated card looks good!

**Pull request merged**
