### PR TITLE
Build DCP from data dumps

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by paulrobinson** [comment]
Docs need updating, as the data dumps are a pre-req to getting this to build.

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by ollyjshaw** [comment]
It all looks good, I'm slightly worried about the race condition between searchisko and awestruct. We can move that into a new ticket for this weeks sprint

**Comment by paulrobinson** [comment]
Agreed, we should tackle the race condition this week. But I'm also keen to get this in, so will merge now and raise a JIRA for this week.

**Pull request merged**
