### PR TITLE
[DEVELOPER-5941] [DEVELOPER-5942] Fix drush cex errors in local development environment

### PR DESCRIPTION
**Pull request by robpblake**
This commit changes the way we run drush cex in the local development environment to ensure that deletion of configuration is properly captured and also to address an issue whereby Drupal could not write to the sync directory because it was owned by root.

The README.md is also updated to reflect the latest changes and the run-config-export.sh now performs a quick check to ensure we have properly bootstrapped the local Drupal instance before trying to export configuration

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5942
* https://issues.jboss.org/browse/DEVELOPER-5941

### Verification Process

* Build should go green
* Make changes to your local Drupal configuration (including uninstalling a module)
  * Run `run-config-export.sh` in the `_docker/drupal/dev` directory
  * Ensure that a `git status` shows what you would expect to see in terms of changes to the Drupal configuration

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Pull request merged**
