### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by LightGuard**
* Using perf improvements in awestruct (my branch currently)
* cdn functions are backed by PStore instead of YAML::Store

### CODE REVIEW

**Comment by paulrobinson** [comment]
Did you see this failure?

      An error occurred: uninitialized constant Psych::Store

**Comment by LightGuard** [comment]
Doh. I fixed that in the other PR. okay, I'll get it back in.

On Thursday, February 18, 2016, Paul Robinson <notifications@github.com>
wrote:

> Did you see this failure?
>
>   An error occurred: uninitialized constant Psych::Store
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/814#issuecomment-185982188>
> .
>


-- 
Sent from Gmail Mobile

**Comment by LightGuard** [comment]
Blinkr looks good, I think all the issues there (there's 8) are known.

**Comment by paulrobinson** [comment]
@LightGuard can you now raise a PR to switch back to the main Aweplug branch?

**Comment by LightGuard** [comment]
Aweplug? This is using master aweplug. You mean awestruct?

**Comment by paulrobinson** [comment]
Yes, sorry.

**Comment by LightGuard** [comment]
I will, these changes to awestruct haven't been merged in to awestruct yet though.

**Pull request merged**
