### PR TITLE
DEVELOPER-3850 - Stored Cross Site scripting present at developers.redhat.com

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3850

Added angular sanitize dependency to help with any other issues that may come up in the text as well, but also used the same technique as elsewhere to remove HTML tags from the content before sending it to the page.

### CODE REVIEW

**Comment by KamiQuasi** [comment]
@LightGuard @adelasofia @Dantheman720 if you want to verify this, try doing a search for "<script>alert" or "Richfaces 5 - Javascript" or "<script>alert'xxxxx'<script>" and it should not give an alert pop-up.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
This looks good to me. I think FE Acceptance tests are not working atm

cc: @RubyGemTSL

**Comment by RubyGemTSL** [comment]
yes looks like a keycloak issue now!

**Pull request merged**
