### PR TITLE
DEVELOPER-3046 Add buzz and resources to 'bottom half' of .NET topic page.

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
1 fail = Keycloak login issue: 500 on login page: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/607/artifact/_cucumber/reports/rhd_test_report.html

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
@paulrobinson Who needs to sign off?

**Comment by paulrobinson** [comment]
I put Burr as the reporter in JIRA, but @lincolnthree could also approve.

**Comment by paulrobinson** [comment]
FYI: @lincolnthree I only added one tag to make sure it worked. Just raise more PRs when you want more tags adding.

**Comment by lincolnthree** [comment]
Approved.

**Pull request merged**
