### PR TITLE
DEVELOPER-3042 CDK Product videos are not appearing on the site

### PR DESCRIPTION
**Pull request by paulrobinson**
Check this by ensuring https://www.youtube.com/playlist?list=PLf3vm0UK6HKot0DBAXHKQfRDjqWKxj2mK videos are in the DCP.

### CODE REVIEW

**Comment by LightGuard** [comment]
You have a JIRA ticket for this? We need to track it.

**Comment by paulrobinson** [comment]
I'll create one.

**Comment by paulrobinson** [comment]
See: https://issues.jboss.org/browse/DEVELOPER-3042

**Comment by LightGuard** [comment]
Keycloak login issue :(

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
