### PR TITLE
[SURGE 3199] Articles Content Type Fixes

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3199

### Verification Process
1. Navigate to: https://developer-preview-3201.ext.us-west.dc.preprod.paas.redhat.com/coderland/serverless/serverless-knative-intro/
2. Verify page grid is in wrapper with gutters that match the rest of the site.
3. Verify that the "Related Articles" section correctly displays cards in a grid.

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by gdoyle1** [comment]
Still not seeing the gutters @rogeralloymagnetic . Related articles look good

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
I demo'd this on Hangouts and got Gina's approval. I will be creating a issue in the Q3 board to standardize the padding/space at the top of node's (below the topic nav) for all content types that cannot/do not render an assembly first.

**Review by jordanpagewhite — APPROVED** [review]
This looks good to me

**Pull request merged**
