### PR TITLE
[DX-SURGE]

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link

https://github.com/redhat-developer/developers.redhat.com/projects/1 and
https://github.com/redhat-developer/rhd-frontend/projects/2

### Verification Process

This is a massive PR containing all of the changes that took place during the DX Surge scope of work.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by KamiQuasi** [comment]
rebuild this please

**Comment by LightGuard** [comment]
rebuild this please

**Comment by LightGuard** [comment]
rebuild this please

**Comment by LightGuard** [comment]
rebuild this please

**Comment by adelasofia** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
It looks like searching from the hamburger menu is still broken on mobile devices.

**Pull request merged**
