### PR TITLE
DEVELOPER-2642 Implementation of RHEL Download Page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
needs a rebase to get latest test updates with changes to login/register pages.

**Comment by paulrobinson** [comment]
@RubyGemTSL shouldn't the CI job be doing a rebase on master?

**Comment by RubyGemTSL** [comment]
@paulrobinson it should be, but I don't think it is as the changes to the tests are missing

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
