### PR TITLE
[RHDX-372] Remove Clicktale from developers.redhat.com

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-372

### Verification Process
go to /clicktale/ctIframe.htm page should now 404 need to check if we want this to 404 or should we add a redirect in content for it?

### CODE REVIEW

**Comment by alistairmc** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Pull request merged**
