### PR TITLE
Fixing the build of container data lite

### PR DESCRIPTION
**Pull request by LightGuard**
I needed to add the `cd` in each command, forgot the sub processes don't
stay with each invocation.

### CODE REVIEW

**Comment by LightGuard** [comment]
Retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
I cry..... 

Looks like another flaky search test. I'm on it.

**Comment by LightGuard** [comment]
@RubyGemTSL or @adelasofia if either of you two are happy with this (it's a fix for the container lite build). Please go ahead and merge.

**Pull request merged**
