### PR TITLE
Force Fuse docs to update to v6.3

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks like that did it.

**Comment by LightGuard** [comment]
@paulrobinson a test timed out on the normal acceptance tests

**Comment by paulrobinson** [comment]
I guess we need to go with this hack for now? We need the Fuse 6.3 docs live today.

**Comment by LightGuard** [comment]
Yep. Not really a hack, well, I guess it's a workaround.

**Pull request merged**
