### PR TITLE
[Developer 3271] Jump Nav FE Updates

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3271

### Verification Process
1. View /topics/service-mesh/
2. Update width of browser down to mobile and confirm it matches the specs in this ticket: https://github.com/redhat-developer/rhd-frontend/issues/375

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Comment by robpblake** [comment]
@rogeralloymagnetic Who needs to review and sign-off on this one?

cheers,

Rob

**Comment by rogeralloymagnetic** [comment]
@robpblake I've added SJ & Gina as reviewers. But, I haven't been able to access the PR environment for any of the PR's I've put up recently so I'm not sure they'll be able to review until that's sorted.

**Review by gdoyle1 — CHANGES_REQUESTED** [review]
@rogeralloymagnetic I could access it! It looks fantastic - the only change I'd like is to have the whole jump-to navigation disappear at breakpoint-sm! It looks great at all other screen sizes.

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 I _can_ do that in Drupal, but it's probably better that it goes in FE. Can you follow-up with Adam on that?

**Comment by jordanpagewhite** [comment]
rebuild this please

**Review by gdoyle1 — APPROVED** [review]
Thanks @rogeralloymagnetic !!

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
@gdoyle1 Is this the desired behavior re: max-width for the contents of the jump-to-nav?

Screen Shot 2019-11-01 at 9 42 49 AM

See: /openshift

**Comment by gdoyle1** [comment]
> @gdoyle1 Is this the desired behavior re: max-width for the contents of the jump-to-nav?
> 
> Screen Shot 2019-11-01 at 9 42 49 AM
> 
> See: https://developer-preview-3312.ext.us-west.dc.preprod.paas.redhat.com/openshift

@jordanpagewhite No that is not the desired behavior - it should have the same margins as the rest of the content so the first item lines up with everything else. Can we make that change please?

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Review by alistairmc — APPROVED** [review]
tested locally margins correct

**Pull request merged**
