### PR TITLE
Optimising the caching of bundle install in the awestruct docker build

### PR DESCRIPTION
**Pull request by ollyjshaw**

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
I'm still seeing the following when I run 'control.rb -b' for a second time:

Step 18 : RUN bundle install
 ---> Running in 26e4c1bf670b
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/awestruct/aweplug.git
Fetching git://github.com/awestruct/awestruct.git
Installing rake 10.0.4
Installing Platform 0.4.0
Installing open4 1.3.4
Installing POpen4 0.1.4
Installing i18n 0.7.0
Installing json 1.8.3 with native extensions
Installing minitest 5.7.0
Installing thread_safe 0.3.5

**Comment by ollyjshaw** [comment]
It should not run bundle install the second time, what was the output prior to that log? It should run Step 15-17 from the cache

```
Step 15 : COPY Gemfile Gemfile
 ---> Using cache
 ---> 96c87aec542c
Step 16 : COPY Gemfile.lock Gemfile.lock
 ---> Using cache
 ---> 227b5dadb824
Step 17 : COPY gemrc /home/awestruct/.gemrc
 ---> Using cache
 ---> 756aa5481d2e
Step 18 : RUN bundle install
```

**Comment by paulrobinson** [comment]
Here's what I have:

Step 15 : COPY Gemfile Gemfile
 ---> Using cache
 ---> f6c1dd80e725
Step 16 : COPY Gemfile.lock Gemfile.lock
 ---> 02e1853ac215
Removing intermediate container fb10444747b3
Step 17 : COPY gemrc /home/awestruct/.gemrc
 ---> 6a44184763db
Removing intermediate container 57c82927118b
Step 18 : RUN bundle install
 ---> Running in 26e4c1bf670b
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/awestruct/aweplug.git
Fetching git://github.com/awestruct/awestruct.git

**Comment by paulrobinson** [comment]
So seems like it's the Gemfile.lock that has changed

**Comment by paulrobinson** [comment]
OK, it builds fast now. It was because my gemfile.lock changed.

**Comment by ollyjshaw** [comment]
Thanks, the running of the gem update step in the piple is on my list for monday :-)

**Pull request merged**
