### PR TITLE
Fixing 'Export Hold' issue. Removed Ukraine from list of countries to…

### PR DESCRIPTION
**Pull request by RubyGemTSL**
… register users as they are blocked from Downloading products in staging.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@RubyGemTSL something is still messed up with timeouts it seems.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
@RubyGemTSL says this is good to go. All tests are passing so merging.

**Pull request merged**
