### PR TITLE
RHD-299 Created Multiple path getting started experience

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by catrobson** [comment]
Approved from a UX standpoint

**Comment by adelasofia** [comment]
@paulrobinson side note: On hold because I need to add the OS selector, working on it now. But I needed to show this to Mike so  I opened the PR

**Comment by wesbos** [comment]
:+1: Good to merge

**Comment by paulrobinson** [comment]
@adelasofia is this good to merge from your perspective?

**Comment by adelasofia** [comment]
@paulrobinson good to merge :+1:

**Pull request merged**
