### PR TITLE
 includes tickets DEVELOPER-3077, DEVELOPER-3078, DEVELOPER-3079

### PR DESCRIPTION
**Pull request by RubyGemTSL**
Searching for 'enterprise linux' should return 'RHEL' product pages first,
Searching for 'red hat developers' should return 'about' page first,
Boost topic-name search terms.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@LightGuard good to go 👍🏻

**Comment by RubyGemTSL** [comment]
@LightGuard damn, I've just noticed an instance variable that needs removed. Hold off on merging please.

**Comment by RubyGemTSL** [comment]
OK now we're good @LightGuard  - please merge.

**Pull request merged**
