### PR TITLE
Fixed registration tests and re-enabled download tests.

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@paulrobinson - even if we see export hold issues from time to time I think given the recent problems that have been missed by not testing downloads we should keep them enabled. We just need to be mindful that the kc_dm tests won't always pass and will need to check out the cucumber report when reviewing/merging. cc @LightGuard.

**Comment by LightGuard** [comment]
Is this good to go?

**Comment by RubyGemTSL** [comment]
@LightGuard yes please! Thanks!

**Comment by RubyGemTSL** [comment]
@paulrobinson this PR includes hardcoded users to test the download flow. 80% of download tests are still being ignored due to Export Hold issues.

**Pull request merged**
