### PR TITLE
Improving the push to drupal

### PR DESCRIPTION
**Pull request by LightGuard**
Seems like we're still having problems with the Drupal push. This uses
the node url (and prints it) and also the previous data from the
existing node (according to the docs this is the proper way to do it).
I'm hoping this helps cut down on new url alias entries.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
Just tested this locally. AFAICS it works (the content appears in Drupal as expected). Just need to get the acceptance tests to pass before we can sign this one off.

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
Yay, all the tests finally pass :)

**Comment by LightGuard** [comment]
@robpblake please review and merge

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
sigh....tests

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard This has merge conflicts now. Could you please take a look.

cheers,

Rob

**Comment by paulrobinson** [comment]
@LightGuard is this still needed?

**Pull request closed without merging**
