### PR TITLE
[DEVELOPER-5592] Change jpeg compression and upload limit

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5592

### Verification Process
log into drupal and check /admin/structure/media/manage/image/fields and see if upload is set to '1024 KB'

Go to /admin/config/media/image-toolkit and check level is set to 60

### CODE REVIEW

**Comment by alistairmc** [comment]
Looks good to me, @LightGuard @KamiQuasi cam someone review, please.

**Comment by robpblake** [comment]
retest this please

**Comment by alistairmc** [comment]
Who needs to review this?

**Comment by robpblake** [comment]
@alistairmc Just to confirm, this is the page I should be checking for the allowed image size:

http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37764/admin/structure/media/manage/image/fields/media.image.image

?

**Comment by alistairmc** [comment]
That url is to check the value has been set, you can test by trying to upload an image bigger that 1mb to one of the image fields in content

**Pull request merged**
