### PR TITLE
DEVELOPER-2911 - Synced the index.html with html.html.twig

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@LightGuard I think this is ready to go. Should everything in the <head> region be included as well?  There was meta data that I didn't include since you had problems with the A/B testing. I can add that in as well, just wasn't sure.

**Comment by LightGuard** [comment]
Well, we need to figure out what to do here since we don't have the idea of staging / dev / prod in drupal, at least I haven't found it.

**Comment by Dantheman720** [comment]
Yeah, agreed. Is this something that we can bring up in the retrospective or maybe a call following the sprint planning meeting?

**Comment by LightGuard** [comment]
Works for me. We'll want to make sure Paul is there too.

On Fri, Apr 22, 2016 at 12:48 PM, Dantheman720 <notifications@github.com>
wrote:

> Yeah, agreed. Is this something that we can bring up in the retrospective
> or maybe a call following the sprint planning meeting?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1036#issuecomment-213550244>
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by Dantheman720** [comment]
👍  Agreed

**Comment by LightGuard** [comment]
I think we'll take this now and please create a ticket for the metrics and A/B testing.

**Pull request merged**
