### PR TITLE
[NO NOT MERGE] Testing for searchisko not starting up

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@LightGuard this seems to have fixed the issue. Agreed?

**Comment by LightGuard** [comment]
It does look that way, yes. Only small thing is that it starts up a Drupal
container and database which we currently don't use, but that's a very
minor thing right now.

On Friday, March 4, 2016, Paul Robinson <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> this seems to have fixed the
> issue. Agreed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/883#issuecomment-192305719>
> .
>


-- 
Sent from Gmail Mobile

**Comment by paulrobinson** [comment]
OK, hopefully that's safe. I'll merge it if this retest succeeds.

**Comment by paulrobinson** [comment]
Gateway Timeout on Vimeo. Probably unrelated.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
This has passed several times previously. Plus the error we get now also happen in production. Maybe we exceeded our Vimeo API request quota, or maybe that API is down.

Merging...

**Pull request merged**
