### PR TITLE
DEVELOPER-4359 Discovered the problem with revisions displaying

### PR DESCRIPTION
**Pull request by LightGuard**
Simple sql update to fix the problem.

### CODE REVIEW

**Comment by LightGuard** [comment]
I need this to go live ASAP, and we'll need to rebuild Drupal.

**Comment by adelasofia** [comment]
@LightGuard how should I test this? Just check if the revisions tab on any drupal page works?

**Comment by LightGuard** [comment]
@adelasofia product pages specifically.

**Comment by LightGuard** [comment]
I've been using the RHOAR product as that's where it was first noticed.

**Comment by LightGuard** [comment]
Relates to DEVELOPER-4359

**Pull request merged**
