### PR TITLE
DEVELOPER-3495 - Implement landing alert message on RHD when redirected from jboss.org

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3495

Added messaging to more pages. Alert is injected into page based on primary category now, so in order to add it to any other pages the category will need to be added to the switch statement in referrer.js

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
Pretty sure the errors in the tests are failures we're expecting to see related to search or logging in.

**Comment by LightGuard** [comment]
@KamiQuasi are we good to merge this, does it need to be signed off by anyone?

**Comment by KamiQuasi** [comment]
@LightGuard I think @tiffanynolan may want to take a look at some of the pages listed in the JIRA issue, just to sign off on them: 
- http://stumpjumper.lab4.eng.bos.redhat.com:33835/?referrer=jbd
- http://stumpjumper.lab4.eng.bos.redhat.com:33835/downloads/?referrer=jbd
- http://stumpjumper.lab4.eng.bos.redhat.com:33835/containers/?referrer=jbd
- http://stumpjumper.lab4.eng.bos.redhat.com:33835/community/contributor/?referrer=jbd
- http://stumpjumper.lab4.eng.bos.redhat.com:33835/quickstarts/eap/kitchensink-ml-ear/?referrer=jbd

**Comment by robpblake** [comment]
retest this please

**Comment by KamiQuasi** [comment]
http://stumpjumper.lab4.eng.bos.redhat.com:33861/?referrer=jbd
http://stumpjumper.lab4.eng.bos.redhat.com:33861/downloads/?referrer=jbd
http://stumpjumper.lab4.eng.bos.redhat.com:33861/containers/?referrer=jbd
http://stumpjumper.lab4.eng.bos.redhat.com:33861/community/contributor/?referrer=jbd
http://stumpjumper.lab4.eng.bos.redhat.com:33861/quickstarts/eap/kitchensink-ml-ear/?referrer=jbd

**Comment by RubyGemTSL** [comment]
Sorry if this is already a known issue, but there may be a genuine failure on this related to the DCP?

When searching for "Containers" the first result should be a link to: http://developers.redhat.com/containers/

This appears second on the list, which is why there is a failure on search page.

**Comment by LightGuard** [comment]
It may be related to having /node/* things exported, which should no longer be happening, but they're still in the DCP.

**Comment by KamiQuasi** [comment]
@LightGuard @Dantheman720 @adelasofia or @paulrobinson did we have any changes to the order that the developer_materials service call would be using recently. The RHD website querystring value is showing up as the last thing, but if I move it to the first type to search the results come back favoring the local website ( type=rht_website )

**Comment by LightGuard** [comment]
I didn't think we did :(

**Comment by Dantheman720** [comment]
@KamiQuasi Sorry I didn't notice this sooner, we actually did have a change to the query string. We were having issues because the query (on the elasticsearch side) was inefficient. The new way of doing this is to use "stype". The latest content query string on the landing page shows the format of the string.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
FYI the old status is not cleared on your current PR's. Please ignore the old status: 'Drupal:Acceptance Tests' above.  New Pull-Requests will only include the new statuses:
- Drupal:FE KC/DM Acceptance Tests
- Drupal:FE Acceptance Tests

**Comment by paulrobinson** [comment]
@KamiQuasi This doesn't seem to work on the exported version of the site: http://developers-pr.stage.redhat.com/pr/1563/export/products/datagrid/overview/?referrer=jbd.

We should add some tests I think too. Visit a few critical pages (with '?referrer=jbd' in the URL) and check that the banner appears.

**Comment by KamiQuasi** [comment]
@paulrobinson I'll see if I can dump the base URL somewhere to use it to be able to make things work on non-root instances. 

@RubyGemTSL shoot me a message when you have time to show me a bit about writing some tests for this

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
Meeting with @RubyGemTSL tomorrow and should have tests written before the end of the day to verify this and get this accepted.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@adelasofia this one is on hold at the moment, but I think given the new ability to pull the environment URL in I should be able to fix it.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by paulrobinson** [comment]
@tiffanynolan has approved this. We just need to get the tests passing, or be sure that they are unrelated to this.

**Comment by paulrobinson** [comment]
Looks like the same tests are failing for the past two runs:

https://www.dropbox.com/s/x6h1jila29j7thq/Screenshot%202016-12-06%2017.04.18.png?dl=0
https://www.dropbox.com/s/3sput5f3bh93msj/Screenshot%202016-12-06%2017.04.28.png?dl=0

@KamiQuasi, @RubyGemTSL, any ideas why? They seem unrelated.

**Comment by KamiQuasi** [comment]
@paulrobinson the errors are unrelated to this code change as near as I can tell. They look like they're related to search.

**Comment by RubyGemTSL** [comment]
@paulrobinson @KamiQuasi I'm struggling to reproduce this. Libor warned me yesterday that we may have seen some failures today around the SO page as they were going to reindex all data in the DCP for stackoverflow. Could be that? I'll do a retest, failing that I'll pull down your branch and run the tests locally.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@paulrobinson @KamiQuasi the current test run confirms that the previous two runs were probably related to the reindexing of the DCP for SO. The latest failures are the same as other current failing PR's. Search results not containing search term.

**Pull request merged**
