### PR TITLE
DEVELOPER-4060 Added RHAMT to products and downloads pages

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4060](https://issues.jboss.org/browse/DEVELOPER-4060)

Added RHAMT - "Red Hat Application Migration Toolkit" to:

- /products/
- /downloads/

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
