### PR TITLE
Adding the frontend build to npm install

### PR DESCRIPTION
**Pull request by LightGuard**
Testing: Make sure the build passes

### CODE REVIEW

**Comment by LightGuard** [comment]
Still need to add the key for font-awesome

**Comment by LightGuard** [comment]
And... our PR vagrant box is using an old version of node and npm. Amazing stuff still works

**Comment by RubyGemTSL** [comment]
@LightGuard not sure what happened to the export but the page doesn't look as though it has any styling (from screenshots and https://developers-pr.stage.redhat.com/pr/2385/export/)

**Comment by LightGuard** [comment]
@RubyGemTSL  yeah, I know. Still testing stuff apparently.

HA, looks like I finally got it.
@KamiQuasi  if you're happy with this, please go ahead and merge (I suggest squashing when you merge)

**Pull request merged**
