### PR TITLE
 Remove Windows from Mac/Linux instructions

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by robpblake** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@pmuir looks like there's a merge conflict now, mind fixing?

**Comment by paulrobinson** [comment]
I've had a go at fixing the merge-confluct: https://github.com/redhat-developer/developers.redhat.com/pull/1288/files but I'm not confident I've made the right merge decisions. @pmuir can you review, or provide someone to review it?

**Comment by paulrobinson** [comment]
Actually, neither 'windows' or 'cygwin' are mentioned on http://developers.redhat.com/products/cdk/get-started/#tab-macLinux. I think this has been resolved by another PR.

**Pull request closed without merging**
