### PR TITLE
Created a resources page. RHD-681

### PR DESCRIPTION
**Pull request by wesbos**
Also closes RHD-670 and RHD-624

### CODE REVIEW

**Comment by paulrobinson** [comment]
The new resources page should be linked from here: https://www.dropbox.com/s/ybjeri4bahf7l95/Screenshot%202015-09-10%2017.56.32.png?dl=0 in the chrome. I suggest it goes before the current items.

**Comment by paulrobinson** [comment]
You should drop the 'Get Started' part of the breadcrumb: https://www.dropbox.com/s/ng45ilsgkia064n/Screenshot%202015-09-10%2017.57.44.png?dl=0 on http://it-developers-pr.stage.redhat.com/pr/419/build/829/ticket-monster/dashboardhtml5/

**Comment by paulrobinson** [comment]
@catrobson, @insectengine Do we need some copy to go at the top of the resources page?

**Comment by paulrobinson** [comment]
Sent to @catrobson and @insectengine for review.

**Comment by catrobson** [comment]
Any chance we can push the publish date filter to the right a bit?  There's a lot of space between keyword filter and format dropdown, and then the publish date feels like it is right on top of the format dropdown.

Also, can we default sort the table by publish date - from most recent to least recent?

**Comment by wesbos** [comment]
@catrobson 

Yes - I've changed the styling to be more even.

And yes - I've switched the sorting so it shows the most recent first - much better than showing 3 year old content first.

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
