### PR TITLE
Update DevSuite version

### PR DESCRIPTION
**Pull request by KamiQuasi**
Updates DevSuite download version due to updated download

### CODE REVIEW

**Comment by KamiQuasi** [comment]
@LightGuard @adelasofia or @Dantheman720 this can be merged as the failing tests are unrelated

**Comment by RubyGemTSL** [comment]
@KamiQuasi I get file not found when clicking on devsuite?

**Comment by RubyGemTSL** [comment]
also other downloads, such as Red Hat Enterprise Linux are throwing an error @KamiQuasi. Can you also try?

**Comment by paulrobinson** [comment]
Look at the URL: https://developers-pr.stage.redhat.com/download-manager/file/devsuite-2.3.0-GA-bundle-installer-mac.zip

I think it should be: https://developers.redhat.com/download-manager/file/devsuite-2.3.0-GA-bundle-installer-mac.zip

**Comment by KamiQuasi** [comment]
@RubyGemTSL and @paulrobinson the URLs are relative, that is why they don't work on PRs.

**Pull request merged**
