### PR TITLE
[HOLD - no need to retest] New Search Page - Developer 1795 (Ian's fixes for conflicts)

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@wesbos @paulrobinson @LightGuard - I fixed the conflicts, the site has rebuilt, however I still don't see any search results. (like I mentioned on the other PR).

May not be related, but when the search query is 'searching' the url changes to http://developers-pr.stage.redhat.com/search/?q=containers (notice that '/pr/1038/build/192/' is missing?

**Comment by RubyGemTSL** [comment]
@LightGuard - no need to retest this, it will always fail.

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request closed without merging**
