### PR TITLE
RHD-891 - Fixed the twitter share link to point to RHD instead of you…

### PR DESCRIPTION
**Pull request by Dantheman720**
…tube/vimeo

Added CDN addition

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
Looks like this breaks something. See this snippet from the error on the linked logfile:

[0;31;49mAn error during rendering /mnt/hudson_workspace/workspace/developers.redhat.com-pull-player-executor/mnt/hudson_workspace/workspace/developers.redhat.com-pull-player-executor/_partials/share.html.slim occurred.[0m
[0;31;49mWhile processing file /mnt/hudson_workspace/workspace/developers.redhat.com-pull-player-executor/_partials/share.html.slim[0m
[0;31;49mAn error occurred: Unable to read file from /mnt/hudson_workspace/workspace/developers.redhat.com-pull-player-executor/events/javaone/2015/index.html[0m
[0;31;49m/home/hudson/.rvm/gems/ruby-2.1.2@www.jboss.org/bundler/gems/aweplug-f912c6d32b6a/lib/aweplug/helpers/resources.rb:232:in `path'

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@LightGuard Any idea why CI won't test this (or at least, won't comment back on it).

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
ok to test

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
