### PR TITLE
Feature/remove compass

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@wesbos can you review?

**Comment by wesbos** [comment]
:+1:  - From a CSS standpoint this is just removing commented out Compass files that I removed on the initial RHD site build

**Comment by paulrobinson** [comment]
Needs rebasing.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
I needed to revert this change as it caused the images, fonts and icons to not display

**Comment by LightGuard** [comment]
Wes, any thoughts here?

On Tue, Oct 27, 2015 at 6:01 PM, Paul Robinson <notifications@github.com>
wrote:

> I needed to revert this change as it caused the images, fonts and icons to
> not display
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/490#issuecomment-151569618>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by wesbos** [comment]
I was having this locally because something was causing it to bind to 0.0.0.0 instead of localhost. Since the icons are fonts, they can't be loaded cross domain. 

So - Not sure what that has to do with Compass, but let's try it in staging?

retest this please

**Comment by LightGuard** [comment]
Do you see them if you load the site on 0.0.0.0?

On Tuesday, October 27, 2015, Wes Bos <notifications@github.com> wrote:

> I was having this locally because something was causing it to bind to
> 0.0.0.0 instead of localhost. Since the icons are fonts, they can't be
> loaded cross domain.
>
> So - Not sure what that has to do with Compass, but let's try it in
> staging?
>
> retest this please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/490#issuecomment-151691516>
> .
>


-- 
Sent from Gmail Mobile

**Comment by wesbos** [comment]
Yep

**Pull request merged**
