### PR TITLE
Adding minimum versions for building the site

### PR DESCRIPTION
**Pull request by LightGuard**
Minimum versions add for:

* docker
* docker-compose
* ruby
* nodejs

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia Any chance of you merging this, it's a change to the README file.

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
Really getting tired of the acceptance tests failing

**Comment by LightGuard** [comment]
They passed!!

**Pull request merged**
