### PR TITLE
[DEVELOPER-1934] Resources Page 

### PR DESCRIPTION
**Pull request by wesbos**

### CODE REVIEW

**Comment by wesbos** [comment]
Functionality is pretty much down pat - design needs some feedback. 

Ignore pagination - will be fixed on the search page which shares this codebase

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
needs a rebase

**Comment by RubyGemTSL** [comment]
@wesbos I am blocked on a couple of tasks for this sprint so I'll work on the tests for this tomorrow.

@paulrobinson - you OK if I do the tests for this?

**Comment by paulrobinson** [comment]
@wesbos can you fix the merge conflicts on this one too please?

**Comment by wesbos** [comment]
@paulrobinson Fixed it

**Comment by paulrobinson** [comment]
Great, appreciated!

**Comment by paulrobinson** [comment]
@wesbos now i'm not seeing any results for blog posts or books. There do seem to be blog posts coming back from the REST call to the DCP. But there don't seem to be any books coming back.

**Comment by wesbos** [comment]
I don't see any books

http://dcp2.jboss.org/v2/rest/search/developer_materials?agg=per_project_counts&agg=tag_cloud&agg=top_contributors&agg=activity_dates_histogram&agg=per_sys_type_counts&field=sys_url_view&field=sys_title&field=sys_last_activity_date&field=sys_description&field=sys_tags&field=sys_project&field=sys_contributor&from=0&project=&query=&size=10&sortBy=score&sys_type=jbossdeveloper_book&sys_type=book

or blog posts:

http://dcp2.jboss.org/v2/rest/search/developer_materials?agg=per_project_counts&agg=tag_cloud&agg=top_contributors&agg=activity_dates_histogram&agg=per_sys_type_counts&field=sys_url_view&field=sys_title&field=sys_last_activity_date&field=sys_description&field=sys_tags&field=sys_project&field=sys_contributor&from=0&project=&query=&size=10&sortBy=score&sys_type=blogpost

If you see data, can you link the query?

**Comment by paulrobinson** [comment]
Actually, I don't see data now. Maybe I made a mistake when i tested it. @unibrew any idea why the queries that @wesbos shows are returning no results?

**Comment by paulrobinson** [comment]
@wesbos, can you respond to: https://issues.jboss.org/browse/DEVELOPER-1934?focusedCommentId=13251194&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13251194. That's what's blocking the queries working.

**Comment by paulrobinson** [comment]
Search is now merged, so I think this needs some work to un-ravel the common code.

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
There must have been some conflicts when rebasing the tests. I've fixed and raised a PR on this branch.

**Comment by RubyGemTSL** [comment]
There is one outstanding failure:

Error: 
expected: "eap 7 download"
got: "eap+7+download"

search_fail

I remember having this issue on the search branch. Does this branch contain the latest from master?

**Comment by RubyGemTSL** [comment]
Go to http://developers-pr.stage.redhat.com/pr/1100/build/1482/
search for eap 7 download 

When search page is presented spaces are replaced with +

**Comment by wesbos** [comment]
Okay good to merge - had it checked out by Jasona nd Adela

**Pull request merged**
