### PR TITLE
[DEVELOPER-5907] Reduce network calls to wordpress

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5907

### Verification Process

* 3 calls are made to the Wordpress REST API for the Dynamic Content List and the Dynamic Content assembly types regardless of how many posts are retrieved from the Wordpress REST API. Previously 2N+1 calls were performed when multiple posts were retrieved, where N is the number of WP posts.
* Verify hypothesis that hitting developers.redhat.com, as opposed to origin-developers.redhat.com, is actually faster

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
### localhost timings

#### jordanpagewhite:reduce-network-calls-to-wordpress

Hitting d.r.c.

0.30877995491028
0.32384300231934
0.25575804710388
0.22560787200928
0.35945105552673
0.44233703613281
0.28016996383667
0.29879689216614
0.32606291770935
0.41397094726562

MEAN ~= 0.32347776889801s

#### redhat-developer:master

NOTE: I changed the apiUrl attribute of WordpressApi.php to developers.redhat.com because origin-developers.redhat.com was incredibly faster, so it didn't provide a decent comparison of the performance.

0.96034789085388
0.78772401809692
0.75112390518188
0.91158413887024
0.69116902351379
0.90094709396362
0.68501901626587
0.76322388648987
0.90473985671997
0.97558617591858

MEAN ~= 0.83314650058746s

That is about a 0.51s improvement hitting d.r.c.

#### jordanpagewhite:reduce-network-calls-to-wordpress - origin-d.r.c.

0.0084228515625
0.0071239471435547
0.010710954666138
0.01593279838562
0.0083019733428955
0.011476993560791
0.010525941848755
0.0098540782928467
0.0079071521759033
0.007874011993408

MEAN ~= 0.0098130702972412

#### redhat-developer:master - origin-d.r.c.

0.03557014465332
0.03495192527771
0.03692102432251
0.048218965530396
0.038633108139038
0.053361892700195
0.035971879959106
0.048557043075562
0.046588182449341
0.039646148681641

MEAN ~= 0.041842031478882

That is about a 0.032s improvement hitting origin-d.r.c.

#### Next steps

I think that we need to understand why hitting origin-developers.redhat.com is so much faster than developers.redhat.com. That seems very counterintuitive to me. @robpblake Do you have any thoughts on this?

**Comment by jordanpagewhite** [comment]
I just pushed up a commit to change the apiUrl to origin-developers.redhat.com based upon my results and comments from the previous comment

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
`Warning: Attempt to assign property of non-object in Drupal\rhd_assemblies\Service\WordpressApi->getContentComposite() (line 248 of /var/www/drupal/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php) #0 /var/www/drupal/web/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'Attempt to assi...', '/var/www/drupal...', 248, Array) #1 /var/www/drupal/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php(248): _drupal_error_handler(2, 'Attempt to assi...', '/var/www/drupal...', 248, Array) #2 /var/www/drupal/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php(56): Drupal\rhd_assemblies\Service\WordpressApi->getContentComposite(Object(stdClass)) #3 /var/www/drupal/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldFormatter/WppostTeaserFormatter.php(63): Drupal\rhd_assemblies\Service\WordpressApi->getContentById(495187) #4 /var/www/drupal/web/core/lib/Drupal/Core/Field/FormatterBase.php(80): Drupal\rhd_assemblies\Plugin\Field\FieldFormatter\WppostTeaserFormatter->viewElements(Object(Drupal\Core\Field\FieldItemList), 'en') #5 /var/www/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(263): Drupal\Core\Field\FormatterBase->view(Object(Drupal\Core\Field\FieldItemList), 'en') #6 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(343): Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Array) #7 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(285): Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'default') #8 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(242): Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) #9 [internal function]: Drupal\Core\Entity\EntityViewBuilder->build(Array) #10 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func(Array, Array) #11 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #12 /var/www/drupal/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array) #13 /var/www/drupal/web/sites/default/files/php/twig/5d2bd4bed2149_field.html.twig_nIbG3TUq0sE1DW6yBZ-t-873F/goIYqMJEoXKXfECG9xwelykQJHiMvtUvCWJmmflFQFQ.php(102): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true) #14 /var/www/drupal/vendor/twig/twig/src/Template.php(455): __TwigTemplate_bea1975fa298b670290083260365ad57f34b7f1b7108de95c9a6ce56ff8ed486->doDisplay(Array, Array) #15 /var/www/drupal/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #16 /var/www/drupal/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array) #17 /var/www/drupal/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array) #18 `

**Comment by robpblake** [comment]
`Warning: Division by zero in Drupal\rhd_assemblies\Service\WordpressApi->getContentComposite() (line 247 of /var/www/drupal/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php) #0 /var/www/drupal/web/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'Division by zer...', '/var/www/drupal...', 247, Array) #1 /var/www/drupal/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php(247): _drupal_error_handler(2, 'Division by zer...', '/var/www/drupal...', 247, Array) #2 /var/www/drupal/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php(56): Drupal\rhd_assemblies\Service\WordpressApi->getContentComposite(Object(stdClass)) #3 /var/www/drupal/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldFormatter/WppostTeaserFormatter.php(63): Drupal\rhd_assemblies\Service\WordpressApi->getContentById(495187) #4 /var/www/drupal/web/core/lib/Drupal/Core/Field/FormatterBase.php(80): Drupal\rhd_assemblies\Plugin\Field\FieldFormatter\WppostTeaserFormatter->viewElements(Object(Drupal\Core\Field\FieldItemList), 'en') #5 /var/www/drupal/web/core/lib/Drupal/Core/Entity/Entity/EntityViewDisplay.php(263): Drupal\Core\Field\FormatterBase->view(Object(Drupal\Core\Field\FieldItemList), 'en') #6 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(343): Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Array) #7 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityViewBuilder.php(285): Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'default') #8 `

**Comment by robpblake** [comment]
Closing in favour of #2988 which builds on this work but fixes the PHP errors in the Drupal logs.

**Pull request closed without merging**
