### PR TITLE
[URGENT] DEVELOPER-3040 Fixed homepage hero broken on Safari

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by DonSchenck** [comment]
Looks good to me.

**Comment by LightGuard** [comment]
@adelasofia is that our sign off?

**Comment by paulrobinson** [comment]
Works for me in Safari.

**Pull request merged**
