### PR TITLE
[HOLD] RHD-844 Created content driven homepage

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by paulrobinson** [comment]
You need to make sure the 'latest resources' feed fails gracefully when the DCP is unavailable. I suggest you display a simple message: "Latest Resource feed is currently unavailable".

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Pull request closed without merging**
