### PR TITLE
DEVELOPER-4354 - Change .NET Core title on Technology pull-down

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@RubyGemTSL - Is there a good way to do this without refactoring the acceptance tests? 

https://issues.jboss.org/browse/DEVELOPER-4354?filter=-1

**Comment by RubyGemTSL** [comment]
@Dantheman720 your update to the tests looks fine.

Error: expected collection contained: [".NET Core", "Red Hat JBoss AMQ", "Red Hat JBoss BPM Suite", "Red Hat JBoss BRMS", "Red Hat JBoss Da...ication Platform", "Red Hat JBoss Fuse", "Red Hat JBoss Web Server", "Red Hat Software Collections"]

actual collection contained: [".NET Core for Red Hat Enterprise Linux", "Red Hat JBoss AMQ", "Red Hat JBoss BPM Suite", "Red Hat J...ication Platform", "Red Hat JBoss Fuse", "Red Hat JBoss Web Server", "Red Hat Software Collections"]
the missing elements were: [".NET Core"]
the extra elements were: [".NET Core for Red Hat Enterprise Linux"]

The problem looks like to product name has not been updated from drupal maybe? The [site preview](https://developers-pr.stage.redhat.com/pr/1986/export/forums/) still lists ".NET Core for Red Hat Enterprise Linux"? as failure suggests.

**Comment by Dantheman720** [comment]
@RubyGemTSL - The problem is the product.yml for dotnet. Since we are only changing the name for the technology dropdown and not the product as a whole, it seems to cause issues with the tests. At least that's the way I understand it.

**Comment by RubyGemTSL** [comment]
@Dantheman720 sorry i'm confused why you updated the forums feature? So the ticket just changes the product in the primary nav menu? i.e. hovering over 'TECHNOLOGIES'?

If my assumption is correct then the only feature that would need updating is the [primary nav feature](https://github.com/redhat-developer/developers.redhat.com/blob/master/_cucumber/features/technologies/technologies.feature).

**Comment by RubyGemTSL** [comment]
In fact from looking at it, it already expects .NET Core so no updates are required.

**Comment by Dantheman720** [comment]
Oh geez! I didn't realize I added that to the forums menu...sorry about that.

**Comment by Dantheman720** [comment]
@adelasofia @KamiQuasi - This should be good to go now.

**Pull request merged**
