### PR TITLE
Updated Fuse Docs to point to 6.2.1

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Clicking on the links for the different docs still sends you to 6.2

**Comment by paulrobinson** [comment]
This fails because the docs processing code only works with the minor
product version, not the 'micro' part. See:
https://github.com/redhat-developer/developers.redhat.com/blob/master/_ext/product.rb#L278

I'm closing this PR as we need a different approach. Also, we might not
actually want to do updates at this granularity.

On Fri, Apr 22, 2016 at 10:05 PM, Jason Porter <notifications@github.com>
wrote:

> Clicking on the links for the different docs still sends you to 6.2
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1039#issuecomment-213588749>
>



-- 
Paul

-----
Paul Robinson
Red Hat Developer Program Engineering (Web Development lead)
JBoss Developer Program (Web Development lead)

Free/busy info:
https://www.google.com/calendar/embed?src=probinso%40redhat.com&ctz=Europe/London

JBoss, a Division of Red Hat
Registered in England and Wales under Company Registration No. 03798903
Directors:Michael Cunningham (US), Charles Peters (US), Matt Parson (US),
Paul Hickey (Ireland)

**Comment by paulrobinson** [comment]
I suggest closing this PR. I would do it myself, but GitHub is reporting an
error.

On Mon, Apr 25, 2016 at 11:29 AM, Paul Robinson <probinso@redhat.com> wrote:

> This fails because the docs processing code only works with the minor
> product version, not the 'micro' part. See:
> https://github.com/redhat-developer/developers.redhat.com/blob/master/_ext/product.rb#L278
>
> I'm closing this PR as we need a different approach. Also, we might not
> actually want to do updates at this granularity.
>
> On Fri, Apr 22, 2016 at 10:05 PM, Jason Porter <notifications@github.com>
> wrote:
>
>> Clicking on the links for the different docs still sends you to 6.2
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/redhat-developer/developers.redhat.com/pull/1039#issuecomment-213588749>
>>
>
>
>
> --
> Paul
>
> -----
> Paul Robinson
> Red Hat Developer Program Engineering (Web Development lead)
> JBoss Developer Program (Web Development lead)
>
> Free/busy info:
> https://www.google.com/calendar/embed?src=probinso%40redhat.com&ctz=Europe/London
>
> JBoss, a Division of Red Hat
> Registered in England and Wales under Company Registration No. 03798903
> Directors:Michael Cunningham (US), Charles Peters (US), Matt Parson (US),
> Paul Hickey (Ireland)
>



-- 
Paul

-----
Paul Robinson
Red Hat Developer Program Engineering (Web Development lead)
JBoss Developer Program (Web Development lead)

Free/busy info:
https://www.google.com/calendar/embed?src=probinso%40redhat.com&ctz=Europe/London

JBoss, a Division of Red Hat
Registered in England and Wales under Company Registration No. 03798903
Directors:Michael Cunningham (US), Charles Peters (US), Matt Parson (US),
Paul Hickey (Ireland)

**Pull request closed without merging**
