### PR TITLE
[DEVELOPER-3614] Added SMTP support to Drupal for sending of emails

### PR DESCRIPTION
**Pull request by robpblake**
This pull request enables SMTP for email sending within Drupal. This is achieved by installing and configuring the [Drupal SMTP module](https://www.drupal.org/project/smtp). Please note that we install version 1.0.0-alpha2 and not beta-1 as email sending is broken in beta1.

The Drupal instance is configured to send via smtp.corp.redhat.com which does not require any authentication details.

### CODE REVIEW

**Comment by robpblake** [comment]
@LightGuard Could you take a review of this one please. I have run `composer update` after adding the smtp module dependency into composer.json. I've also added in the default configuration for the SMTP module into the sync directory.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
We don't need creds to send mail?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard No creds needed as long as sending email to a @redhat.com domain.

**Comment by robpblake** [comment]
@LightGuard Tests are green, so feel free to merge if you get the time today.

cheers,

Rob

**Pull request merged**
