### PR TITLE
[RHDX-414] Update Adobe registered flag reference

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-414](https://projects.engineering.redhat.com/browse/RHDX-414)

### Verification Process
Use Adobe Analytics debugger, which formats the key/values logged to the console, to check for eVar61 for registered flag.

### CODE REVIEW

**Comment by staceymosier** [comment]
rebuild this please

**Comment by staceymosier** [comment]
@alistairmc   
Can you include a temporary patch that any CTA with a background image or within a Two-Col assembly will by default have white text,  until the content has been assigned the correct visual styles?

Please ping me in the morning if you need more context for this request.

**Comment by staceymosier** [comment]
rebuild this please

**Comment by staceymosier** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by staceymosier** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Pull request closed without merging**
