### PR TITLE
[PREVIEW] Rebrand Website

### PR DESCRIPTION
**Pull request by wesbos**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@wesbos notice that I renamed the PR. I didn't want to confuse you.

**Comment by paulrobinson** [comment]
It seems to be failing due to an error in the code. Notice:

      An error occurred: Unable to read file from /mnt/hudson_workspace/workspace/developers.redhat.com-pull-request-builder/images/spotlights/RHDev_homepromo_devoxxbe2015.png

There's also a few other errors which might be related. See: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-pull-request-builder/417/console

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
@wesbos can you take a look at why this PR is broken?

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
Seems like this is legitimately failing due to missing files / config problems

**Comment by paulrobinson** [comment]
@wesbos can you fix this branch and add in all the rebrand work done to date. E.g Adela has some changes to the product pages.

**Comment by wesbos** [comment]
@adelasofia okay it's all yours.

**Comment by paulrobinson** [comment]
This seems to be failing to build:

        An error during rendering /mnt/hudson_workspace/workspace/developers.redhat.com-pull-request-builder/mnt/hudson_workspace/workspace/developers.redhat.com-pull-request-builder/stylesheets/app.scss occurred.

**Comment by wesbos** [comment]
Got it - thanks.

**Comment by paulrobinson** [comment]
@wesbos or @adelasofia, can you fix the build please so that we can preview the progress.

**Comment by adelasofia** [comment]
@wesbos Just sent you a PR with the fixes and the product page changes (cc: @paulrobinson )

**Comment by wesbos** [comment]
Closing this - going to open an integration branch.

**Pull request closed without merging**
