### PR TITLE
compressed images DEVELOPER-2707

### PR DESCRIPTION
**Pull request by wesbos**
This PR shaves almost a meg off of the homepage page load. 

Most have been compressed, but some have been converted to JPG as they were huge as .png

I'll comment more on more easy wins in the issue in JIRA.

### CODE REVIEW

**Comment by paulrobinson** [comment]
Looks like an error with one of the images:

 While processing file /home/awestruct/developer.redhat.com/index.html.slim
14:32:40 An error occurred: Unable to read file from /home/awestruct/developer.redhat.com/images/branding/RHDev_homeherovideo_jbosseap7beta.jpg

**Comment by wesbos** [comment]
Hrm okay I'll have a look

**Comment by paulrobinson** [comment]
@insectengine please review the images. Make sure we've not gone too far on the compression ;-)

**Comment by insectengine** [comment]
Approved!

**Pull request merged**
