### PR TITLE
Update drupal-namespace.js

### PR DESCRIPTION
**Pull request by LightGuard**
Changing the product code for RHAMT

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks like SO questions are pulling in now: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37029/products/rhamt/help

**Comment by LightGuard** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
For some reason the unit-tests didn't run from the updated Dockerfiles.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Again the js-unit-tests failed to run from the latest changes. I think this one either needs merged as it's a small change, or a pull/rebase/force push.

**Pull request merged**
