### PR TITLE
[#DEVELOPER-3029] Start all additional services with docker-compose up

### PR DESCRIPTION
**Pull request by robpblake**
Reverted to starting all services with a docker-compose up to see if we can resolve the ports in use issue.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@LightGuard - this will hopefully fix @rctrh 's PR #1097 . @rctrh once this has been merged into master you will need to rebase to get this change into your PR.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard Are you able to review and merge this? Starting all services at once using docker-compose seems to resolve the issues with ports being in use. It seems to occur when using docker-compose run and starting up multiple supporting services.

**Comment by RubyGemTSL** [comment]
@LightGuard - could you please review this ASAP? @rctrh needs it for #1097 to run.

**Pull request merged**
