### PR TITLE
[DEVELOPER-5833] Fixed img alignment styles

### PR DESCRIPTION
**Pull request by adelasofia**
### JIRA Issue Link
[DEVELOPER-5833 - Center-aligned images don't center align
](https://issues.jboss.org/browse/DEVELOPER-5833)

### CODE REVIEW

**Comment by adelasofia** [comment]
@jordanpagewhite thank you for the feedback on the other PR. I believe this solves all of the issues 😄

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
