### PR TITLE
DEVELOPER-4967 fixes old event pages

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4967 - Old Event pages are incorrectly styled](https://issues.jboss.org/browse/DEVELOPER-4967)

See pages:

* /events/devoxxfrance/2016/
* /events/judcon/2016/brno
* /events/gids/2016
* /events/javaone/2015
* /events/msbuild/2016
* /events/devoxx/2015
* /events/javaone/2016
* /events/javaone/2017

### CODE REVIEW

**Comment by Dantheman720** [comment]
@adelasofia - Looks good! There are a few things that are a bit different on the old theme. The event name banner's date looks larger on the old theme.
screenshot from 2018-05-16 17-47-12

vs.

screenshot from 2018-05-16 17-52-51

The "Share This" also seems a bit off, but I'm not sure how it's supposed to look. It didn't quite work properly on the old theme either.

**Comment by adelasofia** [comment]
@Dantheman720 I fixed a lot of things like the events' dates on the html on the production drupal, and removed the 'share this' links because they didn't work anymore (we deprecated that JS) But those changes haven't made it to the PR

**Comment by adelasofia** [comment]
retest this please

**Comment by Dantheman720** [comment]
@adelasofia - Good deal! Ready to merge?

**Comment by adelasofia** [comment]
@Dantheman720 Yep! thanks dan!

**Pull request merged**
