### PR TITLE
DEVELOPER-3693 - IE-incompatible JS function Math.trunc

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3693

Fixes Math.trunc and also localStorage checking

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@KamiQuasi Do we have someone who can test IE related changes for us?

**Comment by KamiQuasi** [comment]
@robpblake I'll give it a go on my IE VM. Should be quick and painless.

**Comment by KamiQuasi** [comment]
@robpblake it looks like certificate errors on the PR environment won't let IE work correctly. Staging works if you bypass the certificate error, but the PR environment just sits there.

**Comment by LightGuard** [comment]
@KamiQuasi Which version of IE does this affect?

**Comment by KamiQuasi** [comment]
@LightGuard this is any version of IE. Thought maybe it worked in 11, but it doesn't. I was able to check locally and it appears to be working without error besides the odd behavior displayed with login/logout/register that Ian said happens on lower environments.

**Pull request merged**
