### PR TITLE
DEVELOPER-3012 RHSCL 2.2 Beta Node.js v4 TTHWs

### PR DESCRIPTION
**Pull request by rctrh**
* Add node.js v4 in a container beta TTHW
* Add link to container TTHW from updates page
* Formatting improvements on RHSCL node4 beta TTHW

### CODE REVIEW

**Comment by LightGuard** [comment]
this is ok to test

On Thursday, May 12, 2016, JBossJenkins <notifications@github.com> wrote:

> Can one of the admins verify this patch?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1097#issuecomment-218895615>
>


-- 
Sent from Gmail Mobile

**Comment by rctrh** [comment]
@LightGuard the build/tests haven't run yet?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@LightGuard this is failing with:

09:48:27 failed to create endpoint rhdpr1097_drupal_1 on network rhdpr1097_default: Error starting userland proxy: listen tcp 0.0.0.0:32905: bind: address already in use

**Comment by LightGuard** [comment]
Check to see if there are services running on that port / network. I think
we need to do a docker-compose down at the start of the builds.

On Friday, May 13, 2016, Ian Hamilton <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> this is failing with:
>
> 09:48:27 failed to create endpoint rhdpr1097_drupal_1 on network
> rhdpr1097_default: Error starting userland proxy: listen tcp 0.0.0.0:32905:
> bind: address already in use
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1097#issuecomment-219048031>
>


-- 
Sent from Gmail Mobile

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
@rctrh If you merge master into your branch, you should pick up the fix for this issue that I've just pushed as part of pull request #1098 

cheers,

Rob

**Comment by LightGuard** [comment]
retest this please

**Comment by rctrh** [comment]
Either the build didn't happened or I'm not seeing the updates.

**Comment by LightGuard** [comment]
retest this please

**Comment by rctrh** [comment]
This is ok to merge when an admin has a chance.

**Pull request merged**
