### PR TITLE
[DEVELOPER-3323] Added re-write of form action URLs as part of export

### PR DESCRIPTION
**Pull request by robpblake**
This PR adds in the re-write of form target URLs to the export process if the target URL for the form matches the Drupal host from which it was exported.

### CODE REVIEW

**Comment by robpblake** [comment]
@LightGuard Would you mind taking a look at this one.

I've tested the export locally and it re-writes the pages as expected.

cheers,

Rob

**Comment by LightGuard** [comment]
I discovered an issue with Nokogiri and angular code in `href` attributes. We need to test for that. In your tests add an anchor tag with something like `href="{{blah.test[0]]}}"` and make sure that's what you're still getting after the export. You'll probably need to run the whole string through `CGI::unescape` to make that happen.

**Comment by robpblake** [comment]
@LightGuard Included your recommended CGI::unescape work-around.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
