### PR TITLE
DEVELOPER-3143 Microservices Topic Page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
tests will fail due to failing tests being pushed over the weekend. I will have a PR merged soon to fix this.

**Comment by adelasofia** [comment]
This PR needs to be merged after [#1198](https://github.com/redhat-developer/developers.redhat.com/pull/1198) is merged.

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by adelasofia** [comment]
@paulrobinson closing this PR. Jessica said she would have more content for this page at some point during this week or the next.

**Pull request closed without merging**
