### PR TITLE
Redirect to 404 on error

### PR DESCRIPTION
**Pull request by LightGuard**
No product, no sub-page, or other error will redirect to 404.
Also '/product/get-started' will new internally redirect to
'/product/hello-world'.

You can test this by trying to go to a non-existing product or product sub-page. Also, double check /product/get-started goes to the new hello world page.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard It doesn't look like the Drupal instance is booting. When visiting the login page:

http://stumpjumper.lab4.eng.bos.redhat.com:36725/user/login

I only get the error "The website encountered an unexpected error. Please try again later."

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard It looks like the export process is failing on this PR as it thinks there are a load of missing pages. It particularly looks like product pages are missing. A few examples:

```
07:08:55 WARNING: Cannot locate export of 'http://stumpjumper.lab4.eng.bos.redhat.com:36725/products/dotnet/overview' at expected path: '/export/stumpjumper.lab4.eng.bos.redhat.com_36725/products/dotnet/overview/index.html'
07:08:55 WARNING: Cannot locate export of 'http://stumpjumper.lab4.eng.bos.redhat.com:36725/products/dotnet/hello-world' at expected path: '/export/stumpjumper.lab4.eng.bos.redhat.com_36725/products/dotnet/hello-world/index.html'
07:08:55 WARNING: Cannot locate export of 'http://stumpjumper.lab4.eng.bos.redhat.com:36725/products/dotnet/docs-and-apis' at expected path: '/export/stumpjumper.lab4.eng.bos.redhat.com_36725/products/dotnet/docs-and-apis/index.html'
```

See the end of the console output here: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-pull-request-builder-drupal/1156/console for more info.

cheers,

Rob

**Pull request closed without merging**
