### PR TITLE
[MERGE MONDAY FEB. 20] DEVELOPER-3900 Homepage hero for Edson's book

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-3900](https://issues.jboss.org/browse/DEVELOPER-3900) - New Hero for RHD Homepage to go live on Monday, Feb 20 2017

### CODE REVIEW

**Comment by adelasofia** [comment]
Approved by Jason Brock

**Comment by adelasofia** [comment]
@paulrobinson @robpblake @RubyGemTSL 

Since you are online before the rest of the team, can one of you merge this PR on Monday Feb. 20th?

Thanks!

**Comment by RubyGemTSL** [comment]
The download link is broken for me. Can @robpblake or @paulrobinson also try please?

**Comment by paulrobinson** [comment]
The download link works in production. The problem is that the staging download manager is yet to be updated with production data.

**Pull request merged**
