### PR TITLE
Update index.html.slim

### PR DESCRIPTION
**Pull request by insectengine**
Replace Kubernetes Promo with Summit Recap promo and update alt tags for other promos.

### CODE REVIEW

**Comment by adelasofia** [comment]
this is ok to test

**Comment by adelasofia** [comment]
@insectengine before we can merge, can you confirm this looks as it should? 😄  https://developers-pr.stage.redhat.com/pr/1872/export/

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Any reason not to merge this?

**Comment by LightGuard** [comment]
@insectengine @adelasofia @jkbrock @KamiQuasi Any reason not to merge this?

**Comment by adelasofia** [comment]
None that I know of

**Pull request merged**
