### PR TITLE
[DEVELOPER-2906] - fix for docker-selenium build issues

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
If we merge this, will the pull request start using docker-selenium, or is there some other work that needs to be done for that to happen?

**Comment by RubyGemTSL** [comment]
@LightGuard - hold for now. The docker jenkins job is a non failing post build action from the current acceptance tests and I'm getting the following error which i'm looking into

"Sending progress to Github . . . "
rake aborted!
Octokit::NotFound: POST https://api.github.com/repos/redhat-developer/developers.redhat.com/statuses/e5faf713e4cad1d0339d18c13aafd78cbe4a3b61: 404 - Not Found // See: https://developer.github.com/v3
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/home/awestruct/gems/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/home/awestruct/gems/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/home/awestruct/gems/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/home/awestruct/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/awestruct/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/awestruct/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/home/awestruct/gems/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit/connection.rb:28:in `post'
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit/client/statuses.rb:43:in `create_status'
/home/awestruct/gems/gems/octokit-4.3.0/lib/octokit.rb:46:in `method_missing'
/home/awestruct/developer.redhat.com/_lib/github.rb:37:in `update_status'
/home/awestruct/developer.redhat.com/_cucumber/cucumber.rake:26:in `block in <top (required)>'

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@LightGuard - the acceptance test job for docker is fixed so this can be merged. I can't stwich the PR builder until this has been merged though but you can see a successful test run here:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/341/console

Once you merge i'll do the switch

**Comment by LightGuard** [comment]
Is it possible to run the acceptance tests locally?

On Friday, April 29, 2016, Ian Hamilton <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> - the acceptance test job for
> docker is fixed so this can be merged. I can't stwich the PR builder until
> this has been merged though but you can see a successful test run here:
>
>
> http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/341/console
>
> Once you merge i'll do the switch
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1060#issuecomment-215702773>
>


-- 
Sent from Gmail Mobile

**Comment by RubyGemTSL** [comment]
@LightGuard 

cd _cucumber 

bundle exec rake features HOST_TO_TEST=http://developers-pr.stage.redhat.com/pr/1060/build/1065/

or within docker

cd _docker

bundle exec ./control.rb --acceptance_test_target=http://developers-pr.stage.redhat.com/pr/1060/build/1065/

**Comment by LightGuard** [comment]
So to run them against local it would be `bundle exec ./control.rb --acceptance_test_target=http://docker:<port>` Right?

**Comment by LightGuard** [comment]
Are the acceptance tests the last thing to run? So I could do a build locally and run acceptance tests all in one go, or would it be two invocations?

**Comment by RubyGemTSL** [comment]
@LightGuard - 

"So to run them against local it would be bundle exec ./control.rb --acceptance_test_target=http://docker:<port> Right?"

yes thats correct.

Are the acceptance tests the last thing to run? So I could do a build locally and run acceptance tests all in one go, or would it be two invocations?

1. You run the stack first
2. bundle exec ./control.rb --acceptance_test_target=http://docker:<port> 

To verify this PR locally simply do 
cd _docker
bundle exec ./control.rb --acceptance_test_target=http://developers-pr.stage.redhat.com/pr/1060/build/1065/

Or see 
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-acceptance-test-docker/341/console

**Comment by LightGuard** [comment]
I can't run these against a locally running awestruct, probably due to some networking thing with docker, but everything else seems to be working fine.

**Pull request merged**
