### PR TITLE
HOLD - RHD-621 - Fixed the vimeo and youtube stat additions

### PR DESCRIPTION
**Pull request by Dantheman720**
This should work now.  I tested it against my instance of searchisko on Docker

### CODE REVIEW

**Comment by paulrobinson** [comment]
Thanks, can you raise a PR on Aweplug?

**Comment by Dantheman720** [comment]
https://github.com/awestruct/aweplug/pull/107

**Comment by Dantheman720** [comment]
Staging isn't showing my changes; however here is my local docker json (https://www.dropbox.com/s/aeslyr08gvm2x5i/localdockerdcp.json?dl=0).  My guess is that my changes are being overwritten by new builds since the Gemfile.lock hasn't been merged yet?

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by paulrobinson** [comment]
This was already fixed in another PR. closing. Please re-open if i'm mistaken.

**Pull request closed without merging**
