### PR TITLE
DEVELOPER-4042 Fixed .Net product name

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4042](https://issues.jboss.org/browse/DEVELOPER-4042)

Changed ".NET Runtime for Red Hat Linux" to ".NET Runtime for Red Hat Enterprise Linux" in:

- /products/
- /downloads/
- Main navigation
- /forums/

and updated acceptance tests

### CODE REVIEW

**Comment by LightGuard** [comment]
I have no problems with this.

**Comment by Dantheman720** [comment]
@adelasofia - The /products page seems to be reason why the tests are failing. It still shows ".NET Runtime for Red Hat Linux"

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@Dantheman720 Ah yes! I didn't realized the /products/ layout was being ignored. I just fixed the name in drupal so the tests should pass this time

**Pull request merged**
