### PR TITLE
[DO NOT MERGE] DEVELOPER-5609: Re-add blinkr checks to PR pipeline

### PR DESCRIPTION
**Pull request by RubyGemTSL**
### JIRA Issue Link
* [DEVELOPER-5609](https://issues.jboss.org/browse/DEVELOPER-5609): Re-add blinkr checks to PR pipeline

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request closed without merging**
