### PR TITLE
DEVELOPER-3609 - Many get-started pages are hiding content

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3609

Updated logic for RHEL tabs to properly activate default tab

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia please review and merge

**Comment by LightGuard** [comment]
@KamiQuasi merge conflict :(

**Comment by paulrobinson** [comment]
There still seems to be a conflict in the Gulpfile.js.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
