### PR TITLE
DEVELOPER-4092 Fixed blue box on .net topic page

### PR DESCRIPTION
**Pull request by adelasofia**
HACKATHON -- [DEVELOPER-4092 Fixed blue box on .net topic page](https://issues.jboss.org/browse/DEVELOPER-4092)

Issue: Blue box was truncating content on smaller windows.

### CODE REVIEW

**Comment by paulrobinson** [comment]
I see this: https://www.dropbox.com/s/kmjaainepj2z9jr/Screenshot%202017-06-15%2017.38.59.png?dl=0 on https://developers-pr.stage.redhat.com/pr/1902/export/dotnet/. Notice the white box that links to get-started.

**Comment by paulrobinson** [comment]
Also, can this only be reproduced on Fedora 25 with Firefox 53?

**Comment by adelasofia** [comment]
@paulrobinson the text in the button shows up white because it was missing a CSS class which needed to be added via drupal. I've added it here: http://stumpjumper.lab4.eng.bos.redhat.com:36902/dotnet

**Comment by adelasofia** [comment]
@paulrobinson I can verify it works in firefox, @LightGuard or @Dantheman720 could you check if it looks ok in fedora?

**Comment by paulrobinson** [comment]
Looks good on chrome on my Mac. @LightGuard or @Dantheman720 can you verify on Fedora then merge?

**Comment by LightGuard** [comment]
Looks good. Merging

**Pull request merged**
