### PR TITLE
[SURGE-3024] Remove Fences

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3024

### Verification Process
Confirm there are no fences set on:
* Assembly Types
* Content Types
* Vocabularies

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
@jordanpagewhite Build fails with:

```

Cloning "https://github.com/redhat-developer/developers.redhat.com " ...
--
  | error: fatal: unable to access 'https://gitlab.corp.redhat.com/uxdd/redhat-theme/':  Peer's certificate issuer has been marked as not trusted by the user.
  | Clone of 'https://gitlab.corp.redhat.com/uxdd/redhat-theme'  into submodule path 'src/styles/redhat-theme' failed
  | Failed to recurse into submodule path 'frontend/rhd-frontend'
```

**Comment by jordanpagewhite** [comment]
Rob already know this, but I will post this for anyone else viewing this PR. This git submodule has been removed from #3015 , and generally will be removed. This branch/PR will likely merge in the changes from #3015 , so this should be resolved once #3015 successfully builds, is reviewed, approved and merged.

**Comment by rogeralloymagnetic** [comment]
retest this please

**Pull request merged**
