### PR TITLE
DEVELOPER-4521 Drupal patch to fix help text not showing for link fields

### PR DESCRIPTION
**Pull request by adelasofia**
Added patch to composer.json for a known bug in Drupal affecting the Help Text for link fields that have the Link Text subfield disabled. https://www.drupal.org/node/2421001

### Review Steps

1. Go to Manage Fields for a content type with a link field
2. Click edit on the link field
3. Add some text to the Help Text field
4. Check Disabled on the Allow link text field
5. Save
6. Go to create a new page for that content type
7. The link field should display the help text

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia It looks like this is probably dying because

1. It's taking a long time to build the containers with the composer changes
2. DB refresh takes a long time
3. composer is slow

There's probably not a whole lot you can do about 1 and 3, but I just put in a PR to help with 2.

**Comment by adelasofia** [comment]
@LightGuard thanks!!

**Pull request closed without merging**
