### PR TITLE
DEVELOPER-4410 - Cheat sheets showing up as both WEBPAGE and CHEAT SHEET in results

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4410

To Test: Visit /admin/content?title=git+cheat+sheet&type=All&langcode=All&moderation_state= and edit the Git Cheatsheet.

* Check the box for "Exclude from search" at the bottom.
* Visit the page and notice that: 
```javascript
<noscript>
    &lt;meta name="DCP:WebpageSearchExclude" content="true"&gt;
  </noscript> 
```
Will appear in the body.

This will force DCP to skip the "WEBPAGE" indexing.

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
no need to retest - it's yet another flaky search test.

**Pull request merged**
