### PR TITLE
[DO NOT MERGE] DEVELOPER-5341 Repository clean-up

### PR DESCRIPTION
**Pull request by adelasofia**
### DO NOT MERGE

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
@adelasofia Can you please update the PR environment `docker-compose.yml` to not try to bind any of the directories you have deleted. It's causing problems with filesystem permissions on the build server as Docker is now trying to create those directories, but it creates them with `root:root` ownership.

In particular could you please delete the following in `developers.redhat.com/_docker/environments/drupal-pull-request/docker-compose.yml`:

```
- ../../../stylesheets/fonts:/var/www/drupal/web/fonts:ro
```
from the `drupal` service definition.

If you could do that before you do another `retest this please` that would be greatly appreciated.

cheers,

Rob

**Comment by LightGuard** [comment]
@adelasofia if we're dropping stylesheets/fonts, we should modify the bash script for local work too.

**Pull request closed without merging**
