### PR TITLE
DEVELOPER-1754 Fixed visibility of logout link

### PR DESCRIPTION
**Pull request by adelasofia**
Jira: [DEVELOPER-1754](https://issues.jboss.org/browse/DEVELOPER-1754)

Definition of Done
- During page rendering we only display Login | Register links .
- Login | Register should then be replaced by user name and logout link once Keycloak JS client detects logged in user.

### CODE REVIEW

**Comment by LightGuard** [comment]
Same errors in the tests

**Comment by LightGuard** [comment]
This seems like a great time for a test. We could write it pretty easily too.

**Comment by adelasofia** [comment]
@LightGuard I just pushed some tests

**Comment by Dantheman720** [comment]
@adelasofia - I'm not seeing the tests under the "Site Navigation Menu". Are they located elsewhere?

**Comment by adelasofia** [comment]
@Dantheman720 they are under /primary_nav/primary_nav.feature

**Pull request merged**
