### PR TITLE
RHD-871 Created Distributed Java EE Architecture Microsite

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by myfear** [comment]
@adelasofia that looks awesome already! What do you think about aligning the book to the left? I sense a lot of optical jumps in there.

**Comment by myfear** [comment]
@adelasofia can you please add the following sentence to my author bio:

"Follow his latest rumblings on his blog.eisele.net or on Twitter @myfear. "

Thank you!

**Comment by adelasofia** [comment]
@myfear I've changed the alignment of the book and added the sentence to your bio, the preview link should be ready soon

**Comment by myfear** [comment]
This design is perfect! Thank you! 

When do we get the download button to work?

**Comment by paulrobinson** [comment]
@myfear I'll chase this with @dhladky. However, we are still aiming to have this live by the end of this week.

**Comment by myfear** [comment]
Got feedback from Emily on this:

" alter the layout a bit and pull the abstract up on the right side and have the image either wrapped with text or on the left side with the Download now button. "

Hope, it's not too late to make this little tweak.

Thanks,
Markus

**Comment by adelasofia** [comment]
@myfear I've added the download link and updated the layout according to Emily's feedback

**Comment by myfear** [comment]
Love it! Looks awesome! 

I do get a 404 when I click on the download link. Is that because of the staging area?

Thanks,
M

**Comment by myfear** [comment]
@paulrobinson I think, we can put this live now. The download is protected for now anyway and the website not promoted. I send Emily a last confirmation but assume, that she is ok with it now.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@myfear I've updated the layout :+1:

**Comment by myfear** [comment]
Thank you soo much @adelasofia ! And sorry for the many cycles! 

Approved and ready to go!

**Comment by paulrobinson** [comment]
@myfear FYI, Emily wants this live on Thursday to maximise our exclusivity period on the book.

**Comment by myfear** [comment]
Thanks for the info!

**Pull request merged**
