### PR TITLE
[RHDX-64] Error: Call to a member function isPublished() on null

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-64](https://projects.engineering.redhat.com/projects/RHDX/issues/RHDX-64)

### Verification Process
2 nodes in production have orphaned Assemblies affecting these urls. This resolves the PHP fatal error.

There 2 URLs in Prod will not load, because of a PHP error:

https://developers.redhat.com/appenv/
https://developers.redhat.com/oraclejdkalternative/

There 2 URLs in this PR environment should load properly:

https://developer-preview-3441.ext.us-west.dc.preprod.paas.redhat.com/appenv/
https://developer-preview-3441.ext.us-west.dc.preprod.paas.redhat.com/oraclejdkalternative/

Also performed some PHPCS clean up. 

### Stakeholders
@jordanpagewhite

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
verify

**Comment by alistairmc** [comment]
rebuild this please

**Comment by robpblake** [comment]
this is ok to test

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
There are actually no UX changes present in this issue. I do want to discuss the _way_ that the On Page Navigation assembly type works with Gina and SJ, but that is not related to this issue or PR. I will do that in Slack and merge this PR now.

**Pull request merged**
