### PR TITLE
DO NOT MERGE YET DEVELOPER-5450: Part 2, Clean up custom theme directories

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This commit removes the RHD theme: both uninstalls it from Drupal and
removes it from the directory tree. We are no longer using it, and this
will make our image smaller.

In order to accomplish this, I had to move some Twig templates, that
were being included, over to the RHDP theme and change some references.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5450

### Verification Process

* Log in to Drupal and visit `/admin/appearance` and verify that the RHD theme is no longer installed, but the RHDP theme is installed and it is set as the default theme
* Generally navigate the site and observe no noticeable difference in the appearance of the site

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
Please do not merge this until my DEVELOPER-5450, Part 1 commit has been merged and verified

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
