### PR TITLE
DEVELOPER-3495 - Add JBD Referral Message

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3495

Adding in a notice for product pages where the user has been redirected from JBD.

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
@KamiQuasi any easy way of testing this?

**Comment by KamiQuasi** [comment]
@LightGuard unfortunately, it appears that a scripting error with DTM is preventing the JS from showing the message. Ideally, it would show up if you went to the URL: /products/fuse/overview/?referrer=jbd

**Comment by LightGuard** [comment]
@KamiQuasi it looks like it works to me, are we good to merge this?

**Comment by KamiQuasi** [comment]
@LightGuard yep, looks like the Adobe Target JS conflicts are cleared up, so it should be okay to merge.

**Pull request merged**
