### PR TITLE
DEVELOPER-3977 Modifying roles

### PR DESCRIPTION
**Pull request by LightGuard**
JIRA: https://issues.jboss.org/browse/DEVELOPER-3977

Please verify Drupal starts up as expected, and the permissions match what is at the spreadsheet: 
https://docs.google.com/a/redhat.com/spreadsheets/d/1ueKUV0FoLbC4OfHVEbY-xN091X_0sZugmW92DCH2k9s/edit?usp=sharing.

Once this is done there will need to be some manual steps to get everyone the correct roles as all of that is stored in the database. I don't feel comfortable trying to do this with a phinx update.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard Looks like we've got merge conflicts on this now.

cheers,

Rob

**Comment by robpblake** [comment]
> Once this is done there will need to be some manual steps to get everyone the correct roles as all of that is stored in the database. I don't feel comfortable trying to do this with a phinx update

@LightGuard Just to clarify this statement. I think you're saying that you will have to make manual changes through the Drupal interface? It's not that we couldn't do this through Phinx, it's just very hard to do so?

Just want to make sure that the Phinx process is giving us the flexibility to make the changes we need.

cheers,

Rob

**Comment by LightGuard** [comment]
This change removes some of the roles we currently have and creates a new role that encompasses some of the roles we currently have. because those roles are being removed, they're removed from the people that currently have them. The tie between user and role is stored in the database. I "think" I know what table contains the role assignments, but I'm not 100% sure I know it all. I could certainly do a diff of a database dump and see where things differ. Probably worth doing that anyway.

**Comment by robpblake** [comment]
@LightGuard Thanks.

I'm still unclear whether your original plan was to re-assign users from the old role to the new one through the Drupal web-interface or whether you were going to re-assign the roles by making changes to the database. 

If through the web interface, then that's fine and seems perfectly reasonable to me, particularly if it's the easiest way to do it. We can give it a try using your PR Drupal instance as that contains all data from production currently.

If you were going to do it by manipulating the database directly, then I feel we should be using Phinx to apply those changes as we'd want to be clear on how to do it and have it tested as part of this PR build before merging your changes.

Hope I'm making myself clear?

cheers,

Rob

**Comment by LightGuard** [comment]
I was going to use the web interface, but I found a way to do it with Drupal update hooks. I'm going to be doing it that way. This also prevents the manual steps and removes any downtime due to rearranging the roles after the push.





On Fri, Jun 2, 2017 at 11:55 AM -0600, "Rob Blake" <notifications@github.com> wrote:












@LightGuard Thanks.


I'm still unclear whether your original plan was to re-assign users from the old role to the new one through the Drupal web-interface or whether you were going to re-assign the roles by making changes to the database.


If through the web interface, then that's fine and seems perfectly reasonable to me, particularly if it's the easiest way to do it. We can give it a try using your PR Drupal instance as that contains all data from production currently.


If you were going to do it by manipulating the database directly, then I feel we should be using Phinx to apply those changes as we'd want to be clear on how to do it and have it tested as part of this PR build before merging your changes.


Hope I'm making myself clear?


cheers,


Rob

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
