### PR TITLE
[FIX] DEVELOPER-4246 - Fix autocompleted function

### PR DESCRIPTION
**Pull request by KamiQuasi**
Code completion error with document.getElementsByName should be getElementsByTagName

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by robpblake** [comment]
@KamiQuasi How do we test this? There are no instructions in the PR body or JIRA issue.

cheers,

Rob

**Comment by KamiQuasi** [comment]
@robpblake sorry about that. To test one should go to the /devnationlive page and register for one of the talks. This fix should make it so that the "Thank You" page automatically goes away.

**Comment by adelasofia** [comment]
This worked for me

**Pull request merged**
