### PR TITLE
RHEL FAQ article Jira DEVELOPER-2880

### PR DESCRIPTION
**Pull request by MikGue**
This is an article for RHEL FAQs.

### CODE REVIEW

**Comment by LightGuard** [comment]
Uh, not sure if this is the name you want... It'll be at /articles/developer-2880 is that what you intended @MikGue?

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by rctrh** [comment]
Please close this PR.   Superceded by PR #1030.

**Pull request closed without merging**
