### PR TITLE
[DEVELOPER-3552] Fix broken 404 error page in export

### PR DESCRIPTION
**Pull request by robpblake**
This PR fixes broken error pages on the site export from Drupal.

It does this by re-writing all absolute links on the error pages back to an absolute form. The value used to replace the relative form of the link is read from the environment variable `drupal.export.final_base_url`. If this value is not set, then it will default to `https://developers.redhat.com`. Any other environment than production should set this variable on the `export` container definition in the environment to ensure that 404 and other error pages are re-written as expected.

At the minute this change only gets applied to the `404-error` and `general-error` page.

**For reviewers:**

1. Navigate to the export of this PR
2. Ensure that `/404-error` page renders correctly, that there are no load errors in the console, and inspect the source to ensure that all links are absolute
3. Do the same for the `/general-error` page

### CODE REVIEW

**Comment by robpblake** [comment]
@paulrobinson / @KamiQuasi Can you please both take a look at this one to make sure its working as expected.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@robpblake Looks good, but https://developers-pr.stage.redhat.com/pr/1750/export/products/bleh/foo.html gives me a generic apache 404. Is that expect?

**Comment by robpblake** [comment]
@LightGuard Yes. The configuration for the pull request environment Apache instance does not re-direct you to the correct 404 location.

**Pull request merged**
