### PR TITLE
RHD-1254 Add mbox code to production site

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
@RubyGemTSL do you want me to keep this open whilst you investigate?

**Comment by RubyGemTSL** [comment]
@paulrobinson - its really strange that this is only happening for this PR.  If you leave it open i'll take a look at it when I get more time.

**Comment by ollyjshaw** [comment]
retest this please

**Pull request closed without merging**
