### PR TITLE
DEVELOPER-3262 - Added new download page for devsuite

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
This should build with the download tables on DevSuite now. The project files now reflect the normalization http://dcp.stage.jboss.org/v2/rest/normalization/project_by_jbossdeveloper_product_code/devsuite

**Comment by LightGuard** [comment]
Is this ready to merge?

**Comment by Dantheman720** [comment]
The redirect in download manager is still directing to CDK for some reason.

**Comment by Dantheman720** [comment]
@nickboldt Can you review http://developers-pr.stage.redhat.com/pr/1276/build/1763/products/devsuite/download/? Notice that the thank-you portion doesn't appear yet. This is because DM redirects to developers.stage.redhat.com instead of my direct PR.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by nickboldt** [comment]
@Dantheman720 I'm still getting redirected to https://access.redhat.com/articles/1340183 when I try to log in as qa@ user. So... I can't test this. :( Who can fix the qa@ user?

**Comment by Dantheman720** [comment]
@lkrzyzanek @velias - Do you know how to fix this on the staging instance of keycloak? I'm not exactly sure why @nickboldt is being redirected to https://access.redhat.com/articles/1340183

**Comment by velias** [comment]
Can you provide exact steps which lead to wrong redirect please?

**Comment by Dantheman720** [comment]
@nickboldt ^^

**Comment by Dantheman720** [comment]
@paulrobinson @LightGuard - This works fine for me. The only item that I wasn't able to check is whether or not the thank you is triggered on the redirect. Are we planning to bring a staging jenkins job back online? If so, can I get access to do manual builds to test this?

**Comment by Dantheman720** [comment]
retest this please

**Comment by nickboldt** [comment]
Steps to reproduce:
open chrome
browse to http://developers-pr.stage.redhat.com/pr/1276/build/1792/products/devsuite/download/
click on link for  Download Red Hat Development Suite 10.0.0 - Restricted -> https://developers.stage.redhat.com/download-manager/file/development-suite-1.0.0-GA-bundle-installer.exe
get redirected to https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/auth?response_type=code&client_id=download-manager-client&redirect_uri=https%3A%2F%2Fdevelopers.stage.redhat.com%2Fdownload-manager%2Frest%2Fkeycloak&state=10%2Fca2b9993-9522-4dbc-9e3b-adda63b26091&login=true
log in as qa@redhat.com user
instead of downloading the .exe, get here: https://access.redhat.com/articles/1340183

**Comment by velias** [comment]
@nickboldt thanks, that looks like misconfiguration of ThankYou page in download manager for given .exe file

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
I am not able to replicate @nickboldt's issue. I attached a video to show what I see on both of my machines.

@LightGuard @adelasofia - Would you be able to test and verify that this works as expected. Here is a videoclip of how I did it. https://www.dropbox.com/s/jade07seg4vfedg/PR_Testing_Instructions.mp4?dl=0

**Comment by LightGuard** [comment]
That all seems to be fine.

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
