### PR TITLE
DEVELOPER-5607 - Added Featured Articles visual style options

### PR DESCRIPTION
**Pull request by adelasofia**
### JIRA Issue Link
[DEVELOPER-5607 - Add Featured Articles visual style options](https://issues.jboss.org/browse/DEVELOPER-5607)

### Verification Process

- **APPROVED BY UX**
- Decrease padding of Featured Articles assembly to match the Rich Text Assembly
- Added visual styles dropdown to Featured Articles assembly

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by adelasofia** [comment]
**this has been approved by UX**

**Comment by alistairmc** [comment]
@LightGuard Are you happy for me to merge this? My first merge on this repo just wanted to be sure!

**Comment by LightGuard** [comment]
Yeah, go ahead!

**Comment by alistairmc** [comment]
Do we use 'merge commit' by default or 'squash and merge'?

**Pull request merged**
