### PR TITLE
DEVELOPER-2964 - Main navigation items are missing a trailing slash i…

### PR DESCRIPTION
**Pull request by Dantheman720**
…n the <a> URI

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
two test scenarios will need updating before this PR is merged!

_cucumber/features/primary_nav/primary_nav.feature:140:in `Then each Communities sub-menu item should contain a link to its retrospective page:'

expected: "http://developers.redhat.com/blog"
got: "http://developers.redhat.com/blog/"

and

_cucumber/features/primary_nav/primary_nav.feature:97:in `Then each Technologies sub-menu heading should contain a link to its retrospective section of the technologies page:'

expected: "http://developers-pr.stage.redhat.com/pr/1227/build/1611/products#infrastructure"
got: "http://developers-pr.stage.redhat.com/pr/1227/build/1611/products/#infrastructure/"


Add / in both cases to fix. Let me know if you have any problems.

**Comment by Dantheman720** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@Dantheman720 

remove the trailing / from "community/contributor/" here:

https://github.com/Dantheman720/developers.redhat.com/blob/9b8930ff82599798ba3c80189ca5eda283d0876e/_cucumber/features/primary_nav/primary_nav.feature#L130

Then your good.

**Comment by LightGuard** [comment]
@Dantheman720 @RubyGemTSL is this good to merge?

**Pull request merged**
