### PR TITLE
DEVELOPER-3032 - Fixed the provide feedback link to only appear on vj…

### PR DESCRIPTION
**Pull request by Dantheman720**
…bug page

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard - Can you review when you get the chance?

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Yeah, looks fine to me. Let's see if we can get an all green build

**Comment by Dantheman720** [comment]
Agreed.

**Comment by LightGuard** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Pull request merged**
