### PR TITLE
DEVELOPER-4806: Author node

### PR DESCRIPTION
**Pull request by delzhand**

### CODE REVIEW

**Comment by delzhand** [comment]
This is a dependency for DEVELOPER-4807 and 4844.

**Comment by LightGuard** [comment]
this is ok to test

**Comment by delzhand** [comment]
Marking this as do not merge for a moment - I need to get a commit in that prevents Fences from doing anything on the current theme.

**Comment by delzhand** [comment]
Once PR #2278 is merged I can unblock this one

**Pull request merged**
