### PR TITLE
DEVELOPER-3577 - Updated the latest content query to use developer materials

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard @paulrobinson - This is ready for review. The latest content is still taking a bit. This is probably because staging DCP is a bit slower than production.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@KamiQuasi please review and merge (once tests pass), also move the JIRA ticket to DONE after you merge.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@KamiQuasi @LightGuard - this should be good to go.

**Comment by Dantheman720** [comment]
@KamiQuasi @LightGuard - We are noticing that the performance is actually worse on production, so we'll need to hold on the merge for now.

**Comment by LightGuard** [comment]
@Dantheman720 Is there anything to test here?

**Comment by LightGuard** [comment]
Wait, is this on hold?

**Comment by paulrobinson** [comment]
@LightGuard yes it's on hold. The query switch was supposed to boost performance, but it made it worse.

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
This query is now taking between 10 and 200ms. A massive improvement. The code looks good. The tests appear to be failing due to the testing users being put on export hold. This is un-related and happening in all PR tests.

**Pull request merged**
