### PR TITLE
DEVELOPER-4213 - Remove + sign from search box on results page

### PR DESCRIPTION
**Pull request by Dantheman720**
To review - Follow https://issues.jboss.org/browse/DEVELOPER-4213

You will need to use the Omnibus app to view evar41. I had to confirm the "privacy alert" for adobe before the omnibus console would populate for this PR.  To do that, open the dpal link in a separate tab and confirm (Chrome Users).

### CODE REVIEW

**Comment by adelasofia** [comment]
@Dantheman720 I still see "%20" instead of "+" in the url in the exported preview, but it works in the drupal preview, is this expected?

**Comment by Dantheman720** [comment]
@adelasofia That's strange. It seems to work for me in the export. Could be a caching issue?

**Comment by adelasofia** [comment]
@Dantheman720 it was the cache :) merged

**Comment by Dantheman720** [comment]
@adelasofia Woot! Thanks!

**Pull request merged**
