### PR TITLE
[DEVELOPER-5872] CTA Form Assembly updates

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5872

### Verification Process
1. Create CTA Form with Visual Styles pictured in Jira ticket

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
@rogeralloymagnetic Is this one ready to roll? Who needs to sign-off?

cheers,

Rob

**Comment by rogeralloymagnetic** [comment]
@robpblake I think it's still waiting on a UX review. I'll ping them.

**Pull request merged**
