### PR TITLE
[SURGE-3123][SURGE-3125][SURGE-3127][SURGE-3128][SURGE-3129][SURGE-3130]Update page node templates

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link

Closes https://github.com/redhat-developer/developers.redhat.com/issues/3123
Closes https://github.com/redhat-developer/developers.redhat.com/issues/3125
Closes https://github.com/redhat-developer/developers.redhat.com/issues/3127
Closes https://github.com/redhat-developer/developers.redhat.com/issues/3128
Closes https://github.com/redhat-developer/developers.redhat.com/issues/3129
Closes https://github.com/redhat-developer/developers.redhat.com/issues/3130

### Verification Process

Using the links below, make sure that the following node type's default/full view modes look acceptable for launch. Please note all feedback and/or create tickets, even for feedback that should be addressed at a later date but is not necessarily a launch blocker.

#### #3123 Books

https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/books/adventures-aboard-kluster-kruise-ship/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/books/introducing-istio-service-mesh-microservices/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/books/deploying-openshift/old/ (I see an issue with the related product sidebar card)
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/books/devops-openshift-cloud-deployments-made-easy/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/books/openshift-developers-guide-impatient-beginners/old/

#### #3125 Cheat Sheet

https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/advanced-linux-commands/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/red-hat-enterprise-linux-8-beta/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/containers/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/advanced-red-hat-jboss-enterprise-application-platform-7/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/git/old/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/intro-red-hat-jboss-enterprise-application-platform/old/

#### #3127 Video Resource

https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/videos/youtube/EVD4EXj8RKc/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/videos/youtube/6lZ2d7ZDpFk/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/videos/youtube/tLz_aNLuCR0/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/videos/youtube/Qt-y3JEQAu4/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/videos/youtube/fmOrmNVdKig/

#### #3128 Learning Path

https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/learn/reactive-meets-microservices/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/learn/microservices/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/learn/developing-on-linux-containers/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/learn/linux-starter-kit-for-developers/

#### #3129 Events

This node type + view mode is entirely unstyled on the live site. Please view live site also.

https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/node/212585/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/node/212565/
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/node/212265/

#### #3130 Products

This really just evaluates the 'container' of the page as the entire (new) Product pages are assembly based, and all content on the page, aside from maybe the page title and top-level container element/style should be handled by the individual assemblies placed on the page.

https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/products/openjdk/overview
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/products/codeready-workspaces/overview
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/products/vscode_extensions/overview
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/products/redhatamq2/overview
https://developer-preview-3159.ext.us-west.dc.preprod.paas.redhat.com/products/fuse2/overview

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
@sjcox-rh 

GENERAL FEEDBACK

I have resolved the case of the content types locally

BOOKS

I've updated the alignment of those social icons. That was a simple mistake in a CSS selector.

VIDEO

I have fixed the issue with the video aspect ratio. I forgot to export configuration in my initial commit, but I have done that now. Thanks. I am having difficulty getting the 'More like this' field to work correctly, and I am not sure why right now. I will look into it though.

PRODUCT PAGES

Yes, those are all just assemblies, so the output/formatting of those will be dealt with in individual assembly tickets. The one in your screenshot, for example, is the Rich Text Columns, which was just completed/merged by Roger today.

**Comment by sjcox-rh** [comment]
@jordanpagewhite great, you da best! This is all good then.

**Comment by jordanpagewhite** [comment]
### Remaining issue

@sjcox-rh Just FYI, the 1 remaining issue on this PR now is the 'More Like This' section not loading. After quite a bit of looking around, I realized that this section is generated via a JS file here: `./rhd-frontend/src/scripts/@rhd/js/related-content.js` in the Prod version of the `rhd-frontend` package. It seems that this file and a lot of other JS files were not brought over into this new version of the `rhd-frontend` project, so thank you a ton for catching this because as a result I found a bunch of other things that needed to be included.

So, that issue is In Progress and will be addressed in the FE repo. I will review this on the PR site once it builds.

**Comment by jordanpagewhite** [comment]
Screen Shot 2019-10-07 at 8 41 45 AM

From commit:

>>> Currently, this section will render with Foundation classes i.e. the
grid will be wrong and the Card styles do not match our current Card
component on the site. However, I created a ticket in the FE repo here:
redhat-developer/rhd-frontend#305 to update
the Foundation classes with PatternFly classes.

**Comment by sjcox-rh** [comment]
@jordanpagewhite just slacked you about this as well, but this is good to merge since there is a follow up issue to address the "More Like This" grid fix.

**Comment by jordanpagewhite** [comment]
SJ approved in Slack. merging now

**Pull request merged**
