### PR TITLE
Fixes RHD-625 missing bom

### PR DESCRIPTION
**Pull request by LightGuard**
This is part of a larger fix, but they can be independent.

### CODE REVIEW

**Comment by wesbos** [comment]
This will give me the target_product in the JSON feed?

**Comment by LightGuard** [comment]
@wesbos Hoping so. We'll see when it builds

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@wesbos @paulrobinson Could I get someone to review this please? It's good to go, and important for us to get into production.

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
