### PR TITLE
Feature/product try it hero needs the image to float above the text when responsive #3414

### LINKED ISSUE #3414: Product try it hero needs the image to float above the text when responsive
**Description**
The product try it hero is currently squishing the image when it is placed to the left or right side of the text. This also occurs on the product download hero.

**To Reproduce**
1. Go to https://developers.redhat.com/products/codeready-workspaces/overview
2. Decrease width of screen to a mobile size

**Expected behavior**
The image should move above the text at the medium breakpoint.

You can see this behavior if you:

1. Go here https://developers.redhat.com/topics/kubernetes/
2. Scroll to 'Setup a Kubernetes development environment' section (content with image assembly)
3. Decrease width of screen to a mobile size

**Screenshots/GIFs**
Product try it hero: 
Screen Shot 2019-11-26 at 7 12 23 PM

Content with image:
Screen Shot 2019-11-26 at 7 12 36 PM

**Additional context**
@alistairmc and I spoke about this while he was working on #3408 as he added the product download hero in there. It looks like the front-end site isn't showing any examples of the hero with an image placed to the left or right of the text. May be worth updating those examples to include that.

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
Fixes #3414 

### Verification Process
Go to. /products/codeready-workspaces/overview on mobile screen sizes image should be above text.

Build should go green

### CODE REVIEW

**Comment by alistairmc** [comment]
rebuild this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Pull request merged**
