### PR TITLE
DEVELOPER-3801 Moved issue collector cta to footer

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
You'll have to edit the 404 page in drupal. You can see the ignore_export is true.

**Comment by adelasofia** [comment]
@LightGuard Yep, I was just fixing the syntax error in case someone used that template as reference for anything else

**Comment by LightGuard** [comment]
Okay, cool. All good.

**Comment by adelasofia** [comment]
Approved by Tiffany N.

**Pull request merged**
