### PR TITLE
[HOLD] DEVELOPER-4526 - Remove Archetypes, Quickstarts, BOMs, Ticket-Monster and Demos from Awestruct pipeline

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
Well, looks like it worked as far as not sending things to drupal!

**Comment by LightGuard** [comment]
I doubt the failure here is anything we need to worry about.

**Comment by RubyGemTSL** [comment]
yup, I've fixed the desktop test and now the mobile one is failing, typical. I'll have this fixed first thing tomorrow.

**Comment by Dantheman720** [comment]
This PR needs to be held until we can coordinate a release with @lkoranda.

**Comment by LightGuard** [comment]
@Dantheman720 what needs releasing for the coordination?

**Comment by Dantheman720** [comment]
@KamiQuasi @LightGuard - I backed out the migration to see if it was causing the build issues...I don't think it's the issue because everything is working fine locally. Is Jenkins having issues?

**Pull request closed without merging**
