### PR TITLE
[SURGE 3038] Product Download Hero

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### Github Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3038

### Verification Process
1. Create or view existing product download hero
2. Try all content variations
3. Confirm that it matches FE markup here: https://redhat-developer.github.io/rhd-frontend/components/product-download-hero/

### CODE REVIEW

**Comment by robpblake** [comment]
@rogeralloymagnetic The `npm install` process is failing with:

```
File dist/js/@rhd/rhd.old.min.js written successfully !
--
  | tsconfig.prod.json:8:9 - error TS5023: Unknown compiler option 'allowUmdGlobalAccess'.
  |  
  | 8         "allowUmdGlobalAccess": true,

```

I'm gonna guess that is caused by running the wrong version of node in the Drupal container. Leave it with me.

**Comment by robpblake** [comment]
Caused by redhat-developer/rhd-frontend#188

**Comment by robpblake** [comment]
@rogeralloymagnetic I'm seeing the following error in Drupal when it tries to run cron with this PR:

```
"PHP Fatal error:  Cannot use Drupal\\file\\Entity\\File as File because the name is already in use in /var/www/drupal/web/themes/custom/rhdp2/rhdp2.theme on line 11", " [error]  Drush command terminated abnormally due to an unrecoverable error.", "Error: Cannot use Drupal\\file\\Entity\\File as File because the name is already in use in /var/www/drupal/web/themes/custom/rhdp2/rhdp2.theme, line 11```

**Comment by rogeralloymagnetic** [comment]
@jordanpagewhite The Visual Styles in that ticket still don't quite match up for this or the product_try_it_hero. I've updated the Visual Styles in config to add in the new classes and put `(deprecated)` in the title of the old classes.

**Comment by rogeralloymagnetic** [comment]
Visual Styles issues documented here: https://github.com/redhat-developer/developers.redhat.com/issues/3103

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
