### PR TITLE
DEVELOPER-2703 RHEL Docs and APIs page changes

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia Who is the reviewer, is it @MikGue

**Comment by adelasofia** [comment]
@LightGuard Yes, I'll leave a comment once this is approved and ready for code review

**Comment by adelasofia** [comment]
Approved by Mike Guerette

**Pull request merged**
