### PR TITLE
[NEVER MERGE] Revert "Revert "Feature/remove compass""

### PR DESCRIPTION
**Pull request by paulrobinson**
Putting this fix back in again, to see if it breaks in staging.

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@LightGuard I've re-created this PR that you raised. Notice that the preview is broken in that images, fonts and icons don't appear. Can you investigate?

**Comment by LightGuard** [comment]
We should probably add a -b localhost to the awestruct invocation from rake.

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by LightGuard** [comment]
Are we still looking at using this?

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@LightGuard we can still use this if you can make it work. I'll close the PR as you've now seen the issue.

**Comment by LightGuard** [comment]
PR build was reaped, can't see it.

**Pull request closed without merging**
