### PR TITLE
[DEVELOPER-4183] Fix running Drupal in Docker for drupal-dev environment

### PR DESCRIPTION
**Pull request by robpblake**
This PR fixes running Drupal inside of Docker within the `drupal-dev` environment. 

For reviewers:

- cd _docker
- ruby ./control.rb -b
- ruby ./control.rb -r

Ensure that Drupal is now running on your local machine.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 @KamiQuasi could one of you try this, please? I cannot get past the need for decrypting the secrets file. If you aren't able to get to it within the next couple of hours I'll bypass that part and try it that way.

**Comment by Dantheman720** [comment]
@robpblake This works for me. @LightGuard was having issues with the vault, so holding until we can get  an additional +1

**Comment by LightGuard** [comment]
@KamiQuasi @adelasofia could one of you please verify this works for you?

**Comment by adelasofia** [comment]
@robpblake I might be testing this the wrong way, but once I run `ruby ./control.rb -rb` I get _No supporting services to start._ at the end

**Comment by Dantheman720** [comment]
@adelasofia - I received the same message; however, if you --run-the-stack, it should work just fine.

**Comment by LightGuard** [comment]
@KamiQuasi have you been able to get this to work?

**Comment by KamiQuasi** [comment]
@LightGuard giving it a go now. Seems to be building Drupal at the moment. Will see how it goes.

**Comment by Dantheman720** [comment]
Can we merge this?

**Comment by KamiQuasi** [comment]
@Dantheman720 @robpblake @LightGuard @adelasofia I have been having environment problems that should probably not delay getting this out. They aren't specific to this PR, so if others have had success I'd say go ahead and merge.

**Comment by LightGuard** [comment]
That's where things get tricky. Some people have had success, others have not, and no one has had success with the original instructions that Rob said to use with this PR.

**Comment by adelasofia** [comment]
I have not been able to build this either. I can use the setup script but not --run-the-stack. It's my environment not these changes though.

**Comment by Dantheman720** [comment]
@robpblake - I'm having issues with it on my mac as well. It works fine on Linux though.

**Comment by robpblake** [comment]
@Dantheman720 @adelasofia @KamiQuasi I've updated the instructions to separate out the -br commands. That should work, but let's get your environment issues fixed first.

Give me a shout on HipChat when you're around.

cheers,

Rob

**Pull request merged**
