### PR TITLE
DEVELOPER-3297 All pages should be marked as 'canonical'

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@LightGuard does this seem a reasonable approach for enabling the canonical link on just the product pages?

**Comment by paulrobinson** [comment]
@LightGuard: Actually we need this on every page. Does this seem reasonable? I'm not sure what the code I removed was for.

**Comment by LightGuard** [comment]
:+1:

**Pull request merged**
