### PR TITLE
DEVELOPER-4539 - Upstream project images fail to load on Firefox

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4539

To test, visit the projects page and make sure that all of the functionality exists. I've tested this on Firefox 52 which was mentioned in the issue. The loading doesn't seem to be an issue with the refactored code.

### CODE REVIEW

**Comment by LightGuard** [comment]
Firefox 57 works fine w/o this, but with it, no go. Chrome doesn't work either.

**Comment by Dantheman720** [comment]
@LightGuard - It should work on the "drupal-site" version. The export doesn't pick up my drupal projects page edits.

**Comment by LightGuard** [comment]
Works on the drupal site, not working on the export has me a bit concerned though.

**Comment by LightGuard** [comment]
Okay, I understand what's happening now. This change required a content change as well as what's happening within this pull request, which is why the export doesn't work.

**Pull request merged**
