### PR TITLE
[RHDX-310] Add ckeditor_templates and supporting modules/plugins.

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-310

**Notes:** 
* Create new templates here: https://localhost/admin/config/content/ckeditor_templates
* Templates can (but currently don't) have images and descriptions. @maryshak1996 maybe you could provide some if you think they'd be useful. See the "Templates dialogue" screenshot below.
* The divs can be a little finicky since at the end of the day we're still in ckeditor. But I assume anyone using this feature will be comfortable with the Source view. If not, we could discuss using tables, but I'd really rather not.

### Verification Process
1. Add a new rich_text assembly
2. Click on the new "Templates" icon (highlighted in screenshot below)
3. Update text and save.

#### Editor Icon
Screen Shot 2020-06-18 at 2 42 05 PM

#### Templates Dialog
Screen Shot 2020-06-22 at 10 24 00 AM
Screen Shot 2020-06-22 at 10 24 06 AM

#### Final Product
Screen Shot 2020-06-18 at 2 32 09 PM

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
@jordanpagewhite please see my last comment on the ticket: https://projects.engineering.redhat.com/browse/RHDX-310?focusedCommentId=2479422&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2479422

**Comment by maryshak1996** [comment]
@rogeralloymagnetic I'm happy to come up with some descriptions to help content creators make use of the columns and source view with it :) as for now, here's some images that might help:
two-col
two-col copy
two-col copy 3
two-col copy 2

**Review by maryshak1996 — APPROVED** [review]
works perfect!

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Review by staceymosier — APPROVED** [review]

**Review by jordanpagewhite — APPROVED** [review]
Looks good to me! Thanks

**Pull request merged**
