### PR TITLE
DEVELOPER-4302 - OneBox Component

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-4302

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@adelasofia or @LightGuard we've got UX and PM approval, so other than a code review this can be merged

**Pull request merged**
