### PR TITLE
DEVELOPER-3662 - Implement DCP rivers indexer for the events Drupal REST Export

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by LightGuard** [comment]
@Dantheman720 What's the best way to verify this?

**Comment by Dantheman720** [comment]
https://www.dropbox.com/s/6xiq10igulrngnq/Events.mp4?dl=0

**Comment by paulrobinson** [comment]
I think we should see the Drupal server changes and the DCP River changes as seperate things. 

I propose merging this once we are happy that:

1. The Events can be added, updated and removed from Drupal
2. The JSON response from the REST API looks right.

Further changes may then be needed to make the DCP River work correctly. But that can easily be done later.

**Comment by paulrobinson** [comment]
The spreadsheet has validation that should be applied on the event form. E.g. min and max field sizes.

**Comment by paulrobinson** [comment]
What's the 'Event Background Image' field for? Is that an override to the event image?

**Comment by paulrobinson** [comment]
I added an event, and got back what I expected here: http://stumpjumper.lab4.eng.bos.redhat.com:36613/drupal/events

This seems good to go after the form issues have been fixed and @LightGuard has done a code review.

**Comment by Dantheman720** [comment]
@paulrobinson @LightGuard - We'll probably want to have Jess or Mike work with this first, but validation is working now (thanks Jason :)). I added some help text and changed the Target Products to a selection box.

**Comment by paulrobinson** [comment]
I added an event ('Paul's Test Event 2') and then deleted it. However, the content is still appearing in http://stumpjumper.lab4.eng.bos.redhat.com:36613/drupal/events, despite it not being listed in http://stumpjumper.lab4.eng.bos.redhat.com:36613/admin/content?status=All&type=events&title=&uid=&langcode=All.

I wonder if this is just a caching issue?

**Comment by LightGuard** [comment]
Ah, that's a view, yes, it's possible that's a caching issue.

**Comment by LightGuard** [comment]
Nope, not a caching issue. @Dantheman720 you need to add another filter criteria: Content revision: Deleted flag (= False)

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please.

**Comment by robpblake** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@paulrobinson @LightGuard - Can this be merged now, or do we need to wait for KC/DM tests to pass? My plan is to get this PR merged and make sure that staging DCP can communicate with the staging instance of Drupal Site (not the export since export lik. If that is the case, I'll raise a ticket with IT to create a firewall exception (I spoke with @unibrew a little bit about this). Once that is done, we'll work on getting the staging instances mirrored  in production.

**Pull request merged**
