### PR TITLE
[HOLD] DEVELOPER-4256: Refactor current Search acceptance tests using webdriverIO

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[DEVELOPER-4256](https://issues.jboss.org/browse/DEVELOPER-4256): This PR introduces tests for the updated search page using the new webdriverio test framework.

Holding this until the [PR for the loading spinner](https://github.com/redhat-developer/developers.redhat.com/pull/1960) is complete. Will update tests when that is merged.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
I'm good with this, it took 99 minutes for the e2e tests to run, @RubyGemTSL is that expected?

**Comment by RubyGemTSL** [comment]
@LightGuard Hold not sure where you got that from? I see that they took just  [3 min 58 sec](https://redhat-dev-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Node_End_To_End_Tests/234/). 

Hold on merging this, thanks. I spoke to Luke and we're not going to introduce the new tests until I'm back from Holiday. I need to get everyone together and go through the new test framework in case anything goes wrong when I'm away. The unit-tests will be fine for now. we've managed this long without updated search tests.

**Comment by LightGuard** [comment]
@RubyGemTSL Got that number from Jenkins. Not sure how it calculated it.

**Pull request closed without merging**
