### PR TITLE
[Developer 3253] Add logged in user to mobile nav

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3253

### Verification Process
1. View mobile nav as an anonymous user
2. See "Login" text
3. Login
4. View mobile nav as a logged in user
5. See first and last name displayed in mobile nav

### CODE REVIEW

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Comment by robpblake** [comment]
Checked this and confirmed that user name does appear on the mobile menu after logging in.

@rogeralloymagnetic Is there anything preventing this from being merged?

cheers,

Rob

**Review by robpblake — APPROVED** [review]

**Comment by robpblake** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
@robpblake this is waiting on style changes from Adela.

**Comment by rogeralloymagnetic** [comment]
@robpblake I just talked with Adela and she's going to make another PR later today for the style changes. Merging this now.

**Pull request merged**
