### PR TITLE
[DEVELOPER-5816] change fix position on toc

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5816

### Verification Process
Go to a page with a sticky nav and check it is not overlapping the disqus or footer areas.

/articles/red-hat-developer-program-benefits

### CODE REVIEW

**Comment by alistairmc** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by alistairmc** [comment]
@robpblake  this is ux approved now

**Pull request merged**
