### PR TITLE
[DEVELOPER-5700] Product pages invalid array key featured

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5700

### Verification Process

Go here:

/products/codeready-workspaces/download

Then login to an admin account and go here:

/admin/reports/dblog

You should *not* see error(s) like this:

```
User error: "featured" is an invalid render array key in Drupal\Core\Render\Element::children() (line 97 of /Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Element.php) #0 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(256, '"featured" is a...', '/Users/jowhite/...', 97, Array) #1 
[internal function]: _drupal_error_handler(256, '"featured" is a...', '/Users/jowhite/...', 97, Array) #2 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Element.php(97): trigger_error('"featured" is a...', 256) #3 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/modules/contrib/assembly/assembly.page.inc(38): Drupal\Core\Render\Element::children(Array) #4 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Theme/ThemeManager.php(287): template_preprocess_assembly(Array, 'assembly', Array) #5 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('assembly', Array) #6 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #7 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\Core\Render\Renderer->render(Array) #8 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/sites/default/files/php/twig/5c7ffaf0b3ff3_field.html.twig_1OtXR9DjdfFQhd7UOQfz0f8j7/KlgkeDjBnBpz-I_QzrsNacsLYsOuoKGiuv242kXj-So.php(90): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true) #9 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/twig/twig/lib/Twig/Template.php(428): __TwigTemplate_fdce0be70f9fdfb78bc2c9a3608ef43feef61491d29b11a99f485a5628944977->doDisplay(Array, Array) #10 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/twig/twig/lib/Twig/Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #11 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/twig/twig/lib/Twig/Template.php(407): Twig_Template->display(Array) #12 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array) #13 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('modules/contrib...', Array) #14 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('field', Array) #15 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(450): Drupal\Core\Render\Renderer->doRender(Array) #16 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #17 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Template/TwigExtension.php(490): Drupal\Core\Render\Renderer->render(Array) #18 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/sites/default/files/php/twig/5c7ffaf0b3ff3_node--product--product-do_Wi-zk_mQCJJCpJcTCeaYHynR5/dHTbUFR9RuoBvTzByRiTkk5DDD59UshhfpaYww9SBHQ.php(89): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true) #19 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/twig/twig/lib/Twig/Template.php(428): __TwigTemplate_3980b5b23ff782d1438b1d3d06db9584e1c351596e9d5969269639129d65c0d4->doDisplay(Array, Array) #20 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/twig/twig/lib/Twig/Template.php(399): Twig_Template->displayWithErrorHandling(Array, Array) #21 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/twig/twig/lib/Twig/Template.php(407): Twig_Template->display(Array) #22 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/themes/engines/twig/twig.engine(64): Twig_Template->render(Array) #23 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('themes/custom/r...', Array) #24 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('node', Array) #25 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false) #26 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Controller/ProductsDownloadsController.php(195): Drupal\Core\Render\Renderer->render(Array) #27 
[internal function]: Drupal\rhd_assemblies\Controller\ProductsDownloadsController->content('codeready-works...') #28 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #29 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #30 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #31 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #32 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #33 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #34 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #35 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #36 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #37 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #38 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/modules/contrib/jsonapi/src/StackMiddleware/FormatSetter.php(41): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #39 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/modules/ban/src/BanMiddleware.php(50): Drupal\jsonapi\StackMiddleware\FormatSetter->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #40 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\ban\BanMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #41 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #42 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #43 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #44 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #45 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/vendor/drush/drush/misc/d8-rs-router.php(62): require('/Users/jowhite/...') #46 
{main}.
```

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
@LightGuard Could you give this a review whenever you have a free moment? Thank you

**Pull request merged**
