### PR TITLE
DEVELOPER-1746 - Fixed hardcoded javascript error that leads to broke…

### PR DESCRIPTION
**Pull request by Dantheman720**
…n video links in production

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
I'm still seeing dcpbeta-searchisko.rhcloud.com URLs. Take a look at the XHR network calls on: http://it-developers-pr.stage.redhat.com/pr/692/build/446/video/youtube/KUhORHjJj08/

It calls:

       http://dcpbeta-searchisko.rhcloud.com/v1/rest/search?content_provider=jboss-developer&content_provider=rht&content_provider=openshift&field=sys_author&field=target_product&field=contributors&field=duration&field=github_repo_url&field=level&field=sys_contributors&field=sys_created&field=sys_description&field=sys_title&field=sys_tags&field=sys_url_view&field=thumbnail&field=sys_type&field=sys_rating_num&field=sys_rating_avg&field=experimental&project=eap&query=sys_type:(video)&size=500&sortBy=new-create

**Comment by paulrobinson** [comment]
retest this please

**Comment by Dantheman720** [comment]
Yeah.  On the staging build, it will still call dcpbeta-searchisko.rhcloud.com since we have it listed in the site.yaml.  Should I switch that to our docker version?  

In production however, this error should not show up since it now points to app.dcp.url.search.

**Comment by paulrobinson** [comment]
I'll investigate that on Monday. This PR is a step in the right direction, so merging.

**Pull request merged**
