### PR TITLE
DEVELOPER-3431 - Download action resets situation tab

### PR DESCRIPTION
**Pull request by Dantheman720**
retest this please

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by adelasofia** [comment]
@Dantheman720 it did not keep me in the correct tab :( I'm using Chrome V.64

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
Darn! Did you navigate back to the same origin? The redirect will send you developers.redhat.com from the PR

**Comment by Dantheman720** [comment]
retest this please.

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
