### PR TITLE
Searchbar ui

### PR DESCRIPTION
**Pull request by Dantheman720**
Read for review.

### CODE REVIEW

**Comment by paulrobinson** [comment]
@Dantheman720 the infinite scrolling is not working for me. Don;t worry about it though. We might use pagination anyway. Otherwise, Wes will know how to fix it when he does the visuals.

**Comment by Dantheman720** [comment]
@paulrobinson That's strange - when you search http://it-developers-pr.stage.redhat.com/pr/576/build/1217/search/?s=cdi/ you aren't able to infinite scroll?  Mine seems to work on chrome.

**Comment by Dantheman720** [comment]
@paulrobinson Also, I have no idea why the redirect isn't working...really frustrating.  It works on localhost just fine, but I can't seem to get it on staging...

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
Closing, as this is now ready for @wesbos to finish off (after wireframe is approved). Please keep the branch around.

**Pull request closed without merging**
