### PR TITLE
Fixes DEVELOPER-2505 (angular dcp not working)

### PR DESCRIPTION
**Pull request by LightGuard**
THIS MUST BE MERGED AFTER #762 

This relies on all the pages being pushed to drupal, which is in a different pull request as mentioned above.

I took out the wrapping of everything in a function as that was causing
some scope issues in the javascript. Because of that I had to create $
for our jquery stuff. I'm also no longer uglifying the concated
javascript files because it was causing problems with the angular module
as well. We can look at what's really happening with that at some other
point.

### CODE REVIEW

**Comment by paulrobinson** [comment]
For some reason the DCP is not available for this PR. I suggest retesting to bring it back. We should hold fire, to keep the CI box free for hard launch builds. I'll try this out on Monday.

**Comment by paulrobinson** [comment]
To review, just make sure the JS is working.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
I've built this PR, and visited: http://docker:32769/resources

I see: https://www.dropbox.com/s/p98640qe1zrrnxn/Screenshot%202016-02-18%2014.58.15.png?dl=0

Also, this error is in the console: Uncaught SyntaxError: Unexpected token ILLEGAL

**Comment by LightGuard** [comment]
Hm, haven't seen that. I'll have to build locally to see what's up.

On Thu, Feb 18, 2016 at 7:59 AM, Paul Robinson <notifications@github.com>
wrote:

> I've built this PR, and visited: http://docker:32769/resources
>
> I see:
> https://www.dropbox.com/s/p98640qe1zrrnxn/Screenshot%202016-02-18%2014.58.15.png?dl=0
>
> Also, this error is in the console: Uncaught SyntaxError: Unexpected token
> ILLEGAL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/763#issuecomment-185756820>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by paulrobinson** [comment]
Did you get chance to reproduce?

**Comment by LightGuard** [comment]
Not yet

On Tue, Feb 23, 2016 at 8:14 AM, Paul Robinson <notifications@github.com>
wrote:

> Did you get chance to reproduce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/763#issuecomment-187597122>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
There's still a syntax error, but as near as I can figure it's caused by trying to contact keycloak.

**Comment by LightGuard** [comment]
I discovered the root of the problem in drupal. To test this you'll need to go to a page that's coming from awestruct (http://docker:32769/resources or http://docker:32769/node/<some number>) otherwise you'll see an issue where app isn't defined. We could fix that, but it only a problem on pages within drupal that have not been pushed to from awestruct.

**Comment by LightGuard** [comment]
Testing by closing and reopening.

**Pull request closed without merging**
