### PR TITLE
[DEVELOPER-5861] Series Content Type

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This implements the configuration necessary to create the Series content
type, as specified in DEVELOPER-5861. There will be a follow-up ticket
to implement an Assembly type and provide styles and designs for this
content type and the related assembly type.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5861

### Verification Process

Go here: /node/add/series

Do this:

* Add content to the fields in the Content tab of the Compose interface
* Save the form to create the Series
* This should redirect you to your newly created Series content

You should see this:

The content should successfully created and the data types / references should allow the editor to create a Series as defined in https://issues.jboss.org/browse/DEVELOPER-5861

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@jordanpagewhite I'm seeing dangling configuration on this one: https://developer-preview-2981.ext.us-west.dc.preprod.paas.redhat.com/admin/config/development/configuration

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
