### PR TITLE
[RHDX-309] Add Kiosk Mode option 

### PR DESCRIPTION
**Pull request by staceymosier**
### JIRA Issue Link
[RHDX-309](https://projects.engineering.redhat.com/browse/RHDX-309)

### Verification Process
1. Sign in and edit the page /eventtutorials/
2. See the Kiosk Mode field option. Check it to enable and publish the change
3. View the page and verify it has a minimal header
4. Remove the setting and publish; Verify the page updates to show the full website header
5. View other content types and non-nodes (assemblies, term, user pages) and verify there are no new or introduced php warnings

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
Also @sjcox-rh from a UX / user workflow perspective, 

If a user navigates from (for example) the https://developer-preview-3514.ext.us-west.dc.preprod.paas.redhat.com/eventtutorials/ page that Stacey linked to one of the Katacoda scenarios, do we need to create some way for the user(s) to get back to the https://developer-preview-3514.ext.us-west.dc.preprod.paas.redhat.com/eventtutorials/ page? The original functionality of the breadcrumbs assumed that Katacoda courses would all live under the /courses route, so the breadcrumb 'All Courses' directs back to the /courses route.

**Comment by staceymosier** [comment]
@sjcox-rh   I will address the padding for the Katakoda (kiosk-mode) header here in this PR.

Regarding breadcrumbs, it may be easier to have a short chat.  I cannot determine what the end scenario will be based on the comments above. If we can speak today or tomorrow morning, it may be possible to put it into this PR.

**Comment by staceymosier** [comment]
@sjcox-rh  @jordanpagewhite   Spacing is reduced to --rhd-theme--container-spacer-md 16px.
Breadcrumbs question will go into a ticket for next sprint.  Thanks!

**Comment by jordanpagewhite** [comment]
Thank you @staceymosier for those changes. I created this issue to track the breadcrumbs request https://projects.engineering.redhat.com/browse/RHDX-329

**Pull request merged**
