### PR TITLE
[HOLD] DEVELOPER-3164 RHD-1592 RHD-1593

### PR DESCRIPTION
**Pull request by pmuir**
Initial work for updating CDK get-started and overview pages. 

Open issues:
* Links adding for development suite (assume this can be done by web team once dev suite is added)
* Web team support for get started page - ping me when done so I can review the content

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by pmuir** [comment]
Video will be made next week by Alexey Kaxakov

**Comment by pmuir** [comment]
Link added for video.

**Comment by pmuir** [comment]
@Dantheman720 added my PR to his big merge branch, so the changes are now live.

**Pull request closed without merging**
