### PR TITLE
[RHDX-341] Add meta description to assembly_page content type

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://projects.engineering.redhat.com/browse/RHDX-341

### Verification Process
1. Login. https://developer-preview-3525.ext.us-west.dc.preprod.paas.redhat.com/user/login
2. Edit a node with the "Page" content type.
3. See that a new "Short Description" field exists.
4. Enter content into that field and save the node.
5. View source on the node and see that the "description" and "og:description" meta tags show the entered content.

### Note:
Internal search results have not been tested.

### CODE REVIEW

**Comment by robcoffman** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
retest this please

**Review by jordanpagewhite — APPROVED** [review]
These changes look good to me. I ran through the verification steps on this Page node: https://developer-preview-3525.ext.us-west.dc.preprod.paas.redhat.com/webinars/developer-productivity-on-kubernetes-with-openshift/

**Review by staceymosier — APPROVED** [review]
I was able to add a description to a Page cheat sheet,  and I was also able to override that value from the node Metatag field as well.

**Review by gdoyle1 — APPROVED** [review]
Approving based on our bluejeans call!

**Pull request merged**
