### PR TITLE
DEVELOPER-4406: Update the add content drop-down menu

### PR DESCRIPTION
**Pull request by LightGuard**
JIRA: https://issues.jboss.org/browse/DEVELOPER-4406

Added the missing content types to the menu.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
This is another one that doesn't seem to have picked up the latest changes to the Dockerfiles.

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
I don't think retesting this is going to help. For whatever reason the new changes aren't being picked up. Maybe review manually and if you think it has no risk then merge if happy? I think either merging or closing/reopening a new PR is the only option with this.

**Comment by LightGuard** [comment]
@adelasofia the change I made solely affects Drupal admin, so it doesn't touch any of the tests. If you're comfortable with the changes to the PR instance with this ticket, go ahead and merge. If not, let me know and I'll merge in the change from prod here and rebuild it.

**Pull request merged**
