### PR TITLE
Fix coding resource display

### PR DESCRIPTION
**Pull request by LightGuard**
Create a coding resource, verify it displays properly (meaning it displays pretty much the same as other quickstarts). You'll notice a difference in the target product display, but that should be fine.

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
If the broken links checks don't finish, I don't think that's a problem. @RubyGemTSL, what are your thoughts?

**Comment by RubyGemTSL** [comment]
@LightGuard yes, unfortunately phantomjs uses a lot of resource and then crashes which is out of my control, it's a known issue with the phantomjs team but they no longer maintain it. I need to get some time to really dig deeper into the root cause or switch to headless chrome/firefox. I'll need to do this asap as it appears to be happening more and more recently.

**Comment by RubyGemTSL** [comment]
But to answer your question - I don't think it's necessary to do a retest when the broken link checks don't finish.

**Pull request merged**
