### PR TITLE
[HOLD] Login/register tests

### PR DESCRIPTION
**Pull request by RubyGemTSL**
adding wip for login/reg ticket RHD-970

adding wip

adding wip

added scenarios for social login, and password reset, now using gmail rather than guerrilla mail

removed @wip tag

fixed conflicts

completed password reset scenario

added new line to feature

added wip for registrations refactor

adding wip for 970

added wip for social login. Fixed issue with tests not loggin out.

added test for miss-matching passwords on registration.

added test for miss-matching passwords on registration.

updated email to use when registering customers

completed tests

completed tests

fixed conflicts

fixed conflicts

fixed conflicts

added begin rescue to login/registration pages as the links are not always responsive.

### CODE REVIEW

**Comment by ollyjshaw** [comment]
This failed due to some experiments I was running on the nightly build. I'll have it back shortly

**Comment by ollyjshaw** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@paulrobinson @ollyjshaw unfortunately this can't be merged until the staging PR instance uses the staging version keycloak. Currently it is pointing to production therefore tests will always fail.

**Comment by ollyjshaw** [comment]
@RubyGemTSL Don't forget this staging PR instance is in your control. Can you change the config in site.yml? Sounds like changing the keycloak config is the work of this ticket.

**Comment by RubyGemTSL** [comment]
@ollyjshaw I'm pretty sure there was a ticket for this in progress. I'll try updating the config. currently having trying to get around an issue with docker and awestruct  "undefined method for []"  grrr.

**Comment by RubyGemTSL** [comment]
There is also an issue with Products and Downloads page. They don't look right. Must have been caused by a rebase conflict I suspect. Weirdly when I compare with master the relevant layouts.html files are identical. Strange, will fix that first.

**Pull request closed without merging**
