### PR TITLE
[DEVELOPER-5840]: PSA-2019-05-07

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This implements the Drupal core update from 8.6.15 to 8.7.1, which
includes a necessary Lighting update to 3.3.1. After making these
updates with a `composer update drupal/core acquia/lightning
--with-dependencies`, I rebuilt the cache and then ran `drush updb`,
then I rebuilt the cache and ran `drush update:lightning`. Lastly, I
rebuilt the cache, verified the site was loading and that there weren't
errors in the logs, and after verifying that, I exported config.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5840

### Verification Process

* Visit: /admin/reports/status and verify we are on Drupal core version 8.7.1
* The site passes with all green tests
* The site functions exactly as it currently does but on the new Drupal core version

### Drupal 8.7.0 Release Notes

https://www.drupal.org/project/drupal/releases/8.7.0

The Drupal 8.7.1 release notes are mostly uninteresting and really only include the fix for SA-CORE-2019-007: https://www.drupal.org/SA-CORE-2019-007

### CODE REVIEW

**Comment by robpblake** [comment]
@jordanpagewhite I'd be keen to understand if this change has any impact on us running `drush -y --entity-updates updb` when we bootstrap Drupal:

> Drupal core no longer provides support for automatic entity updates

[Drupal 8.7.1 Release Notes](https://www.drupal.org/project/drupal/releases/8.7.0)

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
RHEL hello world download timed out again. Is that a concern?

**Comment by robpblake** [comment]
@LightGuard Yes. I think either the test is outdated or functionality changed. Either way it doesn't work.

**Comment by alistairmc** [comment]
I tested the hello world page in my PR it's taking over 60secs to return, I am in the process of increasing the timeout to see if the test will pass. If not I think I will need to update the rhel download test functionality

**Comment by alistairmc** [comment]
Just tested the extra wait, still no success.

**Comment by robpblake** [comment]
@jordanpagewhite If you think we no longer need it, could you update the Drupal boot sequence to remove the `--entity-updates` call from our `drush` command?

The files in question are:

- legacy envs: `_docker/drupal/drupal-filesystem/scripts/drupal_install_checker.rb`
- Managed Platform: `_docker/drupal/managed-platform/ansible/bootstrap-drupal.yml`

cheers,

Rob

**Comment by jordanpagewhite** [comment]
@robpblake I addressed the `--entity-updates` you mentioned in your review, and I found 1 instance in our `tests/` directory.

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@jordanpagewhite It looks like there is a lot of dangling Drupal configuration to import on this one. Take a look at: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37941/admin/config/development/configuration

**Pull request closed without merging**
