### PR TITLE
[BLOCKED] Rhd-1314 - CDK featured Downloads DEPENDANT ON DEVELOPER-1792+RDH-1381

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
expected fail, chrome drive not available

**Comment by paulrobinson** [comment]
Can you close this PR, and Re-open when the blockers have been resolved, and thus it's ready for review and merge?

**Pull request closed without merging**
