### PR TITLE
Style fix for Hello World and Topic pages

### PR DESCRIPTION
**Pull request by adelasofia**
Fixes issue with active tab having a bottom margin: see [screenshot 1](https://www.dropbox.com/s/xx0ypee5b9xvz4a/Screenshot%202018-02-23%2010.40.14.png?dl=0) , [screenshot 2](https://www.dropbox.com/s/eqx0hlrvrgu4127/Screenshot%202018-02-23%2010.43.01.png?dl=0)

**To review go to:**
- /products/devsuite/hello-world/#fndtn-windows
- /products/webserver/hello-world/

Also fixes issue with Topic pages not displaying font colors correctly: see [screenshot](https://www.dropbox.com/s/uhudd1hp2s9w1gz/Screenshot%202018-02-23%2012.01.41.png?dl=0)

**To review go to:**
- /topics/devops/

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
@LightGuard Products with tabs on their hello world pages. These are two examples:
- /products/devsuite/hello-world/#fndtn-windows
- /products/webserver/hello-world

for the Topic page I fixed /topics/devops/ so the text in the orange and green boxes is white

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
