### PR TITLE
Update mobile customer portal link

### PR DESCRIPTION
**Pull request by lincolnthree**

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@RubyGemTSL Not sure what's going on with that test, I manually verified it, works as expected.

**Comment by RubyGemTSL** [comment]
@LightGuard the failure is not related to this PR.

There is an intermittent failure on the registration page that I have been struggling to reproduce manually. Sometimes the validation message is not shown at field level, but instead displayed at the top of the page! I have also seen an occurrence where this test successfully registers a customer without entering all required fields. I'll continue to try and reproduce this, and raise an issue with Marks team.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Blinkr failed that time! Bundler error!

retesting

**Comment by LightGuard** [comment]
Going to call this one good and merge

**Pull request merged**
