### PR TITLE
[DEVELOPER-5692] update default paddings rich text

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5692
https://issues.jboss.org/browse/DEVELOPER-5693

### Verification Process
Review page assembly type padding test rich text assembly for no-padding option classs 
check h2 styles and assembly padding

once this is live we will need to remove the no top space class from the 'The Latest' section as this is now too close to the above component, I have made this change in this pr as a test

### CODE REVIEW

**Comment by sjcox-rh** [comment]
@alistairmc This looks good! UX Approved

**Comment by alistairmc** [comment]
@KamiQuasi can you take a look at this PR when you are online, Thanks

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
@KamiQuasi This has the right number of files changed now since the new merge, do you think you will get a chance to review and merge?

**Pull request merged**
