### PR TITLE
DEVELOPER-3312 - Drupal Publication Workflow

### PR DESCRIPTION
**Pull request by LightGuard**
This allows for a more fine-grained workflow:

Create Draft -> Review (Request Review)
Draft -> Publish (Publish)
Review -> Create new Draft (Back to Draft)
Review -> Review (Keep in Review)
Review -> Publish (Publish)
Publish -> Archive (Archive)
Publish -> Draft (Create New Draft)

It is possible for us to create more states and transitions as needed.

This also reworks the permissions a bit to follow the workflow.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by paulrobinson** [comment]
@RubyGemTSL are these SO failures something you are already investigating?

**Comment by robpblake** [comment]
@paulrobinson This was last tested 7+ days ago, recommend we re-test.

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@paulrobinson the SO tests should be fixed now. As Rob said lets see how the retest goes.

**Pull request merged**
