### PR TITLE
DEVELOPER-4245 Added loading image in search results

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4245 - Add loading image while waiting for results](https://issues.jboss.org/browse/DEVELOPER-4245)

Requirements:
The amount of time to return search results can be multiple seconds. There should be an image showing that loading is happening so users do not get confused.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@KamiQuasi @adelasofia I don't see the loading spinner on the site preview, do you?

**Comment by KamiQuasi** [comment]
@RubyGemTSL I'm working on some comments for the PR, but yeah because of the way we're loading records I don't think the class change is showing up during the actual data load.

**Comment by RubyGemTSL** [comment]
Thanks Luke. OK i'll hang fire on testing until it's ready. Sorry for treading on your toes :)

**Pull request closed without merging**
