### PR TITLE
[PREVIEW] DEVELOPER-1795 Added search page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
docker build

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Replaced by https://github.com/redhat-developer/developers.redhat.com/pull/722

**Pull request closed without merging**
