### PR TITLE
BRMS product overview page improvements

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
@eschabell @paulrobinson Here is the new PR for the BRMS Overview page's improvements.

**Comment by paulrobinson** [comment]
@adelasofia have you checked that this looks right in all the places that use _partials/video_thumb.html.slim?

**Comment by adelasofia** [comment]
@paulrobinson it's good :+1:

**Comment by paulrobinson** [comment]
Great, can you squash, then I'll merge.

**Pull request merged**
