### PR TITLE
Add Articles example page

### PR DESCRIPTION
**Pull request by mindreeper2420**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-83

### Verification Process
On the demo site, visit the `pages/articles` page. You should see the demo for the new Articles page, which includes the proper positioning and layout of the Series Assembly.

### Demo Link
A demo of the work can be found here: https://rhd-frontend-demo.netlify.com/pages/articles/

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@alistairmc @jordanpagewhite is the PR okay to merge? I missed it before I went on PTO.

**Comment by jordanpagewhite** [comment]
@mindreeper2420 I asked @alistairmc to review this PR  tomorrow when he has a chance. Can you resolve the merge conflict when you have a chance? Thanks

**Comment by alistairmc** [comment]
@mindreeper2420 @jordanpagewhite  took a quick look Adam you will need to get latest and resolve any conflicts before I can review this as there seems to be some crossover in the css cleanup I did to remove rhdp2.css file. Give me a shout if you need any help to resolve the conflicts

**Comment by mindreeper2420** [comment]
@alistairmc @jordanpagewhite The build is failing, but nothing really changed from the last update. I rebased master onto this branch and just had an issue where the highlighter styles weren't found. The work for this PR only added code to the articles, as well as a new article example page.

**Comment by alistairmc** [comment]
rebuild this please

**Pull request merged**
