### PR TITLE
[DEVELOPER-5731] change cdk to 3.7.0-2

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5731

### Verification Process
go to cdk download and check 3.7.0-2 is downloaded

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by alistairmc** [comment]
the failing test seems to be a login issue, going to retest

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Pull request merged**
