### PR TITLE
[DEVELOPER-4375] Add indent/outdent to WYSIWYG

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This adds indent/outdent functionality to the CKEditor WYSIWYG Red Hat
text format. This includes adding the actual buttons in the text format
of the editor and installing and configuring the ckeditor_indentblock
Drupal contrib module.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-4375

### Verification Process

* Go to any Article (for example) node edit form

* In the Body field, create something that looks like this using the new indent button to the far right of the WYSIWYG to indent some text blocks

Screen Shot 2019-03-11 at 3 34 49 PM

* Submit the node edit form to persist your changes and view the node you just edited. It should look something like this

Screen Shot 2019-03-11 at 3 34 57 PM

### CODE REVIEW

**Comment by alistairmc** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@jordanpagewhite I'm getting CKEditor script errors on pages that prevent the text editor from showing up.
```
Failed to load resource: the server responded with a status of 404 (Not Found)
ckeditor.js?v=4.10.1:248 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "indentblock" was not found at "/plugin.js?t=po9jtm".
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.<anonymous> (ckeditor.js?v=4.10.1:248)
    at a (ckeditor.js?v=4.10.1:244)
    at Array.n (ckeditor.js?v=4.10.1:244)
    at w (ckeditor.js?v=4.10.1:244)
    at HTMLScriptElement.CKEDITOR.env.ie.b.$.onerror (ckeditor.js?v=4.10.1:245)
```

**Comment by jordanpagewhite** [comment]
@KamiQuasi Ah, thank you Luke. I see the issue now. The libraries directory isn't tracked with Git it seems, so a library that I had downloaded to my local env didn't make it into the PR. I wonder if I should download that with Composer perhaps. I will take a look at that. Thank you.

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by LightGuard** [comment]
merge conflict :(

**Comment by robpblake** [comment]
@jordanpagewhite What's the status on this one?

cheers,

Rob

**Comment by jordanpagewhite** [comment]
@robpblake I just resolved the merge conflict yesterday. It is ready for review whenever @KamiQuasi and/or @LightGuard get a chance.

**Comment by LightGuard** [comment]
Seeing the same thing @KamiQuasi was. Can't successfully load up CKEditor

**Comment by jordanpagewhite** [comment]
@LightGuard Sorry about that. I tricked myself on my local environment by already having a file downloaded that wasn't tracked by git.

Anyway, I am not downloading the CKEditor Indentblock plugin file with our composer.json and composer.lock file. I just tested it out in the PR environment and verified the functionality.

**Comment by jordanpagewhite** [comment]
@LightGuard or @KamiQuasi This is now ready to review whenever either of you have an opportunity. Sorry for the false starts previously. I wasn't downloading the CKEditor plugin properly with Composer, and I tricked myself into thinking it was working because of an untracked file on my local environment.

**Comment by LightGuard** [comment]
Needs and update

**Pull request merged**
