### PR TITLE
DEVELOPER-3817 - Move AngularJS app scope to parent div for product get started

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3817

Resolves an issue where Angular doesn't like having multiple ng-app directives on a single page.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
Downloads are broken in PR environment. Email sent to David.

**Comment by KamiQuasi** [comment]
@RubyGemTSL thanks for the heads up, I didn't think I had broken things, but wasn't 100% certain.

**Comment by RubyGemTSL** [comment]
I don't think we should hold on merging PR's unless you're actually working on something related to downloads. I'm still waiting for an answer as to what's happening with the failures.

**Comment by KamiQuasi** [comment]
@LightGuard @adelasofia or @Dantheman720 if one of you wants to check my changes and merge, Tiffany gave approval for the successful utilization of the drop-down on multiple tabs this morning.

**Pull request merged**
