### PR TITLE
[DEVELOPER 5543 v2 & DEVELOPER 5541] Update search filters and remove Dev suite

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5541 - items 1 and 4 ( 3 and 4 are in a new story )
https://issues.jboss.org/browse/DEVELOPER-5543

### Verification Process
Search page products filters should be no Dev Suite and ".NET Runtime for Red Hat Enterprise Linux" changed to ".NET Core".

### CODE REVIEW

**Comment by alistairmc** [comment]
@adelasofia this is ready to review and merge if you are ok approving it.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
This is a change to the search filters, hence why the search filter test is failing. No need to retest as it won't make the test pass :)

@alistairmc i'll have a look and raise PR on here with a fix to the test. Probably just an xpath or css change.

**Comment by robpblake** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
Tests are working again, this seems ok now @adelasofia can you review please

**Pull request merged**
