### PR TITLE
[HOLD for Monday Oct. 31] DEVELOPER-3626 New .NET Core RHD Hero

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
@LightGuard Any idea why in the site preview I'm getting a combination of the current homepage hero and the new one I'm trying to push? The preview has the right CSS but the HTML was not updated

**Comment by robpblake** [comment]
@adelasofia I suspect that you'll need the change in #1556. There was an update a while back to stop Awestruct pushing in the homepage into Drupal so I suspect your changes to the HTML are being ignored. @LightGuard can probably confirm this better than I, but that is my suspicion.

It may be easier to for to apply the changes in #1556 as part of your PR.

cheers,

Rob

**Comment by adelasofia** [comment]
@robpblake thank you!

**Comment by adelasofia** [comment]
Approved by James -- This should be merged on Monday Oct. 31st

**Comment by robpblake** [comment]
@adelasofia I see a broken image on the following page: http://stumpjumper.lab4.eng.bos.redhat.com:33820/promotions/dot-net-core

**Comment by robpblake** [comment]
@adelasofia Ignore my previous comment. It is because we're not pulling the images down from production into the pull request environment.

**Pull request merged**
