### PR TITLE
Developer 2387 docker prs

### PR DESCRIPTION
**Pull request by ollyjshaw**

### CODE REVIEW

**Comment by paulrobinson** [comment]
is this ready to merge?

**Comment by ollyjshaw** [comment]
Hang fire thanks, I need a retest.

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/XXX-IN-PROGRESS-developers.redhat.com-pull-request-builder-docker/92/console
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-pull-request-builder/649/console

Good to go @paulrobinson

**Pull request merged**
