### PR TITLE
DEVELOPER-2443 Review/fixed 'cdk_beta' merge issues

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
I only found a minor style issue, it looks good other than that :+1:

**Comment by adelasofia** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
Failing build due to being a CDK branch PR. Added tickets to help with this:
https://issues.jboss.org/browse/DEVELOPER-2459
https://issues.jboss.org/browse/DEVELOPER-2460
@paulrobinson

**Pull request merged**
