### PR TITLE
RHD-559 Use Searchisko v2 on "Buzz" pages on developers.redhat.com

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by lkrzyzanek** [comment]
I guess it failed because of not running http://dcp-searchisko.rhcloud.com is it correct ? The dcp-searchisko is up now.

**Comment by paulrobinson** [comment]
retest this please

**Comment by lukas-vlcek** [comment]
I am thinking about putting `_config/site.yml` and `javascripts/namespace.js` files into separate PR and merge it ASAP (as long as it only adds new configuration it should not break current production). The thing is that other Searchisko 2 switching PRs (like https://github.com/redhat-developer/developers.redhat.com/pull/324) can benefit from this.

@paulrobinson @wesbos @lkrzyzanek WDYT?

**Comment by paulrobinson** [comment]
@lukas-vlcek agreed, that sounds sensible.

**Comment by lukas-vlcek** [comment]
@paulrobinson ok, I will prepare new PR for `_config/site.yml` and `javascripts/namespace.js` files only.

**Comment by paulrobinson** [comment]
Closing this PR, as @lukas-vlcek will combine my changes into his DCP 2 PR for Friday.

**Pull request closed without merging**
