### PR TITLE
[DO NOT MERGE] [RHDENG-2753] Integrate Drupal with SSO login for content editors

### PR DESCRIPTION
**Pull request by robpblake**
This PR introduces SSO sign-in for content editors. In the first instance it is all direct members of  the RHDP dev team that will be asked to try this out.

This PR makes the following changes to Drupal:

- It incorporates the changes from #2796 to prevent SSO failures from caching of HTTP GET requests
- It installs and configures integration with KeyCloak for local dev and PR environments
- It installs and configures an active session limit for each user
   - Each user may now have a maximum of 3 active sessions

**Please note this PR is targeting `stage` branch so that we can test things there first.**

### JIRA Issue Link
* https://issues.jboss.org/browse/RHDENG-2753

### Verification Process

* Build should go green
* Verify that there are no pending configuration changes to import in the Drupal Admin interface
* Verify that the session limit module is installed and maximum permitted sessions is 3 per-user
* All of the following team members must confirm that they can login with their RHDP stage account:
  * @paulrobinson 
  * @robpblake 
  * @RubyGemTSL 
  * @LightGuard 
  * @jordanpagewhite 
  * @alistairmc 
  * @adelasofia 

#### For PR reviewers

Please visit the `/user/login` page for Drupal on this PR. You'll notice that there is a "Login with your developer account" section. Can you please test that you can log in using the account that you can login with for the front-end at https://developers.stage.redhat.com.

The account you are using for https://developers.stage.redhat.com must have an email address that matches your account in Drupal. For everyone this should be your `@redhat.com` address.

Once you're logged into Drupal, please just have a small play around e.g. edit some content, try and change some settings just to make sure things are working as expected.

Any questions, please let me know. Can you also comment or +1 this PR once you've confirmed that you can login.

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks like you have stuff in here that's in a different PR for the guzzle caching.

**Comment by LightGuard** [comment]
This does not seem to be working. I log in, it sends me back to /user/login. I'm not actually logged into Drupal. If I try to go to /admin it tells me I'm not authenticated.

**Comment by jordanpagewhite** [comment]
Yes, it looks like some code for the Guzzle caching has made it into this PR. I think that the js-e2e-tests fail is a false negative. I cannot authenticate to developers.stage.redhat.com at all from this PR Drupal environment. When I try to authenticate, I receive this error:

screen shot 2019-01-24 at 11 03 06 pm

**Comment by jordanpagewhite** [comment]
I tried your rblake@redhat.com account to see if I would receive the same error while authenticating, but I received this error instead:

screen shot 2019-01-24 at 11 09 52 pm

**Comment by robpblake** [comment]
@jordanpagewhite / @LightGuard I've bought in the Guzzle work into this PR so that we can test it. Without it the SSO functionality is broken, so it's intentional for it to be there.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
I just tested this out, and I was successfully authenticated to the correct Drupal account after creating a staging Keycloak account with my redhat.com email address.

screen shot 2019-01-28 at 7 36 48 am

As you can see in the screenshot (above), after creating the account on staging Keycloak, I was redirected and successfully authenticated to Drupal, but I was not authenticated to Keycloak on developers.redhat.com. The text/icon in the top right corner of the site still says 'Log in', whereas in a previous state of this work, it changed to display the username showing that you are successfully logged into Keycloak.

I am not sure if this is an intentional change or not, but I thought I should point it out.

**Comment by robpblake** [comment]
@jordanpagewhite That is fine as the front-end of Drupal is using a different `client id` to talk to Keycloak and the Keycloak configuration for that client won't permit a `redirect` URL to the build server host.

**Comment by LightGuard** [comment]
retest this please

**Pull request closed without merging**
