### PR TITLE
[DEVELOPER 3270] Show Curated Link assembly title in template

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3270

### Verification Process
1. Go to /openshift in your browser like a visitor would
2. Open https://developers.redhat.com/openshift/edit in your signed-in Drupal authoring session via a different browser
3. Notice that on-page Titles for the Curated Link assemblies now display on page

Screen Shot 2019-11-07 at 8 21 00 AM

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
The titles are display, but I am going to wait until the tests pass to approve this PR

**Comment by robpblake** [comment]
retest this please

**Review by jordanpagewhite — APPROVED** [review]
This looks good to me

**Pull request merged**
