### PR TITLE
DEVELOPER-4678 - Reference keycloak JS from Keycloak server

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-4678

Drupal library changes to reduce some clutter in the html.html.twig file and also load the keycloak.js file straight from the auth server rather than build it in our scripts.

### CODE REVIEW

**Comment by LightGuard** [comment]
Good with these changes, @KamiQuasi any reason NOT to merge?

**Comment by lkrzyzanek** [comment]
Checking the https://developers-pr.stage.redhat.com/pr/2197/export/ (not sure if it's right place) but the HTML source have following:
<script src="auth/js/keycloak/">
It needs to be /auth/js/keycloak.js. Then it would leads to https://developers-pr.stage.redhat.com/auth/js/keycloak.js

**Comment by LightGuard** [comment]
@KamiQuasi  can we push this to the staging branch to try it there?

**Comment by lkrzyzanek** [comment]
Checking https://developers.stage.redhat.com and there is wrong link to the JS. There is ``<script src="auth/js/keycloak/"></script>``

**Comment by KamiQuasi** [comment]
@lkrzyzanek I'm checking with others to see if that know why the export would be stripping off the file extension. If we can prevent that in this case I think the change will work.

**Comment by lkrzyzanek** [comment]
Ok, thanks. btw. the right URL is: <script src="/auth/js/keycloak.js"></script> (the slash at the begin is needed as well otherwise it'll work only on homepage.)

**Pull request closed without merging**
