### PR TITLE
[READY!!] DEVELOPER-4427 Use production Download Manager in pull-request environment

### PR DESCRIPTION
**Pull request by RubyGemTSL**
[DEVELOPER-4427](https://issues.jboss.org/browse/DEVELOPER-4427)
Use production Download Manager in pull-request environment

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@Dantheman720 @LightGuard any idea where I'm going wrong here? I'm attempting to switch the PR environment site config to use production KC and DM. The site preview is still pointing to staging.

**Comment by LightGuard** [comment]
Did this work for you?

**Comment by RubyGemTSL** [comment]
@LightGuard downloads are correctly pointing to prod, however the login and register links aren't working. Any idea what I'm missing?

**Comment by RubyGemTSL** [comment]
@LightGuard I see that clicking on the download button correctly takes me to prod login page which is good. However I need the LOGIN|REGISTER links to also work for a sanity test on PR's.

**Comment by LightGuard** [comment]
There should be an option to change the key cloak location too

Jason Porter
Sent from Outlook<https://aka.ms/qtex0l> on iOS
________________________________

**Comment by RubyGemTSL** [comment]
@lkrzyzanek any idea why the login|register buttons aren't working? Am I missing a config change somewhere?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@lkrzyzanek - It looks like prod keycloak won't let us use it outside of prod environment?
@robpblake looked into this for me and found that the Keycloak.js wrapper is coded that way? Can you help?

**Comment by LightGuard** [comment]
There hasn't been any activity on this for nearly a month. Do we want to keep it open?

**Comment by RubyGemTSL** [comment]
it's still blocked @LightGuard.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
WOOHOOO!!! It's finally ready @LightGuard!

**Comment by RubyGemTSL** [comment]
Ignore the failing ruby tests. They are left over from before they were removed.

**Pull request merged**
