### PR TITLE
[PREVIEW] Site re-brand + Topics Integration Branch

### PR DESCRIPTION
**Pull request by wesbos**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@paulrobinson @wesbos I am going to be testing this branch as part of the x browser/device tests during this sprint. Shall I fix the current failing tests?

**Comment by RubyGemTSL** [comment]
@wesbos on the Technologies page there are two elements with the id of #infrastructure_management

Can we rename duplicate elements with the same id?

**Comment by RubyGemTSL** [comment]
I've updated the tests as part of my testing branch DEVELOPER-2540. Only 1 failure now due to duplicate id (as mentioned above).

There needs to be tests for the new nav menu and search functionality @paulrobinson ?

**Comment by paulrobinson** [comment]
@RubyGemTSL thanks for fixing these tests. Can you raise a PR on this branch so that Wes can pull in your fixes?

**Comment by RubyGemTSL** [comment]
@paulrobinson done.

I still think we should have some tests for the new functionality - I can help with this.

p.s. i'll also fix the dupe id mentioned above

**Comment by paulrobinson** [comment]
Thanks @RubyGemTSL. Please do create the nav tests. I don't think this is the right approach going forward, as the developers should write their own tests. However, given the timing constraints this week, it would be great for you to help.

**Comment by paulrobinson** [comment]
Retest this please

**Comment by wesbos** [comment]
latest is ready: http://it-developers-pr.stage.redhat.com/pr/754/build/184/

**Comment by wesbos** [comment]
Latest build: http://it-developers-pr.stage.redhat.com/pr/754/build/188/

**Comment by RubyGemTSL** [comment]
@wesbos there seems to be an issue with smaller resolutions (when Menu appears).

When I select 'Menu' I get the dropdown, however the links don't work.

1. Clicking on 'Topics' does nothing and no additional sub-menu items are displayed? 
2. Clicking on 'Technologies' links to 'Technologies page (and no additional sub-menu items are displayed?)
3. Clicking on 'Community' does nothing  (and no additional sub-menu items are displayed?)

**Comment by RubyGemTSL** [comment]
@wesbos can you merge the latest master?

**Comment by RubyGemTSL** [comment]
@wesbos is the latest 194?

If so, the mobile menu options don't work for me and @paulrobinson

**Comment by wesbos** [comment]
It says it's still building, but this link seems to work http://developers-pr.stage.redhat.com/pr/754/build/218/#

**Comment by ollyjshaw** [comment]
retest this please

**Pull request merged**
