### PR TITLE
[ON HOLD UNTIL ROB IS BACK] [DEVELOPER-5706, DEVELOPER-5707]: Stop running export on PR's

### PR DESCRIPTION
**Pull request by RubyGemTSL**
This PR removes the export process for the pull request pipeline now that we're on Managed Platform and the export no longer exists.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5706
* https://issues.jboss.org/browse/DEVELOPER-5707

### Verification Process
* The host to test environment variable in the [PR build job](https://redhat-dev-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Pull%20Requests/job/Pull_Request_Build/configure) has been changed 
from:
   - HOST_TO_TEST=https://developers-pr.stage.redhat.com/pr/${ghprbPullId}/export 
to:
   - HOST_TO_TEST=http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com
* The build should go green
* The status checks should not include the site export
* The acceptance tests should run and pass against Drupal.

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by jordanpagewhite** [comment]
Hey @RubyGemTSL is there anything blocking or preventing this?

**Comment by RubyGemTSL** [comment]
Hey @jordanpagewhite this cannot be merged until an agreement has been made with David and Lukas over at DEVELOPER-5672.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
I’ve just had a chat with Paul about that. Unfortunately, we have to wait until Rob is back. Lukas and David have some security concerns with the way we’re hosting the drupal environment. We also need a change to the Download Manager in order to handle the drupal host + port. It’s kind of out of my hands until Rob comes back in around 3 weeks

**Comment by dhladky** [comment]
Just to note: the overall consensus was the old way of using pr link will be used so no Download Manager changes will be necessary. The way how to overcome the problem was described in https://issues.jboss.org/browse/DEVELOPER-5672?focusedCommentId=13705009&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13705009

> I’ve just had a chat with Paul about this work. Unfortunately, we have to wait until Rob is back. Lukas and David have some security concerns with the way we’re hosting the drupal environment. We also need a change to the Download Manager in order to handle the drupal host + port. It’s kind of out of my hands until Rob comes back in around 3 weeks

**Pull request closed without merging**
