### PR TITLE
[DEVELOPER-5519] Add conditions for rendering of download links

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5519

### Verification Process
go to /books/java-persistence-hibernate

should now show a link to the external site rather than the download link.

If pdf link is blank external book.url is rendered if it is populated.
-->

### CODE REVIEW

**Comment by sjcox-rh** [comment]
@alistairmc I just checked this and the download button isn't showing an external link. Also, when selecting it, it just refreshes the page.

screen shot 2018-11-16 at 9 38 22 am

**Comment by sjcox-rh** [comment]
@alistairmc UX approved, looks good!

**Comment by alistairmc** [comment]
@KamiQuasi this is UX approved, can it be reviewed and merged please.

**Comment by alistairmc** [comment]
@adelasofia would you be able to merge this in Lukes absence, thanks.

**Pull request merged**
