### PR TITLE
DEVELOPER-4030 Added RHD hero for Summit

### PR DESCRIPTION
**Pull request by adelasofia**
DO NOT MERGE UNTIL MONDAY. APRIL 24TH

[DEVELOPER-4030](https://issues.jboss.org/browse/DEVELOPER-4030)

Mockup: http://design.jboss.org/redhatdeveloper/marketing/summit_2017/website/images/RHDP_hero_summit_r1v1.png

### CODE REVIEW

**Comment by adelasofia** [comment]
This has been approved. Will reopen this PR on Friday.

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@paulrobinson This has been approved by Mike and James. Good to go for tomorrow

**Pull request merged**
