### PR TITLE
DEVELOPER-3528 - Update download manager links for mobile

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3528

Forces correct browser behavior for download links to PDF files to prevent mobile PDF Viewer from opening them when user is not authenticated.

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
@KamiQuasi I don't really have any way of testing, this, do I? I don't have an android device.

**Comment by RubyGemTSL** [comment]
@LightGuard @KamiQuasi I'll test it for you.

**Comment by paulrobinson** [comment]
@lkrzyzanek has already approved that this works.

**Comment by paulrobinson** [comment]
The tests are now passing, as we updated the Docker Cheetsheet to use the correct download manager.

**Pull request merged**
