### PR TITLE
RHD-278 Index Red Hat Developer Blog

### PR DESCRIPTION
**Pull request by paulrobinson**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
The buzz query is returning no results: http://dcp2-searchisko.rhcloud.com/v2/rest/search?field=sys_url_view&field=sys_title&field=sys_contributors&field=sys_description&field=sys_created&field=author&field=sys_tags&field=sys_content_id&tag=softwarecollections&size=8&sys_type=blogpost&sortBy=new-create&from=0

I've not yet had chance to investigate why.

**Comment by LightGuard** [comment]
I'm not sure what this fix has to do with the proposed issue... bad naming?

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
@wesbos you might need to speak to @RubyGemTSL about how to write / change the acceptance tests for the new code you're adding. cc @paulrobinson

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retests this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
@paulrobinson can you rebase please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Replaced with another PR, which I'm about to raise.

**Pull request closed without merging**
