### PR TITLE
[DEVELOPER-5469] Hide tags from Article content type.

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5469

### Verification Process
- Link tags don't show at bottom of article nodes

### CODE REVIEW

**Comment by sjcox-rh** [comment]
@rogeralloymagnetic Just took a look and looks good from our end.  Will it be easy to pull tags back in whenever we're ready?

**Comment by rogeralloymagnetic** [comment]
Yes, I just moved it to hidden for that content type. So, it's only a
matter of moving it out from hidden and re-exporting the configs.

**Comment by sjcox-rh** [comment]
@rogeralloymagnetic perfect, good to know.

**Comment by LightGuard** [comment]
Is this ready to go?

**Comment by rogeralloymagnetic** [comment]
> Is this ready to go?

Looks like it has approval from UX and has passed all tests, so it should be good to go.

**Pull request merged**
