### PR TITLE
RHD-1530: Add RHEL 6 FAQs to no-cost RHEL FAQ article

### PR DESCRIPTION
**Pull request by rctrh**

### CODE REVIEW

**Comment by LightGuard** [comment]
this is ok to test

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by rctrh** [comment]
What's needed to get fix the failing tests?

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
It's timing out communicating with another system, known issue. It'll go green eventually.

**Comment by LightGuard** [comment]
@rctrh Green now

**Pull request merged**
