### PR TITLE
CDK 2 Beta Launch

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by ollyjshaw** [comment]
This PR and 835 seem to be holding on to problematic volumes. To fix this for now:

1. Close the PR
2. Open a new PR (ensure that the number is different, don't reopen 835/835)

@paulrobinson @adelasofia

**Comment by paulrobinson** [comment]
Replaced by: https://github.com/redhat-developer/developers.redhat.com/pull/844

**Pull request closed without merging**
