### PR TITLE
DEVELOPER-3377 - sys_url_view should point to the abstract/purchase page

### PR DESCRIPTION
**Pull request by Dantheman720**
@paulrobinson @LightGuard  - Waiting on https://github.com/awestruct/aweplug/pull/117 to be merged. Then this can be rebased and merged.

### CODE REVIEW

**Comment by LightGuard** [comment]
Book links in search aren't going anywhere, @Dantheman720

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Not seeing this work in http://developers-pr.stage.redhat.com/pr/1346/build/1944/resources/ when I search for books.

**Comment by Dantheman720** [comment]
@LightGuard - I think it's the query here. I'll take a look into adding a custom query for it. The field=sys_url_view portion isn't doing anything. You can see the proper urls if you use http://dcp.stage.jboss.org/v2/rest/sys/es/search/data_jbossdeveloper_book/_search

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 I still can't click on any links for books.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by LightGuard** [comment]
Okay, I've seen it work. Assuming all the tests are still green I'll go ahead and merge

**Comment by Dantheman720** [comment]
@LightGuard Thanks!

**Pull request merged**
