### PR TITLE
DEVELOPER-3583 - Drupal Topic - Blue card body text size needs to match pre-drupal page versions

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by paulrobinson** [comment]
This doesn't look right to me: http://developers-pr.stage.redhat.com/pr/1557/drupal/584/microservices/

**Comment by LightGuard** [comment]
Closing as according to @Dantheman720 there isn't any sort of engineering required for this.

**Comment by LightGuard** [comment]
Are we sure this is what we want to do? Stripping the tags seems a bit excessive. It's also very odd for the editors if say they make something bold or have a list or something in there and it's not formatted the way they expect.

**Comment by Dantheman720** [comment]
@LightGuard @paulrobinson - I think this quick css change would actually be better if we are looking to keep tags in place and whatnot.

**Comment by Dantheman720** [comment]
@MikGue - Please review this http://developers-pr.stage.redhat.com/pr/1557/drupal/621/microservices/

**Comment by Dantheman720** [comment]
@adelasofia @LightGuard - Mike G approved this. Can you approve/merge this? It's a minor css change to keep the blue cards consistent with the awestruct build.

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
