### PR TITLE
DEVELOPER-3973 Modified Cheat Sheet content type

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
Code looks good to me.

**Comment by LightGuard** [comment]
@adelasofia Who needs to sign off on this?

**Comment by adelasofia** [comment]
@LightGuard Tiffany, Emily and James. I've sent them a link to review it, I'll let you know when it is approved

**Comment by adelasofia** [comment]
@LightGuard this has been approved, ready to be merged 👍

**Pull request merged**
