### PR TITLE
updated RHEL DOC and API page

### PR DESCRIPTION
**Pull request by MikGue**
removed extraneous text and items.  Add tables in Languages section

### CODE REVIEW

**Comment by MikGue** [comment]
I forgot to mention - someone (Adela?) will need to enhance the tables as I wasn't quite able to insert the proper attributes.

**Comment by MikGue** [comment]
https://issues.jboss.org/browse/DEVELOPER-2662

**Comment by LightGuard** [comment]
@MikGue Looks like this is an octopus related merge, but it's being made against master. Please clarify.

**Comment by paulrobinson** [comment]
@LightGuard We merged the octopus branch in last week, so all commits are going into master now. I should have removed the Octopus branch at the time.

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@MikGue I'm not seeing the changes at http://developers-pr.stage.redhat.com/pr/964/build/715/products/rhel/docs-and-apis/ are you seeing them somewhere else?

**Comment by LightGuard** [comment]
@adelasofia Is this the one you're going to be taking over? If so, we can probably close this once you create your own PR?

**Comment by adelasofia** [comment]
Closing this. Replaced by [982](https://github.com/redhat-developer/developers.redhat.com/pull/982)

**Pull request closed without merging**
