### PR TITLE
OpenJDK links update

### PR DESCRIPTION
**Pull request by akashche**
Updated download link to 8u102-1 MSI, added missed link in the first paragraph.

### CODE REVIEW

**Comment by paulrobinson** [comment]
This is ok to test

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@akashche This looks good to me. Is there any more work to be done here or can this be signed off?

**Comment by akashche** [comment]
@robpblake , I think it can be signed off, thanks!

**Pull request merged**
