### PR TITLE
DEVELOPER-4205 - UI & design updates for the on-site search page

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
Who needs to sign off on this for it to be merged?

**Comment by Dantheman720** [comment]
@tiffanynolan - Can you review this when you have a moment? Thanks!

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@LightGuard - Tiffany is out until Thursday. Once she reviews, we should be good to go.

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@KamiQuasi There is a problem with the replacement icon for the X in the search bar; The svg icon is not showing up, see [screenshot](https://www.dropbox.com/s/c208mi4nakkaoqg/Screenshot%202017-08-30%2009.18.09.png?dl=0) but if I change the svg to another one in the same directory, with the same permissions it shows up, see [screenshot](https://www.dropbox.com/s/9qcex0s7bknbpip/Screenshot%202017-08-30%2009.19.43.png?dl=0). Do you know what might be causing this?

**Comment by Dantheman720** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
@Dantheman720 has this been approved

**Comment by adelasofia** [comment]
@Dantheman720 so sorry! I meant to cancel my comment and closed your PR instead 😢

**Comment by Dantheman720** [comment]
@adelasofia - Haha! No worries!

**Comment by LightGuard** [comment]
Is this good to go?

**Comment by tiffanynolan** [comment]
Not yet. I just added a few comments to the JIRA for some issues I found.

**Comment by Dantheman720** [comment]
@LightGuard - this should be good to go now. Would you like me to retest before merge?

**Comment by Dantheman720** [comment]
retest this please

**Pull request merged**
