### PR TITLE
Fixes DEVELOPER-3688 Get Started -> Hello World

### PR DESCRIPTION
**Pull request by LightGuard**
Please see https://issues.jboss.org/browse/DEVELOPER-3688 for full information.

We want to move the "Get Started" pages to be called "Hello World". We should also be able to keep the "Get Started" pages for now so we can do the redirects, then remove the old pages.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@tiffanynolan were you good with this?

**Comment by tiffanynolan** [comment]
Yes, I added a comment to https://issues.jboss.org/browse/DEVELOPER-3688, so feel free to publish this when ready.

**Comment by LightGuard** [comment]
Right, on Drupal they won't work, but in production, they should still exist (you'll go to the older Get Started page). Once these are in place we can then create the redirects to go to the new Hello World pages.

**Comment by LightGuard** [comment]
Looks like KC/DM tests are simply timing out.

**Comment by adelasofia** [comment]
@LightGuard Yep, I talked to Ian about it this morning. He said not to hold any PRs because of this.

**Pull request merged**
