### PR TITLE
DEVELOPER-4019 - Create thank you page component for media downloads

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4019

The best way I've found to test this is to try downloading the Developer Salary Report 2016:
https://developers.stage.redhat.com/download-manager/file/Developers_Salary_Report_2016_pdf

This will redirect you to this PR and you should notice the correct name and direct link.

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@KamiQuasi - This was approved by UX.

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by Dantheman720** [comment]
I added the thank you page back, so testing that link should work.

**Pull request merged**
