### PR TITLE
[HOLD] docker selenium fixes.

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
You may need to change the configuration on the Jenkins jobs as well. I know the pull request job takes care of port selection.

**Comment by LightGuard** [comment]
Is this ready to merge then, @RubyGemTSL?

**Comment by RubyGemTSL** [comment]
@LightGuard - From as discussion with Rob this morning - the issues yesterday were caused by the PR reaper being broken. I broke it by adding a newline in it. Rob has hopefully fixed that so fingers crossed. So port 4444 was tied to PR 977. Once that is up and running it would have been fine.

However this change was needed anyways - so to answer your question - yes its good to merge :)

**Pull request merged**
