### PR TITLE
DEVELOPER-3264 Red Hat Enterprise Linux Developer Suite refers to "Re…

### PR DESCRIPTION
**Pull request by paulrobinson**
…d Hat Developer Suite"

### CODE REVIEW

**Comment by LightGuard** [comment]
@paulrobinson Who needs to sign off on this?

**Comment by LightGuard** [comment]
Was there more to it than just this small change?

**Comment by paulrobinson** [comment]
Len signed off on the small change, but added in some other changes, which i think Lincoln needs to look at.

This can be merged. I'll move the issue over to the content team for the rest of the work.

**Comment by LightGuard** [comment]
Closing until Jenkins comes back

**Comment by paulrobinson** [comment]
retest this please

**Comment by robpblake** [comment]
@paulrobinson This one still good to merge?

**Comment by paulrobinson** [comment]
@robpblake yes please.

**Pull request merged**
