### PR TITLE
DEVELOPER-2666 - update DTS and SCL download pages

### PR DESCRIPTION
**Pull request by Dantheman720**
DEVELOPER-2666 - Octopus Changes: DTS and SCL download pages

### CODE REVIEW

**Comment by paulrobinson** [comment]
Asked @MikGue to review on https://issues.jboss.org/browse/DEVELOPER-2666

**Comment by Dantheman720** [comment]
Has this issue been resolved?

**Comment by paulrobinson** [comment]
@LightGuard, @Dantheman720: Why was this closed? Did it get replaced?

**Comment by Dantheman720** [comment]
I was wondering the same thing.  Was this closed by mistake?

**Comment by LightGuard** [comment]
Yeah, must have closed it by mistake, sorry.

**Comment by paulrobinson** [comment]
This is now a dup of https://github.com/redhat-developer/developers.redhat.com/pull/942

**Pull request closed without merging**
