### PR TITLE
Feature/developer 5214 404 page fix 

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
* Link to the JIRA ticket(s) this pull request solves
https://issues.jboss.org/browse/DEVELOPER-5214

### CODE REVIEW

**Comment by alistairmc** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@alistairmc, apologies. I'm still having issues with the the broken-link-checks. Bear with me, i'm working on it 😓

**Comment by alistairmc** [comment]
@RubyGemTSL what are the e2e tests run is this on the exported site?

**Comment by RubyGemTSL** [comment]
@alistairmc yes, the exported-site-preview

**Comment by RubyGemTSL** [comment]
Looks good from my side (the testing stuff) @alistairmc  👍

**Comment by alistairmc** [comment]
@LightGuard could you review this and merge if you are ok with it.

**Pull request merged**
