### PR TITLE
[HOLD UNTIL SUNDAY] RHD-1611 Added DevNation homepage hero

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
Approved. Hero must go live on Sunday: June 26th @ 12:00 p.m.

**Comment by paulrobinson** [comment]
Is that 12 noon in SFO?

**Comment by Dantheman720** [comment]
Yeah, that appears as noon pacific for me.

**Comment by adelasofia** [comment]
@paulrobinson I'm closing this PR, will reopen it closer to the date it needs to go live

**Comment by paulrobinson** [comment]
retest this please

**Pull request merged**
