### PR TITLE
Could not embed videos previously.

### PR DESCRIPTION
**Pull request by LightGuard**
You'll have to pick either an embedded or thumbnail view when you place
a media item.

To test this you'll want to try to embed a video using the media embed button. You'll see an option for how you want to embed the media.

### CODE REVIEW

**Comment by LightGuard** [comment]
Tests timed out

retest this please.

**Comment by adelasofia** [comment]
@LightGuard I've tried embedding a video on a product page, and while it does show the video in the editor, it does not show it on the preview mode or in the 'published' page

editor: https://www.dropbox.com/s/g892u7k3nvb17rd/Screenshot%202017-06-21%2015.26.22.png?dl=0

preview/published: https://www.dropbox.com/s/raxnrisopew193l/Screenshot%202017-06-21%2015.26.53.png?dl=0

**Comment by LightGuard** [comment]
@adelasofia preview doesn't work correctly on product pages. I recommend using an article.

**Comment by adelasofia** [comment]
Failing tests are unrelated.

**Pull request merged**
