### PR TITLE
[HOLD] DEVELOPER-3679 - Provide environment URLs to Front-end

### PR DESCRIPTION
**Pull request by KamiQuasi**
https://issues.jboss.org/browse/DEVELOPER-3679

Sets rhd_base_url and rhd_final_base_url in docker_compose file and then provides those via the Drupal Theme to the drupalSettings object in JavaScript

### CODE REVIEW

**Comment by LightGuard** [comment]
@KamiQuasi Are you still adding things to this?

**Comment by KamiQuasi** [comment]
@LightGuard looks good to me. Just put in a small change to remove trailing slashes, but I'm seeing both URLs properly in the PR environment (in developer console type "drupalSettings.rhd.urls" on either drupal or export). Will also need Drupal config values updated for Prod when this rolls out. Values to add would be rhd_base_url set to the Drupal instance domain (without protocol) and rhd_final_base_url set to "developers.redhat.com"

**Comment by KamiQuasi** [comment]
@LightGuard this one can also be merged today and config values put in to the production environment. See previous comment for keys and values.

**Comment by LightGuard** [comment]
@KamiQuasi Merged, give it about 30 minutes and double check everything in prod is working correctly, please.

**Pull request merged**
