### PR TITLE
Update topics.js

### PR DESCRIPTION
**Pull request by Dantheman720**
Enterprise-java pages also are affected by the planet jboss issues.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 Who's the reviewer? Also, what's the JIRA ticket for this?

**Comment by LightGuard** [comment]
@Dantheman720 Seeing `Cannot read property '0' of undefined` in the console on the topics pages now.

**Comment by Dantheman720** [comment]
@LightGuard This is related to https://issues.jboss.org/browse/DEVELOPER-2782.  Wasn't in the initial ticket, but Lincoln pointed out that the enterprise-java page was also having this problem.

**Comment by LightGuard** [comment]
@Dantheman720 Still need to fix the javascript though.

**Comment by Dantheman720** [comment]
@LightGuard Yeah, I'm not sure why I did that.  I had the fix done locally and then patched it with the wrong code.

**Comment by LightGuard** [comment]
@Dantheman720 who needs to sign off on this?

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
This is related to https://issues.jboss.org/browse/DEVELOPER-2782

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
This seems to be blocked by Blinkr as OS1 is offline.

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
I believe this is ready for sign off

**Comment by Dantheman720** [comment]
Yeah, I spoke with Lincoln about this on hipchat today. He was reviewing
it, but never stated whether or not fixes needed to be made.

**Comment by LightGuard** [comment]
Are we still waiting for Lincoln to give us the thumbs up @Dantheman720?

**Pull request merged**
