### PR TITLE
[DEVELOPER-3318] "Get Started" button on product pages gives a 404

### PR DESCRIPTION
**Pull request by LightGuard**
Please see https://issues.jboss.org/browse/DEVELOPER-3318 for full
information.

I've switched to building up the correct URL now instead of using a
relative URL. I also noticed the community links had the same problem,
so I fixed that here as well.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
Tested this locally in Drupal and it all seems to be working fine. Tested the site preview as well and again it seems to be working as expected.

**Pull request merged**
