### PR TITLE
DEVELOPER-2582 Fixed Page width for product pages on mobile

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@adelasofia sorry the tests will fail for this PR.

There is a crash in docker-chrome. I am waiting on a fix to to merged: https://github.com/redhat-developer/developers.redhat.com/pull/1000

CC @paulrobinson @LightGuard

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@adelasofia the tests are now failing as the Login page seems to be flaky today (extra slow to load) so the tests are timing out. I'll try retesting.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
hmmm random 500's on the login page:

http://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/developers.redhat.com-frontend-acceptance-tests/ws/_cucumber/screenshots/screenshot_2016-04-11-15-57-02.873.html

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
This was approved yesterday by Tiffany Nolan

**Comment by LightGuard** [comment]
Great, thanks!

**Pull request merged**
