### PR TITLE
Update index.html.slim

### PR DESCRIPTION
**Pull request by insectengine**
Change out the five promos on the home page to reflect the changes requested in DESIGN-826

### CODE REVIEW

**Comment by adelasofia** [comment]
This is ok to test

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by insectengine** [comment]
Approved.

**Comment by insectengine** [comment]
Carousel approved.

**Comment by LightGuard** [comment]
@adelasofia @insectengine I'm guessing this is good to go now?

**Comment by adelasofia** [comment]
@LightGuard Yes, just waiting on the last green check to merge

**Comment by LightGuard** [comment]
Blinker will take another 20 minutes, and I'm not seeing issues with what has been changed when I visit the site. Do we have a JIRA ticket for this?

**Comment by adelasofia** [comment]
@LightGuard All tests passed now and James approved. Jira is DESIGN-826. Merging it now

**Pull request merged**
