### PR TITLE
Feature/fix drupal config import

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Pretty sure the tests are not related, they're all keycloak tests... big surprise there :(

**Comment by Dantheman720** [comment]
+1 this worked for me as well.

@RubyGemTSL - The tests seem to be failing because of Keycloak issues again. I am happy to merge this once we get the green light.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
yeah there's a problem with keycloak. I also get a 500 locally. Feel free to merge given that there is 1 fail unrelated to this PR. However I'll still work on figuring out what is happening in the meantime.

**Comment by RubyGemTSL** [comment]
Didn't get a response in IRC. I've sent a mail to Vlastimil. In the meantime I will raise a PR that ignores the failing scenario until I can get diagnose the failure.

**Comment by RubyGemTSL** [comment]
see #1472

**Pull request merged**
