### PR TITLE
RHD-1412 Updated Markus' book page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
Retest this please

**Comment by paulrobinson** [comment]
Retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
Retest this please

**Comment by paulrobinson** [comment]
This PR might be permanently broken. It's possible that it's picking up old Docker data volumes. I created https://github.com/redhat-developer/developers.redhat.com/pull/855 to try it on a fresh env.

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Merged by a diff PR

**Pull request closed without merging**
