### PR TITLE
drupal works again

### PR DESCRIPTION
**Pull request by LightGuard**
Try this Paul

### CODE REVIEW

**Comment by paulrobinson** [comment]
Sorry Jason, needs a rebase :-(

I've been having trouble testing this today as I broke my Boot2Docker environment. Looks like it's back working now, so will try and test it today, or on Sunday.

**Comment by paulrobinson** [comment]
Replaced by https://github.com/redhat-developer/developers.redhat.com/pull/486.

@LightGuard can you review ^^^

**Comment by LightGuard** [comment]
`--run-the-stack` is fine for now, but once the pull requests I sent yesterday are merged in it should do a gen instead of a preview. Everything else looks good.

**Comment by paulrobinson** [comment]
Can you raise a PR for the change you mention in ^^^

**Pull request closed without merging**
