### PR TITLE
DEVELOPER-5436 - remove display:none from empty item to fix JS top calc

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
* Link to the JIRA ticket(s) this pull request solves
https://issues.jboss.org/browse/DEVELOPER-5436

### CODE REVIEW

**Comment by alistairmc** [comment]
Please Retest

**Comment by alistairmc** [comment]
@kadel can you merge this please once Gina has given the UX OK.

**Comment by gdoyle1** [comment]
@alistairmc This is approved. Thank you!

**Comment by alistairmc** [comment]
@KamiQuasi @adelasofia could this be reviewed and merged, the issue was the div was being set to display:none on :empty at this point the top can't be calculated since object is no longer painted, setting opacity instead and removing background and border, hides but is still painted and top can be correctly calculated.

**Pull request merged**
