### PR TITLE
DEVELOPER-4526 - Remove Archetypes, Quickstarts, BOMs, Ticket-Monster and Demos from Awestruct pipeline

### PR DESCRIPTION
**Pull request by Dantheman720**
To test: Download the export files from this PR and search for instances of Red Hat Developers. There should only be 4 remaining at this point (1 of which should remain on /video/youtube/3_ob3Pq7pyw/ and the other which I updated in prod).

### CODE REVIEW

**Comment by Dantheman720** [comment]
@LightGuard @KamiQuasi - Can you review this when you get the chance? I don't believe the acceptance test has anything to do with this. It's related to the alert box timing out.

We need this to be coordinated with RHDENG, so do not merge until they have updated their health checks.

**Comment by Dantheman720** [comment]
For further details on the DO NOT MERGE - https://issues.jboss.org/browse/RHDENG-1829

**Comment by LightGuard** [comment]
I'm good with this going through.

**Comment by RubyGemTSL** [comment]
@Dantheman720 that failing test is not related to your PR. I finally found the root cause of that failure, and was fixed as part of #2145.

**Comment by Dantheman720** [comment]
@RubyGemTSL - Good deal! Thanks!

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request closed without merging**
