### PR TITLE
RHD-1293 - Added case for infinite scroll doesn't apply to buzz

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
@wesbos can you review please.

**Comment by wesbos** [comment]
Code checks out, but can you rename that var from `noscroll` to `noScroll` - we camelCase our variables in the JS

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
@Dantheman720 the problem was that you didn't have permission to retest. you do now (along with the rest of the front-end team).

**Pull request merged**
