### PR TITLE
DEVELOPER-4793 Changes from Tiffany

### PR DESCRIPTION
**Pull request by LightGuard**
Updates that Tiffany made she wants added to prod.

JIRA: https://issues.jboss.org/browse/DEVELOPER-4793

testing: verify the changes Tiffany made in the JIRA are actually there.

### CODE REVIEW

**Comment by LightGuard** [comment]
@tiffanynolan watch here for the builds to finish and verify everything is correct.

**Comment by tiffanynolan** [comment]
@LightGuard Part of the build is failing. Can you take a look?

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
@tiffanynolan please comment here or in JIRA if this is good to go.

**Comment by LightGuard** [comment]
Once the tests pass, Tiffany has said this is good to go.

**Pull request merged**
