### PR TITLE
[DEVELOPER-5661] move download html into js

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5661

### Verification Process
test existing downloads should still work and should be able to download on any page with correct download url.

test download works on any page by grabbing the ?params from a download once signed in.

when pasted on any page you should be able to download and see the download message

### CODE REVIEW

**Comment by alistairmc** [comment]
@KamiQuasi can you take a look at this, its a quick hack to allow download on other page types.

Think in the future we should look to make this a download web component/assembly.

**Comment by alistairmc** [comment]
Ignore my last comment after last check in test are broken

**Comment by paulrobinson** [comment]
This needs a thorough review and thorough check when it's in production. We've had product download outages caused by bad pushes to this code.

**Comment by LightGuard** [comment]
Can we try this in staging first?

**Comment by alistairmc** [comment]
@LightGuard would make sense, whats the process for doing that?

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Pull request merged**
