### PR TITLE
Adding Rob Terzi to the secrets file

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by adelasofia** [comment]
Works for me 👍

**Comment by LightGuard** [comment]
@rct Will you mind pulling this down and seeing if it works for you, please?

**Comment by rct** [comment]
Sorry should have mentioned yesterday, I can decrypt successfully now.

**Comment by LightGuard** [comment]
If @rct can decrypt successfully now, we need to merge this. @adelasofia if you don't mind.

**Pull request merged**
