### PR TITLE
Update bad_text.rb

### PR DESCRIPTION
**Pull request by ollyjshaw**
Adding a PR as suggested by @LightGuard to fix the failing blinkr tests

### CODE REVIEW

**Comment by LightGuard** [comment]
ready to test

**Comment by LightGuard** [comment]
ok to test

**Comment by Dantheman720** [comment]
Can one of the admins verify this patch?

**Comment by LightGuard** [comment]
ok to test

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@ollyjshaw are all of the PRs being run through docker now?

**Comment by LightGuard** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Pull request merged**
