### PR TITLE
DEVELOPER-3833 Workflow emails

### PR DESCRIPTION
**Pull request by LightGuard**
Emails should be going out on workflow status changes. Putting this up to test, though it will probably go in as is.

See https://issues.jboss.org/browse/DEVELOPER-3833 for more information.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
Downloads are broken in PR environment. Email sent to @dhladky.

**Comment by RubyGemTSL** [comment]
Downloads are broken in PR environment. Email sent to David.

**Comment by RubyGemTSL** [comment]
I don't think we should hold on merging PR's unless you're actually working on something related to downloads. I'm still waiting for an answer as to what's happening with the failures.

**Comment by LightGuard** [comment]
Emails are going out, probably good to go with this.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Timeouts? ...... *sigh*

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
The KC DM tests will fail as the IT backends are broken. I wanted to investigate the failures in frontend tests however the job had gone from jenkins history. Retesting so I can see where we're at now.

**Comment by RubyGemTSL** [comment]
The tests that are failing should not be ran via the frontend profile! Something seems to have changed that has messed the tags up. They should be tagged with @kc. I'll fix.

**Comment by RubyGemTSL** [comment]
FYI #1766 fixes the issues with tags. But, like I say don't let the above failures stop you from merging if it's ready.

**Comment by robpblake** [comment]
@LightGuard There are merge conflicts on this PR now.

cheers,

Rob

**Comment by LightGuard** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 @KamiQuasi I think we're good now. KC/DM errors are non-related

**Pull request merged**
