### PR TITLE
[HOLD] DEVELOPER-3012 RHEL6 Node.js RHSCL 2.2 Beta TTHW

### PR DESCRIPTION
**Pull request by rctrh**
* created RHEL6 version of Node.js RHSCL 2.2 Beta TTHW since both RHEL6 and RHEL7 tabs are added to the page automatically.

### CODE REVIEW

**Comment by LightGuard** [comment]
this is ok to test

**Comment by rctrh** [comment]
Don't merge yet. Need help from @adelasofia to fix that tab links.

**Comment by LightGuard** [comment]
this is ok to test

**Comment by rctrh** [comment]
@adelasofia,  I can rename the pages from `-nodejs-bta` to `-nodejsbeta` if it makes it easier, doesn't break any existing regexes.

**Comment by adelasofia** [comment]
Closing this. Replaced by [#1090](https://github.com/redhat-developer/developers.redhat.com/pull/1090)

**Pull request closed without merging**
