### PR TITLE
DEVELOPER-4052 Included all content types and labels in search

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-4052](https://issues.jboss.org/browse/DEVELOPER-4052) - Update search results to name content types more specifically

### CODE REVIEW

**Comment by KamiQuasi** [comment]
@adelasofia the ones I could find seemed like they worked well. Anythings specific to check that may not be blatantly obvious?

**Comment by RubyGemTSL** [comment]
Looks like the stubbed data may need updating. I'm looking at this now.

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@adelasofia @KamiQuasi 

There is a problem with PR's currently. The Fuse page is missing causing these failures.
There is also three fails related to pagination on the Search page, I have tested the exported URL for this PR locally and it work's fine with updated fixtures. 

If this is ready to go and approved I feel confident that this isn't the cause of the issues.

**Comment by adelasofia** [comment]
@RubyGemTSL thank you!

This has not yet been approved by Paul, I'll leave a comment once it is approved and can be merged.

**Comment by RubyGemTSL** [comment]
@adelasofia I've updated the fixtures for this PR and raise a PR on your branch. Once you merge the tests should go green again now that other issues have also been fixed.

**Comment by adelasofia** [comment]
Thank you so much! @RubyGemTSL

**Comment by adelasofia** [comment]
This has been approved by Paul

**Comment by RubyGemTSL** [comment]
I can see lots of errors in the console unrelated to this PR, however I am just going to do a retest to verify that it is not the updated stubs causing this.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Pull request merged**
