### PR TITLE
[On Hold]Ensure a host is provided for the report

### PR DESCRIPTION
**Pull request by ollyjshaw**

### CODE REVIEW

**Comment by ollyjshaw** [comment]
@paulrobinson ready to merge

**Comment by paulrobinson** [comment]
Should we wait for Blinkr to finish, or will that fail?

**Comment by ollyjshaw** [comment]
@paulrobinson blinkr on OS1 had network issues and I had to cancel the build http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-blinkr/47/

I think we'd better hang fire until I can it back

**Comment by ollyjshaw** [comment]
retest this please

**Pull request merged**
