### PR TITLE
DEVELOPER-4415 - Add support for OS detection for the pervasive red DOWNLOAD buttons

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4415

To test: Visit the download page of each of the products and confirm that they still refer to the correct download.

Special cases:
DevSuite and CDK should now detect the platform that you are running (RHEL, MacOS or Windows). These should point to the downloads listed on https://docs.google.com/document/d/1m1WljXUSM8EonxaFKtDTmysxrWUnssH1PiShKZ6Mz1o/edit?ts=59c0d31b#

The e2e test failures are unrelated to this component

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@Dantheman720 failed on the flaky search test. Hopefully my PR #2110 will fix that.

**Pull request merged**
