### PR TITLE
RHD-765 Separated Register and Login links

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by paulrobinson** [comment]
It doesn't seem to be quite right yet. I did:

1. visited http://it-developers-pr.stage.redhat.com/pr/462/build/952
2. Clicked on 'login'
3. clicked on 'LinkedIn'
4. Noticed that the register button still displays, despite being logged in: https://www.dropbox.com/s/n6xhuub696lh2eg/Screenshot%202015-10-08%2010.01.27.png?dl=0

**Comment by lkrzyzanek** [comment]
Good catch @paulrobinson . I checked if register link correctly point to registration page.

@adelasofia the register link and divider needs to be hidden in same way as "login":
https://github.com/redhat-developer/developers.redhat.com/blob/master/javascripts/sso.js#L12

**Comment by adelasofia** [comment]
@paulrobinson @lkrzyzanek fixed it :smiley:

**Comment by lkrzyzanek** [comment]
@adelasofia Looks good to me now. Thanks!
@paulrobinson please do final test and merge it today if possible. I'm going to push redesigned login/registration page today.

**Pull request merged**
