### PR TITLE
DEVELOPER-4031 - [update] Adjust styles from feedback

### PR DESCRIPTION
**Pull request by KamiQuasi**
Adds some margin under the text box to space the new button properly, and adds a border to delineate the response section

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
I'm fine to merge this even if tests don't run or fail. It's only a css change.

**Comment by LightGuard** [comment]
Tests timed out

**Pull request merged**
