### PR TITLE
[SURGE 3060] Product Try-It Hero

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3060

### Verification Process
1. View Product Try-It Hero: `/products/codeready-workspaces`
2. Check that it matches FE: https://redhat-developer.github.io/rhd-frontend/components/product-try-it/

### CODE REVIEW

**Comment by rogeralloymagnetic** [comment]
Visual Styles issues documented here: https://github.com/redhat-developer/developers.redhat.com/issues/3103

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by rogeralloymagnetic** [comment]
rebuild this please

**Pull request merged**
