### PR TITLE
DEVELOPER-5045 - Product Community pages are empty

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-5045

### CODE REVIEW

**Comment by LightGuard** [comment]
This works, but the page refresh is bad. Hitting it on every request in FF.

**Comment by Dantheman720** [comment]
I don't seem to have that problem in FF or Chrome.

**Comment by adelasofia** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by adelasofia** [comment]
@LightGuard @Dantheman720 I'm seeing the page refresh. The URL changes to `https://developers-pr.stage.redhat.com/pr/2481/export/products/eap/community/?redirect_fragment=!filter-product%3Deap#error=login_required&state=70c74f14-7e78-4b2a-8e32-21377330d294` for a second and then goes back to the original URL.

**Comment by adelasofia** [comment]
Nevermind, its due to the expired cookie. Unrelated to this PR.

**Pull request merged**
