### PR TITLE
[DEVELOPER-2957] - Add valididation checks to registration page

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@lkrzyzanek to review the feature file before @LightGuard merges.

**Comment by lkrzyzanek** [comment]
I checked "files changed" and seems to be good although I'm not expert on these kind of validations.

**Comment by RubyGemTSL** [comment]
thanks @lkrzyzanek - it was really just a quick review to verify that I have implemented your suggestions in the google doc (https://docs.google.com/spreadsheets/d/1JRMJZEPCoCu279f3-R3ciZ2pzaOhygw-ac4KGPgN6V8/edit#gid=0). I have greyed out what is covered in this PR.

**Comment by RubyGemTSL** [comment]
@LightGuard reviewer happy - OK to merge

**Pull request merged**
