### PR TITLE
DEVELOPER-3681 - Investigate & fix failing Resource/Topics tests

### PR DESCRIPTION
**Pull request by RubyGemTSL**
…amically loading elements.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@paulrobinson - there is 14 white cards displayed on mobile devices. I assume there should be 16 as per desktop view? cc @KamiQuasi

**Comment by KamiQuasi** [comment]
@RubyGemTSL kind of a weird case, but the white card test was mostly just to make sure we had the minimum for the desktop of 16. The visibility of fewer on the mobile view is a function of the style sheet not the actual number of records returned. If we want to bump up the visible number to 16 we just have to increase the height of the container of the white cards.

**Comment by RubyGemTSL** [comment]
Thanks @KamiQuasi - we can either tag with @desktop to only run on desktop or fix for mobile? Do you have an opinion either way on this @paulrobinson ?

**Comment by paulrobinson** [comment]
I think it makes sense to show the same amount of card on mobile vs desktop. Any reason not to?

**Comment by RubyGemTSL** [comment]
OK I raised a bug https://issues.jboss.org/browse/DEVELOPER-3682

**Comment by RubyGemTSL** [comment]
pushed a @desktop only tag for the failing white card tests for mobile. Will be fixed as part of issue I raised above.

**Comment by RubyGemTSL** [comment]
@KamiQuasi any idea why there is only 12 white cards on the .NET topic page? (This is Desktop view too)

**Comment by KamiQuasi** [comment]
@RubyGemTSL it appears that the query being used has some unwanted %20 (space character) in some of the terms like "%20.net" let me see if I can adjust them and that should help.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@RubyGemTSL and @paulrobinson the "fix" was to log in to Drupal and remove the extra spaces from the .Net Topic's "Data Tags" field. The values there are apparently parsed exactly and additional space around the comma-delimited values causes the front-end to query using the space characters, which reduces the number of results.

**Comment by RubyGemTSL** [comment]
@KamiQuasi any idea how/when the changes will make it to PR environment as this is still failing

**Comment by paulrobinson** [comment]
The buzz tags on the .NET topic in production were not updated. I just updated them now. I suggest retrying this in about 3hours.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
@RubyGemTSL is this good to go now?

**Comment by LightGuard** [comment]
Looks like we're good. @RubyGemTSL ?

**Comment by RubyGemTSL** [comment]
@LightGuard also good - thanks!

**Pull request merged**
