### PR TITLE
[SURGE 3052] Rich Text Columns

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3052

### Verification Process
1. Create Rich Text Columns assembly on a node
2. Check all visual styles work as desired

Note: follow-up FE ticket created here: https://github.com/redhat-developer/rhd-frontend/issues/284

Example page: https://developer-preview-3147.ext.us-west.dc.preprod.paas.redhat.com/products/fuse2/overview

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
This is currently blocked by the Dark implementation in the rhd-frontend repo. It does not target the visual style class.

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/rhd-frontend/issues/291 has been resolved, so this issue/PR is unblocked

**Comment by jordanpagewhite** [comment]
@sjcox-rh and/or @gdoyle1 If you notice any style (or generally FE) issues in your review, would you please open follow-up ticket(s) in the rhd-frontend Q2FY2020 Design Surge board. I would prefer to not further block our Drupal tickets with FE feedback if possible given our proximity to the deadline.

**Review by sjcox-rh — APPROVED** [review]
Checked all the visual styles and everything looks good @jordanpagewhite

**Review by jordanpagewhite — APPROVED** [review]
Code changes look good to me

**Pull request merged**
