### PR TITLE
DEVELOPER-3179 - Swap HERO with 0 dollar RHEL promo

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 who needs to review?

**Comment by Dantheman720** [comment]
@LightGuard @insectengine - Hey James, can you review this when you get the chance?

**Comment by Dantheman720** [comment]
@adelasofia - Can you review/merge this when you get the chance? @insectengine said it looks good.

**Pull request merged**
