### PR TITLE
[HOLD] Testing Search against Staging DCP

### PR DESCRIPTION
**Pull request by paulrobinson**
The PR build of the DCP still doesn't contain rht_website data. Not sure why yet, so I've raised this PR which points to the main staging dcp (dcp.stage.jboss.org). 

This will make it possible to review the Search page functionality.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
Thanks @paulrobinson ! Will work on the tests today

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by wesbos** [comment]
Closing in favour of https://github.com/redhat-developer/developers.redhat.com/pull/1086 which now has the temp DCP url

**Pull request closed without merging**
