### PR TITLE
CDK docs fixes

### PR DESCRIPTION
**Pull request by rkratky**
Please merge to

- update a number of old links to CDK-related docs
- fix a bit of mark-up

### CODE REVIEW

**Comment by paulrobinson** [comment]
This is ok to test

**Comment by paulrobinson** [comment]
@rkratky Do these pages look as you would want:

* http://developers-pr.stage.redhat.com/pr/1640/export/products/cdk/resources/
* http://developers-pr.stage.redhat.com/pr/1640/export/products/cdk/overview/

If so, this looks ready to merge.

**Comment by LightGuard** [comment]
Waiting to hear from @rkratky before merging

**Comment by rkratky** [comment]
@paulrobinson @LightGuard Yes, the pages look fine.

**Pull request merged**
