### PR TITLE
Adela's Latest Octopus changes

### PR DESCRIPTION
**Pull request by paulrobinson**
I've updated the branch with master, trying to see if i can get the tests to pass.

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this now please

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@adelasofia - two tests need updating to reflect changes to download page. cc @paulrobinson

**Comment by RubyGemTSL** [comment]
see my comments on #905

**Comment by adelasofia** [comment]
@RubyGemTSL what do you mean by 'the products will need to be removed'?

**Comment by paulrobinson** [comment]
I guess the problem is that the downloads have changed between http://developers.redhat.com/downloads/ and http://developers-pr.stage.redhat.com/pr/925/build/578/downloads/.

**Comment by paulrobinson** [comment]
Actually it's the 'OTHER DEVELOPER RESOURCES' that have changed, from 3 to 2 items.

**Comment by RubyGemTSL** [comment]
@paulrobinson is correct.

**Comment by RubyGemTSL** [comment]
@adelasofia there are 15 products listed on this page: https://github.com/adelasofia/developers.redhat.com/tree/DEVELOPER-2472-new/products

Do the 15 still need to be there? as there are 13 downloads?

**Comment by paulrobinson** [comment]
Toolset and Collections come with the RHEL download (sort of) so don't warrant their own download link on /downloads. They are products in their own right, so do have product pages.

**Comment by RubyGemTSL** [comment]
OK. So what I was doing was scanning the products file for products that contain a 'download.doc'. Software Collections and developer toolset still contain a 'download.doc'. Do they need to be there? If not you can remove them and one of the failing tests should pass. This should be enough. If they need to be there for another reason I'll have a rethink

**Comment by paulrobinson** [comment]
I beleive these pages will be staying: http://developers.redhat.com/products/developertoolset/download/ and http://developers.redhat.com/products/softwarecollections/overview/, so another solution is needed.

**Comment by RubyGemTSL** [comment]
OK - it should really come from the rest endpoint now anyway. This was implemented a long time ago. Working on it now.

**Comment by paulrobinson** [comment]
@RubyGemTSL I merged your PR, but it's failing for another reason. Can you take a look?

**Comment by RubyGemTSL** [comment]
@paulrobinson will do

**Comment by adelasofia** [comment]
@paulrobinson keep in mind that [PR#922](https://github.com/redhat-developer/developers.redhat.com/pull/922) is ahead of this one in terms of content

**Comment by RubyGemTSL** [comment]
fixed tests and raised a PR on paulrobinson:DEVELOPER-2472-new

**Pull request merged**
