### PR TITLE
[DEVELOPER-2933] Publish content from Drupal

### PR DESCRIPTION
**Pull request by robpblake**
This pull request adds in the ability to publish a static export of the Drupal site. Please see the accompanying README.md for a full explanation of how it works.

### CODE REVIEW

**Comment by robpblake** [comment]
@LightGuard A review from you would be appreciated.

cheers,

Rob

**Comment by LightGuard** [comment]
Yep, I'll take a look

**Comment by LightGuard** [comment]
Rob, 

I had done `export DOCKER_HOST_IP=172.17.0.1`, but still no dice:

```
2016-06-10 17:27:34] INFO - Beginning export of content from Drupal at 'docker:32769'...
[2016-06-10 17:27:34] INFO - Invoking cron on host 'http://docker:32769/cron/rhd'. Please be patient this may take a while...
[2016-06-10 17:33:35] ERROR - Failed to export content from Drupal at 'docker:32769'
/usr/local/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /usr/local/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
        from /usr/local/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
        from /usr/local/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
        from /usr/local/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
        from /usr/local/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:1378:in `request'
        from /home/awestruct/developer.redhat.com/_docker/lib/export/cron_invoker.rb:29:in `block in invoke_cron!'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:853:in `start'
        from /usr/local/lib/ruby/2.1.0/net/http.rb:583:in `start'
        from /home/awestruct/developer.redhat.com/_docker/lib/export/cron_invoker.rb:27:in `invoke_cron!'
        from _docker/lib/export/export.rb:32:in `export!'
        from _docker/lib/export/export.rb:67:in `<main>'
Error running docker-compose
bundle exec ruby ./control.rb -e drupal-dev --export  6.14s user 0.83s system 1% cpu 6:11.74 total
```

**Comment by LightGuard** [comment]
Okay, second time it worked. Not sure what happened the first time, timed out waiting for cron maybe?

**Comment by LightGuard** [comment]
Doing it this way is dog slow though

**Comment by LightGuard** [comment]
```
[2016-06-10 18:07:35] INFO - (Console): HTTrack Website Copier/3.48-22 mirror complete in 14 minutes 13 seconds : 2696 links scanned, 2442 files written (93823586 bytes overall), 2442 files updated [95228524 bytes received at 111639 bytes/sec], 1525213 bytes transferred using HTTP compression in 3 files, ratio 24%
```

It worked, but it was really slow. I loaded up the export into a node http server and everything looks like it's working as it should.

**Comment by LightGuard** [comment]
I'm going to merge this and we can work on local dev tweaks next week.

**Pull request merged**
