### PR TITLE
DEVELOPER-3981 Fixed highlighting of search term

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by robpblake** [comment]
Needs #1861 merged before the build will go through.

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
See if we can get the tests to finish

**Comment by adelasofia** [comment]
@LightGuard this has been approved by James and Tiffany 👍

**Pull request merged**
