### PR TITLE
[DEVELOPER-5374] add / to default values

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5374

### Verification Process
add / to default values for canonical and og:url links

### CODE REVIEW

**Comment by alistairmc** [comment]
@LightGuard @KamiQuasi can you see any issues changing these value, seems to work fine from my testing?

**Comment by alistairmc** [comment]
@KamiQuasi @LightGuard could this be reviewed, please.

**Comment by LightGuard** [comment]
I'm good with this after UX signs off.

**Comment by alistairmc** [comment]
@tiffanynolan was ok with this approach, I am happy if you are to merge @LightGuard

**Pull request merged**
