### PR TITLE
Feature/developer 4975

### PR DESCRIPTION
**Pull request by alistairmc**
header image should now be available on https://developers.redhat.com/devnation2015/ and http://rhdp-drupal.stage.redhat.com/devnation2015

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
this is ok to test

**Comment by KamiQuasi** [comment]
retest this please

**Comment by alistairmc** [comment]
How do I check the exported site? http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37518/ looks ok

**Comment by KamiQuasi** [comment]
@alistairmc In the checks the "Details" link on the "exported-site-preview" item will take you to the export. I'll be merging when it goes green as when I change the URL for the image in the dev tools it looked good.

**Comment by alistairmc** [comment]
Thanks yes just tested, going to investigate to see if there is a way this can be improved for testing.

**Pull request merged**
