### PR TITLE
Updated title to 'OpenJDK'

### PR DESCRIPTION
**Pull request by dbhole**
Update the title to say "OpenJDK" instead of "Red Hat OpenJDK"

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by robpblake** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
FYI the old status is not cleared on your current PR's. Please ignore the old status: 'Drupal:Acceptance Tests' above.  New Pull-Requests will only include the new statuses:
- Drupal:FE KC/DM Acceptance Tests
- Drupal:FE Acceptance Tests

**Pull request merged**
