### PR TITLE
DEVELOPER-4050 - Identify premium content in search results

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-4050

@tiffanynolan @adelasofia - I used a padlock icon since I wasn't sure where to find the "key" icon. Do you know what icon I should be using instead?

### CODE REVIEW

**Comment by tiffanynolan** [comment]
@Dantheman720 I'll update the JIRA with more info. We def. need to use the key icon.

**Comment by Dantheman720** [comment]
@tiffanynolan Thanks!

**Comment by adelasofia** [comment]
@Dantheman720 The icon isn't showing up. You probably need to upload the image/icon to static.jboss.org and then use that generated link in the scss in order for it to work.
[screenshot](https://www.dropbox.com/s/l9frmiuuunduitc/Screenshot%202017-08-16%2008.29.35.png?dl=0)

**Comment by Dantheman720** [comment]
@adelasofia - Ah! Do you know how I can upload that?

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by tiffanynolan** [comment]
@Dantheman720 I still don't see the key icons. Can you let me know when they're uploaded?

**Comment by Dantheman720** [comment]
retest this please.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by Dantheman720** [comment]
@tiffanynolan - The icon should be showing up now.

**Comment by Dantheman720** [comment]
retest this please

**Pull request merged**
