### PR TITLE
DEVELOPER-3468 (Canonical URLs)

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
@LightGuard This approach won't work in consideration of the export process. After the export has run, the canonical tag will point to the Drupal URL rather than developers.redhat.com. I'd suggest if possible we simply hard-code the beginning of the canonical URL to be developers.redhat.com if possible, otherwise we're going to need to alter the export process to re-write the canonical URL value.

**Comment by LightGuard** [comment]
Yeah, I think I realized that after I submitted this PR, then did some digging into what this link tag actually does. IMO I still don't think we should do it. Check the JIRA for my reasoning.

**Comment by paulrobinson** [comment]
I'm closing this for now. We can re-open when we've consulted an SEO expert and we know what to do.

**Pull request closed without merging**
