### PR TITLE
DEVELOPER-2825 Outdented CDK on Technologies menu

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
Approved by Mike Guerette

**Comment by LightGuard** [comment]
This feels like there should be a test for it

**Comment by LightGuard** [comment]
There's no description or further info in the issue to mark this as done.

**Comment by adelasofia** [comment]
@LightGuard Not sure I understand what you mean, the issue was just a small style fix to CDK on the megamenu

**Comment by LightGuard** [comment]
It was hidden on mobile before, wasn't it?

**Comment by LightGuard** [comment]
K, I'll go ahead and merge, but we need to call out style changes in the process document as I'm sure they'll come up frequently. The JIRA issue probably should have at least had the name of the person to approve.

**Pull request merged**
