### PR TITLE
[DEVELOPER-5385] Add url decode loop and mobile message

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link

https://issues.jboss.org/browse/DEVELOPER-5385

### Verification Process

screen shot 2018-11-09 at 16 17 07
screen shot 2018-11-09 at 16 10 42

### CODE REVIEW

**Comment by LightGuard** [comment]
Looks like we're waiting for confirmation. @alistairmc I think some screenshots here would be useful as this isn't the easiest thing to setup to test.

**Comment by alistairmc** [comment]
@alistairmc  You are not kidding! will screenshot before I request any merge

**Comment by sjcox-rh** [comment]
@alistairmc This would only be the messaging for mobile, correct?

**Comment by sjcox-rh** [comment]
@alistairmc Since this is the experience for both desktop and mobile, how does the user download on a desktop? I would think that the inline notification for the mobile download would only appear on mobile based screen sizes. 

I feel like there is a CTA missing for desktop downloading and it should be under the download item name.

**Comment by alistairmc** [comment]
@sjcox-rh the second screenshot is desktop, its the existing functionality. The file will already be downloading when that screen is shown, the direct link is just a backup

**Comment by alistairmc** [comment]
@sjcox-rh the mobile message will only show on mobile devices

**Comment by sjcox-rh** [comment]
@alistairmc  Oh got it, sorry I double checked and now I understand the flow. Yes, this all looks good from a UX perspective.

Thanks!

**Pull request merged**
