### PR TITLE
Revert "Fixes for issues found during analytics training"

### PR DESCRIPTION
**Pull request by paulrobinson**
Reverts redhat-developer/developers.redhat.com#1696

### CODE REVIEW

**Comment by LightGuard** [comment]
Checking if this is the issue with downloads or not.

**Comment by LightGuard** [comment]
Yep, downloads work correctly on staging now. This is a pretty high priority issue, but I'll see if tests actually work.

**Comment by paulrobinson** [comment]
Agreed, looks to be working. Need to see it working with the export first, and check it doesn't break tests

**Comment by paulrobinson** [comment]
Export works too.

**Comment by RubyGemTSL** [comment]
@LightGuard @paulrobinson - FYI tests would not have caught this as download tests are still disabled due to export hold issues. There was also changes to the registration page at the end of last week that broke the registration tests.

**Comment by paulrobinson** [comment]
OK. I think we need to chase this up again. The lack of download tests is really hurting us

**Pull request merged**
