### PR TITLE
[DRUPAL] Topics and misc

### PR DESCRIPTION
**Pull request by LightGuard**
Mostly things to support topics here, but there's A LOT in the PR. I strongly recommend doing a squash merge for this :)

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@RubyGemTSL Mind taking a look? I've had multiple failures here on the unit tests, but they're dealing with login, which I haven't touched.

**Comment by RubyGemTSL** [comment]
@LightGuard - I noticed yesterday that something wasn't quite right with the staging environment. It is causing failures on login page, lots of timeouts, password reset email is not received after 60 seconds. I'll need to debug this morning and hopefully by the time you guys come back online i'll have everything figured out.

**Comment by LightGuard** [comment]
@RubyGemTSL Great, thanks for looking into it!

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
Anyone that wants to test this (and I'd like to at least get one :+1: from someone) please merge this branch (or pull it down) and cd into the `_docker` directory and execute `bundle exec ./control -u --run-the-stack` @RubyGemTSL @Dantheman720 @adelasofia @paulrobinson @robpblake

**Comment by Dantheman720** [comment]
Will do!

**Comment by Dantheman720** [comment]
Looks good to me +1

**Comment by Dantheman720** [comment]
This may help with review: https://www.dropbox.com/s/uwoix6ciwxeo1u7/DrupalTopic.mp4?dl=0

**Comment by LightGuard** [comment]
I've confirmed the javascript issue (vjbug issue) is fixed -- DEVELOPER-2796

**Comment by adelasofia** [comment]
Looks good to me too 👍

**Pull request merged**
