### PR TITLE
Check if searchisko is properly accepting requests

### PR DESCRIPTION
**Pull request by LightGuard**
Also some minor syntax changes and not killing containers all the time

### CODE REVIEW

**Comment by LightGuard** [comment]
@rct Could you please merge this locally and try it out

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this pleas

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Timed out waiting for reply :( but everything else is good

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
HAHA!! IT WORKED!! BTW, @rct has said this fixes his issues as well.

**Comment by rctrh** [comment]
This resolved the problems starting/building the site on my Fedora VM with docker.  Hope to see this merged soon.

**Comment by robpblake** [comment]
@paulrobinson Can you review and merge please. I've had a look and it all seems reasonable and we can build on Jason's work for v1 release.

**Comment by rctrh** [comment]
@LightGuard is this waiting for more testing?

**Comment by LightGuard** [comment]
@rctrh No, this has been merged.

**Pull request merged**
