### PR TITLE
DEVELOPER-2900 for JBDS 9.1.0.GA, set current_version: 9.1.0.GA

### PR DESCRIPTION
**Pull request by nickboldt**
DEVELOPER-2900 for JBDS 9.1.0.GA, set current_version: 9.1.0.GA. 
Safe to merge -- bits are live in CSP now.

### CODE REVIEW

**Comment by LightGuard** [comment]
Apparently there are merge issues, please resolve master and this branch and re-push.

**Comment by nickboldt** [comment]
rebased and re-pushed. It's a one-line change in one file.

**Comment by LightGuard** [comment]
ok to test

**Comment by LightGuard** [comment]
Thanks @nickboldt! Once all the tests go green I'll go ahead and merge.

**Comment by LightGuard** [comment]
@nickboldt Are the download manager and documentation sites all current with this release? I'm seeing a lot of 404s in the blinkr report about this version.

**Comment by nickboldt** [comment]
@LightGuard no. As I said in the commit message, "DO NOT APPLY until content is in Download Manager / CSP next week".

Please wait until Monday. Will announce availability in DEVELOPER-2900.

**Comment by LightGuard** [comment]
Sorry, I must have skipped that part. Let us know when we're good to merge.

On Friday, April 15, 2016, Nick Boldt <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> no. As I said in the commit
> message, "DO NOT APPLY until content is in Download Manager / CSP next
> week".
>
> Please wait until Monday. Will announce availability in DEVELOPER-2900.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/1021#issuecomment-210726280>
>


-- 
Sent from Gmail Mobile

**Comment by nickboldt** [comment]
Safe to merge -- bits are live in CSP now.

**Pull request merged**
