### PR TITLE
DEVELOPER-5175 Fetch other static resources

### PR DESCRIPTION
**Pull request by LightGuard**
Attempting to use typhoeus for fetching the resources.

* https://issues.jboss.org/browse/DEVELOPER-5175 

* Find the og:image url in the homepage
* Verify it does not 404 in the export

### CODE REVIEW

**Comment by LightGuard** [comment]
Ha! I think I got it this time.

**Comment by LightGuard** [comment]
@RubyGemTSL I'm adding you, simply as someone else who knows enough ruby to review it.

**Comment by RubyGemTSL** [comment]
looks good 👍

**Comment by adelasofia** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@LightGuard OK if I merge?

**Comment by LightGuard** [comment]
Yeah, go ahead.

**Pull request merged**
