### PR TITLE
DEVELOPER-3746 Added active state to primary nav

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by KamiQuasi** [comment]
retest this please

**Comment by KamiQuasi** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
@KamiQuasi I made the changes we talked about. Should be working fine now 👍

**Comment by LightGuard** [comment]
Looks like failures are due to keycloak timing out.

**Comment by LightGuard** [comment]
@adelasofia Any reason not to merge this now?

**Comment by adelasofia** [comment]
@LightGuard Nope, please merge if you can

**Pull request merged**
