### PR TITLE
DEVELOPER-2830 CDK2 TTHW Beta5 Updates.

### PR DESCRIPTION
**Pull request by rctrh**
* Beta5 updates for CDK2 TTHWs
* Changes are independent of the new CDK get-started page.  (Can be merged with or without)

### CODE REVIEW

**Comment by paulrobinson** [comment]
this is ok to test

**Comment by paulrobinson** [comment]
Looks like there is an error with file /products/cdk/get-started-cdk2-ruby.adoc. Maybe @adelasofia can advise?

**Comment by rctrh** [comment]
@paulrobinson - This is the problem with Ruby code in a code block getting interpreted by something (awestruct?) that I mailed you about yesterday.

See commit 83d900e, I work around this by changing the Ruby code.

**Comment by paulrobinson** [comment]
Yes, @adelasofia and I think so. Although we don't know for sure. @adelasofia can you verify?

**Comment by LightGuard** [comment]
Are we okay to merge this or is work being done somewhere else? @adelasofia @rctrh

**Comment by rctrh** [comment]
I think we are OK to merge this.  It can go out now, before the get-started page that @adelasofia is working on in #977

**Pull request merged**
