### PR TITLE
DEVELOPER-4013 moderation transition tokens in email

### PR DESCRIPTION
**Pull request by LightGuard**
JIRA: https://issues.jboss.org/browse/DEVELOPER-4013

This isn't the easiest of things to test, unfortunately, well, at least not without spamming people. You to /admin/help/token to check the token is properly installed under 'Node'. You'll have edit one of the workbench moderation templates to also send it to administrators, or add yourself to the Content Team Role. Once that's done you'll need to go through and create some content or change and run it through the workflow pipeline. I suggest creating a new article and running it through the various workflow steps to ensure the emails are sent correctly, at least I think emails are sent from the PR environments. 

In the emails, you'll see a 'by <user name>' in the second sentence.

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
Looks like the status stuff isn't working correctly. @robpblake Are you happy with the approach we talked about? I still need to make one small change manually after everything is deployed: adding a role to two people that I can't (for whatever reason) make happen in an update.

**Comment by robpblake** [comment]
The acceptance tests are timing out on this for some reason. Maybe worth another re-test this please.

@LightGuard Does your comment above relate to #1884 ?

**Comment by robpblake** [comment]
retest this please

**Comment by LightGuard** [comment]
@robpblake Yeah commented on the wrong issue.

**Comment by LightGuard** [comment]
Please merge, if you're happy with it.

**Pull request merged**
