### PR TITLE
[RHDX-296] Feature/card labels are overpass and not the correct color

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-296

### Verification Process
Check the cards on the homepage have the correct font and colour for the label.

### CODE REVIEW

**Comment by alistairmc** [comment]
rebuild this please

**Comment by alistairmc** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Comment by alistairmc** [comment]
> For font-weight, would you prefer to use --rhd-global--FontWeight-Display--regular defined in typography/_weights.scss?
> 
> The changes match the request so I am OKing this.

Had already realised this, was just waiting for the build to finish before pushing that change, totaly agree @staceymosier

**Comment by alistairmc** [comment]
> For font-weight, would you prefer to use --rhd-global--FontWeight-Display--regular defined in typography/_weights.scss?
> 
> The changes match the request so I am OKing this.

Had already realised this, was just waiting for the build to finish before pushing that change, totaly agree @staceymosier

**Comment by alistairmc** [comment]
@gdoyle1 I have made the font-weight change can you re-approve, please.

**Pull request merged**
