### PR TITLE
Fixing missing upstream projects

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by paulrobinson** [comment]
Working on http://stumpjumper.lab4.eng.bos.redhat.com:36677/products/bpmsuite2/community and http://stumpjumper.lab4.eng.bos.redhat.com:36677/products/brms2/community

**Comment by paulrobinson** [comment]
It's not working on http://stumpjumper.lab4.eng.bos.redhat.com:36677/products/cdk/community. I suspect it's loading all projects, as there are non specified.

**Comment by LightGuard** [comment]
@paulrobinson Are there any upstream projects for cdk? You can suppress the display of upstream projects in the Community Paragraph by unchecking the box.

**Comment by tiffanynolan** [comment]
I spot checked BRMS and BPM Suite and they look good. I can check some more once the code is merged.

**Comment by LightGuard** [comment]
@Dantheman720 @adelasofia @KamiQuasi Could one of you merge this please? Tiffany has signed off on it.

**Pull request merged**
