### PR TITLE
Updated SO query to use the same DCP as the rest of the build.

### PR DESCRIPTION
**Pull request by paulrobinson**
Replacing https://github.com/redhat-developer/developers.redhat.com/pull/1487.

This really should build and test cleanly. I'm not sure why we keep getting (unrelated) issues showing up.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by paulrobinson** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@paulrobinson Is this good to go?

**Comment by paulrobinson** [comment]
Yes. The stack page is using the staging DCP now, so it looks right.

**Pull request merged**
