### PR TITLE
[SURGE 3050] Dynamic Content Assembly

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3050

### Verification Process
1. Add existing Dynamic Content assembly to a node. (Available on Articles)
2. Try with Wordpress & Drupal filters
3. Try all Visual Styles

##### Default / no visual styles

Screen Shot 2019-10-01 at 2 26 23 PM

Screen Shot 2019-10-01 at 2 26 29 PM

Screen Shot 2019-10-01 at 2 26 34 PM

##### Dark

Screen Shot 2019-10-01 at 2 27 32 PM

##### Center (current) with `.center` class

Screen Shot 2019-10-01 at 2 28 29 PM

##### Center with `.centered` class

Screen Shot 2019-10-01 at 2 28 38 PM

**NOTE:** Can we update the class of the visual style here?  @rogeralloymagnetic 

##### Gray background

Screen Shot 2019-10-01 at 2 28 46 PM

##### No padding top

Screen Shot 2019-10-01 at 2 29 30 PM

##### No padding bottom

Screen Shot 2019-10-01 at 2 29 41 PM

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
@rogeralloymagnetic I approve this PR pending the change of the Center visual style class from `.center` to `.centered`

**Review by sjcox-rh — APPROVED** [review]
@rogeralloymagnetic all visual styles look good to go from design perspective.

**Comment by jordanpagewhite** [comment]
@rogeralloymagnetic Feel free to merge this in the morning if that is helpful as long as you confirm that the Centered visual style is actually centered (see screenshots above). You might need to change the class name and then merge. Thanks

**Comment by robpblake** [comment]
rebuild this please

**Pull request merged**
