### PR TITLE
[MWES-2760] Update /user/login with instructions for content editors to use SSO login.

### PR DESCRIPTION
**Pull request by robpblake**
This PR updates the `/user/login` page in Drupal to provide instructions to content editors to use their SSO account to log in to Drupal and partially hides the legacy login that will will retire in the future.

### JIRA Issue Link
* https://issues.jboss.org/browse/MWES-2760

### Verification Process

* Build should go green
* You can still login with your SSO account
* You can still login with the legacy method
* There are no dangling content import changes in Drupal.

### CODE REVIEW

**Comment by robpblake** [comment]
@paulrobinson Can you please take a look at the wording on `/user/login` of the Drupal associated with this PR. Happy to adjust it as you see fit to ensure it's clear for content editors.

cheers,

Rob

**Comment by paulrobinson** [comment]
There's no such thing as a "Red Hat Developer account". It's just a "Red Hat Account". 

How about:

```
Content editors should now log in using their Red Hat account.

Please ensure that your Red Hat account has the same email address as used by your account in Drupal. For assistance, please contact the RHDP Engineering team or use the 'report a website issue' link in the footer below.
```

**Comment by robpblake** [comment]
@jordanpagewhite It looks like the jQuery show/hide functionality isn't quite working on this one.

cheers,

Rob

**Comment by robpblake** [comment]
@jordanpagewhite Can you please review the changes in this PR and approve if you're happy.

cheers,

Rob

**Comment by robpblake** [comment]
@paulrobinson Can you take another look at the login page please for the Drupal instance and approve this PR if you're happy.

cheers,

Rob

**Comment by paulrobinson** [comment]
Login button needs changing to "Log in with your Red Hat Account"

**Comment by robpblake** [comment]
@paulrobinson How about now?

cheers,

Rob

**Comment by paulrobinson** [comment]
Looks good, thanks.

**Pull request merged**
