### PR TITLE
[DEVELOPER-5617] Update Drupal core to 8.6.7

### PR DESCRIPTION
**Pull request by jordanpagewhite**
This commit updates Drupal core to the latest version, 8.6.7.

### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5617

### Verification Process

* Drupal core is at version 8.6.7
* There is no hanging config on the PR environment
* There are no hanging db updates on the PR environment causing out of sync config
* All tests pass

### CODE REVIEW

**Comment by robpblake** [comment]
@jordanpagewhite Is it worth us updating everything that says it's out-of-date on the Drupal status page with this PR? I'm seeing updates to other modules and lightning as well?

cheers,

Rob

**Comment by jordanpagewhite** [comment]
@robpblake That is a good point. I can take care of those other contrib updates today. Thank you.

**Comment by LightGuard** [comment]
@jordanpagewhite will you be adding commits to this PR?

**Comment by jordanpagewhite** [comment]
@LightGuard Yes, I will take care of that soon. Sorry, I became preoccupied with other tasks.

**Comment by jordanpagewhite** [comment]
@LightGuard I have updated this PR with changes to non-core packages (lightning) and included the exported config.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
Merge conflict

**Comment by jordanpagewhite** [comment]
@LightGuard I resolved the merge conflict in the latest commit

**Comment by jordanpagewhite** [comment]
retest this please

**Comment by LightGuard** [comment]
merge conflict

**Pull request merged**
