### PR TITLE
[DEVELOPER-5481] Product comparison table assembly

### PR DESCRIPTION
**Pull request by jordanpagewhite**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5481

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
@tiffanynolan Feel free to test out the Product feature assembly type in this PR environment. I have made the Product feature assembly type available via the Content field on the Article nodes, but I feel that it is easier to create a Product feature via this route `/assembly/add/product_comparison_table` and then add an existing Product feature to an Article.

There is also a Release taxonomy vocabulary that you will have to add terms to if you wish to assign a release to a Feature. If you have any questions at any point, don't hesitate to reach out. Thank you.

**Comment by jordanpagewhite** [comment]
@tiffanynolan Have you had an opportunity to look at this?

**Comment by LightGuard** [comment]
@adelasofia if you're happy with this, I think we're ready to merge.

**Comment by jordanpagewhite** [comment]
Here is a screenshot of what the Product Features might look like now after my latest commit @adelasofia 

screen shot 2018-11-27 at 3 50 35 pm

**Comment by sjcox-rh** [comment]
Looks good @jordanpagewhite! I think this is good to merge

**Pull request merged**
