### PR TITLE
DEVELOPER-3932 Removed Resources from main nav

### PR DESCRIPTION
**Pull request by adelasofia**
[DEVELOPER-3932](https://issues.jboss.org/browse/DEVELOPER-3932)

Removes the Resources page from the main nav, and from the navigation e2e tests.

_Part 1 of a series of PRs to remove the Resources page._

### CODE REVIEW

**Comment by adelasofia** [comment]
@RubyGemTSL do you know why I get a 404 when I try to see the e2e test results? I believe this is happening on all PRs

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
tests still failing? :(

**Comment by adelasofia** [comment]
@LightGuard yep but they are failing on all PRs :(

**Comment by LightGuard** [comment]
Any reason NOT to merge this?

**Comment by adelasofia** [comment]
@LightGuard nope, please merge it

**Comment by RubyGemTSL** [comment]
@adelasofia @LightGuard  sorry I've been off sick for over a week. I'll look into the failures today. If the failures aren't related to this PR, go ahead and merge.

**Pull request merged**
