### PR TITLE
Update Carousel

### PR DESCRIPTION
**Pull request by insectengine**
Updated carousel to remove Build and add Devoxx France and GIDS

### CODE REVIEW

**Comment by LightGuard** [comment]
ok to test

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by insectengine** [comment]
Preview of carousel approved

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by insectengine** [comment]
approved.

**Pull request merged**
