### PR TITLE
[MWES-3357] Move configuration from rhd.settings.yml into rhd.settings.php

### PR DESCRIPTION
**Pull request by robpblake**
This PR moves all configuration that was previously stored in `rhd.settings.yml` into `rhd.settings.php` and removes the need for us to parse the `rhd.settings.yml` (potentially multiple times) on each request to Drupal.

This should aid with performance of Drupal, particularly in environments where `rhd.settings.yml` is stored on a "slow" NFS disk.

This PR does not remove the process of templating and creating `rhd.settings.yml`, it is merely ignored by the `rhd.settings.php`. Once this is proved to be working, we can update our Openshift Templates to remove the mount of `rhd.settings.yml` and a follow-up PR here will remove the creation of `rhd.settings.yml` from our Ansible playbooks.

### JIRA Issue Link
* https://issues.jboss.org/browse/MWES-3357

### Verification Process

* The build should go green
* [Log in to the Drupal container](https://github.com/redhat-developer/developers.redhat.com/tree/master/previews) for this PR and ensure that the following all match:
  * `drush ev "echo (\Drupal::config('redhat_developers')->get('environment') . \"\n\");"` == `preview`
  * `drush ev "echo (\Drupal::config('redhat_developers')->get('broker') . \"\n\");"` == `https://broker.staging.redhat.com/partner/drc/userMapping?redirect=`
  * `drush ev "echo (\Drupal::config('redhat_developers')->get('dtm_code') . \"\n\");"` == `https://www.redhat.com/dtm-staging.js`
  * `drush ev "echo (\Drupal::config('redhat_developers')->get('downloadManager')['baseUrl'] . \"\n\");"` == `https://developers.stage.redhat.com`
  * `drush ev "echo (\Drupal::config('redhat_developers')->get('keycloak')['accountUrl'] . \"\n\");"` == `https://developers.stage.redhat.com/auth/realms/rhd/account/`
* Please visit `/user/login` on Drupal and ensure you can login using the SSO login
* Please visit `/products/rhel/downloads` and ensure that you can download RHEL 8
* Pick a product at random and ensure that download information is correctly populated when you visit the `downloads` tab
* Please visit `/help` and ensure that content loads in the StackOverflow section
* Please visit `/search` and ensure that search works
* Please ensure that you can log in as a site visitor using the `Log In` link in the top right-hand corner
* Please review the `_docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2` included in this PR and ensure that the values defined in the `redhat_developers` section match exactly the values that were previously defined in the `_docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.yml.j2` file.

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
rebuild this please

**Comment by alistairmc** [comment]
@robpblake 

drush ev "echo (\Drupal::config('redhat_developers')->get('keycloak')['content_editor_sso']['redirect_url'] . \"\n\");"

is returning a blank value

**Comment by robpblake** [comment]
@alistairmc Yes you're right and that shouldn't exist because I've removed it from the configuration object as it was duplicating things. So..bad instructions on my part.

Instead, could you please confirm that the following exist and match as expected below:

- `drush cget openid_connect.settings.keycloak settings.redirect_url --include-overridden` == `https://developer-preview-2984.ext.us-west.dc.preprod.paas.redhat.com/openid-connect/keycloak`
- `drush cget openid_connect.settings.keycloak settings.client_id --include-overridden` == `rhd-web-cms-localdev`
- `drush cget openid_connect.settings.keycloak settings.keycloak_base --include-overridden` == `https://developers.stage.redhat.com/auth`
- `drush cget openid_connect.settings.keycloak settings.keycloak_realm --include-overridden` == `rhd`
- `drush cget openid_connect.settings.keycloak settings.authorization_endpoint_kc --include-overridden` == `https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/auth`
- `drush cget openid_connect.settings.keycloak settings.token_endpoint_kc --include-overridden` == `https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/token`
- `drush cget openid_connect.settings.keycloak settings.userinfo_endpoint_kc --include-overridden` == `https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/userinfo`

cheers,

Rob

**Comment by alistairmc** [comment]
@robpblake  are you happy for this to be merged?

**Pull request merged**
