### PR TITLE
RHD-763 Added registration confirmation page

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
Waiting for Emily or Ray to approve the content of the page. I've checked the functionality and it seems to be working.

**Comment by rayploski** [comment]
I just changed my notification settings to go to my RH.com email so I should see these more often.  

I would like to change the grey boxes copy to stronger calls to action.  Edits welcome.

Software Collections:
Get started with Red Hat's latest recommended versions of Python, PHP, Ruby, Node.js, MariaDB, PostgreSQL, Nginx and much more.  You'll learn how to install and configure your development environment and get productive all in ten minutes.


Red Hat Mobile Application Platform:
Learn how to create and prototype new mobile apps.  Learn how-to create, discover and re-use across multiple app projects to speed app dev while maintaining control. Get started with Red Hat Mobile Application Platform.

Red Hat JBoss Enterprise Application Platform:
Follow along the tutorial to learn Java EE fundamentals and more including: JPA, JAX-RS, HTML5 and jQuery Mobile to get you started on using Java EE6 and JBoss Enterprise Application Platform.

**Comment by rayploski** [comment]
Looks good!  Thank you.

**Pull request merged**
