### PR TITLE
Removed version number text from WildFly link

### PR DESCRIPTION
**Pull request by paulrobinson**
This link is unlikely to get updated as new versions are released. It also adds little value, so I've simplified the text.

### CODE REVIEW

**Comment by paulrobinson** [comment]
@RubyGemTSL can you review this content change? You just need to look at http://developers-pr.stage.redhat.com/pr/1590/export/products/eap/download/ and check that the "Prefer to use the Upstream Project Version?" section looks right. It should simply have the version number removed.

**Comment by paulrobinson** [comment]
I'm not getting a response from the person who requested this. I think this is the right fix though, so would rather merge it and undo if we are ever told it's wrong.

**Comment by RubyGemTSL** [comment]
@paulrobinson - looks fine to me.

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
@paulrobinson Is this good to go?

**Comment by paulrobinson** [comment]
@robpblake yes. See my last comment.

**Pull request merged**
