### PR TITLE
DEVELOPER-2497 - Fixed the video query

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by paulrobinson** [comment]
This doesn't seem to work when there are two related products:

Notice that there are two related video sections on here and they render: http://developers.redhat.com/video/vimeo/131199128/. On here the first one is empty: http://it-developers-pr.stage.redhat.com/pr/735/build/618/video/vimeo/131199128/

I think the DCP query is wrong. This is what it should be. Notice that I switched 'query' to 'project' as you need to find only videos with 'devstudio' as the related product (stored as 'project').

      http://10.39.168.5:32778/v2/rest/search/developer_materials?newFirst=true&project=devstudio&sys_type=video

However, that fails on our DCP instance, but works on the productions one:

      http://dcp2.jboss.org/v2/rest/search/developer_materials?newFirst=true&project=devstudio&sys_type=video

I'll need to find out why that query is breaking.

**Comment by ollyjshaw** [comment]
docker build

**Comment by ollyjshaw** [comment]
docker build

**Comment by Dantheman720** [comment]
Yeah, I should have used project over query.  It seems that the docker dcp instance is still down though for testing.

**Comment by ollyjshaw** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please.

**Comment by paulrobinson** [comment]
This query now works: http://10.39.168.5:32778/v2/rest/search/developer_materials?newFirst=true&project=devstudio&sys_type=video

You should be able to proceed now.

**Comment by Dantheman720** [comment]
The query doesn't seem to be working here.

**Comment by Dantheman720** [comment]
retest this please.

**Comment by Dantheman720** [comment]
This issue is also linked to DEVELOPER-2498

**Pull request merged**
