### PR TITLE
Octopus Launch

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this now please

**Comment by paulrobinson** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
failed to build. retesting now

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by paulrobinson** [comment]
@adelasofia I merged https://github.com/redhat-developer/developers.redhat.com/pull/925 as the tests were passing and it had most of what we wanted for today's staging build.

Can you fix the conflicts on this, and let me know when the changes have been approved please.

**Pull request merged**
