### PR TITLE
DEVELOPER-2977 Software Collections Update Page

### PR DESCRIPTION
**Pull request by rctrh**
Create Updates page for Software Collections RHSCL 2.2 Beta.

### CODE REVIEW

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
@rctrh how is anyone going to get to this page? Nothing, afaict links to it.

**Comment by rct** [comment]
@LightGuard What controls the left menu?   The goal is to have an updates link.like /products/eap/

**Comment by LightGuard** [comment]
My bad, didn't know we had that built in. You can see it's there in the preview build: http://developers-pr.stage.redhat.com/pr/1078/build/1097/products/softwarecollections/overview/

**Comment by rctrh** [comment]
@LightGuard, I was optimistically hoping it would happen automagically when I couldn't figure out what made it appear in the eap page.

@MikGue to approve.

**Comment by rctrh** [comment]
Ready to merge, approved by @MikGue - https://issues.jboss.org/browse/DEVELOPER-2977

**Pull request merged**
