### PR TITLE
Added adaptive placeholders' functionality to select elements

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
hmmm, something not right with the awestruct tests. They also fail locally. I'll investigate. Drupal tests are fine.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia who needs to review?

**Comment by adelasofia** [comment]
@LightGuard Libor will be using this on the login/reg pages, so as long as these changes look good to you or @KamiQuasi they can be merged and Libor will take it from here

**Comment by adelasofia** [comment]
@LightGuard This PR adds the ability to have adaptive placeholders in 'Select' elements

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Comment by LightGuard** [comment]
@adelasofia Yes, I understand, but I'm not sure what "adaptive placeholders" are, or what they do :)

**Pull request merged**
