### PR TITLE
updated get-started.adoc

### PR DESCRIPTION
**Pull request by harshulmadan**
Please verify if the design similar to Fuse product pages. 

In addition, in this product page >Step1 is : Install and Configure - 5 mins, Step 2. Set up your Development Environment – 5 mins, Step 3.  Build your first project using JBoss Data Virtualization -12 mins 

unlike it is in Fuse product page

### CODE REVIEW

**Comment by LightGuard** [comment]
this is ok to test

**Comment by LightGuard** [comment]
Who needs to sign off on this and is it ready to go?

**Comment by paulrobinson** [comment]
Can you resolve the merge conflicts please? Also check these changes haven't already gone live. It's possible they were included in a bunch of other changes we made. See: http://developers.redhat.com/products/datavirt/get-started/

**Comment by Dantheman720** [comment]
I think this was already incorporated into the PR. Aside from the setup times.

**Comment by paulrobinson** [comment]
OK, I'll close the PR. @harshulmadan please create a new PR with any changes that are outstanding.

**Pull request closed without merging**
