### PR TITLE
DEVELOPER-3648 - create a seperate jenkins task for KC and DM acceptance tests

### PR DESCRIPTION
**Pull request by RubyGemTSL**

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@robpblake good for review. We'll make the change to the acceptance test job and retest on Monday.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
@robpblake I've uncommented out the command to run the kc dm tests retesting now.

**Comment by RubyGemTSL** [comment]
@robpblake Didn't work - don't merger We'll have to change the setup.

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
To be merged Tuesday AM

**Comment by robpblake** [comment]
Looks good to go. Merging.

**Pull request merged**
