### PR TITLE
DEVELOPER-3845 created Cheat Sheets REST export view

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
Is this only working on published entities?

**Comment by adelasofia** [comment]
@LightGuard yep, only published cheat sheets

**Comment by LightGuard** [comment]
@adelasofia would this affect the tests that are failing?

**Comment by LightGuard** [comment]
Looks like tests are failing all over the place :(

**Comment by adelasofia** [comment]
retest this please

**Comment by adelasofia** [comment]
retest this please

**Pull request merged**
