### PR TITLE
Feature/developer 5212 - add js to clamp lines and add elipsiss

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
* Link to the JIRA ticket(s) this pull request solves
https://issues.jboss.org/browse/DEVELOPER-5212

### CODE REVIEW

**Comment by alistairmc** [comment]
retest this please

**Comment by KamiQuasi** [comment]
@alistairmc two items of feedback looking at https://developers-pr.stage.redhat.com/pr/2541/export/learning-paths/microservices/:
1. It seems like the ellipses are being put on things that aren't actually overflowing and things that do don't get them
2. We'll probably also want to apply this to the description texts as well as they are supposed to be cut off after three lines when displayed

**Comment by alistairmc** [comment]
@KamiQuasi I have checked in a fix for the firefox issue and added the 3 line clamp, I have tested and all seems fine can you review and ok?

**Comment by alistairmc** [comment]
depending on which story checks in first there may be a merge issue with https://github.com/redhat-developer/developers.redhat.com/pull/2547

**Comment by KamiQuasi** [comment]
Looks good. Let's ship it.

**Pull request merged**
