### PR TITLE
DEVELOPER-3587 - Improve the performance of /downloads

### PR DESCRIPTION
**Pull request by Dantheman720**
https://issues.jboss.org/browse/DEVELOPER-3587

Currently, we have the download button show "fetching" while it is iterating through the api products and fetching them one by one. With the new download functionality, there is no need for that since it does a one-time bulk fetch.

Some thoughts though:

1.) What do we want displayed when download-manager is down? I know that we have an alert that shows outages; however, if nothing is displayed, it will just show "Popular Downloads" and "All Downloads"

image

2.) Once this does get merged in, will the products.json be exported similar to onebox.json?

### CODE REVIEW

**Comment by LightGuard** [comment]
@Dantheman720 who needs to sign off on this?

**Comment by Dantheman720** [comment]
@KamiQuasi - Can you take a look when you get the chance. I think I'll still need to make some changes (mostly to componentize the css as well), but I wanted to get this in so that you could take a look.

**Comment by KamiQuasi** [comment]
@Dantheman720 everything looks pretty good to me. There is some refactoring that we might be able to do down the road with some of the new stuff we're doing, but overall I give it a thumbs up.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
@Dantheman720 merge conflict now

**Comment by Dantheman720** [comment]
@LightGuard - I updated and pushed a new version. I'd like to check it in staging again before merge though

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
Trying the new drupal install on a pull request

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
Any reason not to merge this?

**Comment by Dantheman720** [comment]
@LightGuard - I think this can be merged.

**Pull request merged**
