### PR TITLE
DEVELOPER-5101 - Cheatsheet download is not always triggered

### PR DESCRIPTION
**Pull request by Dantheman720**
retest this please

### CODE REVIEW

**Comment by Dantheman720** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by Dantheman720** [comment]
retest this please

**Comment by Dantheman720** [comment]
@RubyGemTSL - I think this should work now. It was returning true even when the timeout had expired.

**Comment by RubyGemTSL** [comment]
@Dantheman720 checking this out now. If it's good i'll merge. I'll spend a bit of time testing first.

**Comment by Dantheman720** [comment]
@RubyGemTSL - Sounds good! Thank you sir!

**Comment by RubyGemTSL** [comment]
@Dantheman720 sorry to be the barer of bad news, but the double download issue is back on this :(

**Comment by RubyGemTSL** [comment]
screen shot 2018-06-29 at 22 43 49

**Pull request merged**
