### PR TITLE
DEVELOPER-4521 Fix help text not showing on Drupal fields

### PR DESCRIPTION
**Pull request by adelasofia**
## [DEVELOPER-4521 Fix help text not showing on Drupal fields](https://issues.jboss.org/browse/DEVELOPER-4521)
There is a known bug in Drupal affecting the Help Text for link fields that have the Link Text subfield disabled. Drupal issue: https://www.drupal.org/node/2421001

### Steps to review

1. Go to create a new video resource in /node/add/video_resource
2. The SlideShare Source field should display the help text _Src attribute content from the embed code provided by SlideShare. For a more detailed explanation on where to get this link, see this doc._

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
Hi @adelasofia 

Drupal is failing to boot on your PR with the following error:

```
Updating configuration...
Executing drush dbup
DEBUG - executing command /var/www/drupal/vendor/bin/drush ["-y", "--root=/var/www/drupal/web", "--entity-updates", "updb"]
drupal_install_checker.rb:10:in `exec!':  ------------ ------------- ------------- -------------------------------------  (RuntimeError)
  Module       Update ID     Type          Description                          
 ------------ ------------- ------------- ------------------------------------- 
  comment      enable_comm   post-update   Enable the comment admin view.       
               ent_admin_v                                                      
               iew                                                              
  paragraphs   set_paragra   post-update   Set the parent id, type and field    
               phs_parent_                 name to the already created          
               fields                      paragraphs.   @param $sandbox        
  rest         create_rest   post-update   Create REST resource configuration   
               _resource_c                 entities.   @see rest_update_8201()  
               onfig_entit                  @see                                
               ies                         https:www.drupal.orgnode2308745      
  rest         resource_gr   post-update   Simplify method-granularity REST     
               anularity                   resource config to                   
                                           resource-granularity.   @see         
                                           https:www.drupal.orgnode2721595      
 ------------ ------------- ------------- ------------------------------------- 

 // Do you wish to run the specified pending updates?: yes.                     

 [error]  Drupal\Core\Entity\EntityStorageException: 'action' entity with ID 'comment_delete_action' already exists. in Drupal\Core\Entity\EntityStorageBase->doPreSave() (line 425 of /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php). 
 [ok] Post updating comment
Array	Array
 [success] Cache rebuild complete.
 [success] Finished performing updates.
	from drupal_install_checker.rb:132:in `update_db'
	from drupal_install_checker.rb:157:in `<main>'
DEBUG - execution of command '/var/www/drupal/vendor/bin/drush ["-y", "--root=/var/www/drupal/web", "--entity-updates", "updb"]' has failed with status code='1'
```
Your PR is applying a lot of updates to the dependencies used by Drupal and also an update to core Drupal itself. It is possible to simply apply the patch that resolves the issue you're trying to fix rather than updating all the dependencies at the same time?

cheers,

Rob

**Comment by LightGuard** [comment]
Please see #2164.

**Comment by LightGuard** [comment]
Once we can get Drupal running on this PR, I don't see why we can't merge it.

**Comment by robpblake** [comment]
retest this please

**Comment by adelasofia** [comment]
@LightGuard yes please!

**Pull request merged**
