### PR TITLE
RHD-1769 Removed slider from Events page

### PR DESCRIPTION
**Pull request by adelasofia**
Commented out slider and fixed block comment for filters from Events page

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
@LightGuard it looks like the old 'Export Hold' issue when downloading has reared it's ugly head again! I'll report this to David tomorrow.

**Comment by LightGuard** [comment]
@RubyGemTSL should we be retesting now?

**Comment by RubyGemTSL** [comment]
@LightGuard - should be OK now as there was only 1 occurrence of the 'Export Hold' yesterday/today. I emailed @dhladky to let him know the issue may still be around.

**Comment by adelasofia** [comment]
Retest this please

**Comment by adelasofia** [comment]
Approved by James C.

**Pull request merged**
