### PR TITLE
DEVELOPER-3819 Fixed Download button on Product mobile pages

### PR DESCRIPTION
**Pull request by adelasofia**

### CODE REVIEW

**Comment by LightGuard** [comment]
@RubyGemTSL please verify and merge.

**Comment by RubyGemTSL** [comment]
@adelasofia @LightGuard does the page exist because I still get en error "The website encountered an unexpected error. Please try again later." when clicking on the download button.

**Comment by paulrobinson** [comment]
@RubyGemTSL which page did you try this on? Can you provide a link?

**Comment by RubyGemTSL** [comment]
@paulrobinson 
http://developer-drupal.web.prod.ext.phx2.redhat.com/products/eap/overview

In mobile view click on the 'Download' button

**Comment by RubyGemTSL** [comment]
Looks good but will run broken link check to verify. Will report back soon as just in the middle of something.

**Pull request merged**
