### PR TITLE
[DEVELOPER-5396] Add collection assembly.

### PR DESCRIPTION
**Pull request by rogeralloymagnetic**
## JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-5396

## Verification Process
- User is able to create an assembly with filtered Labels based on one or more existing taxonomy terms (Vocabulary terms must be present)
- User can choose the number of results output
- User can choose to show pagination
- Assembly displays the list of content in "tile" format
- Collection Assembly pulls from "Article", "Books" and "Video Resources" content types.

## Screens

**NOTE:** These screenshots include content without images to show how those would display. Ideally, all content being pulled into this Assembly would have images added in production.

### Admin
screen shot 2018-10-26 at 7 19 12 am

#### Desktop (No Pager)
screen shot 2018-10-26 at 7 20 11 am

#### Laptop (Pager)
screen shot 2018-10-26 at 7 20 44 am

#### Tablet (Pager)
screen shot 2018-10-26 at 7 21 01 am

#### Mobile (Pager)
screen shot 2018-10-26 at 7 22 19 am

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
retest this please

**Comment by rogeralloymagnetic** [comment]
@robpblake Can you let me know what the failure was? I see the composer.lock has a conflicting content-hash now. This push is the first time I've committed a module change to this repo, I'm not sure if there is something specific that has to happen to work with the platform. @fearlsgroove

**Comment by LightGuard** [comment]
@rogeralloymagnetic: Cannot locate export of 'http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37699/products' at expected path: '/export/rhdp-jenkins-slave.lab4.eng.bos.redhat.com_37699/products/index.html'

Update the conflict and we'll try it again. Could have been a data issue from the data dump that was being used.

**Comment by LightGuard** [comment]
@rogeralloymagnetic still broken. You can see the page that's causing the failure at http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37699/products. It's pretty messed up and kinda looks like there was an error in rendering.

Looking at the drupal logs (http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37699/admin/reports/dblog/event/5535253 and http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37699/admin/reports/dblog/event/5535254) there's certainly going on there.

**Comment by rogeralloymagnetic** [comment]
@LightGuard The issues caught in testing have been sorted on this now.

**Comment by sjcox-rh** [comment]
@rogeralloymagnetic 

Gina and I reviewed the pagination and we think that the use of pagination within a section on a page would be confusing behavior. 

We recommend perhaps using a carousel for this section, like one I mocked up below:
screen shot 2018-11-19 at 8 31 25 am

**Comment by rogeralloymagnetic** [comment]
screen shot 2018-11-20 at 8 01 12 am
screen shot 2018-11-20 at 8 00 22 am

Added pager dots visual style.

**Comment by sjcox-rh** [comment]
Nice! @rogeralloymagnetic I think that works much better.

**Comment by KamiQuasi** [comment]
retest this please

**Comment by LightGuard** [comment]
still broken

**Pull request merged**
