### PR TITLE
[DEVELOPER-2979] Refactor automated test setup

### PR DESCRIPTION
**Pull request by RubyGemTSL**
adding wip for test refactor

wip

wip

wip

complete refactor of acceptance tests

wip

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
all good now @LightGuard

**Pull request merged**
