### PR TITLE
New Search Revisions

### PR DESCRIPTION
**Pull request by KamiQuasi**
### JIRA Issue Link
* https://issues.jboss.org/browse/DEVELOPER-5172
* https://issues.jboss.org/browse/DEVELOPER-5903

### Verification Process
* Log in to Drupal
* Set the new fusion search page to published
* Check the page for functionality, behaviors, and results

### CODE REVIEW

**Comment by robpblake** [comment]
@KamiQuasi Can you tell me how the Fusion endpoint for the new search is going to be configured please? I'd like to ensure that it's managed alongside all of our other environment configuration in a single place.

**Comment by gdoyle1** [comment]
[UAT for Search PR](https://trello.com/c/yj5zVlhx/722-uat-for-search-pr)

**Comment by robpblake** [comment]
@KamiQuasi I've just merged #3390 which will make the Fusion API endpoint available to you via `drupalSetttings.rhd.fusion.url`. Can you update to make use of this so that things are not hard-coded in Drupal.

cheers,

Rob

**Comment by robpblake** [comment]
retest this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by robcoffman** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
Link to pr env: https://developer-preview-3366.ext.us-west.dc.preprod.paas.redhat.com/

**Comment by alistairmc** [comment]
@KamiQuasi @robcoffman @robpblake @jordanpagewhite this has been sitting in PR for a long time is this valid and can we get the merge conflicts resolved and re-tested.

**Comment by robpblake** [comment]
@alistairmc I think this is for the new Fusion-based search, so I would suggest that this is dependent upon the Fusion deployment being GA'ed and available. I do not know the status of the Fusion deployment, @LightGuard should be able to advise.

Just looking at this PR, I see a couple of issues with it:

* I can't tell if it's using environment configuration to read the new Search API endpoint or if it is hard-coded. We expose the endpoint for the Search API via `drupalSettings.rhd.fusion.url` to JS, so this implementation should make use of that.
* The new functionality is not tested as part of this PR. This is a big change and it should be verified that our automated test suite passes before this gets merged. Otherwise I will assume that this will break the current automated testing and will therefore block the rest of the team once it's gets merged in. I would like to see this PR automatically promoting the new search functionality to live (perhaps via an update_hook, but @jordanpagewhite can advise on the best way to do that) so that we can be sure the test suite continues to work when this changes go live.

cheers,

Rob

**Comment by jordanpagewhite** [comment]
I am going to close this pull request since it is not clear, at this point, what the timeline/expectations are for these changes. I have pulled this branch to my local environment, as has Stacey, and we will pick this back up once we have a clear timeline

**Pull request closed without merging**
