### PR TITLE
[RHDX-508] Restore hero_image field

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-508

### Verification Process
go to /products and check the featured products have product logos
Screenshot 2020-05-15 at 16 18 33

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
This hit the Jenkins PR trigger timeout like most of our other PRs. This PR should resolve this issue. Once #3572 is merged, we can rebuild this.

**Comment by alistairmc** [comment]
rebuild this please

**Comment by alistairmc** [comment]
retest this please

**Comment by alistairmc** [comment]
retest this please

**Pull request merged**
