### PR TITLE
[DEVELOPER 3295] Two Column Eloqua Form

### PR DESCRIPTION
**Pull request by ghost**
### JIRA Issue Link
* https://github.com/redhat-developer/developers.redhat.com/issues/3295

### Verification Process
1. Go to https://developer-preview-3395.ext.us-west.dc.preprod.paas.redhat.com/contact-sales
2. If it isn't already displaying in 2 columns, go edit the "Sign-up Form" assembly and add the "Two column" visual style (https://developer-preview-3395.ext.us-west.dc.preprod.paas.redhat.com/contact-sales/edit)
3. View the page and confirm the form displays in two columns and collapses to 1 on mobile viewports

### CODE REVIEW

**Comment by robpblake** [comment]
retest this please

**Comment by robpblake** [comment]
rebuild this please

**Review by jordanpagewhite — APPROVED** [review]
This looks good to me now. Thanks you for the patience with resolving that unrelated float issue Roger. I've slightly updated the testing instructions

**Review by sjcox-rh — APPROVED** [review]
Two columns looks good and adjusts to 1 column on mobile.

**Pull request merged**
