### PR TITLE
Feature/visited button color incorrect on secondary button rhdx 413

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://projects.engineering.redhat.com/browse/RHDX-413

### Verification Process
on the homepage using safari on Mac inspect the more developer tools button and enabled the visited sudo class using style inspector, visual state should remain the same as non visited

### CODE REVIEW

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by jordanpagewhite** [comment]
rebuild this please

**Comment by robpblake** [comment]
retest this please

**Pull request merged**
