### PR TITLE
feature/DEVELOPER-2504 (drupal cdn sass function)

### PR DESCRIPTION
**Pull request by LightGuard**
I needed things from DEVELOPER-2503 so that's merged here as well.

### CODE REVIEW

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by ollyjshaw** [comment]
retest this please

**Comment by paulrobinson** [comment]
To review: run up the Drupal build on my laptop and check the fonts and background images (heroes) look right.

**Comment by paulrobinson** [comment]
retest this please

**Comment by paulrobinson** [comment]
When I build this I get the following. Do I need to 'npm install' something?

bundle exec ./control.rb -u --run-the-stack
Decrypting...
decrypting vault
Vault decrypted
Setting ports...
AWESTRUCT_HOST_PORT available at 32768
DRUPAL_HOST_PORT available at 32769
DRUPALPGSQL_HOST_PORT available at 32770
MYSQL_HOST_PORT available at 32771
SEARCHISKO_HOST_PORT available at 32772
Killing docker services...
args to docker compise are []
Building...
Building CSS and JS for drupal
[15:51:56] Working directory changed to ~/dev/developer.redhat.com
module.js:338
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/paul/dev/developer.redhat.com/Gulpfile.js:4:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by LightGuard** [comment]
Yes. The readme now says you have to install node, npm and then npm install
at the project root.

On Thursday, February 18, 2016, Paul Robinson <notifications@github.com>
wrote:

> When I build this I get the following. Do I need to 'npm install'
> something?
>
> bundle exec ./control.rb -u --run-the-stack
> Decrypting...
> decrypting vault
> Vault decrypted
> Setting ports...
> AWESTRUCT_HOST_PORT available at 32768
> DRUPAL_HOST_PORT available at 32769
> DRUPALPGSQL_HOST_PORT available at 32770
> MYSQL_HOST_PORT available at 32771
> SEARCHISKO_HOST_PORT available at 32772
> Killing docker services...
> args to docker compise are []
> Building...
> Building CSS and JS for drupal
> [15:51:56] Working directory changed to ~/dev/developer.redhat.com
> module.js:338
> throw err;
> ^
> Error: Cannot find module 'node-sass'
> at Function.Module._resolveFilename (module.js:336:15)
> at Function.Module._load (module.js:278:25)
> at Module.require (module.js:365:17)
> at require (module.js:384:17)
> at Object. (/Users/paul/dev/developer.redhat.com/Gulpfile.js:4:12)
> at Module._compile (module.js:460:26)
> at Object.Module._extensions..js (module.js:478:10)
> at Module.load (module.js:355:32)
> at Function.Module._load (module.js:310:12)
> at Module.require (module.js:365:17)
> at require (module.js:384:17)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redhat-developer/developers.redhat.com/pull/774#issuecomment-185786510>
> .
>


-- 
Sent from Gmail Mobile

**Comment by paulrobinson** [comment]
Got this working on my machine. Fonts and heros look right. I can merge this once I've verified that it doesn't break the production site.

**Comment by paulrobinson** [comment]
retest this please

**Comment by LightGuard** [comment]
Need this to get the current production look and feel done.

**Comment by LightGuard** [comment]
Superseded by #843

**Pull request closed without merging**
