### PR TITLE
[DEVELOPER-4722] add publish date module and amend twig code for learning paths

### PR DESCRIPTION
**Pull request by alistairmc**
### JIRA Issue Link
https://issues.jboss.org/browse/DEVELOPER-4722

### CODE REVIEW

**Comment by alistairmc** [comment]
@jordanpagewhite please check this over and if ok get one of the team to merge

**Comment by jordanpagewhite** [comment]
This looks good to me! It is wise to use those conditionals since content editors will need to enter publication dates on existing nodes (as desired) for them to appear / for the variables to be available. Thanks.

**Comment by jordanpagewhite** [comment]
@LightGuard This is ready for a quick review and merge whenever you have a chance. I have approved the changes.

**Comment by LightGuard** [comment]
Waiting to see the okay from UX.

**Comment by alistairmc** [comment]
@tiffanynolan is this ok for UX

**Pull request merged**
