### PR TITLE
[DO NOT MERGE] First attempt at fixing keycloak

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
retest this please

**Comment by LightGuard** [comment]
@KamiQuasi Please take a look.

**Comment by RubyGemTSL** [comment]
let me know if you need any help with this, but the tests are failing because the login/register links aren't working. (probably what you're trying to fix here)

**Comment by KamiQuasi** [comment]
@RubyGemTSL and @LightGuard this "worked" as far as the including of the path to the script file, but the functionality of the script is pointing to production without the same querystring variables, so the iframe inclusion fails to work. Hoping @lkrzyzanek might be able to sort out why.

**Pull request merged**
