### PR TITLE
[HOLD] DEVELOPER-5117: Investigate/fix Blinkr build timeout issues.	

### PR DESCRIPTION
**Pull request by RubyGemTSL**
### JIRA Issue Link
* [DEVELOPER-5117](https://issues.jboss.org/browse/DEVELOPER-5117)

### Verification Process
- This PR is going to need to be retested several times to verify that a build timeout does not occur.
- results are consistent .

### CODE REVIEW

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by RubyGemTSL** [comment]
retest this please

**Comment by LightGuard** [comment]
Seeing as how the blinkr report hasn't finished yet (after 15 hours)... I'm not sure if this worked

**Comment by RubyGemTSL** [comment]
@LightGuard yep, it's a work in progress. Very frustrating.

**Pull request closed without merging**
